### ISSUE TITLE
Screen is always on that loading thing

### ISSUE THREAD

**Issue by RiceWitch** [TheRealJoelmatic/RemoveAdblockThing#100]
IT TAKES FOREVER TO LOAD sometimes it just won't, blank screen, is this thing broken????

**Comment by Tarkorr** [comment]
have you whitelisted youtube of you're adblock ?

**Comment by TruongChi128** [comment]
same for me

**Comment by wwuutt** [comment]
I am on WIn10. 
It works as intended when opening on the main youtube.com page.  
But I get the black loading page when opening in a new tab.  
I have done all the requirements above, such as whitelisting in firefox browser as well as my ublock.
Also, with more testing, strange but it works fine also on tabs when used in "Private Browsing Mode"

**Comment by Tarkorr** [comment]
It must be another extension that is conflicting with it.

**Comment by dommilosz** [comment]
Same for me.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/54410730/c6213083-4377-4808-b842-60f2d4b039ae)
