### ISSUE TITLE
Sometimes the ads dont load, nor does the video.

### ISSUE THREAD

**Issue by 128ajb** [TheRealJoelmatic/RemoveAdblockThing#104]
![cap1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/149311059/947bf281-c964-4bed-b2f5-2fa7335352cc)
As my title says, the ads sometimes are stuck on a blank screen with the time the ad is supposed to run for. The progress bar isn't loading, so i refresh the page, and then nothing loads. There are no other plugins enabled on my laptop (win 10) and the plugin, the exact same setup and version on my desktop (win11) works without any issues.

**Comment by 128ajb** [comment]
I should add, my browser is Opera GX and sometimes the adblocker works, other times it doesn't. It is very strange,

**Comment by marceloavf** [comment]
That happened to me sometimes, really weird, can you check your network/console to see if anything strange is being blocked?

**Comment by francofgp** [comment]
Today I found the same problem.

**Comment by pmsobrado** [comment]
Same thing happened to me today.

**Comment by beeonlinecy** [comment]
same here

**Comment by MarinGHG** [comment]
same for me, i guess youtube changed something about their anti adblock script

**Comment by jongdetim** [comment]
yt definitely changed something today. not a single adblocker, including this one works for me now. The page simply doesn't load when i have all adblockers off. Somehow, if i open videos in a new tab, they still won't load even without any adblockers. strange.

**Comment by binarick** [comment]
it doesn't work now

**Comment by BearadactylPrime** [comment]
Adding on to this. It doesn't totally not work like some of the people are claiming here, but it is hit or miss as of today. Any ads that appear to overlay over a video seem to pop up, though a page refresh removes them. 

Midrolls seem to be handled just fine, still, from my personal testing. It's only ads at the start of the video, and it isn't consistent.

**Comment by Astral100** [comment]
Same as everyone else says. Most of the time just a blank broken looking screen appears for a long time and then after a few minute video starts playing. Same thing keeps happening even if you stop using adblocker and this script.

**Comment by NiceGlassesDude** [comment]
I have the same issue.

**Comment by 128ajb** [comment]
I will be able to update my issue later today, as I will have access to my desktop setup again. Will reply with the update when I can.

**Comment by FabianLoRs** [comment]
Same issue in Brave

**Comment by 128ajb** [comment]
Updating my issue, It still works flawlessly on my desktop.

**Comment by chucheloff** [comment]
not working in chrome for me either

**Comment by Astral100** [comment]
it may be vpn related

**Comment by pmsobrado** [comment]
@Astral100 VPN related how? I'm not using any VPN.

**Comment by Astral100** [comment]
Oh ok. I am using VPN, same as another user here, so I thought it might be related. But I guess not.

**Comment by pmsobrado** [comment]
We should ask other people that have the issue and have reported here, but I think many users just surf the web normally :S
