### ISSUE TITLE
Scrolling doesn't work after clicking on a new video, must exit and enter fullscreen again.

### ISSUE THREAD

**Issue by MonotoneDevelopment** [TheRealJoelmatic/RemoveAdblockThing#106]
^^^ It is what it is ^^^

**Comment by 128ajb** [comment]
Ive had that issue as well. I believe it has something to do with the "adblockers are not allowed on youtube" popup. With my old adblocker, I would select the elements and block them so that popup would not appear. The video allows me to scroll when I enter full screen and scroll.

**Comment by dramr** [comment]
I was playing a video on a playlist then this Youtube adblocker is not allowed thing popping up all the time.then video gonna enter full screen and gonna be small again. then its gonna move on to another video on the playlist.  Funny thing is. When u watching individual video's on yt this Blocker works. not just so much on playlist vids. specially ur watching a marathon or something

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
