### ISSUE TITLE
The extension no longer works for me.

### ISSUE THREAD

**Issue by Dobby457** [TheRealJoelmatic/RemoveAdblockThing#108]
Whenever I attempt to click a new video, the adblock detection-media player disabled thingy will flash on the media player really quickly, then the media player will turn black and the video doesn't load. I'm on Opera GX if that changes anything.

**Comment by alfrederique** [comment]
Same here

**Comment by jigar007** [comment]
+1

**Comment by MansHeree** [comment]
+1

**Comment by ralinchan** [comment]
You need to update it. In Tampermonkey dashboard, mine shows version 2.0 and it works

**Comment by Dobby457** [comment]
> You need to update it. In Tampermonkey dashboard, mine shows version 2.0 and it works

it didnt work for me

**Comment by ralinchan** [comment]
> > You need to update it. In Tampermonkey dashboard, mine shows version 2.0 and it works
> 
> it didnt work for me

What's your dashboard look like?

Mine shows version 2.0, 7kb, last updated 6h ago. Works even better than the last version instead of like 5x speeding ads it like auto completes any ads that do show + I don't get the disable adblocker popup

**Comment by Dobby457** [comment]
> > > You need to update it. In Tampermonkey dashboard, mine shows version 2.0 and it works
> > 
> > 
> > it didnt work for me
> 
> What's your dashboard look like?
> 
> Mine shows version 2.0, 7kb, last updated 6h ago. Works even better than the last version instead of like 5x speeding ads it like auto completes any ads that do show + I don't get the disable adblocker popup

my dashboard looks pretty much like what you described what browser are you using

**Comment by Dobby457** [comment]
> > > > You need to update it. In Tampermonkey dashboard, mine shows version 2.0 and it works
> > > 
> > > 
> > > it didnt work for me
> > 
> > 
> > What's your dashboard look like?
> > Mine shows version 2.0, 7kb, last updated 6h ago. Works even better than the last version instead of like 5x speeding ads it like auto completes any ads that do show + I don't get the disable adblocker popup
> 
> my dashboard looks pretty much like what you described what browser are you using

OH DUDE IT WORKS IT WORKS FUCK YES NEVERMIND

**Comment by Dobby457** [comment]
if you use opera gx you have to completely disable the build in adblocker
