### ISSUE TITLE
Script not working with Enhancer for Youtube

### ISSUE THREAD

**Issue by Pitkox** [TheRealJoelmatic/RemoveAdblockThing#111]
Any chance for use this script and this addon?
https://addons.mozilla.org/pl/firefox/addon/enhancer-for-youtube/

**Comment by chybbud** [comment]
just turn off "Block ads" on Enhancer for YouTube
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/125054868/2d6f0b85-f82c-4194-8022-f04a4a381126)

**Comment by Pitkox** [comment]
almost, now YT working good, but Enhancer not at all. I need to control vol by scroll.

**Comment by Pitkox** [comment]
Sorry,after clear all cache everything is fine ;)
