### ISSUE TITLE
Video doesn't load and it stays on the ad screen with no ad playing sometimes

### ISSUE THREAD

**Issue by victorgore** [TheRealJoelmatic/RemoveAdblockThing#112]
Sometimes the ad won't load and then the video stays with the yellow ad loading bar while it works other times

**Comment by krystek357** [comment]
You probably didn't turn off your adblock

**Comment by xhfhope** [comment]
In my case I needed to turn off Enhancer for Youtube as well

**Comment by onepiecehung** [comment]
@xhfhope thanks, it's working, but a few days ago, I could use it normally Enhancer for Youtube, but today not working~~

**Comment by victorgore** [comment]
That makes sense, I turned off enhancer for YouTube
