### ISSUE TITLE
Doesn't Skip Surveys

### ISSUE THREAD

**Issue by kekerdubber** [TheRealJoelmatic/RemoveAdblockThing#113]
Sometimes I get a survey and it doesn't skip it on Chrome. It's able to block everything else though.

**Comment by krystek357** [comment]
thats because the script only fast-forwards the ads. Survey is not an video, so there's no way to skip it. Hope they will fix it :/

**Comment by TheRealJoelmatic** [comment]
This has been fixed in the latest version of the script.
