### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by VNPavan** [TheRealJoelmatic/RemoveAdblockThing#119]
stopped working on youtube as of today

**Comment by f3dm76** [comment]
Can confirm. MacOS 14.1 (23B74). Opera One(version: 103.0.4928.47) (arm64)
When launched just shows black screen:
<img width="1017" alt="Screenshot 2023-11-07 at 15 47 51" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/9447630/665f6cb5-3292-4c1e-9b96-a97efbbb86a2">

Here is how the popup looks like for me with Tampermonkey disabled:
<img width="1001" alt="Screenshot 2023-11-07 at 15 45 24" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/9447630/67a64af3-d814-45d1-868f-ae52ed03804f">

**Comment by mrsmilyy** [comment]
me toooooooooooooo

**Comment by AymericSpin** [comment]
Same

**Comment by AymericKing** [comment]
Same

**Comment by arnabs542** [comment]
same

**Comment by TheRealFame** [comment]
Same over here.

**Comment by Taragryen** [comment]
same
