### ISSUE TITLE
It is not working anymore. Nov 09 2023 ** Solved

### ISSUE THREAD

**Issue by MSZ-MGS** [TheRealJoelmatic/RemoveAdblockThing#126]
Hi there,

Since today morning the ads screen blocking is not working anymore.
What happening is, when I click on any youtube, the screen flashes quickly, I see the ads screen, then the screen goes like Fullscreen then get closed and it return to the youtub video, however the video is black and nothing is playing.

More info:
I am using Chrome, it got updated yesterdays.

**Comment by MSZ-MGS** [comment]
My aplogies, it worked. I don't know why the adsblock got activated.
I disabled the AdBlock and returned normal, the ads screen is not showing anymore.

Thank you!.

**Comment by FirePlank** [comment]
You can close the issue then if its solved

**Comment by MSZ-MGS** [comment]
Yes sir, I'll close it, You may mentioned that the Adblock sometimes reactivated after browser or extension update.
