### ISSUE TITLE
Incompatible with Youtube Enhanced?

### ISSUE THREAD

**Issue by Felina-Lain** [TheRealJoelmatic/RemoveAdblockThing#127]
Hi, not sure it's an issue per say, it might be me doing something wrong, but I also use youtube Enhanced in parallel (lots of neat options)
I turned off the enhanced adblocker, and the script works to perfection, no ads, no messages
BUT enhanced menu and options are gone, and enhanced itself seems to not be working anymore (I had checked for exemple a setting to hide end cards, and now they're showing again)
If I turn off the script I get ads back but Enhanced works again.

Dunno if that's something that can be changed?

**Comment by ralinchan** [comment]
If you're using Firefox, Enhanced is just broken as per the developer so trying to "fix" another script working with it is probably pointless

**Comment by Felina-Lain** [comment]
> If you're using Firefox, Enhanced is just broken as per the developer so trying to "fix" another script working with it is probably pointless

Oh, ok, didn't notice because it seemed to work fine for me, but alright, apologies then for the false report
