### ISSUE TITLE
Updated version causes pop up of ad for an adblocker

### ISSUE THREAD

**Issue by ralinchan** [TheRealJoelmatic/RemoveAdblockThing#129]
Running Firefox 119

Tampermonkey shows the script updated about 15 minutes ago. Now every time I load up YouTube, it pops up it's own ad for an addon called "AdSkip Youtube".

[https://i.imgur.com/7MGfOSU.png](url)

**Comment by efirdc** [comment]
That's not an ad. It's just instructions on how to utilize the script properly. It probably shouldn't come up every time you open youtube though.

**Comment by banderweir** [comment]
Super annoying and overlays every embedded video on other sites. Commenting out lines 347-378 seems to remove it

**Comment by ralinchan** [comment]
> That's not an ad. It's just instructions on how to utilize the script properly. It probably shouldn't come up every time you open youtube though.

I called it an ad because clicking on it takes you to a page to download an addon called "AdSkip Youtube"

**Comment by i1u5** [comment]
Created a script to remove annoying overlays, but it's working so now you gotta create a problem? @TheRealJoelmatic

**Comment by JonPetitta** [comment]
> > That's not an ad. It's just instructions on how to utilize the script properly. It probably shouldn't come up every time you open youtube though.
> 
> I called it an ad because clicking on it takes you to a page to download an addon called "AdSkip Youtube"

I am not seeing that behavior, also I do not see in the code where it has a link to that extension.

In the code it just fires an event that sets localstorage (and hides the overlay) as I mentioned above.

IMHO it is an issue related to poor choice of words, at least I'm hoping it is a coincidence, that the title used is the same as the other extension...  The text used should be plain to see where it is coming from, thus the title should be 'RemoveAdblockThing'.
