### ISSUE TITLE
makes youtube lag and load very slow

### ISSUE THREAD

**Issue by Rankerfps** [TheRealJoelmatic/RemoveAdblockThing#130]
i believe youtube is trying to patch this and that is what is causing the lag [this has been fixed]

**Comment by jesvijonathan** [comment]
Revert to [v8](https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v8) for now... 

Mark as solution if this helps :)

**Comment by Dodsy-91** [comment]
Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

**Comment by Rankerfps** [comment]
> Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

ok thanks
