### ISSUE TITLE
load is slower now

### ISSUE THREAD

**Issue by janmichael88** [TheRealJoelmatic/RemoveAdblockThing#135]
Was working without a hitch until today, but now youtube loads a littler slower.

**Comment by Dodsy-91** [comment]
Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

**Comment by janmichael88** [comment]
awesome! 2.4 worked like a charm! thanks!
