### ISSUE TITLE
Way too slow performance

### ISSUE THREAD

**Issue by jesvijonathan** [TheRealJoelmatic/RemoveAdblockThing#136]
very slow, loading, scrolling, etc
it was good before tho

**Comment by jesvijonathan** [comment]
specifically on v9,
the previous versions were fine though...

**Comment by Renkoto** [comment]
Same here, YT performance has suddenly dropped too much since yesterday.

**Comment by Dodsy-91** [comment]
Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue
