### ISSUE TITLE
SLOWS DOWN YOUTUBE

### ISSUE THREAD

**Issue by Pooland1** [TheRealJoelmatic/RemoveAdblockThing#137]
Like a few days ago everything was running smoothly, now its very slow and sometimes at the start when you click on a video, this script doesnt skip the ad.

**Comment by jesvijonathan** [comment]
Revert to [v8](https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v8) for now...

**Comment by Dodsy-91** [comment]
Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

**Comment by Pooland1** [comment]
alright

**Comment by Pooland1** [comment]
> Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

This Worked

**Comment by Pooland1** [comment]
> Revert to [v8](https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v8) for now...

This also worked thanks

**Comment by lenhatquang2512** [comment]
> Update to 2.4 here https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js it should fix the issue

It worked thanks

**Comment by katawful** [comment]
2.4 works, thanks so much
