### ISSUE TITLE
Shows annoying adskip popups!!!!

### ISSUE THREAD

**Issue by MxMatrixDemon** [TheRealJoelmatic/RemoveAdblockThing#141]
Shows a popup and have to click "got it!".

- firefox 119.0.1
- tampermonkey 4.19.0
- about:

// ==UserScript==
// @name         Remove Adblock Thing
// @namespace    http://tampermonkey.net/
// @version      2.4
// @description  Removes Adblock Thing
// @author       JoelMatic
// @match        https://www.youtube.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=youtube.com
// @updateURL    https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js
// @downloadURL  https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js
// @grant        none
// ==/UserScript==

**Comment by SleepingPig35** [comment]
Could you send a possible URL of that this happens?
