### ISSUE TITLE
dude implement an auto update function like already : | 

### ISSUE THREAD

**Issue by minanagehsalalma** [TheRealJoelmatic/RemoveAdblockThing#143]

**Comment by SleepingPig35** [comment]
Already done before in issue https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/37

**Comment by SleepingPig35** [comment]
It could be however possible to add a feature that opens a tab every time it updates but currently, an auto-update function has been added.

**Comment by minanagehsalalma** [comment]
@SleepingPig35 i see 

so it works ? if so then why did i have to update it manually the last to times /?

**Comment by SleepingPig35** [comment]
What browser / extension do you use? 
Tampermonkey on Chrome works.

**Comment by SleepingPig35** [comment]
Btw I just realized the problem might be that you have an older version which does have the auto-update function.

**Comment by minanagehsalalma** [comment]
> Btw I just realized the problem might be that you have an older version which does have the auto-update function.

Nope i always updated it manually

I am using tamper money chrome

**Comment by TheRealJoelmatic** [comment]
Ive added an update checker now in 2.6 that makes it much faster to update now.
