### ISSUE TITLE
cannot use clip button when script is on

### ISSUE THREAD

**Issue by temptationstairway** [TheRealJoelmatic/RemoveAdblockThing#149]
if i turn the script off, i can use clips freely again. when it's on i don't have the ability to use clips at all. you can keep hitting the button but nothing happens.

**Comment by AymericKing** [comment]
Same

**Comment by temptationstairway** [comment]
clips as in the feature that allows you to clip the video to show people
[image: image.png]

**Comment by Stroov** [comment]
oh understood that wont work because this script plays yt videos embeded in another site youtube never rolled that feature to embeded vids

**Comment by temptationstairway** [comment]
yeah well its not very helpful and also this script still has youtube
adblock popups..

**Comment by temptationstairway** [comment]
i wonder what the actual thing blocking it is... i use another userscript
and that one lets me make clips while doing the same thing as this one so
idgi

**Comment by TheRealJoelmatic** [comment]
This was Fixed in the lastest version.
