### ISSUE TITLE
Non-Video Ads Showing Up

### ISSUE THREAD

**Issue by Anonymous327** [TheRealJoelmatic/RemoveAdblockThing#155]
Is anyone seeing non-video ads that you have to skip manually?

**Comment by ralinchan** [comment]
Yea, I assume it's Youtube trying to fight a losing battle to claw extra pennies. I've gotten ones for Opera and Google Survey ones

**Comment by Shinobift** [comment]
can you add auto skip for this kind of adds 
 skip manually was not good!

**Comment by reynoldsalceda** [comment]
To resolve the issue for non-video ads, modify the following line: 
```
video.currentTime = video.duration;
```
Change it to: 
```
video.currentTime = video.duration || 0;
```

**Comment by Shinobift** [comment]
> To resolve the issue for non-video ads, modify the following line:
> 
> ```
> video.currentTime = video.duration;
> ```
> 
> Change it to:
> 
> ```
> video.currentTime = video.duration || 0;
> ```

Thank you!

**Comment by ngovandang** [comment]
solution doesnt work for me, any idea why?

**Comment by ralinchan** [comment]
> solution doesnt work for me, any idea why?

Because Youtube added a number of more overlay ads that this doesn't cover or when you edited the line you forgot to click save to make it stick or both
