### ISSUE TITLE
Cannot block Adds

### ISSUE THREAD

**Issue by Aizaz-hash** [TheRealJoelmatic/RemoveAdblockThing#159]
Ads are popping up and this blocker is unable to block any add

**Comment by ralinchan** [comment]
you need to provide more information since i'm not seeing this issue at all

**Comment by bacnd** [comment]
I'm also facing a similar situation like this

**Comment by ralinchan** [comment]
> I'm also facing a similar situation like this

Not sure why you think not giving any more information is at all helpful for resolving your issue

**Comment by reynoldsalceda** [comment]
To resolve the issue for non-video ads, modify the following line:
`video.currentTime = video.duration;`
Change it to:
`video.currentTime = video.duration || 0;`
