### ISSUE TITLE
Vertical Scroll Bar appears when Youtube Video is full screen

### ISSUE THREAD

**Issue by john-bao-git** [TheRealJoelmatic/RemoveAdblockThing#160]
First image does not have the script, the second has the script on.

![Image without script](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/12505482/c9bba755-8e18-464f-b028-520744122695)

![Image with script](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/12505482/b20646f8-c641-4b34-904d-a8648312bee2)

Not sure when this started happening, but I believe I noticed this last Sunday or Monday. I clicked to check if there was an update to the script, and it said no updates. I checked in Firefox Incognito, and there was no scrollbar.

**Comment by ralinchan** [comment]
Not seeing this issue on firefox 120

Need more information

**Comment by john-bao-git** [comment]
Thank you for your reply and solution. Updating Firefox seems to have fixed the issue, not sure why the browser didn't auto-update, and when I did look for an update before, it found none.
