### ISSUE TITLE
Can't play in youtube music

### ISSUE THREAD

**Issue by minhchienwikipedia** [TheRealJoelmatic/RemoveAdblockThing#161]
When I add the script and open https://music.youtube.com/ to try to play a video, it's not showing ads video and won't play any video, (just in case youtube shows ads video). Can you guy help me check it?

**Comment by minhchienwikipedia** [comment]
@itsmetoolala  not for me :( 
<img width="1072" alt="image" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20647079/c0dc7eea-bd76-4fb9-bebf-4e43ad6d965f">

**Comment by ralinchan** [comment]
Seeing no issue.

Need more information.

**Comment by minhchienwikipedia** [comment]
I just checked in the console and saw this error
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20647079/cb37fc69-54d5-4ef6-85ae-74a6785b5e76)

**Comment by ralinchan** [comment]
Telling us the error without telling us anything about your system doesn't help. This error is not a result of this script

**Comment by minhchienwikipedia** [comment]
@ralinchan  so what do you need to reproduce this issue?

**Comment by ralinchan** [comment]
Like I said, this is not an issue with this script. If you got a version of this script that tries to open websites in another frame, you got it from somewhere suspect. It is something with what you have installed.

**Comment by minhchienwikipedia** [comment]
I just add excludes Youtube Music site for this script and use Adblock for Youtube Music and it works!
