### ISSUE TITLE
Spam error in dev tool

### ISSUE THREAD

**Issue by Gawasna** [TheRealJoelmatic/RemoveAdblockThing#163]
I have noticed that your code will spam errors when loading on the home page of YouTube for the first time.
Error: "Uncaught TypeError: Cannot read properties of undefined (reading 'targetId')" constantly spamming while on the home page
it causes lag and is a bit annoying :)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/140888030/f9b68728-4bac-46c4-9afe-d8f608123f28)
https://drive.google.com/file/d/1gh16nVbC5QHfgwRBzMhoWGkzn3fLX1xA/view?usp=sharing
I'm not familiar with JavaScript, but I found this : Or instead of using childElement.data.targetId, you can use childElement.data?.targetId. This will check if data exists before accessing the targetId property. If data does not exist, accessing targetId will be skipped and will not cause an error.

**Comment by TheRealJoelmatic** [comment]
This should be fixed in the latest version (2.6)
