### ISSUE TITLE
Error in youtube again.

### ISSUE THREAD

**Issue by CIoudStrife** [TheRealJoelmatic/RemoveAdblockThing#165]
I'm using Windows + Brave, with Ghostery + Tampermonkey addon for youtube premium, and some hours ago i still having the error, the windows get black.

**Comment by spreagit** [comment]
Same for me

**Comment by CIoudStrife** [comment]
> Same for me



> If you open it in a new window, it will play, but if you just play the video, only a black screen will appear and it will not play.

It working today!, mistake was only yesterday.

**Comment by singulararmchair** [comment]
It stopped working completely for me. Not sure when was the last time I went on YouTube; most likely in the past week.

**Comment by nstein5** [comment]
Open in a private window and ensure your extensions are enabled on private windows.
