### ISSUE TITLE
Adblocker doesn't work

### ISSUE THREAD

**Issue by syovzai** [TheRealJoelmatic/RemoveAdblockThing#166]
I think the reason why it's not working is cause I didn't install it properly. I got kinda lost after the 'Utilities' tab part cause I don't see where I'm supposed to create a new script as pictured below.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/77398864/2942e712-8443-4427-994c-fcb18141c1d1)

**Comment by nstein5** [comment]
Open in a private window and ensure your extensions are enabled on private windows.

**Comment by TheRealJoelmatic** [comment]
If you need help with installation check this video out. https://www.youtube.com/watch?v=72PPKv--xe4&t=6s&ab_channel=Joelmatic
