### ISSUE TITLE
Automatic skip doesn't work

### ISSUE THREAD

**Issue by 2019mikelee** [TheRealJoelmatic/RemoveAdblockThing#168]
Ad Speed up works, but I have to press skip ads buttons mannually.
![skip](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/63326549/4a89ba0a-7d05-48f0-af4a-540b65ec6834)

**Comment by TheRealJoelmatic** [comment]
This has been fixed in the latest version.
