### ISSUE TITLE
not blocking ads since 2023/12/7

### ISSUE THREAD

**Issue by Noire-Black-Heart** [TheRealJoelmatic/RemoveAdblockThing#175]
acts like there's not any adblocker installed since there's really not any

**Comment by vermaysha** [comment]
Are you using an extension like Enhancer For Youtube?

**Comment by xozi** [comment]
Confirmed, something updated recently that is mitigating. Ublock origin is also unable to block anything right now.

**Comment by xozi** [comment]
I just checked, it seems other ad-blockers are having issues currently. YouTube just updated the anti-adblock detection it seems so check what ad-blockers you have currently and trying disabling them temporarily. It seems this script is still working fine by itself.
