### ISSUE TITLE
Adblocker skips videos when in a playlist instead of just ads

### ISSUE THREAD

**Issue by OtakuChan49** [TheRealJoelmatic/RemoveAdblockThing#176]
Hello!

Thank you for the wonderful code you created. I can't express how much gratitude I have for all the contributors to this code. 
However, there is one major issue: when in a playlist, the adblocker skips the video entirely instead of just the ad, which in turn ends up skipping every video in the playlist without ever playing them. 
Could this issue be resolved? 
Much appreciated!

**Comment by Altex2** [comment]
+1

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
