### ISSUE TITLE
v5.6 is still broken. Downgrading to v5.3 is still the best solution. [Downgrade instructions included]

### ISSUE THREAD

**Issue by GroggyOtter** [TheRealJoelmatic/RemoveAdblockThing#1765]
**Script version**
v5.6

**Describe the bug**
- Next/previous buttons no longer show up on the video screen.
- "AutoPlay" toggle no longer shows up on the video screen
- Holding down left mouse on the video doesn't fast forward the video
- There was something else but I can't remember what it was...

**Desktop (please complete the following information):**
 - OS: Windows 10 v10.0.19045.4291
 - Browser: Chrome

**Additional context**
RAT has not worked since v5.3

**Temporary fix**
Downgrade to v5.3  

1. Go to the [v5.3 commit](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js)
1. Click the `Raw` button
1. TamperMonkey should open up asking if you want to downgrade.
1. Say yes.
1. Restart your browser and go to YouTube.
1. If you get a popup asking if you want to update, click the red skip button b/c 5.6 is broken.  
  When 5.7 comes out, you should get another notification asking if you want to update.

**Comment by csptt-alt** [comment]
Still getting double audio on v 5.3.
Workaround: Press spacebar and it should pause the first audio.

**Comment by Mendax1989** [comment]
TheRealJoelmatic removed the messages with fixes. 3.8 worked. 5.3 it's broken. Double Audio.

**Comment by Peryite89** [comment]
53 is broken for me, double audio. 5.6 works, but I get error message on YouTube for some videos, "Video not available.
Playback on other websites has been deactivated by the video owner. Watch on YouTube".

**Comment by GroggyOtter** [comment]
@csptt-alt  
@Peryite89  
@Mendax1989  

### Everything I say is from a Windows OS standpoint using Chrome browser and I do not speak for other operating systems or other browsers.

> Still getting double audio on v 5.3.

I've been using 5.3 since 5.4 came out and introduced the double audio bug.  
I've used 5.3 through 5.4, 5.5, and 5.6 because all of these are broken and 5.3 isn't.  
I can't figure out how certain others and saying 5.3 doesn't work for them when I've had zero issues with it for 2 weeks now.

If you have double audio, it is impossible you're on a version lower than v5.4 because that specific bug was introduced by 5.4.  
Double audio is confirmation you're not downgraded.

Check TamperMonkey.  
The script's version number should be displayed next to the script:
![chrome_FUTrTpQfsc](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/e91afa71-d8c2-43dd-a7cc-3c432300840f)

Go into the script itself, and there's a line up top that tells you the current version:
![chrome_RGdQkfCpx1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/35db8ddf-c11c-4200-80e9-2f9125eb4b97)

If that's not 5.3, you need to re-downgrade.

Other things that can help:

* Ensure you click "Skip" if the update popup happens.
* You can manually set the version from 5.3 to 5.6 so you won't get the update notification for 5.6.
  Change the `// @version      5.3` to `// @version      5.6`, click "File", then click save.
* Alternatively, you can change the line `const updateCheck = true` to `const updateCheck = false`.
  Make sure to save the script after editing.

@slzero-X  
Yeah, I reported a few of the people doing it but they're creating new accounts.  
Something like Daddy Ghost and Grand Daddy Ghost were posting earlier and those accounts are now deleted.

**Comment by brianrho** [comment]
Youtube engineers putting in that hard work.

**Comment by wiiotaku** [comment]
5.3 doesn't work anymore due to youtube improving its system to detect ads, 5.6 is broken but at least it skips ads

**Comment by GroggyOtter** [comment]
> 5.3 doesn't work anymore due to youtube improving its system to detect ads, 5.6 is broken but at least it skips ads

False. It's working perfectly fine. Have been using it since 5.4 came out without issue.

**Comment by leafygreens7** [comment]
5.3 is not working for me, youtube detects it and just puts up the "ad blockers violate youtube's terms of service" screen. Is there a reason why it works for you but does not function for me?

**Comment by 413jmee** [comment]
> 5.3 is not working for me, youtube detects it and just puts up the "ad blockers violate youtube's terms of service" screen. Is there a reason why it works for you but does not function for me?

i just refresh the page a few times and it eventually works. lately it’s been detecting midroll ads too but those have only taken a single refresh each. at this point its more about the principle for me, i’d rather be inconvenienced by semi-working adblock than be inconvenienced by youtube’s atrocious ad system.
