### ISSUE TITLE
Stopped working at all

### ISSUE THREAD

**Issue by clouds737** [TheRealJoelmatic/RemoveAdblockThing#178]
As of yesterday, after 2 months of grace, it stopped working 100%

**Comment by Mystery24601** [comment]
Yep, same thing here. I figured I'd check any alternative programs for blocking YouTube's problematic state (which YouTube already was to be honest. Ever since Google bought YouTube, it has only gone downhill) but no luck.

**Comment by Mystery24601** [comment]
However, the best option you can do now is use third-party apps like NewPipe (which is open-source and free) for your phone.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
