### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by chrysos77** [TheRealJoelmatic/RemoveAdblockThing#179]
it stopped working

**Comment by Ahmed5ameh** [comment]
It's not working on brave

**Comment by bobbhy** [comment]
Stopped working

**Comment by Ahmed5ameh** [comment]
> It's not working on brave

I cleared brave cookies and cache and that fixed it ;)

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
