### ISSUE TITLE
Maximizes the video instead of blocking the ads

### ISSUE THREAD

**Issue by akavi1** [TheRealJoelmatic/RemoveAdblockThing#180]
Weird behavior. When clicking on a related video and landing on the new video's webpage, the script seems to fullscreen the video, then returns it to the original size and displays a black screen where the video should be. Reloading the page triggers the normal function of this script, but I have to reload whenever I click on a related video

**Comment by Moose1005** [comment]
Glad to see I am not the only one

**Comment by TikaToka** [comment]
me too, if I refresh. then it works, but I always have to refresh 1 time to watch every single video

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
