### ISSUE TITLE
Create a new script button missing

### ISSUE THREAD

**Issue by Michael21107** [TheRealJoelmatic/RemoveAdblockThing#186]
There is no _Create a new script_ button in the _Utilities_ tab. At least not only there if u consider the + button it. #187  ![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/121039033/580592b8-7d97-4b87-8362-5ca7c632da85)____

**Comment by ralinchan** [comment]
the instructions should say to use import from file since you're downloading the raw from github

**Comment by Michael21107** [comment]
i dont think thats necessary since clicking the link is all i needed to install it (and confirming it ofc)

**Comment by TheRealJoelmatic** [comment]
If you need help installing the script check out this video: https://www.youtube.com/watch?v=72PPKv--xe4&t=6s&ab_channel=Joelmatic

**Comment by Michael21107** [comment]
I dont, just that one step wasn't accurate but I see it's fixed already
