### ISSUE TITLE
5.6 still broken, but all messages, including fixes, removed. Great job TheRealJoelmatic.

### ISSUE THREAD

**Issue by Mendax1989** [TheRealJoelmatic/RemoveAdblockThing#1874]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Mendax1989** [comment]
5.6 not working, remove adblock message, video not registered as watched, doublr audio.

**Comment by GroggyOtter** [comment]
I got you fam.

https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/1765
