### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Michael21107** [TheRealJoelmatic/RemoveAdblockThing#188]
upon installation, is the script automatically updated given that the user enables auto script updates in TM settings on every release?

**Comment by TheRealJoelmatic** [comment]
In the latest version (2.6) I've added an update checker that makes it simple to update when a new release is out.

**Comment by Michael21107** [comment]
so people still need need to update it somehow?

**Comment by TheRealJoelmatic** [comment]
https://clipchamp.com/watch/KGV1k0sZr2M

**Comment by Michael21107** [comment]
please, just yes or no

**Comment by Michael21107** [comment]
Will setting this make it update automatically?
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/121039033/79f51a1c-6901-4c3d-94fe-5115af2aa0aa)

**Comment by TheRealJoelmatic** [comment]
> Will setting this make it update automatically? ![image](https://private-user-images.githubusercontent.com/121039033/289381650-79f51a1c-6901-4c3d-94fe-5115af2aa0aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyMzkxMDAsIm5iZiI6MTcwMjIzODgwMCwicGF0aCI6Ii8xMjEwMzkwMzMvMjg5MzgxNjUwLTc5ZjUxYTFjLTY5MDEtNGMzZC05NGZlLTUxMTVhZjJhYTBhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMDA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYmMyZDgyZDk5OTJiNjFmMDZmYzZmY2MxMzQyYWMxODY5NmJjN2VjOGJlZmU2ZmYwZjQxYjM1NDI1N2M3MmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JjXNLhmJAUjg3bBh3JMz57mXFjt_4KYo8CYqLKydlkU)
in theory yea

**Comment by Michael21107** [comment]
why only in theory?
