### ISSUE TITLE
Blinking white box appears for a few seconds (two isses)

### ISSUE THREAD

**Issue by janmichael88** [TheRealJoelmatic/RemoveAdblockThing#189]
1. The blocker blocks ads but sometimes a thingy with like a survey pops up and I have the option to skip it, which I do right away.
2. Sometimes instead of the survey, I see a blinking white box (the size of one third of the video) flicker on and off for a few seconds.

**Comment by supersmith2500** [comment]
The Ad Center pops up in almost every video and it's starting to get more intrusive. Please fix.

**Comment by denn333** [comment]
Are you seeing an image like this?  I am getting it, too. I disabled personalized ads in Google, but I get this anyway.
![Untitled](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/73580082/ba179f0d-839a-4a4d-9f2a-ec5d8eff935e)

**Comment by ralinchan** [comment]
@denn333 Exactly what i'm seeing

That seems to be the flashing white box that appears but like half the time, it will stay and have to manually close it.

**Comment by janmichael88** [comment]
yup! thats what i am seeing!

**Comment by Necrome397** [comment]
I almost get seizures because of the flashing white box so I went back to a previous version where I have to skip manually but at least nothing is flashing all the time.

**Comment by mickleby** [comment]
I got the blinking white box for the first time today using 2.7
<img width="960" alt="image" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/1623707/52433623-d719-4921-96ab-2fb9fa046b12">

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
