### ISSUE TITLE
Ad Center Pops Up

### ISSUE THREAD

**Issue by Pooland1** [TheRealJoelmatic/RemoveAdblockThing#192]
<img width="714" alt="d" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/140262669/20e0bca9-0d4e-4170-a84c-b6d78c052c39">
This pops up when I click on a video

**Comment by Pooland1** [comment]
> doesn't this duplicate [#190 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/190#issue-2034093867) ??

Yeah, I was too lazy to screenshot this myself

**Comment by Michael21107** [comment]
i dont think u should open a duplicate issue (one that's already mentioned in a different one)

**Comment by Pooland1** [comment]
I have the right to do so, nobody is forcing me. This is my life, not yours

**Comment by mickleby** [comment]
> I have the right to do so, nobody is forcing me. This is my life, not yours

Actually, this is a community. So, we behave in pro-social ways and we make some effort not to create extra work for the mods and maintainers 😅

**Comment by Pooland1** [comment]
Ok.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
