### ISSUE TITLE
I soved the ad centre problem ( and mix skipping problem potentially):

### ISSUE THREAD

**Issue by Altex2** [TheRealJoelmatic/RemoveAdblockThing#193]
I figured out how the code works and I modified it so the ad centre thing does not show up anymore... this solution seems to solve the mix skipping problem... 

here is the code:

you need to open the .js file in a text editor ( NOTEPAD WORKS TOO BUT YOU WILL NOT SEE THE NUMBERED CODE LINES)

replace this code:

```
if (ad)
            {
                if (debugMessages) console.log("Remove Adblock Thing: Found Ad");

                const video = document.querySelector('video');
                const openAdCenterButton = document.querySelector('.ytp-ad-button-icon');
                const blockAdButton = document.querySelector('[label="Block ad"]');
                const blockAdButtonConfirm = document.querySelector('.Eddif [label="CONTINUE"] button');

                if (video) video.playbackRate = 10;
                if (video) video.volume = 0;
                if (video) video.currentTime = video.duration || 0;

                if (video) skipBtn?.click();

                openAdCenterButton?.click();
                blockAdButton?.click();
                blockAdButtonConfirm?.click();

                if (debugMessages) console.log("Remove Adblock Thing: skipped Ad (✔️)");
            }

```

(LINES 132 - 152)

WITH THIS CODE :

```
if (ad)
            {
                if (debugMessages) console.log("Remove Adblock Thing: Found Ad");

                const video = document.querySelector('video');
                const openAdCenterButton = document.querySelector('.ytp-ad-button-icon');
                const blockAdButton = document.querySelector('[label="Block ad"]');
                const blockAdButtonConfirm = document.querySelector('.Eddif [label="CONTINUE"] button');
                const closeAdCenterButton = document.querrySelector('zBmRhe-Bz112c');

                if (video) video.playbackRate = 10;
                if (video) video.volume = 0;
                if (video) video.currentTime = video.duration || 0;

                if (video) skipBtn?.click();

                openAdCenterButton?.click();
                blockAdButton?.click();
                blockAdButtonConfirm?.click();
                closeAdCenterButton?.click();
                

                if (debugMessages) console.log("Remove Adblock Thing: skipped Ad (✔️)");
            }
            
```
            

BE AWARE OF THE INDENTATION OF THE CODE IS IMPORTANT ... IF THE CODE IS NOT THE SAME INDENTATION AS BEFORE IT WILL NOT WORK!!

IT SHOULD LOOK LIKE THE SCREENSHOOT THAT I PROVIDED:
<img width="899" alt="Screenshot 2023-12-10 at 12 36 32" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/82447550/6cb3dc69-47bd-4191-8cfc-288217cd4e92">

**Comment by supersmith2500** [comment]
Still refuses to work and still getting these ANNOYING pop-ups. Is this Google's doing?

**Comment by Altex2** [comment]
> Still refuses to work and still getting these ANNOYING pop-ups. Is this Google's doing?

I need to test it more and yes, this is Google method to make more money

**Comment by supersmith2500** [comment]
I'm I doing something wrong?
![Untitled](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/153391692/2236e265-53fd-4529-b311-e1dce8109ea0)

**Comment by Altex2** [comment]
> I'm I doing something wrong?
> 
> ![Untitled](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/153391692/2236e265-53fd-4529-b311-e1dce8109ea0)
> 
> 

It should work! You did it right .. what app do you use to load the js file?

**Comment by Altex2** [comment]
> Hey! That works now! Commercials are now shown bit longer in time, but no ads center so far! Thank you! (using TFYT)

Glad I could help ❤️❤️

**Comment by hwisulee** [comment]
First of all, we are delivering the contents to you using a translator, so please understand.

After the update, the advertising center popped up, so I was angry and looked for the code.
In order for the advertising center window to appear, it must be clicked on that button in the advertisement.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/62528282/663b6aaf-e97a-43a7-8de7-a14784a9b7ca)

If you find the corresponding button in the RemoveAdblockThing code, you can find const openAdCenterButton in lines 132-152 the same as Altex2 wrote.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/62528282/0b248e29-87c1-49c6-8bdb-8e664d873015)

But I don't know why I need that button.
Looking at the past history of the code, I found that the item was added to the "New Skipping method and Cleaned up code".

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/62528282/5bf853db-5ee1-42db-920b-5e9cb0412ddc)

As everyone knows, however, without that button in the previous version of the code, the ad skip worked well, and we couldn't find any use in the current version. So I just tried using it after annotating it, but so far, I haven't found any problems.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/62528282/720cbadf-2b33-400f-ab42-f5c89e568242)

Maybe my developer friend forgot to handle that button after the test.
And, I would like to thank Altex2, who posted the information needed to resolve it quickly.

**Comment by supersmith2500** [comment]
Which app do I need? (Sorry for my low knowledge about coding.)
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/193#issuecomment-1848958216

**Comment by Altex2** [comment]
> Which app do I need? (Sorry for my low knowledge about coding.)
> 
> Nope. broken now.
> 
> https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/193#issuecomment-1848958216



To load the js:
If you are on Windows use tampermonkey!

If you are on mac use Userscripts!

Both are free..

**Comment by supersmith2500** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/193#issuecomment-1848968253
I already used it and it's still not fixed. Still pop-ups and now ads plays.

**Comment by supersmith2500** [comment]
Doesn't matter what I do. I'll just break the extension anyway. No way to fix. It's either ads or this annoyhing pop-up? Where are you @TheRealJoelmatic?

**Comment by TheRealJoelmatic** [comment]
Check out the latest version (2.6) it should be fixed now

**Comment by Altex2** [comment]
> Check out the latest version (2.6) it should be fixed now

Thank you for your implication <3 and for using my method of fixing it :))). Finally I did something great with my life ..

**Comment by TheRealJoelmatic** [comment]
Np, thanks for the solution :)

**Comment by Lulabellexd** [comment]
Hello, this is a dumb question but where do I find the js file for this remove adblock thing extension? Thanks in advance!
