### ISSUE TITLE
White box appears when an ad trys to load 

### ISSUE THREAD

**Issue by A-little-loony** [TheRealJoelmatic/RemoveAdblockThing#194]
starts  flashing on the screen and sometimes wont go away after pressing skip on the ad.  Sometimes refreshing the page makes it go away

**Comment by Michael21107** [comment]
looks like it's the ad preferences thing from YT as I saw it stay on the screen after the flickering ended

**Comment by prabhavagrawal7** [comment]
Same with me

**Comment by ExiStEnSs** [comment]
same

**Comment by 128ajb** [comment]
This happens every so often on 2.7 for me. the fix im using right now is just deleting the element if it pops up. takes a little longer than i'd like, but its better than ads. 5 seconds to remove a box is better than 45 seconds of ads

**Comment by prabhavagrawal7** [comment]
I am not facing this issue as of now

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
