### ISSUE TITLE
Pop-up of ads preferences

### ISSUE THREAD

**Issue by x9nico** [TheRealJoelmatic/RemoveAdblockThing#196]
Hey!
When I'm looking a youtube video, I have this pop-up : 

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/8091015/d6f9e2fa-2d0a-4fb5-a357-0d5f2b0be7fa)

Please disable it!

**Comment by TheRealJoelmatic** [comment]
should be fixed in the latest version (2.6)
