### ISSUE TITLE
tens of Spambots creating new issues.

### ISSUE THREAD

**Issue by Dimitris-Klis** [TheRealJoelmatic/RemoveAdblockThing#1966]
I found this article which might help ._.
https://dev.to/nikpoltoratsky/how-to-deal-with-github-spambots-5e6n

**Comment by GroggyOtter** [comment]
I'm in the process of reporting a slew of them directly to GitHub right now.  
Joel will need to come through and delete all the spam posts. GitHub doesn't do that.  

For those reading this, Ghost isn't a person.  
Ghost is the account that all deleted and banned accounts redirect to.  

If you see a post by "Ghost", that person has already been banned and the post is just waiting for deletion by Joel (or another repo admins).

**Comment by FrozenDragon0** [comment]
> I'm in the process of reporting a slew of them directly to GitHub right now. Joel will need to come through and delete all the spam posts. GitHub doesn't do that.
> 
> For those reading this, Ghost isn't a person. Ghost is the account that all deleted and banned accounts redirect to.
> 
> If you see a post by "Ghost", that person has already been banned and the post is just waiting for deletion by Joel (or another repo admins).

I feel so damn sorry for Joel with the amount of posts Joel's gonna have to delete.

**Comment by photosense** [comment]
I'm amazed I even saw this post. Is there a way to pin it? new to Github.
