### ISSUE TITLE
Scrolling broken?

### ISSUE THREAD

**Issue by lushythedev** [TheRealJoelmatic/RemoveAdblockThing#20]
Using the latest version that you published an hour ago on Monday, 16th October, however, since then scrolling down seems to be broken.

**Comment by svnkxmza** [comment]
The pause button is also broken.

**Comment by LSparkzwz** [comment]
I'm using it on firefox, I think that after the popup gets removed there's a semi transparent html element covering the whole page, which doesn't let you either scroll or interact with the page in other ways
Deleting the responsible node should fix that

**Comment by Albedo-13** [comment]
Currently working on solution. As temporarily decision you can toggle full screen video (click twice, open and close)

**Comment by MatiasBrunacci** [comment]
> Using the latest version that you published an hour ago on Monday, 16th October, however, since then scrolling down seems to be broken.

Same issue here!

**Comment by MatiasBrunacci** [comment]
> Currently working on solution. As temporarily decision you can toggle full screen video (click twice, open and close)

I can't since the greyed-out screen does not allow me to click on the video controls.

**Comment by tordenflesk** [comment]
> > Currently working on solution. As temporarily decision you can toggle full screen video (click twice, open and close)
> 
> I can't since the greyed-out screen does not allow me to click on the video controls.

F or Double-click.

**Comment by Albedo-13** [comment]
We're looking for solutions, but for last day there where no "Remove your adblock" annoying models for me. So can't actually test & improve script
