### ISSUE TITLE
Ad Centre is not properly closed after Ads are skipped

### ISSUE THREAD

**Issue by Thraxelon** [TheRealJoelmatic/RemoveAdblockThing#201]
When ads is detected, the script will open the Ad Centre, but it is not closed properly.
It will still play the video, but with the modal still open

**Comment by Thraxelon** [comment]
I commented out part of the script that opens this modal instead :
Line-173 `openAdCenterButton?.click();`
It is now working properly (for now).

**Comment by 128ajb** [comment]
commenting out line 173 did not seem to fix the issue for me

**Comment by Thraxelon** [comment]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/58166832/b5de3aa4-4c69-4071-82a2-7a8c26dd29ea)

Try restart browser or hard reload the youtube page?

**Comment by Thraxelon** [comment]
Closing this due to duplicate on #190
