### ISSUE TITLE
Ad Center fixed but Chapter button doesn't work with the command on

### ISSUE THREAD

**Issue by stainless1028** [TheRealJoelmatic/RemoveAdblockThing#202]
https://imgur.com/a/rfbcJfs

**Comment by Altex2** [comment]
I will try to fix it and come back with an update as soon as possible...

**Comment by Altex2** [comment]
I found I fix for your issue just remove the lines of code from line 212 - 226 , basically remove this code:

```
 document.head.appendChild(style);

        sponsor?.forEach((element) => {
             if (element.getAttribute("id") === "panels") {
                element.childNodes?.forEach((childElement) => {
                  if (childElement?.data.targetId && childElement?.data.targetId !=="engagement-panel-macro-markers-description-chapters"){
                      //Skipping the Chapters section
                        childElement.style.display = 'none';
                    }
                   });
            } else {
                element.style.display = 'none';
            }
         });
```

the js works just fine without it and the chapters now work

**Comment by Altex2** [comment]
> I found I fix for your issue just remove the lines of code from line 212 - 226 , basically remove this code:
> 
> ```
>  document.head.appendChild(style);
> 
>         sponsor?.forEach((element) => {
>              if (element.getAttribute("id") === "panels") {
>                 element.childNodes?.forEach((childElement) => {
>                   if (childElement?.data.targetId && childElement?.data.targetId !=="engagement-panel-macro-markers-description-chapters"){
>                       //Skipping the Chapters section
>                         childElement.style.display = 'none';
>                     }
>                    });
>             } else {
>                 element.style.display = 'none';
>             }
>          });
> ```
> 
> the js works just fine without it and the chapters now work

I WAS WRONG , I AM SORRY GUYS AFTER MORE TESTING I FOUND OUT THAT YOU JUST NEED TO REMOVE THE:

`document.head.appendChild(style);`

AT LINE 213 , IF YOU REMOVE JUST THAT LINE THE CODE WILL BE FULLY FUNTIONAL , EVEN THE ADS WILL NOT SHOW UP AND THE CHAPTERS WORK JUST FINE...
