### ISSUE TITLE
Ad Center still appears

### ISSUE THREAD

**Issue by supersmith2500** [TheRealJoelmatic/RemoveAdblockThing#204]
It's still not fixed and I'm still getting the pop-up.
I'm updated to 2.6.

**Comment by Altex2** [comment]
it does not appear anymore , you did not update it correctly somehow, I can help you do it , contact me on discord 
my username is : "plictisit" without "

**Comment by Smith873** [comment]
According to Tampermonkey, v2.6 of the script was installed on FireFox 27 hours ago.
The Ad Center pop up just appeared, so it's really happening. 
However, it doesn't happen all the time like before, just occasionally, like once every 3 or 4 Youtube videos.

**Comment by Altex2** [comment]
> According to Tampermonkey, v2.6 of the script was installed on FireFox 27 hours ago. The Ad Center pop up just appeared, so it's really happening. However, it doesn't happen all the time like before, just occasionally, like once every 3 or 4 Youtube videos.

for the last hour I was testing the js scrip ... the problem with 2.6 is that chapters are not working but not once I got the ad center....

**Comment by ralinchan** [comment]
> it does not appear anymore , you did not update it correctly somehow, I can help you do it , contact me on discord my username is : "plictisit" without "

Definitely still occurs having tried both the "Reinstall" option when importing the raw js as well as deleting the installed version and then installing the raw js as a new script

[https://i.imgur.com/S5Ms5kT.png](url)

**Comment by Altex2** [comment]
> > it does not appear anymore , you did not update it correctly somehow, I can help you do it , contact me on discord my username is : "plictisit" without "
> 
> Definitely still occurs having tried both the "Reinstall" option when importing the raw js as well as deleting the installed version and then installing the raw js as a new script. I can verify that I didn't install it wrong since the one line change at ln 183 changing "showen" to "block" is what I currently have in my installed version
> 
> ![adwhite](https://private-user-images.githubusercontent.com/78107359/289660634-2751d6c3-f13a-4ed5-a2e5-33d636bfa14e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjY4MjQsIm5iZiI6MTcwMjMyNjUyNCwicGF0aCI6Ii83ODEwNzM1OS8yODk2NjA2MzQtMjc1MWQ2YzMtZjEzYS00ZWQ1LWEyZTUtMzNkNjM2YmZhMTRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwMjg0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5NGM0OTE1MWZmZjU5OGE4YWI4MTViNTNhOTA0OTM5Y2Q1ZmUyYzVjNjM3NDQ3Y2E5OTAxYjI3MTBlYzBkOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4BaUmE22_i-qf7YfP2QQhPq6xaHjgQlVtNPw5TbgR4g)

hmm so weird...

**Comment by ralinchan** [comment]
Update: It's actually even worse than before since the original bug made the Ad Center persist but you could close it. And then it was "fixed" to only flash the white box. But this new "fix" made it so the white box persists and you can't close it because there's no option to interact with it.

**Comment by Altex2** [comment]
> Same here. After it was working perfectly and ads where superfast closed - also ad center - now it appears as blank white one. <img alt="Screenshot 2023-12-11 213546" width="1200" src="https://private-user-images.githubusercontent.com/81344443/289665569-78d36262-d0e1-4e09-be10-1d393cd08d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjc1MTEsIm5iZiI6MTcwMjMyNzIxMSwicGF0aCI6Ii84MTM0NDQ0My8yODk2NjU1NjktNzhkMzYyNjItZDBlMS00ZTA5LWJlMTAtMWQzOTNjZDA4ZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTM2OWZjZDMwOTAxZDc5MWE0NjEyOGUxNDM0YzEzM2UyOWIxM2JlMWY3ZTk2MWY4ZTNhNzMyYTllMTRhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bvHDjnwBDWuKbKOOHld2WqC6DaUp8aDvTVZ9pB2vYBg"> I just refresh then (F5)

if you want try to replace the line 164

this is the original:
`const closeAdCenterButton = document.querySelector('zBmRhe-Bz112c');`

replace it with this:
`const closeAdCenterButton = document.querySelector('.zBmRhe-Bz112c');`

tbh I had it like this from the begging so I think I fixed it accidentally.... lmao

**Comment by Altex2** [comment]
> Done! Works PERFECT! It was just right now flashing up for a micro second and boom...nothing to see. Just watching videos. THANK YOU!!! ♥

No problem , if you have anymore problems you can probably find my profile in the issues tab , I will try to fix whatever I can..

**Comment by ralinchan** [comment]
Implementing your white box fix (adding the period to ln 164) and your chapter button fix (commented it out instead of removing) makes it such that the script stops removing the sponsored video on the recommended page. It appears to be related to the chapter button fix (deletion/removal of ln 164) since if I put it back, the chapter button breaks again but the front page sponsored ad is blocked.

![sponsored](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/89ce9ced-3f40-4b33-b356-6f7bdad77b4b)

**Comment by dramr** [comment]
Ad blockers violate YouTube's Terms of Service
you need to refresh youtube vid morethan 10x everytime LOL.  the last version working well than whats new today.

**Comment by ralinchan** [comment]
And not running an adblocker goes against basic recommendations by the FBI. I challenge Google/Alphabet to prove to me none of their employees run an adblocker.

**Comment by supersmith2500** [comment]
> > > Same here. After it was working perfectly and ads where superfast closed - also ad center - now it appears as blank white one. <img alt="Screenshot 2023-12-11 213546" width="1200" src="https://private-user-images.githubusercontent.com/81344443/289665569-78d36262-d0e1-4e09-be10-1d393cd08d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMjc1MTEsIm5iZiI6MTcwMjMyNzIxMSwicGF0aCI6Ii84MTM0NDQ0My8yODk2NjU1NjktNzhkMzYyNjItZDBlMS00ZTA5LWJlMTAtMWQzOTNjZDA4ZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDIwNDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkZTM2OWZjZDMwOTAxZDc5MWE0NjEyOGUxNDM0YzEzM2UyOWIxM2JlMWY3ZTk2MWY4ZTNhNzMyYTllMTRhY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bvHDjnwBDWuKbKOOHld2WqC6DaUp8aDvTVZ9pB2vYBg"> I just refresh then (F5)
> > 
> > 
> > if you want try to replace the line 164
> > this is the original: `const closeAdCenterButton = document.querySelector('zBmRhe-Bz112c');`
> > replace it with this: `const closeAdCenterButton = document.querySelector('.zBmRhe-Bz112c');`
> > tbh I had it like this from the begging so I think I fixed it accidentally.... lmao
> 
> Done! Works PERFECT! It was just right now flashing up for a micro second and boom...nothing to see. Just watching videos. THANK YOU!!! ♥

Would this break the code?

**Comment by supersmith2500** [comment]
The double ads is breaking the extension now.

**Comment by supersmith2500** [comment]
2.7 and I'm still getting this. Is Google trying to find ways to break it?

**Comment by mickleby** [comment]
2.7 fixed the My Ad Center ...and 2.8 brought it back?

**Comment by ralinchan** [comment]
I'm currently on 2.8 with none of the code modifications listed in these issues (ie the fix chapter issue and stuff) and so far while I occasionally see white box flashes, I don't get white box or ad center persistence (this is having it installed for about 11hrs now).

FF 120.0.1

**Comment by rephlex-ctrl** [comment]
White box flashes yes. The the trick is to not show it at all. I hope someone can find a solution and block this ad center.
