### ISSUE TITLE
ban ghost for botting

### ISSUE THREAD

**Issue by WesleyTRV** [TheRealJoelmatic/RemoveAdblockThing#2041]
please, he is constantly bot spamming it with scams in issues.

**Comment by GroggyOtter** [comment]
Ghost isn't a person. It's the account that all banned/deleted accounts get redirected to.  
Meaning all those Ghost posts are people who have been banned.  
But GitHub doesn't clean up their spam, so it's leftover. Joel has to clean up the excess crap.

And I literally in the process of putting in a manual report on about 15 spam accounts that are all active on this repo, so those will be getting banned shortly.

**Comment by photosense** [comment]
Keep up the good work! 

We appreciate you.
