### ISSUE TITLE
HOW TO FIX CHAPERS NOT WORKING ( CLICK HERE FOR FIX)

### ISSUE THREAD

**Issue by Altex2** [TheRealJoelmatic/RemoveAdblockThing#205]
IF YOU FIND THAT CHAPERS DO NOT WORK ANYMORE WITH THE VERSION 2.6 YOU ARE NOT THE ONLY ONE , HERE IS HOW YOU CAN FIX THAT..

YOU WILL NEED AN TEXT EDITOR ( I PREFFER VISUAL STUDIO CODE ,BUT ANY TEXT EDITOR WILL WORK EVEN NOTEPAD)

FIND THE LINE 213:

IT SHOULD LOOK LIKE THIS : 

`document.head.appendChild(style);`

JUST REMOVE THAT LINE AND SAVE THE JS... NOW THE CHAPERS WILL WORK AGAIN AND EVERITHING( edit it does not remove the ads on the right , on top of recommended so I am stupid, sorry...) WILL WORK PERFECTLY.

**Comment by ralinchan** [comment]
Removal of ln 213 makes it so that the front page sponsored ad video no longer gets blocked

![sponsored](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/89ce9ced-3f40-4b33-b356-6f7bdad77b4b)

**Comment by Altex2** [comment]
> Removal of ln 213 makes it so that the front page sponsored ad video no longer gets blocked so it fixes the chapter button but brings back some ads
> 
> 
> 
> ![sponsored](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/89ce9ced-3f40-4b33-b356-6f7bdad77b4b)

Yeah i know about that too , sorry , at least it fixes the chapter problem .. is late so i can't find a solution today...

**Comment by ralinchan** [comment]
Interesting thing to note: #207 

There is apparently a problem viewing/making comments on shorts and removing ln 213 to fix chapter button also appears to fix the shorts comment issue
