### ISSUE TITLE
Unable to view or make comments on shorts

### ISSUE THREAD

**Issue by ralinchan** [TheRealJoelmatic/RemoveAdblockThing#207]
It appears related to the chapter button bug, but with the new commit that "fixes" the white box/ad center problem (or rather doesn't), it also made it so you cannot view or make comments on Youtube shorts videos.

In the listed issue saying that it's the fix for the chapter button (removing ln 213), doing so also reinstates the ability to view/make comments on shorts

**Comment by Altex2** [comment]
I found a better fix #209
