### ISSUE TITLE
HOW TO FIX CHAPTERS AND SHORTS COMMENTS NOT WORKING(UPDATE)

### ISSUE THREAD

**Issue by Altex2** [TheRealJoelmatic/RemoveAdblockThing#209]
THIS IS AN UPDATE TO THE PREVIOUS FIX THAT I HAVE POSTED... HERE IS THE CODE THAT YOU NEED TO UPDATE 

YOU NEED TO REPLACE THE CODE FROM LINES 194-228 WITH THIS UPDATED CODE:

```
function removePageAds(){

        const sponsor = document.querySelectorAll("div#player-ads.style-scope.ytd-watch-flexy, div#panels.style-scope.ytd-watch-flexy");
        const style = document.createElement('style');

        style.textContent = `
            ytd-action-companion-ad-renderer,
            div#root.style-scope.ytd-display-ad-renderer.yt-simple-endpoint,
            div#sparkles-container.style-scope.ytd-promoted-sparkles-web-renderer,
            div#main-container.style-scope.ytd-promoted-video-renderer,
            ytd-in-feed-ad-layout-renderer,
            .ytd-video-masthead-ad-v3-renderer,
            div#player-ads.style-scope.ytd-watch-flexy,
            #masthead-ad {
                display: none !important;
            }
        `;

        document.head.appendChild(style);

        sponsor?.forEach((element) => {
             if (element.getAttribute("id") === "rendering-content") {
                element.childNodes?.forEach((childElement) => {
                  if (childElement?.data.targetId && childElement?.data.targetId !=="engagement-panel-macro-markers-description-chapters"){
                      //Skipping the Chapters section
                        element.style.display = 'none';
                    }
                   });
            }
         });

         if (debugMessages) console.log("Remove Adblock Thing: Removed page ads (✔️)");
    }
```

BASICALLY I REMOVED THE LINE 207 THAT TARGETS THE CHAPTERS BOX , THEY HAVE THE SAME CLASS AS THE ADS BOX...

IF YOU FIND ANY ISSUES WITH THIS UPDATED CODE PLEASE CONTACT ME OR REPLY TO THIS THREAD <3

**Comment by Altex2** [comment]
@TheRealJoelmatic ......

**Comment by ralinchan** [comment]
So far it seems to be working. Shorts comments and chapter button works. Also appears to have reinstated removal of the front page video ad.

However it seems to have brought back the video ad for recommended videos that shows on the right side of videos:

![rightsidead](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/1be14db8-f850-4dd1-88c9-5df894efd6e8)

**Comment by ralinchan** [comment]
After further testing, using the 2.7 commit by @TheRealJoelmatic and implementing your line replacements, i've been able to run into the persistent ad center again:

![adcenter](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/60fa3f59-5bf4-4ace-b2d8-9825064ca50d)

**Comment by DRCLEMENTAKATENG** [comment]
I am afraid the update and replacement code:114 - 228 is not working on my system.

**Comment by ralinchan** [comment]
After even more testing, I can also confirm that the white screen persistence is again an issue with 2,7 + @Altex2 's replacement code

![whitescreen27](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/519d577d-38cd-42f9-b1a9-1786bf9ab5fb)
