### ISSUE TITLE
flashing white light when blocking ads

### ISSUE THREAD

**Issue by Thee-dandy** [TheRealJoelmatic/RemoveAdblockThing#213]
![afadawwcadawdacwd](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/153705237/1bf5fe88-684e-4eb3-aab0-f9d5bcf49a2d)
no idea why its doing that havent tweaked anything 🤷‍♂️

**Comment by Thee-dandy** [comment]
obv the flash wont show up without me clipping it but you probably get the picture with the solid white text

**Comment by Nibishi** [comment]
It's from the google ad center. The script tries to block it causing a white box to generate instead I think.

**Comment by ol9999** [comment]
I am also having this problem. Before, it used to show a box that explained why I got whatever ad was blocked, and I would have to click an x to get rid of the box. After the update, it just turns the box white and gets rid of the x so I have to reload the page instead.

**Comment by jfvilleforceix** [comment]
Got the same. The corresponding HTML code is : 
`<iframe id="iframe" class="style-scope yt-about-this-ad-renderer" src="about:blank"></iframe>`

**Comment by Radzio-cmd** [comment]
> Got the same. The corresponding HTML code is : `<iframe id="iframe" class="style-scope yt-about-this-ad-renderer" src="about:blank"></iframe>`

@jfvilleforceix  Where can I paste this code?
