### ISSUE TITLE
ad center becomes white and unclosable when script tries to close it

### ISSUE THREAD

**Issue by Lassf** [TheRealJoelmatic/RemoveAdblockThing#215]

**Comment by Carlcamp** [comment]
been having this issue sense update 2.7

**Comment by bizbazboz** [comment]
same. Hope it's fixed soon
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/66413191/88a48841-6277-4a3f-bffa-24fc71cb0c36)

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
