### ISSUE TITLE
Update blocked

### ISSUE THREAD

**Issue by Michael21107** [TheRealJoelmatic/RemoveAdblockThing#219]
update notice also appears on sites that use youtube embedded but after clicking update it says it cant be installed from this site

**Comment by SleepingPig35** [comment]
Please give an example site!

**Comment by Michael21107** [comment]
https://www.gta5-mods.com/

**Comment by Michael21107** [comment]
also, it downloaded the script to my downloads folder which it didn't do on successful updates previously

**Comment by AndyTunnah** [comment]
I had this happen to me, it was "stuck" on 2.7. I opened tampermonkey, clicked utilities tab, then chose "import from file", then selected the file downloaded manually. Now I'm on 2.8 and all is fine!

**Comment by TheRealJoelmatic** [comment]
A new less intrusive update popup as now been added that should fix any problem like this.
