### ISSUE TITLE
opens my ad center on skip after the ad plays for a moment

### ISSUE THREAD

**Issue by Madeline69a** [TheRealJoelmatic/RemoveAdblockThing#221]
the ad shows the first frame (i dont know how i have it i disabled every adblock and only have this on) and then skips
and now it opens the my ad center popup
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/133543130/19bfbc93-2f2c-4896-8546-10ed479c8a05)

**Comment by kaliko69** [comment]
Same problem

**Comment by BreakzWasTaken** [comment]
Same problem also

**Comment by Necrome397** [comment]
I'm using version 2.0 again because I can't find 2.4. I have to skip ads sometimes but at least I can skip them and don''t have to bother with something flickering over the whole screen or the stupid ad center popup.

**Comment by ralinchan** [comment]
> I'm using version 2.0 again because I can't find 2.4. I have to skip ads sometimes but at least I can skip them and don''t have to bother with something flickering over the whole screen or the stupid ad center popup.

You can find all the past commits. Just click on the .js script file to bring up the raw code on Github, then in the upper right click on History.

You'll find 2.4 in the December 1 commit labelled something like Merge Pull Request #116 

Then click the 2nd icon that looks like <> on a piece of paper that's labelled "View code at this point". Then you can download it in the upper right

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
