### ISSUE TITLE
JOEL HELP, SPAM BOT!

### ISSUE THREAD

**Issue by ghost** [TheRealJoelmatic/RemoveAdblockThing#2219]
SPAM BOT ALERT!
ghost is spamming to try compromising acccounts
Take immediate action!
Take IMMEDIATE ACTION!

**Comment by dramr** [comment]
up

**Comment by DanteAnuj** [comment]
up

**Comment by sorphin** [comment]
I already reported it to github and they said "The ghost username is in place to designate accounts that have been deleted by their owners, but that still have content that is visible across the GitHub platform. If you have write permissions to a repository, you can hide, edit, or delete comments from ghost users with the tools described here:"   I told them again to look at the issues here to see all the spam, we'll see if they even do anything/care.

**Comment by TheRealJoelmatic** [comment]
> SPAM BOT ALERT! ghost is spamming to try compromising acccounts Take immediate action! Take IMMEDIATE ACTION!

Ik as its spams my notis Ive tried blocking them ect but Idk how to fix it. Ill keep closing the issues but its just really annoying

**Comment by raffaem** [comment]
Maybe we can move the repo to gitlab, codeberg or the like

**Comment by JNogaj** [comment]
What are the odds YT is behind this attack...
