### ISSUE TITLE
The Share Post overlay pops up after an Add plays and won't go away when clicking the X button.

### ISSUE THREAD

**Issue by Kain0140** [TheRealJoelmatic/RemoveAdblockThing#222]
Refreshing is the only way to remove it.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/146393683/86c88998-e90b-4f71-9357-97232ac1744c)

**Comment by ralinchan** [comment]
I think it has to do with some sort of interaction with the last option window you popped up and then it tries to block an ad. For me, if I use the save function to save a video to a playlist, the next time it tries to block an ad it will bring up my save window with all my playlists and like your share frame, I am unable to close it without refreshing the page.
