### ISSUE TITLE
Unable to see text when making a new comment thread

### ISSUE THREAD

**Issue by ralinchan** [TheRealJoelmatic/RemoveAdblockThing#223]
Using the newest 2.8 on Firefox 120.0.1

When attempting to make a new comment thread, I am unable to see the any text typed. This does not appear to be an issue if you make a reply comment to an existing comment thread.

As an example, I show typing the phrase "Unable to see text" and highlighting the center portion.

![notext](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/78107359/42054573-c844-4cd9-9264-dfe400c0838d)

Edit - Further notes, it appears that the text will become invisible even if you try to edit any comments you've already made including comments that are replies that don't initially have this issue.

**Comment by TheRealJoelmatic** [comment]
This is not a problem related to the script.
