### ISSUE TITLE
This is the only extension I am using and it keeps sending me out of my playlist to random hour long lofi music videos 

### ISSUE THREAD

**Issue by Whynotreally** [TheRealJoelmatic/RemoveAdblockThing#225]
I wanted to receive no ads for watching youtube for music and what I got was some sketchy content view farming it's the same video everytime. It is anytime I am on a playlist the next video after five ends me to said lofi songs video.

**Comment by AlphaSteam** [comment]
You're commenting this in the issues tab of the GitHub page for the script... It literally is open source. You can read what the script does.

This doesn't make sense.
