### ISSUE TITLE
Tab freezes after script removes popup

### ISSUE THREAD

**Issue by Bluestar5101** [TheRealJoelmatic/RemoveAdblockThing#23]
Screen tints ever so slightly black, and I can no longer click on anything on the tab. Video keeps playing.

**Comment by enzomatu1** [comment]
yeah happening to me too i guess is because the pop-up is technically still there, you just cant click off anymore

**Comment by ssmithTaylor** [comment]
I've seen it too, but it only seems to occur occasionally.

**Comment by Albedo-13** [comment]
Just created new PR that seems to fix this issue (hope so). Try out new script version after approval

**Comment by TheRealJoelmatic** [comment]
This should be fixed now
