### ISSUE TITLE
New way to bypass ads

### ISSUE THREAD

**Issue by YT-Advanced** [TheRealJoelmatic/RemoveAdblockThing#231]
In Russia, we don't have any Ads in YouTube, so I think you can fake the user location and bypass ads

**Comment by SleepingPig35** [comment]
Now, that is an interesting idea!
But from my current understanding, YouTube detects user location (correct me if I'm wrong) from the IP address so we can only bypass via a VPN, thus, its not a viable solution to just "fake" the user location and bypass the ads.
