### ISSUE TITLE
Doesn't click the final skip

### ISSUE THREAD

**Issue by JustGuerreiro** [TheRealJoelmatic/RemoveAdblockThing#232]
When a skipable ads apears, it skips the video but shows the final screen to install or check the website or wtv with a skip button.
it looks like it's clicking to skip because its flickering but it might be clicking the wrong place because it isn't skiping

![Screenshot_14](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/77629222/b271d02c-a124-4b04-9f31-b036797496a4)

**Comment by Michael21107** [comment]
the entire screen of youtube is flickering, like dim to bright

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
