### ISSUE TITLE
Ads on Top Right of video is still active

### ISSUE THREAD

**Issue by x9nico** [TheRealJoelmatic/RemoveAdblockThing#233]
**Describe the bug**
An ads pop-up is still active at the top-right of video when we're looking a video (see screenshot) : 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/8091015/5e6e9b30-9fe9-4914-9ba0-f712221cf059)

**To Reproduce**
1. Just go on a video

**Expected behavior**

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/8091015/5e6e9b30-9fe9-4914-9ba0-f712221cf059)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows
 - Browser [e.g. chrome, safari] : Chrome
 - Version [e.g. 22] : 120.0.6099.130

**Additional context**

**Comment by WesternGamer** [comment]
Also have the same issue, does not occur all the time: 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/80211714/bf12c7c8-3ba8-4949-900a-887d7ffb5d3e)

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.

**Comment by x9nico** [comment]
> This was fixed in the latest version.

Hello, in 4.0, it's still here...
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/8091015/c9a591b7-2128-46b9-ab6e-bcf0e6985446)
