### ISSUE TITLE
Doesnt skip ads non video

### ISSUE THREAD

**Issue by 9jaw** [TheRealJoelmatic/RemoveAdblockThing#236]
when you see ads not video mostly it doesnt skip, so i edit the script 

disable this 

`openAdCenterButton?.click();
blockAdButton?.click();
blockAdButtonConfirm?.click();
closeAdCenterButton?.click();
`
and edit this 
`const nonVid = document.querySelector(".ytp-ad-skip-button-modern");`
to this
`const nonVid = document.querySelector(".ytp-ad-skip-button-modern,.ytp-ad-skip-button-slot");`

update
that one doesnt work on my pc but worked fine on my laptop, pretty weird

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
