### ISSUE TITLE
Popup diappears, video does not play. (Newest Opera Version)

### ISSUE THREAD

**Issue by Foxin05** [TheRealJoelmatic/RemoveAdblockThing#24]
I just installed this feature but it doesn't seem to be working. When activated, the popup disappears, but nothing is happening after that. The Video doesn't play, there is just a blank space, where the video should be. I am usesing the Opera Browser on the latest Version (17th Oct. 2023).

**Comment by TheAGames10** [comment]
I am having similar issues, the pop-up disappears, but the overlay is still there, greying everything out and the video cannot play.

Refreshing seems to fix it, but I feel like it's only for a temporary amount of time, Making me feel like every video I play will have the same issue. (I am on the latest version of Chrome, btw)

**Comment by Albedo-13** [comment]
Just created new PR that seems to fix this issue (hope so). Try out new script version after approval
