### ISSUE TITLE
Playback speed does not recover after an ad

### ISSUE THREAD

**Issue by Atype12** [TheRealJoelmatic/RemoveAdblockThing#240]
**Describe the bug**
The double-speed playback speed does not recover after an ad plays.

**To Reproduce** Steps to reproduce the behavior:
1. Play any video.
2. Change the video playback speed (any speed other than 1x)
3. When return to the original video after skipping the ad, the video playback speed has changed back to 1x.
4. To restore the previously set playback speed, I need to adjust the speed one more time.

**Expected behavior**
Whenever It skip an ad, the speed playback setting is always reset to 1x. For example, if the Previous speed was 1.5x, the playback speed of the video after the ad changes to 1x. However, it's still at 1.5x in the player's settings. So to get it playing at 1.5x again, I need to change it to 1.25x or 1.75x and then back to 1.5x for the settings to take effect.

**Desktop (please complete the following information):**
- OS: Windows 11
- Browser : Chrome
- Version : 120.0.6099.130

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
