### ISSUE TITLE
Update check pop up continues, even when the script is already updated.

### ISSUE THREAD

**Issue by GageHeibeck** [TheRealJoelmatic/RemoveAdblockThing#245]
**Describe the bug**
Every time I open up a new tab on YouTube, it tells me to update the script even though it's already on 2.9. 

**Expected behavior**
For it to not pop up at all when disabling the update check in the code.

**Screenshots**
https://imgur.com/a/LmblypB (Both screenshots are through this link)

**Desktop**
 - OS: Windows 10 22H2
 - Browser: Firefox
 - Version: 121.0

**Comment by TheRealJoelmatic** [comment]
A new update popup has been implemented now that is no longer intrusive.
