### ISSUE TITLE
Tiny dot in the middle of the screen and player

### ISSUE THREAD

**Issue by itsmetoolala** [TheRealJoelmatic/RemoveAdblockThing#247]
Hey!
Great work! Everything works fine since last update!

But there is still a small problem that occurred before the last update.
After a while, a small dot will appear on the screen. Right in the middle.
If in full screen, in the middle.
If as a "normal" player, it is more in the middle of the player.
See the screenshot.
Yes, for me it's a purple dot because I have a corresponding background.
So the point depends on the background. So maybe white or black.
Please ask if you still have any questions.
Thank you for this great work!
<img width="239" alt="Screenshot 2024-01-05 045059" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/81344443/75f98e94-f1c0-454c-b720-6f407d0eee37">

**Desktop (please complete the following information):**
 - OS: Win 11 newest updates (daily checked)
 - Browser: chrome, daily updated

**Comment by TheRealJoelmatic** [comment]
I actually noticed this myself as it's a purple dot for me so it's a little more noticeable, I'm going to look into what seems to be causing this but i cant make any promises.

**Comment by AuZ-ASD** [comment]
#369

**Comment by TheRealJoelmatic** [comment]
This has been fixed in the latest version.
