### ISSUE TITLE
"Save video to..." stuck in videos playback

### ISSUE THREAD

**Issue by rephlex-ctrl** [TheRealJoelmatic/RemoveAdblockThing#248]
"Save videos to" the message box appears and cannot be closed except by refreshing the page. And after clearing all cookies on the page - again same thing.
![Screenshot 2024-01-06 014830](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/65548932/6a1a367d-daed-444e-80b9-ec1470a25203)

**Comment by rephlex-ctrl** [comment]
Started showing it very often. It's annoying. Hmm

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
