### ISSUE TITLE
fast forwarding ads

### ISSUE THREAD

**Issue by kcheyes** [TheRealJoelmatic/RemoveAdblockThing#25]
i've noticed that when ads show up on something i'm watching, they're fast forwarded super quickly and disappear in no more than a second or two. is this how it's intended to work? if so, it's quick enough that it doesn't necessarily bother me, but i'm wondering if there's a way to mute the ads while they're fast forwarding? it's a bit of a jump scare when it happens, especially when i'm watching a video where the sound is a bit lower and then i get a loud mid-roll. even though it's over almost instantly, it's still a sudden burst of noise.

**Comment by JEmlay** [comment]
Same question.  This is weird behavior.  Other solutions do not do this.

**Comment by DobroslavD8** [comment]
Same, +1. Might be good enough to have those ads muted if there's no way to not see them.

**Comment by PaulCvasa** [comment]
same here

**Comment by JEmlay** [comment]
@kcheyes Did you find an answer?  Why was his closed?

**Comment by kcheyes** [comment]
@JEmlay the script was updated a few hours ago and the ads are now muted.

**Comment by JEmlay** [comment]
Ah ok, thanks!
