### ISSUE TITLE
Merged

### ISSUE THREAD

**Issue by MrShadow041** [TheRealJoelmatic/RemoveAdblockThing#251]
Just happens when i open any video on youtube.

**Comment by Maetorn** [comment]
same issue here. using Opera. After the latest update at Opera caused the issue

**Comment by MahbbRah** [comment]
same issue here -- using brave

**Comment by TheRealJoelmatic** [comment]
Merged to here; https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/254
