### ISSUE TITLE
Dark spot in the middle of the screen

### ISSUE THREAD

**Issue by KubLuk24** [TheRealJoelmatic/RemoveAdblockThing#252]
**Describe the bug**
A dark spot appears in the middle of the screen with the script enabled. It happens only on youtube and with the script enabled so I know there is not an issue with my screen. (tested using the Eizo screen test site)

**To Reproduce**
1. Simply use the script as normal (happens randomly, may be gone after a refresh)
2. For better visibility of the issue, play a bright video

**Expected behavior**
A dark spot will be seen in the middle of your screen, it will keep being in the center as you scroll through the site.

**Screenshots**
Video of me measuring the colors in selection screenshot I captured of it
https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/47034744/b4b23aa1-0b09-45de-af5e-839b51f2e86c

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.0
 - Browser Chrome
 - Version 120.0.6099.109

**Additional context**
Happens randomly, may be gone after refreshing the page.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/247
