### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by Rambo1116** [TheRealJoelmatic/RemoveAdblockThing#253]
It does not work for me since I updated to the current version (2.9).
Could somebody help? I'm using Opera GX, I don't know if that's a problem!?

**Comment by Rambo1116** [comment]
I tried it with Google Chrome, it works on that platform.

**Comment by fmassaretto** [comment]
For me too, it didn't work on Edge Version 120.0.2210.121

**Comment by TheRealJoelmatic** [comment]
Please specify your problem clearly as I'm not sure what actually is not working.
