### ISSUE TITLE
the image is frozen at the first advertisement normally this is skipped after the update this no longer works

### ISSUE THREAD

**Issue by Armin0101** [TheRealJoelmatic/RemoveAdblockThing#259]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Armin0101** [comment]
the image is frozen at the first advertisement normally this is skipped after the update this no longer works

**Comment by Armin0101** [comment]
![Unbenanntfdgdf](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/94218238/6648c27d-4d92-4ef1-8ac9-41274558af18)

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
