### ISSUE TITLE
Popup disappears early (good), but disables page scrolling (bad)

### ISSUE THREAD

**Issue by BrochachoTheBro** [TheRealJoelmatic/RemoveAdblockThing#26]
This popup is the most stubborn thing on the planet, I swear.

**Comment by SomeoneWhoJustWantsToBeHappy** [comment]
Can confirm, the popup does disappear a mere second or two after it appears, but then scrolling is disabled in a weird way. As in, when attempting to scroll down or click the page-down button, it sort of just jiggles in place as if trying to break free.
