### ISSUE TITLE
Popup bug in Google search

### ISSUE THREAD

**Issue by WesleyTRV** [TheRealJoelmatic/RemoveAdblockThing#261]
**Describe the bug**
A popup occurs on Google Search and happens repeatedly.

**To Reproduce**
1. Go to google.com
2. Search anything
3. encounter the bug

**Expected behavior**
If attempted to search towards Google Search, the popup will occur and will happen repeatedly. If you attempt to click OK, the Windows Explorer window will open to place the download. I wouldn't recommend it. Clicking on cancel will prevent from downloading.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/102339203/8fa8a337-6da3-43ec-8c72-e20375faa86b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by TheRealJoelmatic** [comment]
A new update popup has been implemented now that is no longer intrusive.
