### ISSUE TITLE
ads are now appearing regardless, seems google has caught wind of this.

### ISSUE THREAD

**Issue by slzero-X** [TheRealJoelmatic/RemoveAdblockThing#262]
Not only that, reports of it saying "violate youtube's terms blahblah" is also appearing as well, its was bound to happen at some point.

**Comment by slzero-X** [comment]
I've modified the script myself and to avoid the risk of Google immediately seeing the changes, I am keeping this modification private, if the popup somehow starts appearing i'll change the script again.

If only there were some way to make it polymorphic...

**Comment by britannic192** [comment]
I had the same issue as well after updating to v 3.1. I uninstalled then reinstalled v 2.9 and that seems to have fixed it for now. I pasted the URL for v 2.9 below, click on "Youtube-Ad-blocker-Reminder-Remover.user.js".

https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v2.9

**Comment by glassjar99** [comment]
> I had the same issue as well after updating to v 3.1. I uninstalled then reinstalled v 2.9 and that seems to have fixed it for now. I pasted the URL for v 2.9 below, click on "Youtube-Ad-blocker-Reminder-Remover.user.js".
> 
> https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v2.9

Thanks!

**Comment by Pooland1** [comment]
It works for me, try turning on your ADBLOCKER (Adguard etc.)

**Comment by Pooland1** [comment]
Alongside with the plugin

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2

**Comment by glassjar99** [comment]
> Fixed in 3.2
Thanks!!!

**Comment by glassjar99** [comment]
> Fixed in 3.2

Thanks!!!
