### ISSUE TITLE
Stop working since today...

### ISSUE THREAD

**Issue by CorpseSlayer** [TheRealJoelmatic/RemoveAdblockThing#263]
Script is no longer working , when accessing youtube this happens

![image_2024-01-11_162318974](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/126618918/054d05e3-71b6-4200-95f6-23f2077e7fc7)

it been happening since this morning , today 1/11/24

**Comment by supersmith2500** [comment]
Have you tried updating the script?

**Comment by slzero-X** [comment]
the script was just updated, and its appearing regardless, so that response seems very automated.

**Comment by Doggie52** [comment]
I updated a few minutes ago and started getting these issues, it was working fine before the update that came in a few minutes ago.

**Comment by Nigromante2004** [comment]
Same problem here. I hope see next update solve this problem

**Comment by babylard** [comment]
> the script was just updated, and its appearing regardless, so that response seems very automated.

I believe when it detects the adblocker message it just shows a message saying an update is available, assuming it's already been patched. I'd just wait for now.

**Comment by WoeIsLee** [comment]
Restarted my laptop in an attempt to get the lag/latency to take a hike, which worked, but...........that also made me update this.......lol

**Comment by skakhund** [comment]
Does not work for me either :(

**Comment by Toku69** [comment]
i would try to revert to an older version, working for me right now

**Comment by razercore** [comment]
I have this same problem. The script stopped working after I updated today.

**Comment by WoeIsLee** [comment]
> i would try to revert to an older version, working for me right now

Not the biggest expert here, how do I do that?

**Comment by quackwag** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v2.9


Click the 'Youtube-Ad-blocker-Reminder-Remover.user.js' file, Tampermonkey will ask you if you want to downgrade to 2.9. Click ok

**Comment by WoeIsLee** [comment]
Thank youuuu

**Comment by WoeIsLee** [comment]
Actually that doesnt work either.

**Comment by SpunkyB21** [comment]
Yeah, don't bother reverting back, because it still doesn't work.

**Comment by MuhammetCanLikya** [comment]
None of the versions working. I think Youtube's developer team fixed this script.

**Comment by razercore** [comment]
Reverting fixed it for me.

**Comment by WoeIsLee** [comment]
So I just did some looking on greasyfork and the first one I installed worked and I think I know what the problem is.
Youtube changed the layout of the player itself.
When paused it adds a row of "more videos" at the bottom of the video, essentially the same thing that already exists, and it also adds a copy link button at the top right.
My best guess is that those tweaks, messed the script up somehow.

**Comment by SpunkyB21** [comment]
> So I just did some looking on greasyfork and the first one I installed worked and I think I know what the problem is. Youtube changed the layout of the player itself. When paused it adds a row of "more videos" at the bottom of the video, essentially the same thing that already exists, and it also adds a copy link button at the top right. My best guess is that those tweaks, messed the script up somehow.

What did you install that worked?

**Comment by WoeIsLee** [comment]
I dont really feel like announcing it, a simple search for what we're looking for, and you'll find it in like a minute like I did.

**Comment by SpunkyB21** [comment]
> I dont really feel like announcing it, a simple search for what we're looking for, and you'll find it in like a minute like I did.

Fair enough, but the first one I found on Greasyfork didn't work for me, either. 🤷‍♀️

**Comment by WoeIsLee** [comment]
Same for me, but the next two I found did.

**Comment by SpunkyB21** [comment]
Managed to find one that worked for me, at least for now until this one is fixed.

**Comment by MuhammetCanLikya** [comment]
Maybe you can call me paranoiac but yesterday i uploaded a video on youtube showing this repo to how to install this script and 30 hours later they made a change for this script. I was saying in that video "Remove the adblock thing.". To not this thing happen again if i write a script for this i will share with patreon subcription. I'm not writer of this script.

**Comment by WoeIsLee** [comment]
Not that I spent much time looking but out of the three I installed, two work. Side note, enabling this with them on too, makes this work again so lol.

**Comment by WoeIsLee** [comment]
Just curious, is youtube acting like your not actually watching a video on youtube itself?
Like for example, age restricted videos like this one, https://www.youtube.com/watch?v=EWIe6gPndm8
Its acting as if im not actually on youtube.

**Comment by WoeIsLee** [comment]
> Managed to find one that worked for me, at least for now until this one is fixed.

I just looked at the most recent thread and somebody said downgrade to 2.5
Its working perfect again.

**Comment by mrunknown690** [comment]
1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)

2. Go to the Releases tab on the left hand side bar

3. Download the .js script for v2.9 (it will redirect you to a downgrade page)

4. Click on downgrade.

5. After that, you will have to configure some settings. Change as below:
   const adblocker = false;
   const removePopup = true;
   const updateCheck = false;

**Comment by SpunkyB21** [comment]
> 1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
> 2. Go to the Releases tab on the left hand side bar
> 3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
> 4. Click on downgrade.
> 5. After that, you will have to configure some settings. Change as below:
>    const adblocker = false;
>    const removePopup = true;
>    const updateCheck = false;

OMG thank you! 2.9 is working again!!

**Comment by MuhammetCanLikya** [comment]
> 1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
> 2. Go to the Releases tab on the left hand side bar
> 3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
> 4. Click on downgrade.
> 5. After that, you will have to configure some settings. Change as below:
>    const adblocker = false;
>    const removePopup = true;
>    const updateCheck = false;

this is not working for me

**Comment by samjosel54** [comment]
> 1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
> 2. Go to the Releases tab on the left hand side bar
> 3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
> 4. Click on downgrade.
> 5. After that, you will have to configure some settings. Change as below:
>    const adblocker = false;
>    const removePopup = true;
>    const updateCheck = false;

this is not working for me

**Comment by samjosel54** [comment]
> 1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
> 2. Go to the Releases tab on the left hand side bar
> 3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
> 4. Click on downgrade.
> 5. After that, you will have to configure some settings. Change as below:
>    const adblocker = false;
>    const removePopup = true;
>    const updateCheck = false;

Thread #272

**Comment by MuhammetCanLikya** [comment]
> Thread #272

Version 2.9 is working only if you delete this:
`    const adblocker = true;
 
    // Enable The Popup remover (pointless if you have the Undetected Adblocker)
    const removePopup = false;

    // Checks for updates
    const updateCheck = true;

    // Enable debug messages into the console
    const debugMessages = true;`

And add this:
`const adblocker = false;
const removePopup = true;
const updateCheck = false;`

**Comment by samjosel54** [comment]
> > Thread #272
> 
> Version 2.9 is working only if you delete this:
> 
> const adblocker = true;
> 
> ```
> // Enable The Popup remover (pointless if you have the Undetected Adblocker)
> const removePopup = false;
> 
> // Checks for updates
> const updateCheck = true;
> 
> // Enable debug messages into the console
> const debugMessages = true;
> ```
> 
> And add this: const adblocker = false; const removePopup = true; const updateCheck = false;

I already fixed it for myself but I was just letting that person know to give credit.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
