### ISSUE TITLE
3.1 Bug. Screen flicking again, with the ad display frozen. 

### ISSUE THREAD

**Issue by MrShadow041** [TheRealJoelmatic/RemoveAdblockThing#264]
I am using brave (The white line in my screen is my notebook problem) 

https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/152748661/9173cc64-f724-48a7-a655-e08d075eb5fe

**Comment by sebasdt** [comment]
same for me here.
only on firefox the add skips but jumps back to the beginning.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/67417070/3c492f92-a7db-4346-b918-b635c629d500)

**Comment by BrorsanP2** [comment]
Same

**Comment by MrSteff** [comment]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/31986937/5d5a0928-1405-495e-a3db-73313075a53a)
I believe that's the part that is the issue, it sometimes detects or probably, the video doesn't load fully so it doesn't detect it as a valid number.

thus it gets stuck to 0 constantly.

It's a good idea tho imo, to obfuscate detectors.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
