### ISSUE TITLE
ads freezing at first frame

### ISSUE THREAD

**Issue by uhokay4** [TheRealJoelmatic/RemoveAdblockThing#265]
whenever i start a video, the ad that pops up freezes at its first frame and whenever i try to press play, it pauses and goes back to the first frame, making videos unwatchable

**Comment by uhokay4** [comment]
![bug](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/73552882/19c8a386-bd73-4ad2-b2a4-c160b59ee097)

**Comment by uhokay4** [comment]
this doesn't always happen but it does mostly

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
