### ISSUE TITLE
New versions gives epilepsy flashes instead of skipping ads

### ISSUE THREAD

**Issue by ralinchan** [TheRealJoelmatic/RemoveAdblockThing#268]
Updated to 3.1 because it kept popping up telling me there was an update.

Soon as I did instead of skipping ads now it keeps the ad showing at the start of the video and starts flashing the whole screen

**Comment by Accieo** [comment]
I just had the same issue, you can try reverting back to version 2.9. That seems to be working for me.

**Comment by Gamewolf66** [comment]
> I just had the same issue, you can try reverting back to version 2.9. That seems to be working for me.

and how exactly are we supposed to do that?

**Comment by Mansarde** [comment]
> > I just had the same issue, you can try reverting back to version 2.9. That seems to be working for me.
> 
> and how exactly are we supposed to do that? not everyone who uses this knows, we all started using it around the same time when youtube implemented their ridiculous anti-adblock measures

Go to the main page ("Code" on the top left).
On the right side, click on "Releases".
Then under version 2.9 is a section called "Assets". Click on the long .js filename.
This will open the file and your script extension (Tampermonkey, etc.) will detect the script and ask you if you want to downgrade.

**Comment by Gamewolf66** [comment]
> > > I just had the same issue, you can try reverting back to version 2.9. That seems to be working for me.
> > 
> > 
> > and how exactly are we supposed to do that? not everyone who uses this knows, we all started using it around the same time when youtube implemented their ridiculous anti-adblock measures
> 
> Go to the main page ("Code" on the top left). On the right side, click on "Releases". Then under version 2.9 is a section called "Assets". Click on the long .js filename. This will open the file and your script extension (Tampermonkey, etc.) will detect the script and ask you if you want to downgrade.

THANK YOU!!!!!!

**Comment by mcmanaman8** [comment]
Having the same issue with the new update. Downgraded to 2.9 thanks to Mansarde's explanation back to working fine. Can't stop the pop ups asking to do the update though, even by removing the update check on TM. Beats an ad followed by flashing screen though. Hopefully a fix can be found. Ty.

**Comment by SpunkyB21** [comment]
Reverting to 2.9 doesn't work. I'm also using the Brave browser.

**Comment by mcmanaman8** [comment]
> Reverting to 2.9 doesn't work. I'm also using the Brave browser.

Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?

**Comment by SpunkyB21** [comment]
> > Reverting to 2.9 doesn't work. I'm also using the Brave browser.
> 
> Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?

Brave Shield is off, and it's pointless to even use the script if I turn off uBlock Origin. The only other things I have installed are in the attached photo. Considering the script was working fine until I updated it, I don't think anything else is the issue. 
![Snap1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/49198112/513ca69b-56c6-4890-9657-9bc0da2a2fd0)

**Comment by mcmanaman8** [comment]
> > > Reverting to 2.9 doesn't work. I'm also using the Brave browser.
> > 
> > 
> > Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?
> 
> Brave Shield is off, and it's pointless to even use the script if I turn off uBlock Origin. The only other things I have installed are in the attached photo. Considering the script was working fine until I updated it, I don't think anything else is the issue. ![Snap1](https://private-user-images.githubusercontent.com/49198112/296107602-513ca69b-56c6-4890-9657-9bc0da2a2fd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjY2NjUsIm5iZiI6MTcwNTAyNjM2NSwicGF0aCI6Ii80OTE5ODExMi8yOTYxMDc2MDItNTEzY2E2OWItNTZjNi00ODkwLTk2NTctOWJjMGRhMmEyZmQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDVmOWI5ZTY0OWYxMWI1MzY3ZGQ4MTBlODczYWExYTBkZjlmNDEyNjVmYTdlZjYyN2UzODE3ZjQwMGEwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2IeNeKnQiD9Odp2Ze5SHlOritOlP6_qEnPK0Pln0S4U)

I see. On mine I have Brave Shield off for youtube too but I don't have any adblockers installed other than that, . And since it was working fine before the update for you and you've already tested the extensions and the downgrading failed, I guess the only other thing left would be try to remove the script completely instead of downgrading and getting 2.9 fresh again. If that doesn't work, I'm guessing there'll be some kinda of fix soon, 3.1 broke things for a lot of people it seems.

**Comment by SpunkyB21** [comment]
> > > > Reverting to 2.9 doesn't work. I'm also using the Brave browser.
> > > 
> > > 
> > > Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?
> > 
> > 
> > Brave Shield is off, and it's pointless to even use the script if I turn off uBlock Origin. The only other things I have installed are in the attached photo. Considering the script was working fine until I updated it, I don't think anything else is the issue. ![Snap1](https://private-user-images.githubusercontent.com/49198112/296107602-513ca69b-56c6-4890-9657-9bc0da2a2fd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjY2NjUsIm5iZiI6MTcwNTAyNjM2NSwicGF0aCI6Ii80OTE5ODExMi8yOTYxMDc2MDItNTEzY2E2OWItNTZjNi00ODkwLTk2NTctOWJjMGRhMmEyZmQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDVmOWI5ZTY0OWYxMWI1MzY3ZGQ4MTBlODczYWExYTBkZjlmNDEyNjVmYTdlZjYyN2UzODE3ZjQwMGEwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2IeNeKnQiD9Odp2Ze5SHlOritOlP6_qEnPK0Pln0S4U)
> 
> I see. On mine I have Brave Shield off for youtube too but I don't have any adblockers installed other than that, . And since it was working fine before the update for you and you've already tested the extensions and the downgrading failed, I guess the only other thing left would be try to remove the script completely instead of downgrading and getting 2.9 fresh again. If that doesn't work, I'm guessing there'll be some kinda of fix soon, 3.1 broke things for a lot of people it seems.

Okay, but...I've tried uninstalling and re-installing, and it still said the script was installed. So, how do I fully uninstall the script to get a "clean" install of the previous version?

**Comment by mcmanaman8** [comment]
> > > > > Reverting to 2.9 doesn't work. I'm also using the Brave browser.
> > > > 
> > > > 
> > > > Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?
> > > 
> > > 
> > > Brave Shield is off, and it's pointless to even use the script if I turn off uBlock Origin. The only other things I have installed are in the attached photo. Considering the script was working fine until I updated it, I don't think anything else is the issue. ![Snap1](https://private-user-images.githubusercontent.com/49198112/296107602-513ca69b-56c6-4890-9657-9bc0da2a2fd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjY2NjUsIm5iZiI6MTcwNTAyNjM2NSwicGF0aCI6Ii80OTE5ODExMi8yOTYxMDc2MDItNTEzY2E2OWItNTZjNi00ODkwLTk2NTctOWJjMGRhMmEyZmQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDVmOWI5ZTY0OWYxMWI1MzY3ZGQ4MTBlODczYWExYTBkZjlmNDEyNjVmYTdlZjYyN2UzODE3ZjQwMGEwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2IeNeKnQiD9Odp2Ze5SHlOritOlP6_qEnPK0Pln0S4U)
> > 
> > 
> > I see. On mine I have Brave Shield off for youtube too but I don't have any adblockers installed other than that, . And since it was working fine before the update for you and you've already tested the extensions and the downgrading failed, I guess the only other thing left would be try to remove the script completely instead of downgrading and getting 2.9 fresh again. If that doesn't work, I'm guessing there'll be some kinda of fix soon, 3.1 broke things for a lot of people it seems.
> 
> Okay, but...I've tried uninstalling and re-installing, and it still said the script was installed. So, how do I fully uninstall the script to get a "clean" install of the previous version?

Click on the tampermonkey extension and go to dashboard. On the right you can delete the script. Then you re-install it through github.

**Comment by SpunkyB21** [comment]
> > > > > > Reverting to 2.9 doesn't work. I'm also using the Brave browser.
> > > > > 
> > > > > 
> > > > > Sorry to hear that. Been working fine here since my second edit. Even restarted the computer to test. Maybe you have other scripts/extensions that could be interfering?
> > > > 
> > > > 
> > > > Brave Shield is off, and it's pointless to even use the script if I turn off uBlock Origin. The only other things I have installed are in the attached photo. Considering the script was working fine until I updated it, I don't think anything else is the issue. ![Snap1](https://private-user-images.githubusercontent.com/49198112/296107602-513ca69b-56c6-4890-9657-9bc0da2a2fd0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjY2NjUsIm5iZiI6MTcwNTAyNjM2NSwicGF0aCI6Ii80OTE5ODExMi8yOTYxMDc2MDItNTEzY2E2OWItNTZjNi00ODkwLTk2NTctOWJjMGRhMmEyZmQwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAyMjYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMDVmOWI5ZTY0OWYxMWI1MzY3ZGQ4MTBlODczYWExYTBkZjlmNDEyNjVmYTdlZjYyN2UzODE3ZjQwMGEwMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2IeNeKnQiD9Odp2Ze5SHlOritOlP6_qEnPK0Pln0S4U)
> > > 
> > > 
> > > I see. On mine I have Brave Shield off for youtube too but I don't have any adblockers installed other than that, . And since it was working fine before the update for you and you've already tested the extensions and the downgrading failed, I guess the only other thing left would be try to remove the script completely instead of downgrading and getting 2.9 fresh again. If that doesn't work, I'm guessing there'll be some kinda of fix soon, 3.1 broke things for a lot of people it seems.
> > 
> > 
> > Okay, but...I've tried uninstalling and re-installing, and it still said the script was installed. So, how do I fully uninstall the script to get a "clean" install of the previous version?
> 
> Click on the tampermonkey extension and go to dashboard. On the right you can delete the script. Then you re-install it through github. There's also a trash bin on the dashboard, delete it from there too before installing again.

I did that already. 😂 It's okay, though, because I found an alternative on Greasyfork that works for me, at least until they fix this one.

**Comment by SanatMishra** [comment]
This fixed the problem for me (chrome):
1. Download v2.9 from releases
2. Copy the text of Youtube-Ad-blocker-Reminder-Remover.user.js into a new tampermonkey script
3. Edit random parts of the description and add dummy code as shown: ![ghtest](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/33244589/47a05f20-878d-4e89-a729-90ecf4fd6881)
4. Clear history and browser cache
5. Disable everything, enable the new script
6. Refresh youtube tab, it works before and after signing in
7. Enable my old extensions

Not entirely sure which one's the important step here, but my hypothesis was that youtube saves a list of ad blockers on the browser side, and both versions of the script trigger the same "entry". So just clearing cache might be enough, but for good measure, I changed whatever in the script I thought could contribute to hashing the entry.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2

**Comment by mcmanaman8** [comment]
> Fixed in 3.2

Indeed. Thank you sir.
