### ISSUE TITLE
YT detect the adblock in opera

### ISSUE THREAD

**Issue by valenchu** [TheRealJoelmatic/RemoveAdblockThing#270]
YT detect the adblock in opera, and this not working here. not acelerate the add video
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20959371/8fdf4384-0270-4a26-aacb-b50afec30093)

**Comment by UndiedGamer** [comment]
downgrade to v2.9

**Comment by valenchu** [comment]
@UndiedGamer y dowgrade the version and obtain the same result.

**Comment by UndiedGamer** [comment]
i dont understand your english

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
