### ISSUE TITLE
v 3.1 not work

### ISSUE THREAD

**Issue by Birsen24** [TheRealJoelmatic/RemoveAdblockThing#272]
not working

**Comment by FriesTaker** [comment]
same..

**Comment by dracokr** [comment]
same

**Comment by asktree** [comment]
it is true

**Comment by ToiYeuTien** [comment]
Yes

**Comment by OsmanFerit** [comment]
Yes

**Comment by ChetAlv** [comment]
Yes

**Comment by soorajvarrma** [comment]
Adblock is detected

**Comment by britannic192** [comment]
v 3.1 didn't work for me either, but I just uninstalled then reinstalled v 2.9 and everything seems to be fine again, at least for now.

**Comment by samjosel54** [comment]
Hello,

I may have seem to found a temporary fix for this issue.

Let's just assume you've gotten a notification from the script telling you to update to v3.1.

1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
2. Go to the Releases tab on the left hand side bar
3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
4. Click on downgrade.
5. After that, you will have to configure some settings. Change as below:
    const adblocker = false;
    const removePopup = true;
    const updateCheck = false;

After you've configured the following settings, go to the File tab in the white bar above the code editor and click save.

After that, if you have any additional adblockers enabled on youtube, disable that as the .js script will handle it for you.

**Comment by britannic192** [comment]
> Hello,
> 
> I may have seem to found a temporary fix for this issue.
> 
> Let's just assume you've gotten a notification from the script telling you to update to v3.1.
> 
>     1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)
> 
>     2. Go to the Releases tab on the left hand side bar
> 
>     3. Download the .js script for v2.9 (it will redirect you to a downgrade page)
> 
>     4. Click on downgrade.
> 
>     5. After that, you will have to configure some settings. Change as below:
>        const adblocker = false;
>        const removePopup = true;
>        const updateCheck = false;
> 
> 
> After you've configured the following settings, go to the File tab in the white bar above the code editor and click save.
> 
> After that, if you have any additional adblockers enabled on youtube, disable that as the .js script will handle it for you.
> 
> in some instances where you load a video up, youtube could still detect you even with this fix. to fix this temporarily, just refresh the page.

I appreciate you coming up with this but after making these changes, the ads started to reappear again for me when they hadn't following only a downgrade to v 2.9. Not sure if this is just on my end or not, though.

**Comment by samjosel54** [comment]
I've been receiving the same issue too and I'm not really sure how to fix this. It was working for me like an hour ago. I'm probably planning on finding a fix for this, YT doesn't want to cooperate however. Hope someone finds a solution to this in time.

**Comment by samjosel54** [comment]
In the meantime, try tampering with the settings. I recommend avoiding the confusing chunks of code as that is probably used to make the script "functional".

**Comment by samjosel54** [comment]
Keep updateCheck off though, removeAdblock will beg you to update if you turn it on.

**Comment by samjosel54** [comment]
I'll keep you updated once I find a fix.

**Comment by britannic192** [comment]
> I'll keep you updated on this.

Thanks for trying nonetheless!

**Comment by samjosel54** [comment]
Following up, try enabling the undetected adblocker in the script.

It should go along the lines of this:

//
const adblocker = true;

//

See if that works, if it does, your welcome!

If you're still met with issues though, I'll try to help once you specify what you're having trouble with.

**Comment by samjosel54** [comment]
You might experience video flickering after having loaded up a video with this method, just refresh to fix this temporarily.

Permanent fixes for this are currently stale at the moment, I'm even troubled myself. Hope someone comes up with one though sometime in the future!

**Comment by britannic192** [comment]
> Following up, try enabling the undetected adblocker in the script.
> 
> It should go along the lines of this:
> 
> // const adblocker = true;
> 
> //
> 
> See if that works, if it does, your welcome!
> 
> If you're still met with issues though, I'll try to help once you specify what you're having trouble with.
> 
> don't forget the save the script btw, Ctrl+S for a shortcut or do this manually with the white bar above the editor (File tab).

Seems like this did the trick, everything is working smoothly for me now. Thanks for this fix, appreciate you doing the troubleshooting! Hopefully the next version patches things up for good.

**Comment by samjosel54** [comment]
> > Following up, try enabling the undetected adblocker in the script.
> > It should go along the lines of this:
> > // const adblocker = true;
> > //
> > See if that works, if it does, your welcome!
> > If you're still met with issues though, I'll try to help once you specify what you're having trouble with.
> > don't forget the save the script btw, Ctrl+S for a shortcut or do this manually with the white bar above the editor (File tab).
> 
> Seems like this did the trick, everything is working smoothly for me now. Thanks for this fix, appreciate you doing the troubleshooting! Hopefully the next version patches things up for good.

No problem! I hope so too.

**Comment by mrunknown690** [comment]
> > > Following up, try enabling the undetected adblocker in the script.
> > > It should go along the lines of this:
> > > // const adblocker = true;
> > > //
> > > See if that works, if it does, your welcome!
> > > If you're still met with issues though, I'll try to help once you specify what you're having trouble with.
> > > don't forget the save the script btw, Ctrl+S for a shortcut or do this manually with the white bar above the editor (File tab).
> > 
> > 
> > Seems like this did the trick, everything is working smoothly for me now. Thanks for this fix, appreciate you doing the troubleshooting! Hopefully the next version patches things up for good.
> 
> No problem! I hope so too.



> > > Following up, try enabling the undetected adblocker in the script.
> > > It should go along the lines of this:
> > > // const adblocker = true;
> > > //
> > > See if that works, if it does, your welcome!
> > > If you're still met with issues though, I'll try to help once you specify what you're having trouble with.
> > > don't forget the save the script btw, Ctrl+S for a shortcut or do this manually with the white bar above the editor (File tab).
> > 
> > 
> > Seems like this did the trick, everything is working smoothly for me now. Thanks for this fix, appreciate you doing the troubleshooting! Hopefully the next version patches things up for good.
> 
> No problem! I hope so too.

yup this is working thankyou so much!

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
