### ISSUE TITLE
flickering 

### ISSUE THREAD

**Issue by omar2408** [TheRealJoelmatic/RemoveAdblockThing#274]
every time an ad plays it starts to flicker 
i am on chrome

**Comment by tanjunior** [comment]
Yes it seems like youtube changed something. Lets wait for an update.

**Comment by MorkaZ** [comment]
> Yes it seems like youtube changed something. Lets wait for an update. also take a look at #268

It just started happening after last update. Wasnt happening before, just instantly after update

**Comment by tanjunior** [comment]
roll back to 2.8

**Comment by tanjunior** [comment]
> > Yes it seems like youtube changed something. Lets wait for an update. also take a look at #268
> 
> It just started happening after last update. Wasnt happening before, just instantly after update

roll back to 2.9

**Comment by mrunknown690** [comment]
1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)

2. Go to the Releases tab on the left hand side bar

3. Download the .js script for v2.9 (it will redirect you to a downgrade page)

4. Click on downgrade.

5. After that, you will have to configure some settings. Change as below:
   const adblocker = false;
   const removePopup = true;
   const updateCheck = false;

ITS IS WORKING FOR ME

**Comment by minanagehsalalma** [comment]
thx @mrunknown690 works a lot even that these aren't necessary 

```
const adblocker = false;
const removePopup = true;
```

**Comment by Coydog153** [comment]
Can you send me a link to the downgrade page, i cant find it.

**Comment by minanagehsalalma** [comment]
@Coydog153
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases

**Comment by Coydog153** [comment]
ty

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2

**Comment by tanjunior** [comment]
> Fixed in 3.2

Why is it not shown in releases?
