### ISSUE TITLE
Ads are no longer being skipped. Youtube is getting auto added to the script under Exclude.

### ISSUE THREAD

**Issue by SurivKrowten** [TheRealJoelmatic/RemoveAdblockThing#275]
**Describe the bug**
After the script was updated to the newest version (for me, done on 01/11/2024 at 10:59 PM Central.) YouTube was being added to the excluded section of the script automatically. I have attempted to factory reset it, downgrade it, and remove and re-install it but it keeps adding Youtube to the exclude section. Even when I try to manually remove it, it still isn't fast-forwarding the ads anymore. 

**To Reproduce**
1. For me it was simply updating to the newest version. 

**Expected behavior**
Expected it to function normally after manually removing Youtube from the excluded list but continued to not fast forward the ads. 

**Screenshots**
![Capture 2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/143915028/0b2f8f81-fcec-49ca-9e4b-5020f37a3c2d)
![Capture 1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/143915028/5f42e7a5-9541-40f5-90a4-d9e574570a29)

**Desktop (please complete the following information):**
 - OS: [Windows 10 Pro]
 - Browser [chrome]
 - Version of "Chrome" [120.0.6099.201]
 - Version of "Windows" [22H2]
 - Version of "RemoveAdblockThing" [3.1]

**Additional context**
N/A at this time.

**Comment by mrunknown690** [comment]
1. Go to the original page (TheRealJoelmatic/RemoveAdblockThing)

2. Go to the Releases tab on the left hand side bar

3. Download the .js script for v2.9 (it will redirect you to a downgrade page)

4. Click on downgrade.

5. After that, you will have to configure some settings. Change as below:
   const adblocker = false;
   const removePopup = true;
   const updateCheck = false;

**Comment by supersmith2500** [comment]
Messing with script will just break them anyway. It's either ads or that annoying pop-up that has to be clicked off. ¬_¬

**Comment by Timmiej93** [comment]
@supersmith2500 Changing a simple variable from true to false is not that hard. You can keep clicking the popup if you want, but telling others not to try something that can't harm a single thing, especially here on GitHub, that's just weird.

**Comment by Maxwell999b** [comment]
@mrunknown690 thanks for the Fix <3

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
