### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by IDK222222222222** [TheRealJoelmatic/RemoveAdblockThing#276]
It is not working instead of blocking the ads i am permanently stuck on the disable your adblocker page no matter how many times i reload no many how many times i open a new tab, try different videos, etc I do not have any other addblockers running. 

Also another issue i noticed before it completely broke is sometimes when i would click on the video it would just be a white screen no video would play and i would have to reload the page

This a really great add blocker please fix it

:)

**Comment by useremail4339** [comment]
After update the script Ads started. I'm Use Opera Browser full updated.

**Comment by devtrex007** [comment]
Try updating your browser, it worked for me.

**Comment by hellomrjones** [comment]
Up to date Chrome - still same effect. Doesn't work since this morning at all

**Comment by useremail4339** [comment]
I'm Notice when we use if we use **YouTube Miniplayer** then ads started. otherwise work well.

**Comment by hellomrjones** [comment]
No, it doesn't work at all since last update.

**Comment by sansavision** [comment]
3.1 is broken on firefox!

**Comment by woxylv** [comment]
Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):

1. Uninstall tampermonkey extension.
2. Close web browser and re-open.
3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!

**WOXYLV**

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
