### ISSUE TITLE
Recent update allowed ads back, downgraded to v2.1 of 2 Nov 2023, works OK again

### ISSUE THREAD

**Issue by RingoMcGoogle** [TheRealJoelmatic/RemoveAdblockThing#278]
Got prompted to update to (what I believe to have been) v3.0, and lost all functionality of RemoveAdblockThing. I then reverted to downgrading to v2.1 of 2 Nov 2023 and functionality is back, this earlier version apparently working quite nicely.

**Comment by newpew** [comment]
Hi, where do I find v2.1? I looked at all the tab above but none of them includes previous versions.

**Comment by srprizma** [comment]
Yoo how do I revert back to v2.1?

**Comment by UndiedGamer** [comment]
go to releases, scroll to 2.1 and click on the user.js file, for me version 2.9 works good

**Comment by srprizma** [comment]
> go to releases, scroll to 2.1 and click on the user.js file, for me version 2.9 works good

where's "releases"?

**Comment by marcowarga** [comment]
> Got prompted to update to (what I believe to have been) v3.0, and lost all functionality of RemoveAdblockThing. I then reverted to downgrading to v2.1 of 2 Nov 2023 and functionality is back, this earlier version apparently working quite nicely.

Indeed, that version currently seems to work flawlessly for me.

**Comment by edp1096** [comment]
In my case, v2.9 is working in release, https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/caf13d113cb8f98537769a902150816e221663a4/Youtube-Ad-blocker-Reminder-Remover.user.js

**Comment by RingoMcGoogle** [comment]
#srprizma Releases page is at https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/

**Comment by shakib04** [comment]
same issue.

**Comment by troublednoodle** [comment]
Once downgraded is there anyway to turn off the pop up "Remove Adblock Thing: A new version is available. Please update your script."??

**Comment by RingoMcGoogle** [comment]
@troublednoodle The New version/Update popup doesn't come with 2.1

**Comment by Saraistupid** [comment]
version 2.1 breaks the video player for me, could it be because i'm using youtube redux?
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/37207067/92fcdd73-eb4d-448a-b138-165cbbb08035)

**Comment by RingoMcGoogle** [comment]
@Saraistupid Possibly

**Comment by Saraistupid** [comment]
> @Saraistupid Possibly

I tried with and without youtube redux and youtube enhancer, i tried clearing cache, i tried v2.1-2.9, and i still get the same popup

**Comment by 10b14224cc** [comment]
The version 3.1 in TamperMonkey is not available in this repo. It is not in git tags, and the latest released version here is 2.9.

Are we sure the TamperMonkey version was not hacked?

**Comment by JurajkoDS** [comment]
2.5 works for me as well:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/2.5

**Comment by WoeIsLee** [comment]
> 2.5 works for me as well: https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/2.5

Same here thank youuuu

**Comment by Ferenczyg** [comment]
remove popup on 2.9:

 // Checks for updates
    const updateCheck = false; // true;

**Comment by Saraistupid** [comment]
I found out my issue, I got hit by the firefox experiment, if anyone is on firefox and is experiencing the pseudo-delay youtube added switch your useragent to any Chromium browser, the video player works again for me after that.

**Comment by 6801318d8d** [comment]
Why this was closed?

The problem is still here

**Comment by RingoMcGoogle** [comment]
@6801318d8d Unintended, excuse me

**Comment by RingoMcGoogle** [comment]
@6801318d8d No closing again, the main issue ppl have is with a recent update, this thread only covering a possible workaround, which appears to work for others as well.

**Comment by Ribbian** [comment]
reopen irr
