### ISSUE TITLE
downgrade to v2.9

### ISSUE THREAD

**Issue by valenchu** [TheRealJoelmatic/RemoveAdblockThing#279]
downgrade to v2.9

_Originally posted by @UndiedGamer in https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/270#issuecomment-1888643306_
            y dowgrade the version and obtain the same result.

**Comment by 10b14224cc** [comment]
Why you opened a new issue?

**Comment by Ribbian** [comment]
i didnt work bozo
