### ISSUE TITLE
Update broken it

### ISSUE THREAD

**Issue by Numaticjoe** [TheRealJoelmatic/RemoveAdblockThing#280]
After installing the update the script dosent work at all youtube just comes up with the "adblock is not allowed prompt" as if there was no scrip there whatsoever.
Before the update it was absolutely fine for me

Im on:
(Windows 10 X64, Chrome Version 120.0.6099.217)

EDIT:
After clicking purge all caches on UBlock origin it seems to work again

**Comment by woxylv** [comment]
Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):

1. Uninstall tampermonkey extension.
2. Close web browser and re-open.
3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!

**WOXYLV**

**Comment by GrimnirTheGrey** [comment]
> Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):
> 
> 1. Uninstall tampermonkey extension.
> 2. Close web browser and re-open.
> 3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
> 4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
> 5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!
> 
> **WOXYLV**

Is there a way to disable the update prompt? It's keeps popping up every time I move to another page or video on youtube

**Comment by MuhammetCanLikya** [comment]
> Is there a way to disable the update prompt? It's keeps popping up every time I move to another page or video on youtube

change script with this 

const updateCheck = false;

**Comment by GrimnirTheGrey** [comment]
Many thanks, that's saved my sanity

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
