### ISSUE TITLE
Plugin is causing my browser to lag again.

### ISSUE THREAD

**Issue by Pooland1** [TheRealJoelmatic/RemoveAdblockThing#281]

**Comment by woxylv** [comment]
Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):

1. Uninstall tampermonkey extension.
2. Close web browser and re-open.
3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!

For auto-update popup fix in tampermonkey: (This is when you are on youtube page!)

1. Copy this line under ----> const updateCheck = false;
2. Paste in tampermonkey.
3. Attached screenshot file where you need to paste! 
![tampermonkeyscript](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156456411/7549e493-1dd2-4fa1-b062-7c649f766910)

**WOXYLV**

**Comment by Pooland1** [comment]
Doesn't work sadly, still lagging like hell. My graphics card is rtx 3050 so It can definitely handle a browser lol

**Comment by okkkkoo** [comment]
same question
