### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Jacloch** [TheRealJoelmatic/RemoveAdblockThing#282]
Not working, youtube ads are showing.

**Comment by woxylv** [comment]
Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):

1. Uninstall tampermonkey extension.
2. Close web browser and re-open.
3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!


**WOXYLV**

**Comment by EvGen94** [comment]
@Jacloch Did you reinstall the extension?

**Comment by EvGen94** [comment]
> Not working, youtube ads are showing.
@Jacloch Did you reinstall the extension?

**Comment by woxylv** [comment]
I Already explained what you need to do! Should work fine.

**Comment by muhdkhokhar** [comment]
It works fine @woxylv 

I really appreciate your work
Thanks 
If you have any donate page let us know.

**Comment by woxylv** [comment]
@muhdkhokhar Sorry can't take donation! No Problem. Happy to help.

**Comment by woxylv** [comment]
The best to do now is to wait for proper update!

**Comment by muhdkhokhar** [comment]
what is the update coming?

**Comment by woxylv** [comment]
I quite did not understand your question!

**Comment by woxylv** [comment]
You mean when?

Answer: Soon! Very Soon!

**Comment by muhdkhokhar** [comment]
I mean what will be in the update?

**Comment by woxylv** [comment]
I'm not the one making it! But probably some major fixes. Not really sure what will be in the update.

**Comment by muhdkhokhar** [comment]
I see so its like a company who is doing this?

**Comment by jhriverasa** [comment]
> Downgrade to 2.9. version (Should Work!) To Do so (For Google Chrome):
> 
>     1. Uninstall tampermonkey extension.
> 
>     2. Close web browser and re-open.
> 
>     3. Install tampermonkey extension - https://chromewebstore.google.com/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=lv&utm_source=ext_sidebar
> 
>     4. Install script - https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases
> 
>     5. Do Not! I repeat! Do Not! UPDATE! If it asks for update just cancel it!
> 
> 
> For auto-update popup fix in tampermonkey: (This is when you are on youtube page!)
> 
>     1. Copy this line under ----> const updateCheck = false;
> 
>     2. Paste in tampermonkey.
> 
>     3. Attached screenshot file where you need to paste!
>        ![tampermonkeyscript](https://private-user-images.githubusercontent.com/156456411/296337354-7549e493-1dd2-4fa1-b062-7c649f766910.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwODk3ODcsIm5iZiI6MTcwNTA4OTQ4NywicGF0aCI6Ii8xNTY0NTY0MTEvMjk2MzM3MzU0LTc1NDllNDkzLTFkZDItNGZhMS1iMDYyLTdjNjQ5Zjc2NjkxMC5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxOTU4MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDE4ZTZiNWViOWQ0MmUxMGRlN2ZkOTEwNTczMjI1NzA4N2U1Mjc5MWU4YjA2YWI0ZjdkMGQ5ZTM0ZTZmMDViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VyEuIeBPLHHstTXiaWqlIkN6WDqeTKmY2PIm6EeSObs)
> 
> 
> **WOXYLV**

Yeah Downgrade is an option, but you can do that even easier. 

1. Go to extension's Dashboard, and click to edit the script:
![imagen](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26237878/a5cc4535-d423-4c13-9e53-18ccdbd4e133)
2.  Go to  [Version 3.0](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/83797e0cd1a532cfc6fe3ff6498443199409ee01/Youtube-Ad-blocker-Reminder-Remover.user.js)  and copy/paste 
![imagen](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26237878/3595e570-3c99-41fc-9f3f-cb7e4c970364)
3. Comment the section that create alerts when a new update is available,  and save. 
You still gonna see them in console if you want to.  
![imagen](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26237878/3107d6bd-8059-4b8b-9540-d532889bfe38)

Ez

**Comment by woxylv** [comment]
@jhriverasa It's already done. I had everything explained! Your problem solve is another method.

**Comment by woxylv** [comment]
@jhriverasa By the way the method that I showed was discovered like 10-20hrs ago. I posted here because nobody answered.

**Comment by jhriverasa** [comment]
> @jhriverasa It's already done. I had everything explained! Your problem solve is another method.

What I mean is that you dont even need to install/reinstall / close / click cancel etcetera. heh

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
