### ISSUE TITLE
Missing or Broken Features

### ISSUE THREAD

**Issue by VoxKrynn** [TheRealJoelmatic/RemoveAdblockThing#2820]
**Script version**
Version 5.6

**Describe the bug**
Youtube playlists do not move to the next video. The skip forward, skip backward, Mini, Theater, and Autoplay buttons do not show.

**Expected behavior**
Without the script the buttons appear and a playlist with automatically go to the next video.

**Screenshots**
Image with Script on
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/163516506/732576ce-23f6-44d6-95de-5d155e4746e2)
Image with Script off
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/163516506/b444f0e6-e79a-43d0-9f6f-edbe0d6f5ee7)

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit
 - Browser Opera GX
 - Version 109.0.5097.130

**Additional context**
This seemed to happen after a fairly recent update to the script a week or two ago.

**Comment by GroggyOtter** [comment]
Downgrade to 5.3. It'll fix all that.

https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/1765

**Comment by VoxKrynn** [comment]
> Downgrade to 5.3. It'll fix all that.
> 
> #1765

That worked, thanks for the fix

**Comment by ELSKUII** [comment]
> Downgrade to 5.3. It'll fix all that.
> 
> #1765




How to downgraded the ver?

**Comment by VoxKrynn** [comment]
> > Downgrade to 5.3. It'll fix all that.
> > #1765
> 
> How to downgraded the ver?

It says at the bottom of the post there. Under where it says Temporary fix.

**Comment by IllegalImmigrant** [comment]
> Downgrade to 5.3. It'll fix all that.
> 
> #1765

huge help! thank you so much my guy! Genuinely was losing my MIND trying to understand what i did wrong to make my chrome youtube tabs just break like that lmao
