### ISSUE TITLE
Video freezes on ad

### ISSUE THREAD

**Issue by gh0st11111** [TheRealJoelmatic/RemoveAdblockThing#283]
**Describe the bug**
The ad loads in and the entire youtube page begins flickering. It will not let me watch the ad nor the video.

**To Reproduce**
1. Go to Youtube (with "Remove Adblock Thing" on)
2. Click on a video that has advertisements
3. The video will not play

**Expected behavior**
The advertisement will pause. The webpage will flicker and the "play" button will not work. The video is stuck on second 1 of the ad. Refreshing the page sometimes works.

**Screenshots**
Video clip included

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.61.116

https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156489897/d8322fbe-d429-44d1-baa1-d8c76fe7fdf2

**Comment by Smith873** [comment]
I've seen the same behaviour, which I think started with v3.1.
However, it only happens occasionally, affecting maybe 10% of videos and always when blocking the ads at the start of a video.

Firefox 115.6.0
Firefox ESR
Win 7.

**Comment by carbak** [comment]
I'm having the same issue with my Imac. 
MacOS 11.7.10 
Browser Chrome Version 120.0.6099.216

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
