### ISSUE TITLE
it's stopped working please fix it

### ISSUE THREAD

**Issue by Ribbian** [TheRealJoelmatic/RemoveAdblockThing#285]
**Describe the bug**
the 'adblocker violates YT TOS' pop up is back and I cant watch my videos
**To Reproduce**

**Expected behavior**

**Screenshots**
![Screenshot 2024-01-12 8 47 01 PM](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156494155/d74286af-d2be-486f-befd-9e5a924f726a)

**Desktop (please complete the following information):**
 - Browser  chrome,

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
