### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Zabih-khan** [TheRealJoelmatic/RemoveAdblockThing#288]
**Describe the bug**
The script is not working; the ads appear on the videos and freeze. When I enable the script, I am not able to skip the ads on the video.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
