### ISSUE TITLE
RemoveAdblockingThing does not work  on the first Ad and freezes or does not remove ad at the second ad 

### ISSUE THREAD

**Issue by Retr0nuat** [TheRealJoelmatic/RemoveAdblockThing#289]
**Describe the bug**

**To Reproduce**
1. Go to youtube and click any video if the first ad is removed successfully wait for the second ad and u will see that it freezes in a loop or it will not be removed  

I expected that the first and the following ad after will be smoothly executed after the update but it turns out its quite the opposite with it being very bad that the first version is way better   

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156497639/d5d99fe2-ad2a-4f96-b993-a03e6814acd8)

 if this screenshot is sent correctly u will see that the ad is clearly shown on my screen and is still going on until the skip option is available  and is not removed as expected 

**Desktop (please complete the following information):**
 - Browser Opera GX
 - Version <html>
<body>

106.0.4998.12
--

</body>
</html>

I really hope that this problem is fixed as soon as possible so I can enjoy watching youtube with no ads again

**Comment by muhdkhokhar** [comment]
You will have to downgrade

**Comment by Retr0nuat** [comment]
I was thinking the same but I do not know how to downgrade

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Ribbian** [comment]
> You will have to downgrade

how do I do that

**Comment by muhdkhokhar** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/282

**Comment by Rohirm** [comment]
Downgrade to 2.9 and change the version number in the code to 3.1, then it works and does not notify to update.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
