### ISSUE TITLE
fix it 

### ISSUE THREAD

**Issue by Ribbian** [TheRealJoelmatic/RemoveAdblockThing#291]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by muhdkhokhar** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/282

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
