### ISSUE TITLE
Adblocker bypassed

### ISSUE THREAD

**Issue by TashaSquirrel** [TheRealJoelmatic/RemoveAdblockThing#292]
**Describe the bug**
Ads will load up and play at a normal speed despite adblocker being enabled.

**To Reproduce**
1. Go to Youtube
2. Click on a video
3. Wait.

**Expected behavior**
Ads will load.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/155065811/a228fd9e-05f4-4bd5-bea7-37472e9ef651)

**Desktop (please complete the following information):**
OS: Windows 10
Browser: Chrome
Version 120.0.6099.129/130

**Comment by lakester79** [comment]
same for me

chrome 120.0.6099.217

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
