### ISSUE TITLE
Doesn't work on 3.1

### ISSUE THREAD

**Issue by Badassious** [TheRealJoelmatic/RemoveAdblockThing#293]
I'm using Avast Secure Browser that has the same Chrome script

**Comment by Azazel-BoB** [comment]
Same here, 3.1 doesn't work on Google Chrome either.

**Comment by TheRealDjElite** [comment]
What? There hasnʻt been an update since v2.9 which was 2 weeks ago.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2

**Comment by TheRealDjElite** [comment]
@TheRealJoelmatic How do get v3.2?
