### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by pipploop** [TheRealJoelmatic/RemoveAdblockThing#296]
It doesn't skip the ad and sometimes after refreshing it skips it, other times the youtube vid just frantically blinks

 - OS:  Windows 11
 - Browser: Edge
 - Version New one (?) 3.1 i think

If you could fix it i would be grateful, thank you lots ~

**Comment by woxylv** [comment]
Try this fix (Could also work on Edge) - https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/282

**Comment by Kush3007** [comment]
It is also not working on Firefox but working on Chrome, why is this happening?

**Comment by mrezabidhendi** [comment]
- OS: Windows 11
- Browser: Chrome
- Version 3.1

The following element appears, changes and disappears sequentially and blocks access to the page.
While this happens the ad also shows up, but does not play or anything.
 ![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/36895909/ffd927ef-5ee7-4e92-8a21-40205f49dc91)

**Comment by mrezabidhendi** [comment]
> It is also not working on Firefox but working on Chrome, why is this happening?

not working on Chrome for me.

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
