### ISSUE TITLE
Unable to block youtube ads on chrome 

### ISSUE THREAD

**Issue by Agnibho-8** [TheRealJoelmatic/RemoveAdblockThing#297]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2

**Comment by TheRealJoelmatic** [comment]
Fixed in 3.2
