### ISSUE TITLE
stroboscope

### ISSUE THREAD

**Issue by kinngrimm** [TheRealJoelmatic/RemoveAdblockThing#298]
When active and the removal would take place, the video stops and the whole screen flashes. Like brightness switches forth and back from a lower to higher intensity. Gives me a headache To be clear, there is no advertisement, but instead the vid is frozen and the screen flashes and i can not make the vid start other than by reloading the site.
Aslong it flashes i do not have access to any other site elements.

Not sure how to reroduce this, it just happens at the time the script is active,
It either keeps on flashing or i have to reload the page. Sometimes once is enough at times several times. I would suspect there is some timing involved on how long the advertisment otherwise would go. 

**Expected behavior**
Not allways but sometimes it just works. No idear whats the differance to when it doesn't.

**Screenshots**
Have nothing to tell, as you just see either the brighter or slightly less bright version of a frozen vid.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome ( 120.0.6099.217)
 - script Version 3.1

**Comment by TheRealJoelmatic** [comment]
Is this happening on 3.2?

**Comment by RockyMow** [comment]
yes it happens on 3.2

**Comment by RockyMow** [comment]
ad is showing up anyway and just glitches constantly starting from the start multiple times a second

**Comment by RockyMow** [comment]
> Is this happening on 3.2?

^

**Comment by AuZ-ASD** [comment]
v3.2 yes had this also... but only once - refreshed the tab and its gone (firefox)

**Comment by kinngrimm** [comment]
with 3.2 now the flashing is gone, now it just stops at one point of the vid flickering, one sees the vid seemingly going forth and back a little.
Happened on this vid https://youtu.be/ud-wjPt37os , but i guess it would happen with others. It is not as nausiating as it was before, but i still need to reload.

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.
