### ISSUE TITLE
Ads still appearing (version 3.1/ windows 10/ opera)

### ISSUE THREAD

**Issue by antfan1** [TheRealJoelmatic/RemoveAdblockThing#299]
**Script version**
3.1

**Describe the bug**
Ads are still appearing despite the script being enabled.

**Expected behavior**
Ads removed/ skipped.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera

**Comment by TheRealJoelmatic** [comment]
Update to 3.2 and it should work

**Comment by antfan1** [comment]
> Update to 3.2 and it should work

Worked! Thank you so much
