### ISSUE TITLE
Unsure if this works on Opera Gx

### ISSUE THREAD

**Issue by ZenRecklessJack** [TheRealJoelmatic/RemoveAdblockThing#3]
I'm as beginner as can be, probably a user error more than anything. I was told opera runs on chrome, so idk if this works on opera at all but I've found no success

**Comment by TheRealJoelmatic** [comment]
I don't have Opera GX to test it out but make sure you have done everything correctly.

You can find tamper money here: https://addons.opera.com/en-gb/extensions/details/tampermonkey-beta/
And I would recommend watching this video on how to install the script: https://www.youtube.com/watch?v=jvSf10lgxs4

**Comment by angelapuzzle** [comment]
I haven't tested if it works with Tampermonkey but it definitely works with Violentmonkey.

**Comment by minePFcraft** [comment]
1. I personaly use opera and If you download Tampermonkey from chrome Extessions ist not gona work you must download directly from operas own store 
2. It works with Tampermonkey

**Comment by TheRealJoelmatic** [comment]
> 3. Pls add link in readme to the operas store to Tampermonkey

Ok np, Done

**Comment by ZenRecklessJack** [comment]
> 1. I personaly use opera GX and If you download Tampermonkey from chrome Extessions ist not gona work you must download directly from operas own store

This was it, thanks a million!
