### ISSUE TITLE
Dimmed Cannot Scroll 

### ISSUE THREAD

**Issue by minanagehsalalma** [TheRealJoelmatic/RemoveAdblockThing#30]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20546638/44252529-1548-4df3-8658-ed89b0fdc400)

**Comment by minanagehsalalma** [comment]
oh , disabling ublock fixed it.

**Comment by PatientXero** [comment]
It fixes it, but now you get the fake dating site ads (women wanting green cards).

**Comment by minanagehsalalma** [comment]
> It fixes it, but now you get the fake dating site ads (women wanting green cards).

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20546638/0d03a18e-00bd-4070-8039-22d21b525032)

**Comment by jongdetim** [comment]
the 'adblock' extension + this one completely fixes YT for me. AdBlockPlus + this extension causes the issue you're having for me. I turned off ABP & it's fixed.

**Comment by minanagehsalalma** [comment]
@jongdetim which extension exactly

**Comment by jongdetim** [comment]
"Adblock -- the best adblocker"

**Comment by minanagehsalalma** [comment]
> "Adblock -- the best adblocker"

Hmm everyone is using Ublock tho

Thanks

**Comment by jongdetim** [comment]
> > "Adblock -- the best adblocker"
> 
> Hmm everyone is using Ublock tho
> 
> Thanks

which you disable on youtube if you use RemoveAdblockThing.
