### ISSUE TITLE
videos don't go show up in the seen videos historic

### ISSUE THREAD

**Issue by MensaMonster** [TheRealJoelmatic/RemoveAdblockThing#3000]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by ViSlayer** [comment]
The way everything is being displayed now with that other youtube window hovering youtube does not recognize us as being signed in while watching videos
