### ISSUE TITLE
BUG - Video is unavailable

### ISSUE THREAD

**Issue by JaroslavLajta** [TheRealJoelmatic/RemoveAdblockThing#3001]
**Script version**
5.6

**Describe the bug**
Videos on the Formula 1 channel are unable to view because youtube thinks the video is not open on youtube but somewhere else.

**Expected behavior**
The video should play normally.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/137500002/3497eb53-06fb-479a-b451-e69004d961bf)

**Desktop (please complete the following information):**
 - OS: [W11Pro]
 - Browser [chrome]
 - Version [125.0.6422.142]

**Additional context**

**Comment by jamilhossin002** [comment]
Viral

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

[![](https://camo.githubusercontent.com/50733249f2c112f0909b7f326817ee354a5113504a14f297617b22c10643603e/68747470733a2f2f692e696d6775722e636f6d2f637663797253722e676966)](//www.watch4khd.com/go/)


Viral

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

[![](https://camo.githubusercontent.com/50733249f2c112f0909b7f326817ee354a5113504a14f297617b22c10643603e/68747470733a2f2f692e696d6775722e636f6d2f637663797253722e676966)](//www.watch4khd.com/go/)


Viral

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

[![](https://camo.githubusercontent.com/50733249f2c112f0909b7f326817ee354a5113504a14f297617b22c10643603e/68747470733a2f2f692e696d6775722e636f6d2f637663797253722e676966)](//www.watch4khd.com/go/)


Viral

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

[![](https://camo.githubusercontent.com/50733249f2c112f0909b7f326817ee354a5113504a14f297617b22c10643603e/68747470733a2f2f692e696d6775722e636f6d2f637663797253722e676966)](//www.watch4khd.com/go/)


Viral

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

### **### [📺📱Watch👉Click to Access the Link (Viral Video) ](//www.watch4khd.com/go/)**

[![](https://camo.githubusercontent.com/50733249f2c112f0909b7f326817ee354a5113504a14f297617b22c10643603e/68747470733a2f2f692e696d6775722e636f6d2f637663797253722e676966)](//www.watch4khd.com/go/)

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭
