### ISSUE TITLE
3.2 Issue. The seconds to skip the ad locks in 5 and the video freeze too. (I am using Brave) 

### ISSUE THREAD

**Issue by MrShadow041** [TheRealJoelmatic/RemoveAdblockThing#301]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as you did not fill out the issues template and a duplicate issue)
