### ISSUE TITLE
Ad in loop forbid to iniciate the video

### ISSUE THREAD

**Issue by shufurudin** [TheRealJoelmatic/RemoveAdblockThing#302]
**Script version**
Remove Adblock Thing ver. 3.2

**Describe the bug**
Some ads rewind in a loop without to play the video.

**Expected behavior**
The ad appears quickly and the video start.

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0.6099.217

**Additional context**
It's not a persistent issue, but only occurs in the start of the video. During the video don't appears any ad, only sometimes when I start a video the issue happens.

**Comment by spicebag** [comment]
Same issue here. Also screen flickering.

**Comment by axo31** [comment]
same, the only way to get rid of them is to refresh the page like 5 times -.-. In my case, the ads appear during the video as well.

**Comment by itsmoe15** [comment]
### Same here, with opera gx
Opera V: LVL4 `(core: 97.0.4719.84)`

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as a duplicate issue)
