### ISSUE TITLE
Adds run at the clip start, infinite loop mid-clip

### ISSUE THREAD

**Issue by TRGVoodoo** [TheRealJoelmatic/RemoveAdblockThing#303]
**Script version**
3.2

**Describe the bug**
Sometimes Adds run at the beginning of the clip
Adds mid-clip stay in an infinite loop on multiple occasions, workaround via F5

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro V.10.0.19045 Build 19045
 - Browser: Chrome V.120.0.6099.217

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as a duplicate issue)
