### ISSUE TITLE
Some ads loop

### ISSUE THREAD

**Issue by SlavaZucchini** [TheRealJoelmatic/RemoveAdblockThing#304]
Script: Ver 3.2
PC: Windows 10, Chrome
As the ad begins, it pauses and restarts. Keeps looping very fast. Fix by refreshing the page.
Developer tool revealed loop in script line 165 and 214

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as duplicate issue)
