### ISSUE TITLE
3.2 Issue. Ad flicking frames with the ad skip time frozen (brave)

### ISSUE THREAD

**Issue by MrShadow041** [TheRealJoelmatic/RemoveAdblockThing#305]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/152748661/b9c6ab1c-5e86-4350-bd42-80ce674ac912

**Comment by itsmoe15** [comment]
same

**Comment by Esahc76** [comment]
same here

**Comment by Pottinqq** [comment]
same here but im on firefox and it still happens

**Comment by Necrome397** [comment]
I'm still using version 2.4 on firefox because it seems to get worse with every update. On 2.4 nothing flickers, I only have to click "skip" on ads sometimes.

**Comment by jaredschnelle** [comment]
Try out this change someone submitted. I was on 3.2 and added this change and issues went away: https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/315/commits/3fbd0567a976f0fc1ffb7439e68c5a16010f77c0

**Comment by mavemohiuddin** [comment]
I am also seeing the flicking covering layer, I added a custom change to the script, and it seems to be working for me. Try this out:

#1 Remove     // @grant        none
#2 Add           // @grant        GM_addStyle
#3 Add this at the beginning of the function after // config

const css = `
    tp-yt-iron-overlay-backdrop {
        display: none!important;
    }`

GM_addStyle(css)

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
