### ISSUE TITLE
Ver 3.2 is still very broken

### ISSUE THREAD

**Issue by AnonymousUser2001** [TheRealJoelmatic/RemoveAdblockThing#308]
Script Version: 3.2

Bug Description: There are several issues. For starters, half of the time, it doesn't even skip the ad. Second, I've seen others describe this bug, it plays the fist half second-ish of the ad in a loop. IDK if it would eventually stop, as I refreshed the page after a few seconds. I've even seen some people claiming that now the ad block detection is being triggered by this. However, I haven't experienced this. This all started with Version 3.1, but 3.2 isn't much better.

Setup Information:
Operating System: Windows
Browser: Microsoft Edge V.120.0.2210.121
OS Ver: Windows 11 22H2

I was using this for awhile, and I liked it, as it was about the only reliable way to remove the ads without triggering the adblock detection. Other ways were unreliable. This way was more reliable. I'd love for it to work properly. I don't expect anything like this to be 100% perfect, but it was working quite well before. I would like for these issues to be worked out completely.

**Comment by Pottinqq** [comment]
I am getting the same

**Comment by SurivKrowten** [comment]
The same results on my end. Using Windows 10 Pro, version: 22H2, Chrome: 120.0.6099.217 (Official Build) (64-bit), RemoveAdblockThing: 3.2. Stopped working before and after Chrome was updated earlier today 01/13/24 7:14 PM Central. Using the previous method of clicking [<> Code] top left --> [Releases] middle right --> [Youtube-Ad-blocker-Reminder-Remover.user.js] the first option under Assets. To revert back to 2.9 still seems to work.

**Comment by ShiwayariY** [comment]
Similar issues, Firefox 121.0.1, with both 3.1 and 3.2.
Often the ad will not skip at all, even refreshing the tab does not work.
It is trying to do something but all that is happening is repeated blinking of the progress bar and the notifications dropdown when I click it while the first frame of an ad is frozen. This seems to repeat indefinitely, I've seen it for 30s+ at least.

3.0 still works completely fine at least in my browser, but Tampermonkey seems to sometimes automatically upgrade the script on browser restart, and also give me a popup to upgrade on every new tab, so it's a bit cumbersome to keep it at 3.0 ..

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.
