### ISSUE TITLE
Shows a black screen when trying to play a video

### ISSUE THREAD

**Issue by Totallynotmwa** [TheRealJoelmatic/RemoveAdblockThing#31]
hey, soo when i try playing a video on yt it shows the  "ad blocker breaks tos" and black screen happenes even turning off adblocker breaks it i tried everything i have trying a refreshing method tho and somtimes it playes the video
![Capture6942](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/120023154/dda4088a-f5da-4033-9498-1b9d926ac5c9)

**Comment by rubywastaken** [comment]
"Sometimes uBlock Origin stops updating on an individual's computer for whatever reason, so you have to manually update to the newest version of the plugin, and refresh lists by going into the settings, click Filter Lists -> Purge All Caches -> Update Now. Then restart the browser."

Source: https://www.reddit.com/r/youtube/comments/17079px/how_to_get_rid_of_the_youtube_ad_block_popup/

**Comment by Totallynotmwa** [comment]
> If you use uBlock Origin, click Filter Lists -> Purge All Caches -> Update Now. Then restart the browser.
> 
> From this: https://www.reddit.com/r/youtube/comments/17079px/how_to_get_rid_of_the_youtube_ad_block_popup/

I use brave soo yeah i ue its inbuild adblocker

**Comment by ras52** [comment]
I'm seeing the same too.  I think Youtube has two ad block detectors in use.  One triggers a pop-up which this script does a good job of dismissing.  The second only triggers after you've dismissed the former a certain number of times, and I don't think this script does anything to bypass that.

**Comment by Totallynotmwa** [comment]
> I'm seeing the same too. I think Youtube has two ad block detectors in use. One triggers a pop-up which this script does a good job of dismissing. The second only triggers after you've dismissed the former a certain number of times, and I don't think this script does anything to bypass that.

ya same

**Comment by ras52** [comment]
> I have deactivated my 2 adblockers for just the website of youtube. It works perfect! No need for uninstalling of any addon. Just deactivate it for yt. ^.^

That's not a very helpful suggestion if you're relying on your ad blocker to remove all the ads from Youtube.

**Comment by milanchymcak** [comment]
> > I have deactivated my 2 adblockers for just the website of youtube. It works perfect! No need for uninstalling of any addon. Just deactivate it for yt. ^.^
> 
> Tried it still happens

Try to not have any adblock running on the youtube or check if you browser is not having built-in adblocker (like brave or opera?). That worked for me.

**Comment by Totallynotmwa** [comment]
> > > I have deactivated my 2 adblockers for just the website of youtube. It works perfect! No need for uninstalling of any addon. Just deactivate it for yt. ^.^
> > 
> > 
> > Tried it still happens
> 
> Try to not have any adblock running on the youtube or check if your browser is not having built-in adblocker (like brave or opera?). That worked for me.
@milanchymcak 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/120023154/9495a147-6cce-4e76-8004-163f46af77d5)

**Comment by Totallynotmwa** [comment]
i used a script to fix it i think it works in ublockorigion and brave 
```
[youtube.com](https://youtube.com/)##+js(set, yt.config_.openPopupConfig.supportedPopups.adBlockMessageViewModel, false)

[youtube.com](https://youtube.com/)##+js(set, Object.prototype.adBlocksFound, 0)

[youtube.com](https://youtube.com/)##+js(set, ytplayer.config.args.raw_player_response.adPlacements, [])

[youtube.com](https://youtube.com/)##+js(set, Object.prototype.hasAllowedInstreamAd, true) ```

**Comment by Totallynotmwa** [comment]
nvm

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
