### ISSUE TITLE
Still not working, plus ad beginning screen shows and flashes white sporadically (literal epilepsy trigger warning btw if anyone else has had that bug  happen)

### ISSUE THREAD

**Issue by madstheaquarius** [TheRealJoelmatic/RemoveAdblockThing#310]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as you did not fill out the issues template)
