### ISSUE TITLE
constant pause and play happening

### ISSUE THREAD

**Issue by demdbeef** [TheRealJoelmatic/RemoveAdblockThing#311]
**Script version**
3.2

**Describe the bug**
If a ad appears a constant pause and play loop occurs 

**Expected behavior**
just like the early 2.9 version when every thing was fine

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome
 - Version latest

**Comment by ZeALer** [comment]
Same here.

- OS: Windows 11
- Browser : Edge
- Version latest

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

(Closed as a duplicate issue)
