### ISSUE TITLE
Ads play.

### ISSUE THREAD

**Issue by ItsAlexiaL** [TheRealJoelmatic/RemoveAdblockThing#313]
**Script version**
V3.2

**Describe the bug**
Issue where ads still play. When compared to youtube on mobile (without ad block) I would say that about 70% ads play, and 30% are skipped. 

**Expected behavior**
Ads get completly skipped, just liked in past versions.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera 
 - Version: latest

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.
