### ISSUE TITLE
Ads Still Play

### ISSUE THREAD

**Issue by AFBadBoy** [TheRealJoelmatic/RemoveAdblockThing#314]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
3.2

**Describe the bug**
Ads Still Play Even After Activating The Script

**Expected behavior**
Activate The Script, Launch YouTube, Play A Video, Expected Results: Ads Playing 

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Windows 11 Pro
 - Browser [e.g. chrome, safari] : Microsoft Edge Chromuim Based
 - Version [e.g. 22] : 120.0.2210.133 (Official build)

**Additional context**

**Comment by Pooland1** [comment]
Revert to 2.9

**Comment by ZayxSt** [comment]
> Revert to 2.9

Older versions dont work anymore, not even editing the 4 parameters makes it work

the ads not only plays, but they also glitch and blink, and the only way to get em out is by F5

**Comment by okkkkoo** [comment]
2.9 It works for me.

**Comment by Asherit** [comment]
Mine isn't working too

**Comment by jaredschnelle** [comment]
This super simple thing fixed it for me: https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/315/commits/3fbd0567a976f0fc1ffb7439e68c5a16010f77c0

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.

**Comment by xducker** [comment]
> > Revert to 2.9
> 
> Older versions dont work anymore, not even editing the 4 parameters makes it work
> 
> the ads not only plays, but they also glitch and blink, and the only way to get em out is by F5.
> 
> I recommend using uBO, it actually works right now

what is uBO? ))

**Comment by rephlex-ctrl** [comment]
@TheRealJoelmatic Not working here. Like there is no script at all :(

**Comment by mdero665** [comment]
@TheRealJoelmatic Also not working for me.  Ads still playing.  Not getting the crazy flashing where the skip ad button becomes unusable though.

**Comment by pavelkornev** [comment]
> uBO

https://github.com/gorhill/uBlock/

**Comment by pavelkornev** [comment]
@xducker 

> > > Revert to 2.9
> > 
> > 
> > Older versions dont work anymore, not even editing the 4 parameters makes it work
> > the ads not only plays, but they also glitch and blink, and the only way to get em out is by F5.
> > I recommend using uBO, it actually works right now
> 
> what is uBO? ))

https://github.com/gorhill/uBlock/

**Comment by xducker** [comment]
my version 3.2 works fine :)

**Comment by pavelkornev** [comment]
> my version 3.2 works fine :) (win10, brave)

for me neither v3.2, nor latest v3.3 work :( uBlock works out of the box with zero setup.

**Comment by rephlex-ctrl** [comment]
Version 3.4 so far so good.  Dim page screen after ad skip. А click is required to make it back to normal brightness. But everything else seems to work properly.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
