### ISSUE TITLE
Lagging/cant skip ad

### ISSUE THREAD

**Issue by skokann** [TheRealJoelmatic/RemoveAdblockThing#316]
**Script version**
3.2

**Describe the bug**
when i start video, the video have ad, i cant click skip.. its non skippable

**Expected behavior**

**Screenshots**
https://imgur.com/a/uEiF9vW

**Desktop (please complete the following information):**
 - OS: Windows 11 version latest
 - Browser chrome
 - Version 120.0.6099.217

**Additional context**

**Comment by realduck02** [comment]
Same here.

**Comment by Pooland1** [comment]
My browser is lagging hard even with a RTX 3050 Laptop

**Comment by jaredschnelle** [comment]
This super simple thing fixed it for me: https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/315/commits/3fbd0567a976f0fc1ffb7439e68c5a16010f77c0

**Comment by Fedoba** [comment]
Just downgrade the script to version 2.9 and you'll be fine.

**Comment by callumia** [comment]
> Just downgrade the script to version 2.9 or 3.0 and you'll be fine.

how do i do that?

**Comment by TheRealJoelmatic** [comment]
Check out 3.3, This should now be fixed.
