### ISSUE TITLE
Adblocker not wokking

### ISSUE THREAD

**Issue by chandravamshi** [TheRealJoelmatic/RemoveAdblockThing#317]
**Script version**
3.2

**Describe the bug**
Ads are showing not getting skipped. sometimes the ad is looping unable to skip aswell so i need to referesh multiple times and after this i need watch ad to skip.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: ios macbook air m1 chip
 - Browser chrome latest version. i updated it today.
 - Version 120.0.6099.216 (Official Build) (arm64)

**Additional context**
ads are showing. thats it

**Comment by TheRealJoelmatic** [comment]
Check out 3.3 This should now be fixed.
