### ISSUE TITLE
screen stays greyed out after ad ends

### ISSUE THREAD

**Issue by Y3110wdud3** [TheRealJoelmatic/RemoveAdblockThing#319]
**Script version**
3.3

**Describe the bug**
After the bug skips, the screen is still greyed out
I think this might be a bug related to ad center

**Expected behavior**
Screen should not be grey

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser microsoft edge
 -  - Version [e.g. 22]

**Additional context**

**Comment by Taku0411** [comment]
@Y3110wdud3 
I have the same issue on version 3.4, windows 11 22H2.
For temporary measure, I add the following code in the end of function removePageAds(), and it works well for me now.
~~~
// select gray element and remove 
let elem = document.querySelector("body > tp-yt-iron-overlay-backdrop");
elem.remove();
~~~

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version
