### ISSUE TITLE
3.3 still plays adds and add some freezing feature too

### ISSUE THREAD

**Issue by AuZ-ASD** [TheRealJoelmatic/RemoveAdblockThing#321]
after the 3.2 desaster and downgrading to  2.9.  i tried 3.3 today... 
looked good at the start but then i had two times the youtube tab freez... and now... i see ADD spam!

win 11
firefox 115,6,0esr

**Comment by PaulaBras** [comment]
Try Version 2.9. you will still get the please update me Promt from the script but no ads.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version
