### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Michael21107** [TheRealJoelmatic/RemoveAdblockThing#322]
Do you know if the releases are needed, as the script can be updated automatically through Temper Monkey?

**Comment by TheRealJoelmatic** [comment]
The lastest version of the script will always be found here [Youtube-Ad-blocker-Reminder-Remover.user.js
](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/main/Youtube-Ad-blocker-Reminder-Remover.user.js)

The releases tab is there for almost like milestones making it easier to downgrade if need be.

**Comment by Michael21107** [comment]
gotcha, thanks
