### ISSUE TITLE
constant update reminder when application is up to date

### ISSUE THREAD

**Issue by BlueNinja01** [TheRealJoelmatic/RemoveAdblockThing#326]
**Script version**
3.3

**Describe the bug**
occasionally I will get a popup that will tell me that the application is out of date. I will then go to the tampermonke page to update the script and I will learn that "RemoveAdblockThing" is already up to date. also when the popup is closed I will download a file called "Youtube-Ad-Blocker-Reminder-Remover.user.js" 

**Expected behavior**
The update script popup is shown, there must be an update to download and there should be no file downloaded when popup is closed.

**Screenshots**
non needed

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser [OperaGX]
 - Version LVL 5 (core: 105.0.4970.76)

**Additional context**

**Comment by dahomieomi** [comment]
having the same issue

**Comment by BeefBaby** [comment]
Yeah it keeps happening to me too.

**Comment by John-1a** [comment]
The workaround for me was to set _const updateCheck_ from true to false (line 27 in the script)

**Comment by TheRealJoelmatic** [comment]
A new update popup has been implemented now that is no longer intrusive and fixes this problem.
