### ISSUE TITLE
3.3 Version Occasionally blocks video ADS.

### ISSUE THREAD

**Issue by Pooland1** [TheRealJoelmatic/RemoveAdblockThing#329]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
3.3

**Describe the bug**
This doesn't work at all. Only blocks ads occasionally now, it also stopped blocking these ads 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/140262669/6f3a7af9-88fb-4502-94b8-5808133aecdd)

**Expected behavior**
Block every ad including outside of video

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/140262669/bc41c4ab-e620-4635-a609-1bffd6ed414d)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/140262669/cecf21f4-2f20-4b9e-9c1e-e7251b96dd5b)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2
 - Browser: Microsoft Edge
 - Version: 3.3 

**Additional context**
None.

**Comment by Athliara** [comment]
- OS: Windows 11 23H2
- Browser: Mozilla Firefox 121.0.1
- Version: 3.3

I get ads everytime. Only version 2.8 worked for me. From 2.9 to 3.3 the script broke.

Thank you

**Comment by Athliara** [comment]
Just saw that it got updated to 3.4
I do not get ads on 3.4 anymore.

Thanks again!

**Comment by TheRealJoelmatic** [comment]
♥️
