### ISSUE TITLE
ad yellow bar appears for a split second then player controls (skip,fwd,settings,etc...) becomes unavailable

### ISSUE THREAD

**Issue by kpgrafix** [TheRealJoelmatic/RemoveAdblockThing#330]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by kpgrafix** [comment]
they will show up again at the end of video, but cannot click anything else inside the player (other videos or the player controls)

**Comment by fuste76** [comment]
Same issue randomly appears here. Nearly every second or third video. Navigating through video is only possible with left/right arrow keys and using space key to start/stop. Have to reload the video.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
