### ISSUE TITLE
Overlay after playback Script V3.4

### ISSUE THREAD

**Issue by Guilhermewash** [TheRealJoelmatic/RemoveAdblockThing#331]
**Script version**
Script version: 3.4

**Describe the bug**
After some reproductions, a gray film appears whose code is 
```
(<tp-yt-iron-overlay-backdrop class="opened" style="z-index: 2201;" open=""><!--css-build :shaded-->
</tp-yt-iron-overlay-backdrop>)
``` 
 Which prevents YouTube from playing the next video and the user from clicking on the page

**Expected behavior**
This film does not allow the user to touch anything, disrupting the flow of reproduction and usability.

**Desktop (fill in the following information):**
 - SO: Windows 10 22H2
 - Google Chrome browser
 - Version 120.0.6099.217 (official version) 64 bits

**Comment by Guilhermewash** [comment]
Correction.
The overlay opens after the script runs.

**Comment by Spiderfreak** [comment]
I use Opera GX and I'm also getting this. It's like there's the little pop-up with the update thingy showing up but it's invisible or something.

At times u can actually click on the page to get rid of it, but sometimes u cannot and u are forced to refresh as a result.

**Comment by Guilhermewash** [comment]
You can use the browser's inspect and delete the overlay element so you can continue.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
