### ISSUE TITLE
dark screen appears after ad passes on v3.3

### ISSUE THREAD

**Issue by Blank06230623** [TheRealJoelmatic/RemoveAdblockThing#332]
**Script version**
v3.3

**Describe the bug**
dark screen appears after ad passes

**Desktop**
 - OS: Windows 11 23H2
 - Browser: Chrome 120.0.6099.217

**Comment by ralinchan** [comment]
Also happens on v3.4 on Firefox 121.0.1

Overlaid dark screen that can't be interacted with and must refresh page

**Comment by shufurudin** [comment]
Same here.

_OS: Windows 10
Browser: Chrome
Browser Version: 120.0.6099.217
Remove Adblock Thing ver.: 3.2_

**Comment by Spiderfreak** [comment]
I use Opera GX and I'm also getting that. It's like there's the little pop-up with the update thingy showing up but it's invisible or something.

I'm also on v3.4

**Comment by tuankiet116** [comment]
Same here, it's because of this element 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/57905166/dd872643-66e8-4ba8-90b5-35fbbe652f27)
Hope you can fix it as soon as posible.

**Comment by UndiedGamer** [comment]
or just delete the element everytime until they find a fix

**Comment by tuankiet116** [comment]
just update script by myself

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
