### ISSUE TITLE
Ad skipping doesn't occur on the mobile YouTube website

### ISSUE THREAD

**Issue by lflaurflorin** [TheRealJoelmatic/RemoveAdblockThing#335]
**Script version**
3.4

**Describe the bug**
Ads are not skipped on the mobile YouTube website (https://m.youtube.com/*)

**Expected behavior**
I should have seen a number popping up in tampermonkey, meaning that the script is activated, but it was not activated.
Checking the script edit, i found some check matching the desktop YouTube website, but not for the mobile YouTube website. Thus, are not skipped on m.youtube.com - mobile

I don't know is this is the cause of not... But it appears to be just from my observations. 
Hope it will sort the issue for mobile YouTube website. Thank you!

**Screenshots**
![Screenshot_20240116_030911_Firefox](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/141065083/e36ff54a-7c68-44d5-b7dc-561e85e52b91)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Android 
 - Browser [e.g. chrome, safari] Firefox

**Additional context**

**Comment by UndiedGamer** [comment]
the mobile youtube runs a different website and sadly no one can clearly hack into devtools on it

**Comment by lflaurflorin** [comment]
I'm still grateful that it works on the regular YouTube 😁 thank you for pointing this out, i wasn't aware of this.

On mobile, i do have alternatives, so for now i will be happy with them on mobile and with this script on desktop.

**Comment by Thraxelon** [comment]
For this, i do this change :
Change the @match line from https://www.youtube.com/* into https://*.youtube.com/*

This will also allow ad skips on youtube mobile, and youtube music on my browser
