### ISSUE TITLE
Dark screen

### ISSUE THREAD

**Issue by St3ph3n512** [TheRealJoelmatic/RemoveAdblockThing#337]
The current version of this script successfully skips through ads, however the second an ad is skipped, the screen goes dark and the tab is frozen. In this state, the video still plays, but youtube is unusable, and the only way to bypass it is to refresh the page. This often means that the screen will always be dark and youtube is constantly broken, because ads are automatically played every time the page is refreshed.

**Comment by slzero-X** [comment]
The reason this happens is that due to a error in the code, it does not remove the darken element that is created when an ad plays then closes, as its random if the darken element appears or not after an ad finishes.

**Comment by supersmith2500** [comment]
Google is getting wiser and Joel hasn't done anything. If this extension isn't fixed. I will find a new one or stop using YouTube.

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
