### ISSUE TITLE
The dark screen issue was not fixed, I just got it again

### ISSUE THREAD

**Issue by slzero-X** [TheRealJoelmatic/RemoveAdblockThing#338]
Script version is 3.5, claiming to fix the bug but it still happens, so my manual removal solution is still the only way.
Are you sure you tested the script correctly Joel?

**Comment by skakhund** [comment]
doesn't work for me either again

**Comment by Pendrag00n** [comment]
Happening to me on Firefox 121.0.1 and version 3.5 of the script

**Comment by slzero-X** [comment]
Chrome, some of you will be mad but under the living circumstances as of right now, I can't use any other browser.

**Comment by TokyoTF** [comment]
When the popupRemover() function is executed it is executed only once, and I also see that modalOverlay - ("dark screen") YouTube puts it a few seconds after the page loads so it is 50/50 that it deletes the modalOverlay - (" dark screen")

**Comment by TokyoTF** [comment]
Here I leave you a mini solution that works for me.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/52444606/1e27f304-74d2-4f0d-9d17-b9cbe3d2bada)

**Comment by Pendrag00n** [comment]
> Here I leave you a mini solution that works for me. ![image](https://private-user-images.githubusercontent.com/52444606/297625555-1e27f304-74d2-4f0d-9d17-b9cbe3d2bada.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1ODY2OTEsIm5iZiI6MTcwNTU4NjM5MSwicGF0aCI6Ii81MjQ0NDYwNi8yOTc2MjU1NTUtMWUyN2YzMDQtNzRkMi00ZjBkLTlkMTctYjljYmUzZDJiYWRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDEzNTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTdiNzMxODBlMzJhODA3ODJiMjczNTk0ZmQyNTFmODY5MTg4NWY4NDVjYThjY2Y2NzI3NTcyNmQxNDQxZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CWksCYlqto9QNiw4hWw3AV930S8zgLTOMbFurzMsd3w)

Your fix seems to be working perfectly!

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
