### ISSUE TITLE
Recommending Violentmonkey instead of Tampermonkey

### ISSUE THREAD

**Issue by heyitsazar** [TheRealJoelmatic/RemoveAdblockThing#34]
Thanks for the project! I think we all love open source software so recommending Violentmonkey instead of Tampermonkey on README file is a good idea, in my opinion. Hope contributors also agree with me.

**Comment by Dyras** [comment]
@itsmetoolala
Of course, but isn't it better to recommend FOSS instead of proprietary? Just saying.

**Comment by Official-Husko** [comment]
I second this. Tampermonkey has been proprietary closed source software for a while now. We are on an open-source project so why not advocate for an open-source alternative instead?

**Comment by Official-Husko** [comment]
@TheRealJoelmatic This issue has been marked as "completed" but there is still Tampermonkey on the README. Are the changes still pending or was this just closed?
