### ISSUE TITLE
Constant reminder to update script while on latest update

### ISSUE THREAD

**Issue by GoopGhostt** [TheRealJoelmatic/RemoveAdblockThing#340]
I get constant reminders that I need to update my script, but its already up to date. I'll get 3 alerts in a row back to back and my screen will go slightly dark and I cant click anything, the only thing I can do is refresh the page and sometimes it'll do it again.

Windows 10
Opera GX LVL 5 (core: 105.0.4970.76)

**Comment by keenoy** [comment]
I wonder why this script is working outside the youtube. It literally spams update alerts everywhere with youtube video like google search, even it cannot update there.

**Comment by TokyoTF** [comment]
To stop receiving updates just set updateCheck to false
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/52444606/f3007b6b-524c-4229-a28f-88102c19409b)

**Comment by Muhiyaddeen** [comment]
> To stop receiving updates just set updateCheck to false ![image](https://private-user-images.githubusercontent.com/52444606/297623765-f3007b6b-524c-4229-a28f-88102c19409b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTc5MDcsIm5iZiI6MTcwNTU1NzYwNywicGF0aCI6Ii81MjQ0NDYwNi8yOTc2MjM3NjUtZjMwMDdiNmItNTI0Yy00MjI5LWEyOGYtODgxMDJjMTk0MDliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA2MDAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3ZWRiNzhmMTllZTlkOWQ5MjQxMmFjYWVhYWVjNzlkMjI5YWMyMjQxOGNlMGQ3NjAwMzExZjFkZWViODBkY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LbwpMV6GnCbBopc8ebSxJdJ0-nRO2-Eun6O39fYPX9U)

thanks that helped

**Comment by TheRealJoelmatic** [comment]
A new update popup has been implemented now that is no longer intrusive and fixes this.
