### ISSUE TITLE
Even though the ad got skipped, there was still a dark film/screen

### ISSUE THREAD

**Issue by Spiderfreak** [TheRealJoelmatic/RemoveAdblockThing#341]
**Script version**
v3.5

**Describe the bug**
Ad got skipped but there was the dark film/screen thing that appeared over the ad so even though it got skipped the dark screen just remained, making now my video continue with a dark film/screen over it. To which I'm unable to click on any part of the screen as a result forcing me to refresh the page and restart the video.

**Expected behavior**
I expected to see the ad be cleared without a dark film/screen over my video

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: My version is LVL 5 (core: 105.0.4970.76)

**Additional context**
When the ad appeared the dark film/screen went over it and as a result of that, I was not even able to click on the skip button in general, despite it already automatically skipping eventually.

**Comment by TokyoTF** [comment]
Here I leave a solution to the dark screen _https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/338#issuecomment-1897818271_

**Comment by Naginreed** [comment]
@Spiderfreak 
Can you check with 3.7 and a restart of the Browser after the Update?

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
