### ISSUE TITLE
Remove ads blocker detected pop-up on all sites!!

### ISSUE THREAD

**Issue by krimnassim** [TheRealJoelmatic/RemoveAdblockThing#343]
HI,is there a chance this script to support removing [ads blocker detected] pop-up on all websites in the future?
![Capture](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/62130284/46c87f37-0668-4f06-bacb-597c12bf5f8f)

**Comment by Naginreed** [comment]
It needs to be fitted manually for every single "ad blocker detected" page you are trying to block,
just having it working and updating for youtube is a lot of work, 
so i dont think there will be support for any other site in this project
