### ISSUE TITLE
Static Ads are not skipped

### ISSUE THREAD

**Issue by Thraxelon** [TheRealJoelmatic/RemoveAdblockThing#346]
**Script version**
3.5 (when installed will display the version as 3.4)
**Describe the bug**
Youtube will instead display static ads, with no videos. This is not skipped by the script.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/58166832/68586979-ccd6-4e43-8a9a-45f36ea8f197)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera GX
 - LVL5 (core: 106.0.4998.42) Chromium version:120.0.6099.200

**Comment by supersmith2500** [comment]
Joel's giving up.

**Comment by felipemslima** [comment]
I'm having the same issue

**Comment by supersmith2500** [comment]
3.8 and still not fixed. Any solutions?

**Comment by Thraxelon** [comment]
> 3.8 and still not fixed. Any solutions?

Seems like this issue depends on which ads played,
My issue still persists in 3.8,  but rarely now. Still haven't found a fix for this

**Comment by Thraxelon** [comment]
Closing this issue since this issue still persists on the latest version,
pointing to the newest issue at #367 .

**Comment by Thraxelon** [comment]
Closing this issue since this issue still persists on the latest version,
pointing to the newest issue at #367 .
