### ISSUE TITLE
Script triggers CSP Report

### ISSUE THREAD

**Issue by samuel-jimenez** [TheRealJoelmatic/RemoveAdblockThing#347]
**Script version**
3.5

**Describe the bug**
Script triggers CSP. Error message:
`Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). content.js:60:456`

**Expected behavior**
CSP adjusted to allow script.

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 121

**Additional context**

Report sent to https://accounts.youtube.com/_/IdentityRotateCookiesHttp/cspreport
POST data:

`{"csp-report":{"blocked-uri":"inline","column-number":456,"disposition":"enforce","document-uri":"https://accounts.youtube.com/RotateCookiesPage?origin=https://www.youtube.com&yt_pid=1","effective-directive":"script-src-elem","line-number":60,"original-policy":"script-src 'nonce-hpjqiK1IsVad2aMgD5ChbQ' 'unsafe-inline'; object-src 'none'; base-uri 'self'; report-uri https://accounts.youtube.com/_/IdentityRotateCookiesHttp/cspreport; worker-src 'self'","referrer":"https://www.youtube.com/","source-file":"moz-extension","status-code":200,"violated-directive":"script-src-elem"}}`

**Comment by mcmanaman8** [comment]
I second that. I just went back to 2.9, that one is still working fine for me on Brave.

**Comment by Naginreed** [comment]
So it looks like the CSP is complaining about loading sweetalert2@11 or something within it?

### Workaround 1 - dont load sweetalert2@11

1. Upgrade to the [newest Version](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/main/Youtube-Ad-blocker-Reminder-Remover.user.js?raw=True) 
2. Open Tampermonkey Dashboard
3. Click on the Edit Button on the right side by "Remove Adblock Thing"
4. On Line 36 (under const updateModal) change the enabled: true to enabled: false
5. On top left hit File -> Save (or CTRL+S)
6. Restart the Browser an check if that fixed it

_This should prevent loading sweetalert2@11 Library without turning off your Script-Update pop-ups,
but this change **needs to be redone after every update**_ 

___
### Workaround 2 - No more Updates
1. Upgrade to the [newest Version](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/main/Youtube-Ad-blocker-Reminder-Remover.user.js?raw=True) 
2. Open Tampermonkey Dashboard
3. Click on the Edit Button on the right side by "Remove Adblock Thing"
4. On Line 27 change const updateCheck = `true` to const updateCheck = `false`
5. On top left hit File -> Save (or CTRL+S)
6. Restart the Browser an check if that fixed it

_This turns of checking for script-updates completely, therefore no alerts_
