### ISSUE TITLE
Version 3.5 does not work in Vivaldi

### ISSUE THREAD

**Issue by oomek** [TheRealJoelmatic/RemoveAdblockThing#348]
**Script version**
3.5

**Describe the bug**
Does not work in Vivaldi

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/2974860/f6bf402a-219f-44b6-9764-56634f3af65c)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Vivaldi
 - Version 6.5.3206.55

**Comment by karenda-jp** [comment]
Have you confirmed the installation?
![inst](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/157136243/ddde9e4f-4d61-4d18-bf06-261c72a0fa80)

**Comment by oomek** [comment]
My bad, I had a youtube add blocking extension still active.
