### ISSUE TITLE
wtf is happening

### ISSUE THREAD

**Issue by Ninjatintin** [TheRealJoelmatic/RemoveAdblockThing#3485]
why are there scam bots here

**Comment by lee-jin-gyu96** [comment]
Creating an issue pointing out the ongoing and very obvious issue spam bot situation probably just adds one more issue the contributors need to close

**Comment by LowTierGod445** [comment]
"Creating an issue that points out the ongoing and very obvious issue spam bot situation (and adds nothing of particular value) probably just adds one more issue the contributors need to close" 🤓☝

**Comment by photosense** [comment]
Additional comments on the posts regarding the obvious spam bot situation do not, however, add an issue that needs to be closed. (but they still do not add anything of value) B)

**Comment by lee-jin-gyu96** [comment]
> Additional comments on the posts regarding the obvious spam bot situation do not, however, add an issue that needs to be closed. (but they still do not add anything of value)

Yeah, I was hoping suggesting better ettique without adding to the workload would be of some value, but clearly that's not the case ¯\_(ツ)_/¯

**Comment by Ninjatintin** [comment]
"Additional comments on the posts regarding the obvious spam bot situation do not, however, add an issue that needs to be closed. (but they still do not add anything of value)" 🤓☝
