### ISSUE TITLE
3.5  +3.7  whole page gets grey and no more controle

### ISSUE THREAD

**Issue by AuZ-ASD** [TheRealJoelmatic/RemoveAdblockThing#350]
**Script version**
3.5
edit +3.7

**Describe the bug**
whole youtube page gets a gray tint and the video controls are lost... cant klick anythere

**Expected behavior**
normal pagecolor and not lost control

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: win11
 - Browser firefox 115.6.0esr
 - Version 115.6.0esr

**Additional context**

**Comment by AuZ-ASD** [comment]
same on 3.7

**Comment by ZayxSt** [comment]
yup the whole website destroyed

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
