### ISSUE TITLE
Dark screen still happens (Google Chrome, Script Version 3.7)

### ISSUE THREAD

**Issue by slzero-X** [TheRealJoelmatic/RemoveAdblockThing#351]
Seems it's not possible to prevent it fully, it will always seem to come back again and again, so there appears to be no counter-measure other than manually deleting the element by the end-user.

**There is a literal PULL REQUEST that actually fixes the dark screen, seriously man**

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version
