### ISSUE TITLE
3.7 the screen becomes dimmer after skipping an ad (mozila)

### ISSUE THREAD

**Issue by Rooobertas** [TheRealJoelmatic/RemoveAdblockThing#352]
**Script version**
3.7

**Describe the bug**
The screen becomes dimmer after an ad has been skipped

**Expected behavior**
Skips ad then the screen dimms. Left click to make the screen brighter...

**Screenshots**
sorry no

**Desktop (please complete the following information):**
 -w10
 - Mozila
 - Version 121.0.1.

**Additional context**

**Comment by Naginreed** [comment]
**OS:** Microsoft Windows [Version 10.0.19045.3930]
**Browser:** Mozilla Version 121.0.1 (64-Bit) & Chrome: Version 120.0.6099.225 (Official Build) (64-bit)
both with **3.7 Script** installed on Tampermonkey 5.0.1

### Before Ad
![before](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/4f8c6a14-2217-4c3a-94ce-88b07f35d86f)
### After Ad
![after](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/b7ac0ebd-ea7a-4912-9068-8cbb3b7f6316)

### More detailed Explanation
- happens in all views (Default, Theather, Full-Screen)
- All Video Control is blocked, you cant interact with anything until returned back to normal
- "Left-Click" helps sometimes to Escape the greyzone, but sometimes 2x "ESC" is needed

After **Inspecting** the grey zone apperantly this is called
```
<tp-yt-iron-overlay-backdrop class="opened" opened="" style="z-index: 2201;"><!--css-build:shady-->
</tp-yt-iron-overlay-backdrop>
```

**Comment by slzero-X** [comment]
I am trying out the ignored pull request myself and so far the dim screen has not showed up, if I see it appear momentarily and then disappear consistently then the pull request that was closed actually works.

**Comment by Naginreed** [comment]
@slzero-X i guess you mean #336 which has over 190 changes to current one,

### The one change considering this issue
adding the `tp-yt-iron-overlay-backdrop,` as new line 
in the `function removePageAds`
under section `style.textContent`
just seems to work but gonna check on that for a longer time

**Comment by Guilhermewash** [comment]
Inside the code on line 173, look for "if (hide background) hidebackdrop.remove;" and replace with " if (hidebackdrop) hidebackdrop.remove();"

**Comment by Guilhermewash** [comment]
Adding the () function, it worked here

**Comment by nhan212001** [comment]
set removepopup = true on line 24 will fix this

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version
