### ISSUE TITLE
Watch history no longer works / Some videos  wont play due to being only playable directly on youtube 

### ISSUE THREAD

**Issue by ViSlayer** [TheRealJoelmatic/RemoveAdblockThing#3532]
Because of how the extension now works opening a secondary youtube screen over the default one, youtube thinks we are not signed in so it no longer records watch history, which also means videos we have already clicked keep showing up on the homepage, this also means videos that are set to be played only on youtube will not play at all instead we are given a please watch on youtube screen over and over as you click it

**Comment by hoharrison** [comment]
Still having the same issue @TheRealJoelmatic
