### ISSUE TITLE
[Bug] Age Restrict + Double video

### ISSUE THREAD

**Issue by AzureDao** [TheRealJoelmatic/RemoveAdblockThing#3540]
version
5.6

- Some video is age restricted and can't be access even tough normally is not.. I think youtube didn't recognize my account for the video...
- Sometimes(rarely) the double video still happens

- to much refresh the page 

it's more annoying using this than watching the ads itself

**Comment by ArcusMG** [comment]
I have this same problem. I think it thinks it’s playing an imbedded video. That’s why it keeps wanting you to watch it on YouTube’s website, even though you already are. That also might explain some of the features being missing, like autoplay and skip forward and skip back.
