### ISSUE TITLE
3.7 Screen bugs and dims the player

### ISSUE THREAD

**Issue by imbader** [TheRealJoelmatic/RemoveAdblockThing#355]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
3.7
**Describe the bug**
3.7 Screen bugs and dims the player
**Expected behavior**
3.7 Screen bugs and dims the player
**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
Safari , Latest version 
**Additional context**
fix it asap

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version (3.8).
