### ISSUE TITLE
Can't pause the Videos - videos resume automatically within seconds

### ISSUE THREAD

**Issue by arijitcodes** [TheRealJoelmatic/RemoveAdblockThing#357]
**Script version**
3.8

**Describe the bug**
Once the video starts playing, if I pause the video, it starts back automatically.

**Expected behavior**
The video should stay paused - until I resume it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 120.0.6099.225 (Official Build) (64-bit)

**Comment by arijitcodes** [comment]
Update: I have noticed, if I put the 'removePopup' flag to false, the problem doesn't happen.
But when I keep the 'removePopup' flag to true, the problem occurs.

Note: The reason I kept the removePopup flag as true because of the Static Skippable ads that were being displayed (issue #346 )

**Comment by Naginreed** [comment]
@arijitcodes 
> Note: The reason I kept the removePopup flag as true because of the Static Skippable ads that were being displayed (issue #346 )

Did you check if the static skippable issue still occurs if you are using default settings?

**Comment by TheRealJoelmatic** [comment]
Just pushed a simple [fix to this problem .,](https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js)

**Comment by arijitcodes** [comment]
> @arijitcodes
> 
> > Note: The reason I kept the removePopup flag as true because of the Static Skippable ads that were being displayed (issue #346 )
> 
> Did you check if the static skippable issue still occurs if you are using default settings?

Yes.. We still get Static Skippable Ads when using with default settings. Even with the removePopup = true we get the Statis Skippable ads.

**Comment by supersmith2500** [comment]
I'm still getting static ads.

**Comment by arijitcodes** [comment]
> I'm still getting static ads.

@supersmith2500 
This issue was for Video Pause auto resume bug(read the main description).
Your Static Ads problem is opened on another issue ( issue #346 ), follow that if you want to.

**Comment by supersmith2500** [comment]
> This issue was for Video Pause auto resume bug (read the main description).
> Your Static Ads problem is opened on another issue ( issue #346 ), follow that if you want to.

There is no solution to it at the minute. Both on false and true still occurs static ads.

**Comment by arijitcodes** [comment]
> > This issue was for Video Pause auto resume bug (read the main description).
> > Your Static Ads problem is opened on another issue ( issue #346 ), follow that if you want to.
> 
> There is no solution to it at the minute. Both on false and true still occurs static ads.

This issue is NOT about Static Ads. To follow development / progress about Statis Ads bug, check the issue mentioned in my last response. And I am sure the authors and contributors will be looking into that issue as well, or, they are already looking into it.
