### ISSUE TITLE
Not and issue, just wanted to say thanks.

### ISSUE THREAD

**Issue by mcmanaman8** [TheRealJoelmatic/RemoveAdblockThing#358]
Sorry for posting on the issue page, I wish there was a comment section or something. Maybe there is and I didn't find it.
This latest update is perfect!
Just came from 2,9 which was working fine for me, but this one takes the cake. Extremely fast ad skipping, zero youtube bs.
Thank you very much. Y'all are doing gods work.

**Comment by curiouspolice** [comment]
Came to say the same thing. Bless your heart joelmatic <3
