### ISSUE TITLE
Scroll Bars on Fullscreen

### ISSUE THREAD

**Issue by fuckyou666555** [TheRealJoelmatic/RemoveAdblockThing#36]
Addblock seems to work, no more Notification as well. But once I enter fullscreen I get vertical and horizontal scrollbars on the border of my screen

**Comment by kaimaru18** [comment]
same problem here

**Comment by Neverwinterx** [comment]
Same here. I use Firefox. Scrollbars at bottom and right in fullscreen.

**Comment by Cairo283** [comment]
Well that fixed the scrollbars, but now I'm getting mid-roll ads again.

**Comment by DanielDuesentrieb257** [comment]
For me was working to remove line 77 in the script which says:
`bodyStyle.setProperty('overflow', 'scroll', 'important');`

**Comment by Yashow98** [comment]
> For me was working to remove line 77 in the script which says: `bodyStyle.setProperty('overflow', 'scroll', 'important');`
> 
> EDIT: On the latest Update from author the line changed to N° 89

Thanks! it works for me too.

**Comment by TheRealJoelmatic** [comment]
It should be fixed in the latest version.
