### ISSUE TITLE
Yoooo would yall stop saying this stuff ia 

### ISSUE THREAD

**Issue by WoeIsLee** [TheRealJoelmatic/RemoveAdblockThing#3600]
Now I gotta ask someone to link me the 3.6 or 3.8 file again.

**Comment by kr4kken** [comment]
> Now I gotta ask someone to link me the 3.6 or 3.8 file again.

there is a 3.8??? where?

**Comment by WoeIsLee** [comment]
Idk search the closed issues and look for ones with a lot of comments, its in there somewhere, luckily mine never actually reverted.

**Comment by kr4kken** [comment]
> Idk search the closed issues and look for ones with a lot of comments, its in there somewhere, luckily mine never actually reverted.

i found some sources, thanks!
