### ISSUE TITLE
Popups a video player over the original player

### ISSUE THREAD

**Issue by nixkix05** [TheRealJoelmatic/RemoveAdblockThing#3606]
**Script version**
5.6

**Describe the bug**
When a video is loaded. It loads as a popup over the original video player. There are ads sometimes in the back video player sometimes if the page loads wrong.

**Expected behavior**
I expect to not see a video player popup over the original player. That is the most annoying thing I've dealt with since 5.0. Even Downgrading to 5.0 is better even with the YT Ad popup. All I have to do is reload the page a couple times, or even just once and it still removes ads.

**Desktop (please complete the following information):**
I'm running Windows 11 with the latest Chrome update

**Comment by wiiotaku** [comment]
Well I guess I'm sorry to say but now that's the way it works because according to the release package description:
"The update changed the way the ads are skipped to no longer get detected by YouTube"

**Comment by nixkix05** [comment]
> Well I guess I'm sorry to say but now that's the way it works because according to the release package description: "The update changed the way the ads are skipped to no longer get detected by YouTube"

It still works better than the newer versions. The "The update changed the way the ads are skipped to no longer get detected by YouTube" doesn't mean anything if the older version works better. I test other versions, and if they work then they do. If you never tested it then you can't say much.
