### ISSUE TITLE
Sound problem

### ISSUE THREAD

**Issue by oceandi** [TheRealJoelmatic/RemoveAdblockThing#3608]
[Youtube-Ad-blocker-Reminder-Remover.user.js]
5.0

video audio sounds more muffled than usual

I couldn't see the part in the code that would create noise, but it doesn't happen with add blocker.

**Desktop (please complete the following information):**
 - Macos Sonoma
 - Chrome
 - Version 126.0.6478.62 (Official Build) (arm64)

**Additional context**
here is my email:
korkmaz.x7@gmail.com

**Comment by lenhatquang2512** [comment]
I had the same issue; reloading YouTube solved it. However, there is still laggy for about 1-2 seconds.
