### ISSUE TITLE
Doesn't show red "watched" bar 

### ISSUE THREAD

**Issue by LeoGirl0727** [TheRealJoelmatic/RemoveAdblockThing#3609]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by LeoGirl0727** [comment]
It may seem like a small thing, but watching so many political news sources, I need to know which ones I have already watched, which is shown by the red bar at the bottom.  I do not have any ad issues using AdBlock alone, except for syndicated shows, such as Jimmy Kimmel.  I use Tamper for those only.

**Comment by Roachymart** [comment]
I have version 5.6 and it is not marking videos as watched at all. It's also having issues with videos that need to be played in youtube only because something is making it think it's not being watched from the site.
