### ISSUE TITLE
Start at 0:00 when I watch by Full screen

### ISSUE THREAD

**Issue by GithubSeongGwan** [TheRealJoelmatic/RemoveAdblockThing#3611]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
5.6

**Describe the bug**
Start at 0:00 when I watch by Full screen, or turn off Full Screen.
Usually I use the short key "f"

**Expected behavior**
I expect to see at the point where I was watching at.

Also, I want to see the video at the point where I watched at last time. (When I first click the video. Not related to the full screen.)

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by H3X3R** [comment]
Yes, the same thing happens. Whenever I press "F" key to fullscreen and un-fullscreen, the video starts from the beginning.

Laptop:
    OS: Windows
    Browser: Firefox
    Version 127.0.1

**Comment by wiiotaku** [comment]
Weird, mine doesn't do that unless I use a timestamp (in that case, it would go to back to the time indicated in the timestamp)
