### ISSUE TITLE
Can't watch age-restricted videos

### ISSUE THREAD

**Issue by AsielApodaca** [TheRealJoelmatic/RemoveAdblockThing#3612]
**Script version**
5.6

**Describe the bug**
Videos that are restricted by age don't load, showing a letter "This video is age-restricted and only available on YouTube". The video plays normally when I turn off the script.

**Expected behavior**
I'm logged with legal age, the video should play normally.

**Screenshots**
![Captura de Pantalla 2024-06-21 a la(s) 23 09 49](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/91578957/a9906c6e-4d45-4031-94d6-89a2b9062780)

**Desktop (please complete the following information):**

**Additional context**

**Comment by wiiotaku** [comment]
the videos are now played in a youtube embed player like they were outside youtube (because that's the new way how the script works in order to not be detected by youtube) so you have to deactivate the script in order to watch these
