### ISSUE TITLE
Hides Player bar buttons

### ISSUE THREAD

**Issue by kpanos777** [TheRealJoelmatic/RemoveAdblockThing#3614]
The script also hides Player bar buttons, as the Subtitles, Mini Player, Cinema mode, Autoplay and custom buttons.

**Comment by kpanos777** [comment]
I just downgraded to v3.8 and it seems to be fine.



   On Sunday, June 23, 2024 at 08:25:49 PM GMT+3, Kevinuara ***@***.***> wrote:  
 
 


Hi! Likewise, since like yesterday, that script, while using it with TamperMonkey on Google Chrome on Windows 10, hides several button. I can no longer go into theater mode and when using a playlist, it won't autoplay the next video.

**Comment by Euqoram** [comment]
the newer versions use the youtube embedded video player, you can downgrade to [5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js) (click the Raw button on upper right) and that version is mostly functional. it sometimes gets detected on prerolls, but you can refresh past it till it's fixed, at least
