### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by TMan-21** [TheRealJoelmatic/RemoveAdblockThing#365]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TMan-21** [comment]
not working

**Comment by TheRealJoelmatic** [comment]
Please Describe what is not working.
