### ISSUE TITLE
Static ads still not skipped on Ver. 3.8

### ISSUE THREAD

**Issue by supersmith2500** [TheRealJoelmatic/RemoveAdblockThing#367]
**Script version**
3.8

**Describe the bug**
Static (some malware) ads are not skipped as the script doesn't do them.

**Expected behavior**
It is supposed to close the ad via the skip button without any click input.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 120.0.6099.225 (Official Build) (64-bit)

**Additional context**

If anyone is willing to find a solution, great! I know a similar issue is currently open but this is on a different version. https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/346

**Comment by minanagehsalalma** [comment]
Same problem here , it waits till that circle fills 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20546638/b433a20b-eec5-4c71-9a2a-2e30fe8f4455)

@TheRealJoelmatic

**Comment by Thraxelon** [comment]
Same here, hard to recreate it since it rarely happens for me, and when it happens, the timer is fast, and i cannot find a way to "pause" the timer to properly check it

**Comment by supersmith2500** [comment]
And now video ads won't skip and lacks a skip button.

**Comment by Naginreed** [comment]
Since i have never seen any static ad even if i turn the script off,
is there a possibility these are regionally only?
If we can recreate the issue somewhat persistently its probably also easier to fix it.
When it happens, right-click one the Add and choose "Inspect" so we can post the findings here and (something like "ytp-....-.....")
to find out what is called and maybe trying out different ways to fully block or circumvent it

**Comment by minanagehsalalma** [comment]
@Naginreed i ctrl+s the page when it showed 

[test.zip](https://github.com/TheRealJoelmatic/RemoveAdblockThing/files/14027875/test.zip)

idk if it would be any useful tho

**Comment by minanagehsalalma** [comment]
> Which browser are you using and which country are you accessing youtube from?

@Naginreed latest chrome version on windows

hmm about the the country ... just mail me.

also the ad shows once every 10 vids or so.

**Comment by lullibeps01** [comment]
I used the TimerHooker script to stop the time and then I inspected the element, i copied the element and pasted in this file
[ads-static.zip](https://github.com/TheRealJoelmatic/RemoveAdblockThing/files/14037765/ads-static.zip)

Let me know if it is useful and if you need something else

**Comment by minanagehsalalma** [comment]
@Naginreed

**Comment by minanagehsalalma** [comment]
i was able to copy a part of it really quick 

```html
<img class="ytp-ad-image ytp-ad-action-interstitial-background" id="ad-image:1l" alt="" style="background-image: url(&quot;https://i.ytimg.com/vi/n48_tp6KHuc/hqdefault.jpg&quot;);">
```

**Comment by lullibeps01** [comment]
It seems to work again now, without any change to the code, maybe youtube changed something.

**Comment by rguca** [comment]
> Same problem here , it waits till that circle fills ![image](https://private-user-images.githubusercontent.com/20546638/298426875-b433a20b-eec5-4c71-9a2a-2e30fe8f4455.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDc0MDQsIm5iZiI6MTcwNjQ0NzEwNCwicGF0aCI6Ii8yMDU0NjYzOC8yOTg0MjY4NzUtYjQzM2EyMGItZWVjNS00YzcxLTlhMmEtMmUzMGZlOGY0NDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzMDUwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhNTMyNTZkMmY4Zjk2ZTNmZjU0OTdhNTI5YTBlMDEzMGRkNjZiNTA4MjU4ZjFkNjAzMDMzZjlhNjM4ZmE1MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3sqYVYd76ewI0dhINHy1XYiLg07p5a0J3gv7SA_EnvU)

I can confirm this behaviour. 
The log shows:
![Screenshot 2024-01-28 at 14 08 39](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/45061891/8b1ae0b2-6828-4bee-9e4d-69593d0d0844)
...many more.

It seems like it's pressing the skip button like crazy but it's not working.

**Comment by minanagehsalalma** [comment]
> like crazy but it's not working.

Cause it's clicking on the wrong button... It should check which button is present before triggering the click event.

**Comment by TheRealJoelmatic** [comment]
> > like crazy but it's not working.
> 
> Cause it's clicking on the wrong button... It should check which button is present before triggering the click event.

We are checking what buttons from a list exist and then clicking it
```
Line 171 to line 191

const skipButtons = ['ytp-ad-skip-button-container', 'ytp-ad-skip-button-modern', '.videoAdUiSkipButton', '.ytp-ad-skip-button', '.ytp-ad-skip-button-modern', '.ytp-ad-skip-button' ];
                
...

// Iterate through the array of selectors
skipButtons.forEach(selector => {
// Select all elements matching the current selector
const elements = document.querySelectorAll(selector);

// Check if any elements were found
if (elements && elements.length > 0) {
       // Iterate through the selected elements and click
       elements.forEach(element => {
              element?.click();
       });
}
});
```

**Comment by minanagehsalalma** [comment]
@TheRealJoelmatic is there a way to make it print more debugging info like what button is it continuously trying to click but failing ?

**Comment by rguca** [comment]
I added line 188 to log the element.

![Screenshot 2024-01-28 at 20 21 43](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/45061891/d1fb8403-2de7-4959-888c-e63e7b39b312)
![Screenshot 2024-01-28 at 20 21 25](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/45061891/b86d094e-5671-415d-a99c-a46867f9f900)

**Comment by minanagehsalalma** [comment]
> I added line 188 to log the element.

really cool

> elements.length is always 1

what does this mean? 

also what button is it supposed to be clicking ...the class name doesn't seem to be right.

**Comment by Entarra** [comment]
Been getting these too, we have the right class for the button as far as I can see.  Has me wondering if youtube has gotten wise to our tricks and ignoring programatic events (I tried faking them with dispatchEvent, and it still won't skip)

**Comment by MaKun01** [comment]
Has there been any update on this issue at all? It's been a few months now having this problem.
