### ISSUE TITLE
Ad Banner Shows Up

### ISSUE THREAD

**Issue by WesternGamer** [TheRealJoelmatic/RemoveAdblockThing#368]
**Script version**
3.8

**Describe the bug**
Ad banner shows up after multiple skipped ads on the same video. 

**Expected behavior**
Ad banner should be hidden

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/80211714/d8567f8b-4e64-4e35-bcb4-1c889807d027)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 120.0.6099.225

**Additional context**
None

**Comment by Naginreed** [comment]
@WesternGamer 
You mean the one in the top right? Or the little one inside the YouTube video?
Can you "just for testing" disable the other YouTube related extensions like vidIQ and check if they still show up, just to make sure they don't interfere with each other

**Comment by WesternGamer** [comment]
> @WesternGamer You mean the one in the top right? Or the little one inside the YouTube video? Can you "just for testing" disable the other YouTube related extensions like vidIQ and check if they still show up, just to make sure they don't interfere with each other

I mean the one on the top right. It does still pop up with vidIQ disabled, but I still have Return YouTube Dislike and Sponsorblock installed.

**Comment by Naginreed** [comment]
Next-Time you encounter it can you 
**Right-click** on it and **Inspect**?

You should see a highlighted Code similar like this
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/71943093/9b80368c-dc71-4fd2-bd19-cc264720b0b6)
We would need the ytp-xxx-xxx part.

I'm trying to recreate the problem

**Comment by AuZ-ASD** [comment]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/79934965/62edb7d9-6b0e-4a92-bae8-789ed1fef1f7)
