### ISSUE TITLE
Greyed circle spot on the mid

### ISSUE THREAD

**Issue by clovanzo** [TheRealJoelmatic/RemoveAdblockThing#369]
**Script version**
3.8

**Describe the bug**
It was quite surprising when I noticed there was a gray spot in the middle of the screen, at first I thought it was my monitor.

**Expected behavior**
clean screen

**Screenshots**
![Screenshot 2024-01-23 153935](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/20961761/2c4646f9-8e68-4c41-b23d-c1565afe9e6d)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome 
 - Version 120.0.6099.217

**Additional context**
none

**Comment by AuZ-ASD** [comment]
have the same but not all the time... my center of screen is in the lower right of the video.. first i thought my new screen is having some issue or is dirty... but then i found: the grey spot move around as i move my browserwindow around... so the grey spot is always on the same spot within the video player... only visible on white video
now i wanted to create screenie to show but currently its not happening...

**Comment by Entarra** [comment]
It's the drop-shadow part of the AdCenter not being hidden along with the main popup.
