### ISSUE TITLE
Ad correctly skipped but still requiring to press skip button.

### ISSUE THREAD

**Issue by MaKun01** [TheRealJoelmatic/RemoveAdblockThing#376]
**Script version**
3.8

**Describe the bug**
Ad is correctly skipped but the part after the ad still appears requiring to press the skip button in order to return to video.

**Expected behavior**
Ad is skipped and doesn't require me to click on the skip button but automatically continues playing the video

**Screenshots**
![image_2024-02-04_181758869](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/105678775/7369326c-0cc2-4e16-85b6-ba0bfd9e36fa)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Opera One (Opera)
 - Version 106.0.4998.70

**Comment by Entarra** [comment]
Been messing with these a bit myself and as far as I can tell we have the correct class for the button but it still does not work.  Snooping about with the console I'm seeing mouseover and focusin events on the button container that have me wondering if youtube has added some sort of detection for "real" clicks.

I did try faking those  (sending a dispatchEvent() to the elements), but that doesn't seem to do it either.  So I'm at a loss for options.
