### ISSUE TITLE
[FIXED] Pages are loaded/refreshed twice which gets really annoying

### ISSUE THREAD

**Issue by mcgifthub** [TheRealJoelmatic/RemoveAdblockThing#377]
EDIT: BUG RESOLVED
Fix: For me it was my NordVPN which had web protection/ad blocker enabled which caused it. If you have similar issues try disabling similar services you might have enabled or certain ad blockers.

----------------------------------------------------------------------------------

**Script version**
3.8 (also with 1.0 version so probably all versions)

**Describe the bug**
So whenever I load a page every time it reloads an extra time automatically which trust me, gets very annoying over time. Imagine every new page you load, it reloads twice, it makes my PC feel slower in some way so would really appreciate this fix. Watch video to see what I mean.

**Video**
- https://youtu.be/zuz_KEtmvgM
- https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/146269654/5b9ccce3-3ce8-4a96-8f3a-c071e702bd59

**Desktop (please complete the following information):**
Windows, Chrome latest version

**Comment by MaKun01** [comment]
Close the thread if fixed.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/105678775/3c4dbeb6-5691-4c6a-8fa2-e7c307f0592d)
