### ISSUE TITLE
Youtube released their new "disable after 3 videos" thing for ad blockers.

### ISSUE THREAD

**Issue by spenkluker645** [TheRealJoelmatic/RemoveAdblockThing#38]
![blockthis](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/114310071/f1a946a3-d51f-4866-abfc-b09f2647d31d)

**Comment by surz-p** [comment]
try disabling your existing ad blockers first. should work after a refresh

**Comment by spenkluker645** [comment]
All it does is just remove the text, and leave a black screen on the video.

**Comment by spenkluker645** [comment]
By the way, if you log out of your google account on Youtube, it wont even display the ad blocker warnings.

**Comment by PatientXero** [comment]
The JS addon works. Just disable your adblocker for YouTube. The JS addon will skip through the ads in the YouTube videos.

**Comment by Lazarica-t** [comment]
> try disabling your existing ad blockers first. should work after a refresh

Can confirm it work if you disable other adblocker.

**Comment by austincap** [comment]
Fuck youtube, the ads make the site unusable and Google doesn't need both the advertiser money AND subscription money from us. Pic related.

![banksyishero](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/3488809/41111a8a-31e2-446c-ad8c-a6705a30e042)

**Comment by TheSnoozer** [comment]
Try the following:
Uninstall all ad blockers, remove cookies for youtube, remove cookies for google. restart browser. Install adblocker extension. Try youtube again.

**Comment by MarioMastr** [comment]
can confirm that works

**Comment by VertofChest** [comment]
Whoa whoa sega
Whoa whoa mega
