### ISSUE TITLE
Save to playlist, watch later, etc 3 dots link & notifications not working in Firefox

### ISSUE THREAD

**Issue by Furious-G** [TheRealJoelmatic/RemoveAdblockThing#382]
**Script version**
3.9

**Describe the bug**
The three dots link for save to watch later, etc no longer works. Same with the notifications icon at the top

**Expected behavior**

**Screenshots**
attached

**Desktop (please complete the following information):**
Firefox 122.0.1
Windows 11
![FireShot Webpage Capture 152 - 'YouTube' - www youtube com](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/33108237/fe3e2f11-120d-4e1b-be3b-452783a66c55)

**Comment by ChrisAE123** [comment]
I'm on Chrome Windows 10 and this happens to me too.

**Comment by BeefBaby** [comment]
Having the same issue.
