### ISSUE TITLE
the grey spot is back

### ISSUE THREAD

**Issue by AuZ-ASD** [TheRealJoelmatic/RemoveAdblockThing#385]
**Script version**
3.9

**Describe the bug**
the grey spot is back         
[Entarra](https://github.com/Entarra)  called it: "drop-shadow part of the AdCenter"

**Expected behavior**
no grey dot

**Screenshots**
same as in #369

**Desktop (please complete the following information):**
 - OS: win11
 - Browser firefox
 - Version 115.7.0esr

**Additional context**

**Comment by Entarra** [comment]
Yeah turns out my fix wasn't quite good enough, I have another pending that should actually fix it.
