### ISSUE TITLE
Youtube started block the script! Fix pls

### ISSUE THREAD

**Issue by Polydick** [TheRealJoelmatic/RemoveAdblockThing#386]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Fivel22** [comment]
// ==UserScript==
// @name         Refresh YouTube Page After Loading
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  Refreshes the YouTube page 2 seconds after it's fully loaded
// @author       Your Name
// @match        https://www.youtube.com/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // Function to refresh the page
    function refreshPage() {
        location.reload();
    }

    // Wait for the page to fully load
    window.addEventListener('load', function() {
        // Refresh the page 2 seconds after it's fully loaded
        setTimeout(refreshPage, 2000);
    });
})();

**Comment by Fivel22** [comment]
This script solved the problem, just install it manually in Tapermonkey

**Comment by Fivel22** [comment]
Install the Tampermonkey extension for your browser.
    Click on the Tampermonkey icon and choose "Create a new script."
    Delete any existing code in the editor and paste the above script.
    Save the script by pressing Ctrl + S or Cmd + S.
    Refresh the YouTube page, and the script will automatically refresh the page 2 seconds after the video starts playing.

**Comment by Polydick** [comment]
> ==UserScript== // Обновить страницу YouTube после загрузки // http://tampermonkey.net/ // 0.1 // Обновляет страницу YouTube через 2 секунды после ее полной загрузки // Ваше имя // https://www.youtube.com/* // нет // ==/ UserScript==
> 
> (function() { 'использовать строгий';
> 
> ```
> // Function to refresh the page
> function refreshPage() {
>     location.reload();
> }
> 
> // Wait for the page to fully load
> window.addEventListener('load', function() {
>     // Refresh the page 2 seconds after it's fully loaded
>     setTimeout(refreshPage, 2000);
> });
> ```
> 
> })();

version      4.0
youtube shows the same warning if i use ublock
notebook pc
windows 10
microsoft edge

**Comment by Polydick** [comment]
> ```
> Install the Tampermonkey extension for your browser.
> Click on the Tampermonkey icon and choose "Create a new script."
> Delete any existing code in the editor and paste the above script.
> Save the script by pressing Ctrl + S or Cmd + S.
> Refresh the YouTube page, and the script will automatically refresh the page 2 seconds after the video starts playing.
> ```

I deleted previous script and put yours. Youtube padge just constantly refreshing and paying new video
