### ISSUE TITLE
Both YouTube static ads and the TOS violation warning have started showing up again

### ISSUE THREAD

**Issue by GroggyOtter** [TheRealJoelmatic/RemoveAdblockThing#392]
Updated: Including that "Ad blockers violate YouTube's Terms of Service" is now showing up again as well as static ad images during start/playback of videos.  

***

**Script version**
v4.0

**Describe the bug**
Updated Chrome to:  122.0.6261.112 (Official Build) (64-bit)
Ads are now showing up during videos.  
The ads aren't the actual videos but a static advertisement that stays up for 5-10 seconds.  
It can happen multiple times during a video.

Less than a day later, the "Ad blockers violate YouTube's TOS" message has started coming up. This message stays up while autoplay continues through a list of videos.  
A refresh of the browser seems to fix things temporarily.

**Expected behavior**
The expectation is ads not interrupting playback and definitely to not see the "TOS" message.  
That's the whole reason we flocked to this amazing script!  

(And an obligatory thanks should be made here b/c without Joel and the other awesome people who help out with this project, we'd be forced to deal with YouTube vids that are 30-50% longer due to ad injections! You guys are the real MVPs.)

**Screenshots**
Example of ads showing up:
![screenshot of ad](https://i.imgur.com/1v7umSa.png)

And the TOS screen:  
![screenshot of TOS](https://i.imgur.com/m09aexb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 122.0.6261.112

**Comment by GroggyOtter** [comment]
![Awkward Silence](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/55dd6a82-fdd8-4cf1-a6cb-432a4964b90f)

**Comment by GroggyOtter** [comment]
Posted 2 weeks ago.  
Still happening...

Updated Chrome today, went to YouTube to play a random song.  
Got 2 static ads in a row before the song would play.

![chrome_p8qDNVgvLh](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/9a3bed7a-7f49-4126-94ba-67e61791b7e8)

![chrome_6cUHJQ0Tml](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/24c6d2c1-d96a-4e7d-81c8-c55bc2071b84)

And when going to the next video, this shows up:

![chrome_QLOLuAtuwt](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/29220773/668dbc0b-c92a-45b8-a77b-741713f0a780)

Help us out, Joel!

¯\\\_(ツ)\_\/¯

**Comment by MartinBraquet** [comment]
Which OS are you using? I got the issue on `Ubuntu 22.04.4, 5.15.0-56-generic GNU/Linux`

**Comment by GroggyOtter** [comment]
Not sure what version it was when I posted this but currently I'm running Windows 10 build 19045.4046

The problem doesn't seem to persist anymore, but it has gone away and come back a few times now.

**Comment by GroggyOtter** [comment]
As a general update, this problem doesn't seem to persist anymore.
It happened a few times after updating Chrome, but I haven't seen a static ad in ~2+ weeks.  
Going to close this for now as I can no longer reproduce the problem.
