### ISSUE TITLE
Remove AdBlock Thing doesn't work anymore

### ISSUE THREAD

**Issue by Badassious** [TheRealJoelmatic/RemoveAdblockThing#395]
Please, update the code. Youtube Adblock restrictions have returned

**Comment by paradoxical95** [comment]
Same. Came here to create the same issue.

**Comment by drweb86** [comment]
Can you please update your wonderful plugin. 
Without it its impossible to watch YT because of poor AD politic of google.
And since today YT devs detect your staff.

**Comment by Lilykoi** [comment]
It was so good till it lasted.  Please update this! <3

**Comment by mcmanaman8** [comment]
Version 2.9 still works fine

**Comment by Lilykoi** [comment]
So why don't you update it to an earlier version?

**Comment by Pooland1** [comment]
For me it still works I think...

**Comment by mcmanaman8** [comment]
> So why don't you update it to an earlier version?

I do use 2.9 with no problems. Give it a try, might work for you.

**Comment by Badassious** [comment]
mcmanaman8, Pooland1, Lilykoi. I started this thread wihtout the need to reverse to older updates, I respect TheRealJoelmatic's work and effort and if they need time to update the plugin, then so be it. There are people who needs this yet I don't have to push the developer to make it better neither should you guys push and the others to older updates.

**Comment by mcmanaman8** [comment]
It does zero harm to let people know that they have an option to try 2.9 if there is no other functional update. And if it works for them, good was done. We're not here telling you not to make the thread.

**Comment by Badassious** [comment]
> I'm currently on 4.0 with only 1 ad sneaking through that could be skipped by reloading. It's the one posted on the code page instead of the releases page

Most ads do get to be skipped with the refresh old trick yet there are videos that don't start and enforce the youtube rules text. I've noticed that on Greek videos since my local region is different. But the point is to avoid all complecated methods like vpn, that criples my wifi, and simply have a plugin to stop all demanting ads

**Comment by protectedprofile** [comment]
If I add a comment, then try to edit it, the anti-adblocker returns.

**Comment by ralinchan** [comment]
> If I add a comment, then try to edit it, the anti-adblocker returns.

Just added a comment then edited it. No issue.

**Comment by hatter1888** [comment]
it stopped working today for me after i updated firefox.

**Comment by drweb86** [comment]
It works for me too.

**Comment by useremail4339** [comment]
Show warning please update script.........Please.....................
► YouTube
Ad blockers violate YouTube's Terms of Service
It looks like you may be using an ad blocker. Video playback is blocked unless YouTube is allowlisted or the ad blocker is disabled.
• Ads allow YouTube to be used by billions worldwide.
• You can go ad-free with YouTube Premium, and creators can still get paid from your subscription.
Allow YouTube Ads
![image_2024-05-29_103649314](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/114663811/42fae4a8-22ff-4944-be86-1ce3343e6c0e)

**Comment by ralinchan** [comment]
@useremail4339 Unless they are rolling out this update on youtube slowly, so far the script still functions for me without issue

**Comment by Badassious** [comment]
΅Well, it works yet shorts are still forcing ads as videos. Skippable yet still repetitive

**Comment by ralinchan** [comment]
> ΅Well, it works yet shorts are still forcing ads as videos. Skippable yet still repetitive

Have never had this issue at all.

**Comment by useremail4339** [comment]
Yesterday, script wasn't working even after restarting both the script and the browser. However, today it is working perfectly. Thanks for Replay.

**Comment by Badassious** [comment]
Nah, there's an unbareable loop of stopping and trying to start any video.

**Comment by Badassious** [comment]
Thanks for the new update, Joel Matic. It works but our modder fighting Youtube everytime.
Like Hercules cutting one Hydra head then two pop out.

**Comment by Badassious** [comment]
Celebrated too early. Enforced loop is back even after the recent update

**Comment by Badassious** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156509102/abc72e88-66ad-4ecf-899a-fc191f76860a
