### ISSUE TITLE
Dark spot still in middle of screen after an Ad is skipped

### ISSUE THREAD

**Issue by JohnHargis** [TheRealJoelmatic/RemoveAdblockThing#396]
**Script version**
4.0

**Describe the bug**
After an ad is skipped there is a small dark spot in the middle of the video / window

**Expected behavior**
No dark spot

**Screenshots**
Same as #369 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Opera GX
 - Version 107.0.5045.86
 - Chromium version: 121.0.6167.186

**Additional context**
Refreshing the page gets rid of it but its really annoying to do multiple times per video.

**Comment by andrew-jolley** [comment]
+1 same issue

**Comment by AuZ-ASD** [comment]
+1 same issue
