### ISSUE TITLE
make a new script with this

### ISSUE THREAD

**Issue by kkroww** [TheRealJoelmatic/RemoveAdblockThing#3969]
[Skip Youtube Ads-2024-06-11.user.txt](https://github.com/user-attachments/files/15966598/Skip.Youtube.Ads-2024-06-11.user.txt)

**Comment by kkroww** [comment]
make a new script -> paste it

**Comment by WarpigtheKiller** [comment]
worked rly good.

**Comment by AnmolSecSavvy** [comment]
not working now....any update for this?
