### ISSUE TITLE
Reply function in YouTube comments not working

### ISSUE THREAD

**Issue by pllop330792** [TheRealJoelmatic/RemoveAdblockThing#399]
**Script version**
4.0

**Describe the bug**
The ad-blocking function is working successfully, however, there is a problem when trying to reply to YouTube comments.

**Expected behavior**
Normally, when you click the ‘Reply’ button to respond to a comment, a window should appear for you to write your reply, there is no response when clicking the ‘Reply’ button.

**Screenshots**
![Honeycam 2024-04-16 13-29-43](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/110679278/eb856574-ae91-433c-b170-8704a7c95970)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**

**Comment by ralinchan** [comment]
Testing this with both a Chromium (Edge) and non Chromium (Firefox) browser shows that Reply button still functions as expected.

**Comment by ralinchan** [comment]
If it happens with specific videos only, then it would probably be a more meaningful bug report to post a link to such a video.

**Comment by pllop330792** [comment]
Solved, I don't know which extension it was, but I reinstalled Chrome and removed all extensions except TemperMonkey and it works again.

Before I deleted all extensions, it worked fine when I removed just the script, so it's possible that it was conflicting with some extension.

Sorry for the confusion ;)
