### ISSUE TITLE
Script Disables Other Normal Features?

### ISSUE THREAD

**Issue by cyli1288** [TheRealJoelmatic/RemoveAdblockThing#4]
Installing this script on Greasemonkey results in the disabling of the dotted menu next to Youtube video titles that typically lets me save them to Queue or Watch Later. It also prevents me from viewing new responses to my comments.

**Comment by minePFcraft** [comment]
Try use Tampermonkey instead of Greasemonkey

**Comment by Mr-Turcotte** [comment]
Tampermonkey is not working either

**Comment by TheRealJoelmatic** [comment]
Try out the latest version. Hopefully, it should be fixed for most popups.
