### ISSUE TITLE
Theater mode no longer work

### ISSUE THREAD

**Issue by EV1T** [TheRealJoelmatic/RemoveAdblockThing#4001]
Theater mode no longer work, or att least the button is no longer present in the media-bar

**Comment by Euqoram** [comment]
the newer versions use the youtube embedded video player, you can downgrade to [5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js) (click the Raw button on upper right) and that version is mostly functional. it sometimes gets detected on prerolls, but you can refresh past it till it's fixed, at least
