### ISSUE TITLE
Unable to watch playlists

### ISSUE THREAD

**Issue by RR-glitch** [TheRealJoelmatic/RemoveAdblockThing#4002]
Browser: Edge

Everything seems to work fine, the only thing that's kinda annoying is that I can't watch playlists. The video stops and the next one just doesn't play.

**Comment by Euqoram** [comment]
the newer versions use the youtube embedded video player, you can downgrade to [5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js) (click the Raw button on upper right) and that version is mostly functional. it sometimes gets detected on prerolls, but you can refresh past it.

**Comment by RR-glitch** [comment]
Looks like it worked! Thank you!!
