### ISSUE TITLE
videos keep skipping itself trying to skip the ad

### ISSUE THREAD

**Issue by Pathetacy** [TheRealJoelmatic/RemoveAdblockThing#401]
**Script version**
4.0

**Describe the bug**
recently, videos in a playlist (both made by someone or youtube bots) will skip when loading an advert. this causes the next video to play which always has an advert at the start of that too. which then skips to the next one and repeat.

**Expected behavior**
the advert will show at very fast, sort of noticable speeds and the video keeps playing.

**Screenshots**
unable to do so at this time.

**Desktop (please complete the following information):**
Windows 10
Opera GX

**Additional context**
when a playlist initially starts, it works fine. but as soon as an ad plays, the bug arrives completely killing the playlist, skipping through every single video on there until the playlist runs out.

**Comment by OdisBy** [comment]
Same here

**Comment by fafarazi** [comment]
same
