### ISSUE TITLE
Certain Type of Ad can still appear

### ISSUE THREAD

**Issue by CrazyMew37** [TheRealJoelmatic/RemoveAdblockThing#402]
**Script version**
4.0

**Describe the bug**
There is a certain type of ad that appears to the right of the video player that seems to get deleted but it comes back a split second later. The specific type of ad it is is presented in the screenshot below.

**Expected behavior**
The Ad should disappear without coming back.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/64723948/49544078-a07c-4bc9-b7d3-764aa74773dc)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Floorp (Fork of Firefox)
 - Version: 11.11.2 (Floorp), 23H2 (Windows 11)

**Additional Information**
I believe I've been blocked from the Video Player, so the script will use the undetectable ad-skipping method instead of the one that it normally uses.

**Comment by saiakesani** [comment]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/81065354/e402d5e4-b886-4a3b-817b-e3a0df61d383)
iv been getting this type recently it seems to be timed and usually 1-2 back to back

**Comment by photosense** [comment]
@saiakesani Yup I get those to randomly, about half the time.

Did you find a solution?

**Comment by marceloavf** [comment]
Ads are blocking the video execution more frequently now
