### ISSUE TITLE
so adblock only works if im signed out of my account for some reason

### ISSUE THREAD

**Issue by hatter1888** [TheRealJoelmatic/RemoveAdblockThing#403]
**Script version**
4.0
**Describe the bug**
that "disable adblocker or pay" warning preventing a video from playing pops up on every video if im signed in, but if im not the script seems to function normally. not sure what the issue is. i did recently change my account name, and i did recently update firefox. 

**Expected behavior**
i expected the video to play normally, and not have the video blocked by youtube. 
![Screenshot 2024-04-27 at 19-00-11 A fully destructible BACKROOMS game where the monsters HIDE from YOU  - YouTube](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/13174732/c8bba4c7-75a0-4522-8649-e006d74143b1)

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by WoeIsLee** [comment]
Same here, oddly enough, abp works again so idk, disabled origin now just using abp.

**Comment by photosense** [comment]
what is abp? I use origin and badger, it doesn't seem to matter if they are on or off I still get the ad screen.

**Comment by WoeIsLee** [comment]
adblockplus but all you gotta do is go into origin and manually update your filters, and if you dont the ads section turned on, do it.

**Comment by fafarazi** [comment]
> adblockplus but all you gotta do is go into origin and manually update your filters, and if you dont have the ads section turned on, do it.

the first time it works, but the result is the same as this script (skipping the whole video, red dot at the end of the video and loading without stopping)

**Comment by WoeIsLee** [comment]
> > adblockplus but all you gotta do is go into origin and manually update your filters, and if you dont have the ads section turned on, do it.
> 
> the first time it works, but the result is the same as this script (skipping the whole video, red dot at the end of the video and loading without stopping)

Idk man, I literally updated every filter and have all 3 ad section ones turned on and ive been fine since.
