### ISSUE TITLE
Black screen even with all ad blockers stopped etc.

### ISSUE THREAD

**Issue by Arrowbeak** [TheRealJoelmatic/RemoveAdblockThing#404]
*Script version: 4.0
Script version: 4.0

I keep getting a black screen where all other videos and comments load but not the actual video, sometimes i refresh and it occurs but 90% it will remain black. I have no other ad blocker on or anything.

<img width="1629" alt="Screenshot 2024-04-30 at 02 52 24" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/168499576/3b3d0a22-04e9-4eeb-88fb-09c73952abb8">

**Desktop  info:
 - OS: ios Ventura 13.0.1
 - Browser: Chrome
 - Version: 124.0.6367.93

**Comment by eikhermann** [comment]
I have a similar problem. Everything else loads, video does not load.
Script version: 4.0
OS: IOS Sonoma 14.1.1
Browser: Chrome
Version: 124.0.6367.201 

<img width="1255" alt="youtube-adblockthing" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/142531885/6a406131-dea9-4014-a817-caa521e8e961">

**Comment by EdwardReynolds69** [comment]
- Script version: 4.0

- Browser: Chrome 
- Version: 124.0.6367.209

- OS: Windows10 Pro
- Version: 19045.4412

Workaround: Refresh the tab. Eventually YT gives up after 3-4 goes and the vid starts.

Screenshop nabbed from eikhermann's post above, I see progress text on the left hand side and plays soon text on the right hand just like this and the page hangs here as a nice eternal black void.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/170081930/7fd94c0a-8344-4789-a61b-facd41027694)

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
