### ISSUE TITLE
Main Video plays fast after ad is skipped

### ISSUE THREAD

**Issue by 5Sp4rk** [TheRealJoelmatic/RemoveAdblockThing#406]
Video evidence
https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/170201617/8155c2a6-e224-4ab8-9ffb-83bb4dec04a2

help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 10

**Comment by Vanitazazas** [comment]
I had the same issue just now and I found out it's due to the latest Chrome update so that adblock seemed to be switched on for youtube which causes Remove adblack thing script to crash. Check that your adblack for youtube is turned off and it should be fine.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
