### ISSUE TITLE
Youtube "Adblock not supported" back, won't go away until multiple refreshes

### ISSUE THREAD

**Issue by madstheaquarius** [TheRealJoelmatic/RemoveAdblockThing#408]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

Youtube "Adblock not supported" back, won't go away until multiple refreshes

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)

**Comment by madstheaquarius** [comment]
Sorry, newer to github so wasn't sure about open issues only letting ya know lol. Now the adblock violation error has only showed up once but now ads show speeding through them & have to be skipped .-.
