### ISSUE TITLE
not working anymore see screenshot attached

### ISSUE THREAD

**Issue by chandravamshi** [TheRealJoelmatic/RemoveAdblockThing#409]
<img width="1031" alt="Screenshot 2024-05-31 at 7 29 23 AM" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26179207/96d26ac9-7e24-4701-8dce-d72878047477">

**Comment by LeventHAN** [comment]
Can confirm that if you keep refreshing (F5) the page it works. (For me; Refreshed twice and it was gone)

**Comment by MrL0G1C** [comment]
I'm getting the same message as that pictured above.

Simply refreshing the page is a bad idea as this will likely just hasten complete block of being able to view videos.

Please update asap

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)

**Comment by MrL0G1C** [comment]
Fix has worked for me, thanks. I can't stand ads, they're a perverse psychological assault in my book. I just cancelled Netflix for saying they would move me over to adverts or I have to pay 57% more than when I joined, no thanks.

**Comment by slzero-X** [comment]
@MrL0G1C 

Check any of these things here in the Readme:

Adblock extension: Disable or whitelist YouTube on your ad blocker extension.

Browser built-in adblock: Some browsers have built-in ad blockers. Disable or configure them.

Other Tampermonkey scripts: Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

Wi-Fi/DNS/Firewall adblock rules: Check network settings for any ad-blocking configurations.

Windows hosts file rules: Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.

**Comment by MrL0G1C** [comment]
1. ~~ Adblock extension: Disable or whitelist YouTube on your ad blocker extension. ~~
2. Browser built-in adblock: Some browsers have built-in ad blockers. Disable or configure them.
3. ~~Other Tampermonkey scripts: Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.~~
4. ~~ Wi-Fi/DNS/Firewall adblock rules: Check network settings for any ad-blocking configurations.~~
5. ~~Windows hosts file rules: Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.~~

All others were ok, the Slimjet built in adblock was detected even though www.youtube.com and the entire youtube'com domain were whitelisted. So basically you'll get the warning even if you whitelist youtube.com - the detection must be via some other domain.

I'll have to make a browser profile just for Youtube, easy enough.

**Comment by MrL0G1C** [comment]
Bah, Youtube are working hard on it today, warning popped up again.

**Comment by chandravamshi** [comment]
Actaully it worked after you updated the script 2 days ago. but now  again it is appering as it is in screenshot. refereshing two times works but to do it for every video we watch is kind of uncomfortable. just saying no hate or angry. (my engilsh is not good i do not know how to put it in other words)
