### ISSUE TITLE
Playlayout Remove Problem 

### ISSUE THREAD

**Issue by woxxin14** [TheRealJoelmatic/RemoveAdblockThing#4106]
let playerControlContainer = document.querySelector('div[playable="true"][id="player-control-container"]');
            if (playerControlContainer) {
                playerControlContainer.remove();
            }

Add this code  your Script

**Comment by woxxin14** [comment]
Play layout Remove Problem Solve

**Comment by H3X3R** [comment]
Add it to which line? Tell line number wrt to the original 5.6 script lines of code.
