### ISSUE TITLE
Youtube video page keeps reloading

### ISSUE THREAD

**Issue by SirThinksAl0t** [TheRealJoelmatic/RemoveAdblockThing#411]
**Script version**
5.0 - Updated today

**Describe the bug**
Youtube video page keeps reloading, example:
Video page opens, ads skipped, youtube warning blocks the screen, page reloads, repeats progress.

**Expected behavior**
Video plays normally

**Screenshots**
![Screenshot 2024-05-31 140105](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/39535458/6bfeb769-3e0e-4f91-8874-5ff3ed47b00a)

**Desktop:**
 - OS: **Windows 10** (Updated today)
 - Browser: **Chrome** (Updated today)
 - Version 125.0.6422.142 (Official Build) (64-bit) (**Updated today**)

**Additional context**
I do not have other extensions or scripts turned on, it's just this one.

**Comment by mtnoet1** [comment]
5.0测试有效果，请尝试清理浏览器缓存重新打开
![屏幕截图 2024-05-31 222210](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156861421/0b2ab9ee-ceeb-4759-9c6a-8fed633a0a1f)
![屏幕截图 2024-05-31 222252](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156861421/b28ae6a0-b8bd-4195-9a62-53188a471518)

**Comment by SirThinksAl0t** [comment]
Nevermind, it was a **conflict of the script with Malwarebytes blocking ads & trackers**.
Disabled Malwarebytes for Youtube. Working normally so far.
