### ISSUE TITLE
youtube says "ad block..."

### ISSUE THREAD

**Issue by pedram-asadipour** [TheRealJoelmatic/RemoveAdblockThing#412]
I Have v5 but some time youtube says "ad block.."

**Comment by housebba** [comment]
me too.

**Comment by dequeueing** [comment]
same issue here

**Comment by Toru45** [comment]
same issue

**Comment by Cinnax** [comment]
I just started getting this issue today. Refreshing the page 3 -5 times will work, but obviously Youtube is starting to detect this script and it will soon be obsolete.

**Comment by Kawwaka** [comment]
no guys, the ytb is detecting others adblocks (opera and extentions even if not activated), still works fine after the update

**Comment by SyndiShanX** [comment]
They definitely found a way to detect this and started blocking it

**Comment by muhdkhokhar** [comment]
works fine after update folks

**Comment by h3lpm3pl3ase** [comment]
It's still not working

**Comment by slzero-X** [comment]
Algorithmic detection is what they added now, if it detects any form of advertisement interference without paying them, no matter what extension it is, it will retaliate.
This war will never end.

**Comment by neo79747** [comment]
> Algorithmic detection is what they added now, if it detects any form of advertisement interference without paying them, no matter what extension it is, it will retaliate. This war will never end.

so we lost? or we have to wait for another update? cause it works but we have to reload the site and wait like 2 mins before the video starts unless they do something again......

**Comment by supersmith2500** [comment]
> > Algorithmic detection is what they added now, if it detects any form of advertisement interference without paying them, no matter what extension it is, it will retaliate. This war will never end.
> 
> so we lost? or we have to wait for another update? cause it works but we have to reload the site and wait like 2 mins before the video starts unless they do something again......

Not quite. It still works most of the time.

**Comment by Ryuu0812** [comment]
So we need new script huh? Bro, yt make our day so hard with their annoying ads...

**Comment by supersmith2500** [comment]
> So we need new script huh? Bro, yt make our day so hard with their annoying ads...

More like stressful and furstrating. I almost went to the hospital because of my self-harm disorder and they made it worse for me.

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)

**Comment by fretry1** [comment]
The script is not working anymore as of a few days ago, and the problem persists.
