### ISSUE TITLE
Youtube AdBlock popup still occurs even when script is enabled.

### ISSUE THREAD

**Issue by zman29er** [TheRealJoelmatic/RemoveAdblockThing#413]
**Script version**
v 5.0 (current latest at the time of writing)

**Describe the bug**
AdBlock popup still occurs even when Remove AdBlock Thing script is enabled, even with newest method

**Expected behavior**
AdBlock popup should not occur at all, yet it still occurs.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171362424/f9fa312b-3ac2-4008-bac2-cbd33df7a177)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Opera GX (Chromium)
 - Version: Windows 11

**Additional context**
N/A

**Comment by slzero-X** [comment]
It has been cracked down on, Google has found out about this script and has blacklisted it.
Even if Joel tries to update it to fix the thing, it will get detected regardless, he ain't gonna get this resolved any time soon.

I am considering getting my parents to pay for YouTube Premium, and if you guys get mad that I am paying for a scumbag company, I got no choice, I don't want YouTube to use their totalitarian powers to cease my rights of being able to use their service.

Companies are far more powerful than they actually appear to be.

**Comment by supersmith2500** [comment]
> It has been cracked down on, Google has found out about this script and has blacklisted it. Even if Joel tries to update it to fix the thing, it will get detected regardless, he ain't gonna get this resolved any time soon.
> 
> I am considering getting my parents to pay for YouTube Premium, and if you guys get mad that I am paying for a scumbag company, I got no choice, I don't want YouTube to use their totalitarian powers to cease my rights of being able to use their service.
> 
> Companies are far more powerful than they actually appear to be.

It still works most of the time. I just need to refresh the page in order for it to work. If the script does render unworkable. Then we all know were screwed. I'm sure Joel will find a way to fix it.

**Comment by VerzatileDev** [comment]
At this point youtube will just add the ads into the video itself instead of pop up type of ads. Though currenntly the script seems to work if the regular adblock is enabled as well.

**Comment by slzero-X** [comment]
This time its not just a small portion here, its the enormous vast majority, and of course, Joel thinks it's working as it should as he has never responded to anything here.

Not ONLY that, the responses he made were suspiciously superfast like he's some corporate-created AI entity, autonomously responding to things that start a complaint storm and never responding to matters again.

He might be figuring this out in the background while all the complaints come flooding in knowing that YouTube's on his tail.

**Comment by supersmith2500** [comment]
> This time its not just a small portion here, its the enormous vast majority, and of course, Joel thinks it's working as it should as he has never responded to anything here.
> 
> Not ONLY that, the responses he made were suspiciously superfast like he's some corporate-created AI entity, autonomously responding to things that start a complaint storm and never responding to matters again.
> 
> He might be figuring this out in the background while all the complaints come flooding in knowing that YouTube's on his tail.

Won't be long until Manifest V3 breaks this script.

**Comment by TheRealJoelmatic** [comment]
> It has been cracked down on, Google has found out about this script and has blacklisted it. Even if Joel tries to update it to fix the thing, it will get detected regardless, he ain't gonna get this resolved any time soon.
> 
> I am considering getting my parents to pay for YouTube Premium, and if you guys get mad that I am paying for a scumbag company, I got no choice, I don't want YouTube to use their totalitarian powers to cease my rights of being able to use their service.
> 
> Companies are far more powerful than they actually appear to be.

First of all there is no such thing as a tampermoney script blacklist idk were u got this info from.

> This time its not just a small portion here, its the enormous vast majority, and of course, Joel thinks it's working as it should as he has never responded to anything here.
I have a life to attend to I cant spend all day answering questions on github but I try when I can.

> 
> Not ONLY that, the responses he made were suspiciously superfast like he's some corporate-created AI entity, autonomously responding to things that start a complaint storm and never responding to matters again.

Yep Im a AI 🤣


> He might be figuring this out in the background while all the complaints come flooding in knowing that YouTube's on his tail.
Yea ofc I do when I have time as I use youtube on the daily and refuse to watch any kind of ads at all.

**Comment by TheRealJoelmatic** [comment]
@slzero-X

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.1

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)
