### ISSUE TITLE
NOT AN ISSUE - Thanks note

### ISSUE THREAD

**Issue by muhdkhokhar** [TheRealJoelmatic/RemoveAdblockThing#414]
I just wanted to say thanks so much for this script
Youtube Ads have got worst day by day and they keep blocking your plugin
You come up with a fix so quick
THANKS

**Comment by TheRealJoelmatic** [comment]
Thanks your support is approached :)

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
