### ISSUE TITLE
When I play the video, it just blacks out or gives me an error and I have to refresh.

### ISSUE THREAD

**Issue by Maverick0926** [TheRealJoelmatic/RemoveAdblockThing#415]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

-latest

**Describe the bug**

-When I play the video, it just blacks out or gives me an error and I have to refresh.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.
-
![yt](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/130076365/6994fcdb-7128-43ba-9ee0-cdfcb2530049)

**Desktop (please complete the following information):**
-i`m using window 10 pc

**Additional context**

**Comment by slzero-X** [comment]
The script has been cracked open by YouTube, majority are getting the popup with the script, even by itself.

There are some, however, who are so mega-overkill with their adblock scripts that I am stunned their PC is even able to handle the sheer amount of code that's being blasted at YouTube's anti-adblock.

However, this complaint is far too vague so I don't know anything else other than what you just provided.

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.0

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)
