### ISSUE TITLE
Adblock detected on Tampermonkey Adblock YT

### ISSUE THREAD

**Issue by Ryuu0812** [TheRealJoelmatic/RemoveAdblockThing#416]
**Script version**
Tampermonkey 5.0 Script

**Describe the bug**
There is still adblocker violate yt blablabla

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version : The lasted Update (5.0 Scripts)
 
 Can someone find any solutions?

**Comment by xmanolis** [comment]
I have this issue also.

**Comment by arhum-shaikh1** [comment]
Same. I just checked and I got the AdBlock detected issue.

**Comment by emresaizou** [comment]
Terrible update.

**Comment by Dogeyboy** [comment]
I just had this issue while having the script as well, wtf.

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.1

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/407)

**Comment by slzero-X** [comment]
It still gets detected.
