### ISSUE TITLE
Adblock detected on 5.1

### ISSUE THREAD

**Issue by L0rd-Cryptid** [TheRealJoelmatic/RemoveAdblockThing#418]
**Script version**
5.1

**Screenshots**
![adblock detect](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/170839533/ff5d26c6-b23e-46f0-ad7b-d6be156bf315)

**Describe the bug**
they're at it again with the adblocker detection

**Desktop:**
 - OS: windows 11
 - Browser: Firefox
 - Version: 126.0.1

**Additional context**
I'm gonna put whoever the moron is at youtube that thought trying to crack down on adblock was a good idea thru a paintshaker, this is truly ridiculous

**Comment by slzero-X** [comment]
They have implemented algorithmic detection.
ANY form of advert interference will trigger the script.
Its no longer extension or script based, it is now through an algorithm.

It works like this: (Pseudocode)

AntiAdblockSystem::CheckAdStatus 
{
    Local Var IsAdblockPresent := False
    If (Ad.Playbackspeed !=1)
    {
       IsAdblockPresent := True
    }
    If (Ad.Volume.IsUserSettingInput = False && Ad.Volume.Scale != User.PreviousVideoVolume)
    {
       IsAdblockPresent := True
    }
    Local Var TimerOnLoad = Sys.GetSessionTime()
    Local Var StartPoint = Player.GetCurrentPlaybackTime()
    If (StartPoint  != TimerOnLoad)
    {
       IsAdblockPresent := True
    }
    If (IsAdblockPresent = True) { KillVideoPlayer() }
}

**Comment by L0rd-Cryptid** [comment]
> They have implemented algorithmic detection. ANY form of advert interference will trigger the script. Its no longer extension or script based, it is now through an algorithm.

oh nooooo, I hope that doesn't mean this adblock is useless now, I think there would be riots if it were

**Comment by slzero-X** [comment]
From the looks of it, it absolutely is now.

So long story short: IsOurAdBeingPlayedWith = True > TheyHaveAdBlock!

**Comment by MBurneracc** [comment]
I had the same issue with still getting the message even after installing the 5.0 version.  Decided to screw around and also turned ublock back on for youtube and not getting it any more.  Not sure if it's just dumb luck , ublock just working or the two together but it's worth a try if you're having trouble. Been clicking around through random videos and still hasn't popped back up yet unless it's going to suddenly appear on me again.

**Comment by zowyx** [comment]
> From the looks of it, it absolutely is now.
> 
> So long story short: IsOurAdBeingPlayedWith = True > TheyHaveAdBlock!
> 
> That would probably explain how people without that stuff still get the popup appearing.

do you know any adblock new to use???

**Comment by slzero-X** [comment]
Nope
Any interference will trigger it @zowyx

**Comment by oomek** [comment]
Is this the end of Youtube ad blocking? The current experience is horrible.
I see popups and/or ads in fast forward.

**Comment by dramr** [comment]
same here. after updating my adblock to 5.1, this morning was fine till RN

**Comment by Dogeyboy** [comment]
this fucking sucks.

**Comment by brianrho** [comment]
Huh. Seeing as they've caught on and there are no ideas yet on working around their detection, maybe it'd be worth returning to the previous ad-skipping speed? Or is there any proof that reducing the speed helps significantly in avoiding detection?

**Comment by slzero-X** [comment]
Its not just that, its algorithmic now, I even plan on manually interfering with the ads without an extension and seeing if it gets triggered.

You can use the debugger within the browser to run your own code, so this can be done to prove if its now algorithmic.

**Comment by MBurneracc** [comment]
stop doomposting in an issues thread.  Unless you're dead set on using nothing but this script there are alternatives in the meantime.  I haven't gotten the message a single time since I turned ublock back on for youtube.  So either ublock works or this + ublock works.

**Comment by slzero-X** [comment]
Fine I will, seriously.
Its like my actions are nothing but fearmongering, and being called little shit.
The internet truly is not at all a welcoming place what-so-ever.
This war will never end, simple as that.

**Comment by brianrho** [comment]
> Its not just that, its algorithmic now, 

To be clear, what I was asking is, if the skipping speed can be restored as it used to be, since slowing it down seems to have no effect on their ad detection. (I'll be trying the uBlock combo, except with AdBlock Plus, to see if it helps.)

Also, FWIW, I've noticed the detection mostly (or only?) happens for pre-roll ads -- mid-roll ads skip by just fine, for now at least. Mentioning this in case it helps anyone with ideas.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
