### ISSUE TITLE
Odd behaviour since v5.0 & v5.1 update

### ISSUE THREAD

**Issue by SionFiction** [TheRealJoelmatic/RemoveAdblockThing#419]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
v5.1
**Describe the bug**
1.   On loading a new video, I get the YouTube Adblockers not allowed screen.  Refreshing the page 2-5 times will eventually get the video playing.
2.   Ads interrupt the playing video,  Speeed through Super-Fast [in about 1 sec] & then return to the Video

**Expected behavior**
Before the v5.0 update all was working for me.  v5.0 just stun-locked the YouTube Adblockers message, reloading it again & again.
v5.1 gives me the behaviour listed above, but not ALL the time.  I have restarted Chrome since v5.1.

If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

Windows 11 pro 10.0.22631 build 22631
Chrome 125.0.6422.141 (Official Build)
**Additional context**

Thanks for your great work, I hope you're having a good day!

**Comment by Blodyholy** [comment]
Check out the issue below yours, 418, there is some insight as to why it's not working.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
