### ISSUE TITLE
Does absolutely nothing for me

### ISSUE THREAD

**Issue by Maddieface** [TheRealJoelmatic/RemoveAdblockThing#42]
If I run this with my adblocker off, it just plays ads. If I run it with my adblocker off, it still shows the popup. As far as I can tell the script just isn't doing anything.

**Comment by shimshim938** [comment]
It was working but Youtube has updated code to somehow intentionally or unintentionally bypass the script and block player. 
Script needs rework ..

**Comment by Albedo-13** [comment]
You should run this script with adblocker turned on. Adblocker still able to block video player ads. And this script just blocks "Dont use Adblock" modal window, that is not an ad itself

**Comment by joeyjojojunior** [comment]
In case you're using Youtube enhancement extensions, it might prevent the script from working properly. I was using Enhancer for YouTube and the script only worked intermittently until I turned the extension off.
