### ISSUE TITLE
Youtube adblock at beginning back full swing, only goes away after multiple refreshes

### ISSUE THREAD

**Issue by madstheaquarius** [TheRealJoelmatic/RemoveAdblockThing#421]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
