### ISSUE TITLE
Being detected by Youtube

### ISSUE THREAD

**Issue by Cattlesbusiness** [TheRealJoelmatic/RemoveAdblockThing#422]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by girishb86** [comment]
Same here. The 4.1 update has not helped resolve the issue.

**Comment by jeff39389327** [comment]
new version 5.1

**Comment by yukkeyukka02** [comment]
> 여기도 마찬가지입니다. 5.1 업데이트는 문제 해결에 도움이 되지 않았습니다.

ME TOO

**Comment by neo79747** [comment]
> Same here. The 5.1 update has not helped resolve the issue.

its working for me now yesterday it wasn't, after the update it works for now at least who knows what these money hungry yt idiots will do in the future

**Comment by muhdkhokhar** [comment]
Just keep refreshing page and ad will go away

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
