### ISSUE TITLE
5.1 Version still hasn't resolved the issue either.

### ISSUE THREAD

**Issue by RAZZCATMIN** [TheRealJoelmatic/RemoveAdblockThing#424]
**Script version**
5.1

**Describe the bug**
YouTube is still blocking you from playing YouTube videos because AdBlock has been detected.

 - OS : Windows 11, MacOS Monterey
 - Browser : Chrome

**Comment by slzero-X** [comment]
Its because they have added algorithmic detection, they're really going ham at us now.
Any interference from any source without manual user input will trigger it.
That would easily explain how people are randomly getting the popup out of nowhere without any adblockers.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
