### ISSUE TITLE
Stop complaining, I'll tell you why utube is detecting

### ISSUE THREAD

**Issue by ILLUMN8N** [TheRealJoelmatic/RemoveAdblockThing#425]
Right now this userscript and Youtube are in a bit of an arms race,  Youtube is actively trying to prevent the script from working, you need to give the developer some time to beat them

To the developer: ty bro for trying to help us with the ads you are such a stud, I appreciate you dude/dudette

**Comment by cminglap** [comment]
What do you mean "complaining"? This is a bug reporting page of course we needa tell what's the issues found

Keep it up developer we all have faith in you. Thank you for all the hard work

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
