### ISSUE TITLE
YT bottom-right icons disappeared or changed

### ISSUE THREAD

**Issue by Phil171** [TheRealJoelmatic/RemoveAdblockThing#4254]
**Script version**
Version 5.6

**Describe the bug**
  Hello,
First contribution, sorry if I don't know how to do it or explain... Besides, I'm French, not very comfortable with English sometimes.
When Tampermonkey with Remove Adblock Thing extension works, I have this YT version with these icons, see screenshot 1. I can't see the "cinema" mode icon activated with the "t" key.
If I deactivate the extension and click on "Refresh button" on Firefox, the icons reappear. See screenshot 2
I've uninstalled Firefox, Tampermonkey, the extension, and tried updates without success.

**Expected behavior**

**Screenshots**
1 - https://imgur.com/capture-d-cran-rfLWiQN
2 - https://imgur.com/capture-d-cran-ESXOnzJ

**Desktop (please complete the following information):**
 - OS : Linux Xubuntu 22.04 up to date
 - Browser : Firefox 126.0.1 up to date

**Additional context**

**Comment by AngryAnn** [comment]
I'm also French... with the exact same bug, no previous / next buttons and no " autoplay" or "theater mode" buttons.. 😞 
🏳️

**Comment by Phil171** [comment]
@AngryAnn, Thanks to your tip
