### ISSUE TITLE
Error playing videos

### ISSUE THREAD

**Issue by Sharoos** [TheRealJoelmatic/RemoveAdblockThing#4255]
**Additional context**
"Playback on other websites has been disabled by the video owner
[Watch on YouTube](http://www.youtube.com/watch?v=w0HrVGIaXkQ)"

**Comment by GroggyOtter** [comment]
I don't think this is an addon thing, is it?

**Comment by Lilnora** [comment]
I get that too. And when I turn off this one it goes away.
