### ISSUE TITLE
an Idea from a person who doesn't know how to code but still:

### ISSUE THREAD

**Issue by ILLUMN8N** [TheRealJoelmatic/RemoveAdblockThing#426]
So this idea assumes that userscripts can modify websites

potentially find a way to rather than run the ad really fast, remove the ad system all together, and then remove the detector, anyways ty for reading

**Comment by slzero-X** [comment]
That's not gonna work, because if we kill the anti-adblock script, the site is next to 100% gonna crash or fail to load anything

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
