### ISSUE TITLE
Video Unavailable (Watch on YouTube) error

### ISSUE THREAD

**Issue by nitemare13** [TheRealJoelmatic/RemoveAdblockThing#4263]
**Script version**
Version: Script 5.6 

**Describe the bug**
Saw this error first on the "watch movies free with Ads"
![Screenshot 2024-06-30 214124](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171894739/8c7234d2-cd2c-4c1d-ace4-03a3f0843a4c)

https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171894739/36e480c4-6c0a-4794-87d2-0e3ac121e0b6

 and now I get this error on all videos

**Expected behavior**
Ads are removed and the video begins to play normally, including the free movies 

**Screenshots**
If applicable, add screenshots: Screenshot & Video (sorry for the watermark...)

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 
 - Browser: Chrome, 
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Additional context**

**Comment by namregzepol** [comment]
Same problem here, but in spanish

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/158039/69c1fe49-38ac-46ad-80a6-3797ef2ba809)
