### ISSUE TITLE
https://github.com/NullDev/YT-Anti-Anti-Adblock seem to work

### ISSUE THREAD

**Issue by muhdkhokhar** [TheRealJoelmatic/RemoveAdblockThing#427]
Can you see how that plugin works not yours?

**Comment by Wiese2007** [comment]
tested and still get sometimes the info (but feels less than before) W10 FF126.0.1 Script 5.1 and this one (non others + all addblocks deactivated)

**Comment by pedram-asadipour** [comment]
but sometimes v5.1 not work,after refresh page may be working

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439

**Comment by pedram-asadipour** [comment]
> #439

tank you for new update 🙏
