### ISSUE TITLE
Thank You Joelmatic!

### ISSUE THREAD

**Issue by Pooland1** [TheRealJoelmatic/RemoveAdblockThing#428]
I just want to say: Thank you for this plugin, If this didn't exist, then I would most likely stop using youtube lol
So Thank you so much for helping us fight annoying YouTube Ads!❤️

**Comment by Wiese2007** [comment]
<3

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
