### ISSUE TITLE
Ads still play fast and still have to skip via button 

### ISSUE THREAD

**Issue by supersmith2500** [TheRealJoelmatic/RemoveAdblockThing#430]
**Script version**
5.1

**Describe the bug**
1-2 Ads just stays and plays fast and doesn't skip

**Expected behavior**
It should skip them before going back to video.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 11
 - Chrome
 - Version N/A

**Additional context**
It supposed to skip and then resume to the video.

**Comment by lerokko** [comment]
I have similar issues. I got a six minute add that stuck after 2 minutes. Videos are now skipped slower and with sound. I'd rather black screen my whole computer than having to see those ads. Youtube is sooo 🤏 close to making me pay for Nebula and never using them again.

Regardless of my pissed tone you are doing great work! Thank you

**Comment by Istoleyourfrogs** [comment]
I have the same issue.
Ads play fast instead of getting skipped, also it takes a couple times to refresh the page in order for the script to go through since the Ad-blocker popup shows up..

I have been using your script for months and it has been working perfectly until recently
Thank you for the amazing work!

**Comment by supersmith2500** [comment]
And NOW THIS AWFUL ad-block error is back!

**Comment by arijitcodes** [comment]
I am facing the same issues as well. After the latest update - ads are not being skipped and they are just being played fast!

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
