### ISSUE TITLE
V5.2 still "no adblock allowed"

### ISSUE THREAD

**Issue by JustaGuy1251** [TheRealJoelmatic/RemoveAdblockThing#431]
**Script version**
5.2

**Describe the bug**
Still tells me adblocking isn't allowed

**Expected behavior**
I expected the video to play

**Desktop (please complete the following information):**
Windows 10 (latest)
Chrome (latest)

**Additional context**
F*** youtube, if they'd make premium a lot cheaper and removed the shitty music stuff i'd be willing to pay but they really only give us the choice of either ads (and adblocking) or pay a price most people just can't afford/justify these days.
Hell, perhaps remove the ads before video's but more ads around then, i'd be fine with that as people could still watch videos uninterrupted in that way

**Comment by ralinchan** [comment]
You should probably just switch out of Chrome given they're pushing Manifest V3 next week that blocks ad blocking

**Comment by Lefty-Glasses** [comment]
Im experiencing the same issue on firefox

**Comment by slzero-X** [comment]
Keep trying to bypass it Joel, you won't be winning this any time soon.

**Comment by ralinchan** [comment]
> Keep trying to bypass it Joel, you won't be winning this any time soon.

ublock has bypassed it without an update, you're delusional

**Comment by slzero-X** [comment]
Oh I am deliousonal? I am fucking forced to use Chrome under my parent's authority.
I can't live on my own as I have temper issues that are a serious threat to people.
And you call that shit delusional? Get a fucking grip ya piece of flying horseshit.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
