### ISSUE TITLE
Version 5.2 still with V5.2 still "NoAdblock Allowed" message

### ISSUE THREAD

**Issue by Mendax1989** [TheRealJoelmatic/RemoveAdblockThing#432]
**Script version**
5.2

**Describe the bug**
"NoAdblock Allowed" message

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Latest Version

**Comment by gigadeplex** [comment]
same thing with MacOS using Firefox

**Comment by mag4no10** [comment]
Same with W11 and chrome 125.0.6422.114.
Guess it's the brand new youtube algorithm. 

Good luck and ty for your work !

**Comment by Foomy** [comment]
I have this problem in Firefox, too. Reloading the video page few times resolves the problem temporarily, and one can watch the video. It seem though the reload which works seem not jump over an ad; I mean it after pressing F5 several times YouTube seem not to play an ad anymore and the video comes up directly.

**Comment by Smith873** [comment]
> I have this problem in Firefox, too. Reloading the video page few times resolves the problem temporarily, and one can watch the video. It seem though the reload which works seem not jump over an ad; I mean it after pressing F5 several times YouTube seem not to play an ad anymore and the video comes up directly.

I have the same experience with FireFox v115.11 esr, Win7, script v5.2. 
What worries me is the possibility that YouTube simply allows the video to be played after a refreshing the page a few times. They could just as easily block the video regardless of the number of refreshes.

**Comment by isaac-2408** [comment]
Same issue here with w11 on chrome.

**Comment by fretry1** [comment]
Same issue here with win10 on Edge.

**Comment by geosword** [comment]
I think the thing to remember is that google are probably rolling out this new detection code gradually (A standard SRE practice). I still have two tabs open where ads are skipped, but this could be because Im hitting endpoints which don't have the new detection code deployed to them yet. Either way, excellent work @TheRealJoelmatic we all appreciate your efforts!

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
