### ISSUE TITLE
"NoAdblock Allowed" message shows up when there is an ad prior to video

### ISSUE THREAD

**Issue by punctdan** [TheRealJoelmatic/RemoveAdblockThing#433]
**Script version**
5.2

**Describe the bug**
Ads that appear before the video starts always cause "NoAdblock Allowed" message to show up. You can only bypass it by refreshing the page as much as you need to.

**Expected behavior**
There should be no ad in the view and the video should start without any interference.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera One
 - Version: 110.0.5130.49

**Comment by Pooland1** [comment]
Tbh, I don't mind this bug, because you only have to refresh a few times.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
