### ISSUE TITLE
black screen, audio only

### ISSUE THREAD

**Issue by mamnnn** [TheRealJoelmatic/RemoveAdblockThing#4337]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

when I go to play a video, it starts ok, then screen turns black, & only get audio

**Comment by Mikf12** [comment]
Same here

**Comment by alwinraju** [comment]
Getting the same problem. Can hear the audio of the video playing in the background but cannot see any elements of the video or player. Cannot interact with any elements either if you click on where you would normally find it. I am using version 5.6 of the script. 


OS: MacOS Sonoma 14.5
Browser: Safari Version 17.5 (19618.2.12.11.6)

![Screenshot 09-07-2024 at 03_40_31PM](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/34244581/af841151-08fa-4019-b720-82189584085c)

**Comment by alwinraju** [comment]
Appears to work again if you sign out of YouTube

**Comment by jesvijonathan** [comment]
Fixed in this Pull Request #4756
