### ISSUE TITLE
V5.2 is not skipping ads on youtube 

### ISSUE THREAD

**Issue by amaanmajeed** [TheRealJoelmatic/RemoveAdblockThing#434]
**Script version**
V5.2

**Describe the bug**
it starts the video at where the skip button is visible, but it does not skip the video automatically

**Expected behavior**
Skip the ad

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 125.0.6422.141

**Comment by Cscreato-r** [comment]
same here it shows that the youtube is violating the terms of service and it has identified the adblock....pls fix this asap dev

**Comment by minanagehsalalma** [comment]
Same

it only goes away when you open the vid in a new tab 

@TheRealJoelmatic it just needs access to the new page code.

**Comment by XTREMRUST** [comment]
AdBlock with YouTube whitelisted.
Accept all cookies with YouTube whitelisted.
No other plugin of this type, but when a video is launched, it remains blocked: cf image attached.
If you refresh the page several times, the video launches, but it's annoying.
If you find the trick, we'll love you all ♥

![2024-06-02_15-22-42](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/37950656/e1929a10-b01c-478b-aa77-002e9502283e)

**Comment by gigadeplex** [comment]
Please stop pushing updates if you haven't tested them. Damn, I've updated a number of times now and it keeps showing the warning..

**Comment by Girres43** [comment]
Same issue.

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
