### ISSUE TITLE
5.3 is still not working

### ISSUE THREAD

**Issue by Ninjatintin** [TheRealJoelmatic/RemoveAdblockThing#436]
**Script version**
5.3

**Describe the bug**
Youtube is displaying the ad and going really fast and Youtube displays the anti adblock

**Expected behavior**
The ad should just skip

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest Version

**Additional context**
I know you're trying your hardest to fix the issue

**Comment by ak-47-brar** [comment]
bro do not hype he will continously doing his work to keep this projeact  updated. so instead of cursing him appreciate him.

**Comment by Ninjatintin** [comment]
> bro do not hype he will continously doing his work to keep this projeact updated. so instead of cursing him appreciate him.

ok i made it less rude

**Comment by XTREMRUST** [comment]
THANKS FOR YOUR HELP MAN THANKS
Unfortunately it doesn't work with version 5.3.
This version is well installed, I checked.
I can't do anything on my side so I send you all my support! 

And thanks again for your research into these shitty ads ;)

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439

**Comment by ak-47-brar** [comment]
> > bro do not hype he will continously doing his work to keep this projeact updated. so instead of cursing him appreciate him.
> 
> ok i made it less rude

fake you batch 😂 😂 😂
