### ISSUE TITLE
5.3 is Patched

### ISSUE THREAD

**Issue by King-YT5000** [TheRealJoelmatic/RemoveAdblockThing#438]
**Script version**
5.3

**Describe the bug**
Hello, Youtube has an update and now it displays the Anti Adblock so please fix it. Thank you in advance.

**Desktop**
- OS: Windows
- Browser: Chrome
- Version: Latest Version

**Comment by TheRealJoelmatic** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439
