### ISSUE TITLE
READ BEFORE OPEING A ISSUES | About Current Detection | ("Ad blocker is not allowed on Youtube")

### ISSUE THREAD

**Issue by TheRealJoelmatic** [TheRealJoelmatic/RemoveAdblockThing#439]
This is a Thread to discuss the recent detections answer questions and to clean up the issues page.

## What changed why is YouTube detecting this script now?

This script has been UD for many months now what changed?
As of what I'm aware of YouTube has been aware of this script since 6 January 2023 when they took down my YouTube video showing off how to install and use this script.

Recently YouTube has been cracking down on adblocker bypasses for youtube and as this script is very popular at this point and open source we are a big target.

## Do I plan on supporting this?

Yes, as u can see I've still been working on a way to get this working again.
Any help is very much appreciated.

Feel free to DM me on Discord (Joelmatic)
Or open a pull request 

## Why is taking long

Since all the code is open source, both you and I, as well as YouTube employees, can examine how it functions. Currently, I can compile a build successfully on my machine, but YouTube seems to implement patches to counteract the workaround within 2 to 5 hours after each update.

## Why did I close all the issues

There was a significant backlog of problems that have since been resolved, along with numerous duplicate issues.

Thank you for all the support it's appreciated as I'm trying to fix this script as I refuse to watch ads or pay to remove them.

**Comment by recalldev10** [comment]
If youtube is watching your changes and responding with workarounds, how can you make sure that there is a definite build made?

**Comment by ralinchan** [comment]
> If youtube is watching your changes and responding with workarounds, how can you make sure that there is a definite build made that works for a longer period of time?

He stops making it open source.

**Comment by Ninjatintin** [comment]
> > If youtube is watching your changes and responding with workarounds, how can you make sure that there is a definite build made that works for a longer period of time?
> 
> He stops making it open source.

he can't really do that, he would probably have to obfuscate the code to prevent youtube from countering it

**Comment by brianrho** [comment]
Or find some magic solution that, even when revealed, still makes detection impossible without seriously affecting non-blocking users. In other words, bombard them with false positives.

**Comment by TheRealJoelmatic** [comment]
I've pushed an update that now allows you to watch YouTube ad-free without any detection (5.4)

Please let me know if it works for u.

Also I'm aware playlist don't work as intended by not auto going to the next video.

**Comment by HeroOfTheSword** [comment]
Oddly, the previous version now actually sort of works for me. The ads still come up but they all fast forward within about 5 seconds. Maybe whatever yt changed for this update allowed the previous one to work?! Also how petty of them to bother counteracting your changes, like how many people of their userbase actually bother with scripts, probably <1%.

**Comment by Ameer-Jamal** [comment]
The truth is if youtube wants to put there mind to it they will tear this repo and anything like it apart through engineering solutions against it, even if you found a way to make it closed source (Chrome extension + Obfuscation. + independent extension not on chrome store ) etc , the only way I see this working long term is building many active contributors and also finding a way that is better than a tamperMonkey script as they become hard to maintain after they get big
