### ISSUE TITLE
Ads Play Fast, But "No Adblockers Allowed" Screen Still Appears

### ISSUE THREAD

**Issue by BerriiBerri** [TheRealJoelmatic/RemoveAdblockThing#440]
**Script version**
5.3

**Describe the bug**
I read the new announcement, so I understand that for now, ads will still show, albeit played at a faster speed than usual. However, while this does happen, immediately after the ad ends, the "Ad blockers violate..." screen appears.

**Expected behavior**
I expected to either be able to skip the ads like normal, or in the case where you can't skip the ad(s), view the video.

**Screenshots**
Here is a video demonstrating the issue.
https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156716272/1e9b08f7-461d-4acb-b6fe-c2a67cedc3f2

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Version 125.0.6422.142

**Comment by Ninjatintin** [comment]
getting the same issue

**Comment by Solvmane** [comment]
same issue too, why is YT so greedy geesh

**Comment by Enderlordalatreon** [comment]
This only became a problem when I updated, first it just fast forwarded instead of skipping completely with occasional freezing, now I have this issue. Really strange.

**Comment by Skuen** [comment]
Same issue. Seem like the update doesn't do much. In my case, i do some F5 shit and it's work for a while untill the pop up appear again.

**Comment by TheRealJoelmatic** [comment]
I've updated the script were this on longer happens. Please let me know if it works for u now. v5.4

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439)
