### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Naresh-11** [TheRealJoelmatic/RemoveAdblockThing#441]
**Script version**
letest 
i will use letest chrome
you tube will detect this script yesterday and blocked it when i use this script then the youtube was blocked me

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.4

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439)
