### ISSUE TITLE
The script detected by Youtube as AdBlocker now ( June, 3th 2024 )

### ISSUE THREAD

**Issue by JeromeMathsAndGo** [TheRealJoelmatic/RemoveAdblockThing#443]
**Script version**
5.3

**Describe the bug**
Pop up youtube: "Ad blockers violate YouTube's terms of service". Cannot watch youtube without desactivating the script.

**Expected behavior**
No add on youtube, not detected.

**Screenshots**
(sorry, its in french)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/153611960/b5d78460-3633-4c37-b3d4-f45d2c912fa4)

**Desktop (please complete the following information):**
 - Windows 10

**Additional context**
Since the update of June, 2nd 2024

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.4

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439)
