### ISSUE TITLE
Ad blockers are not allowed on YouTube ( Pictures showa upp ) after the speed up and there to no auto skip

### ISSUE THREAD

**Issue by kaliko69** [TheRealJoelmatic/RemoveAdblockThing#445]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/132271881/97c1c633-a61b-4292-ad7d-8a78e20d41d0)

After pressing allow Youtube ads this comes 

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/132271881/171ee1a2-8552-4b08-9355-049ae950b02e)

After this when we click in in cross option again first pop up comes

**Comment by petr-hybler** [comment]
same here

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.4

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439)
