### ISSUE TITLE
It doesn't work again

### ISSUE THREAD

**Issue by Blank06230623** [TheRealJoelmatic/RemoveAdblockThing#446]
**Script version**
5.3

**Describe the bug**
If I try to watch video, I can't watch it. Looking a picture below will help to understand easily.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/156514133/0498dc5b-4d75-4ac8-a3c4-464efc412ee5)
---Translations---
Ad blockers violate YouTube's Terms of Service
- It looks like you may be using an ad blocker. Video playback is blocked unless YouTube is allowlisted or the ad blocker is disabled.
- Ads allow YouTube to be used by billions worldwide.
- You can go ad-free with YouTube Premium, and creators can still get paid from your subscription.
[Allow YouTube Ads] [Try YouTube Premium]
Not using an ad blocker? [Report issue]

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 Korean
 - Browser: Google Chrome
 - Version: 125.0.6422.113

**Additional context**
The default language is Korean and the default region is South Korea. I can "temporarily" block ads by changing language to English (they won't work again when browser restarts).

**Comment by petr-hybler** [comment]
same here ... couple of F5s worked tho :(

**Comment by TheRealJoelmatic** [comment]
I've updated the script to fix the detection. Please let me know if it works for u now. v5.4

also this a duplicate issue.
(https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439)

**Comment by Blank06230623** [comment]
updated to 5.4 but its still not working
