### ISSUE TITLE
5.4 update -- Audio Ads continue to play

### ISSUE THREAD

**Issue by GrandpaMo** [TheRealJoelmatic/RemoveAdblockThing#447]
Look Below    

          > I've pushed an update that now allows you to watch YouTube ad-free without any detection (5.4)
> 
> Please let me know if it works for u.
> 
> Also I'm aware playlist don't work as intended by not auto going to the next video.

It works now however, the audio of the original ADs now just play behind the video. I believe there can be a mute function that could be implemented.

_Originally posted by @GrandpaMo in https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/439#issuecomment-2145791729_

**Comment by McBenjihood** [comment]
same here for me

**Comment by Dash0219** [comment]
You can press spacebar to pause the ad for now

**Comment by gamemaniac123** [comment]
same

**Comment by GrandpaMo** [comment]
> You can press spacebar to pause the ad for now

If you press the spacebar to pause -- it will replay the video causing duplicate audio bug to occur.

**Comment by GrandpaMo** [comment]
I believe I know where the bug lies at in the code.

"function clearPlayer(videoPlayerElement)" 

It is happening most likely because this function above is not being executed properly causing the duplicate current video is not being deleted. I think the code is being stuck in the while loop. 

Looking at the console logs -- it looks like the function to remove the current player, then remove page ads, then embed replacement video, extraction of ID, then remove the current player again, then finish.

Currently, the replacement "embed" video has no ads and works perfectly but the current video is being played in the background like a normal video with ads. I am trying to figure why the function clearPlayer is not giving the error.

I will try to play around with it and update anything I find.

**Comment by GrandpaMo** [comment]
Update:

Version 5.0 seems to be unpatched so far probably because youtube's patching of current updates may have reversed the damage done. 

You can downgrade the script for now at: https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v5.0/Youtube-Ad-blocker-Reminder-Remover.user.js

**Comment by GrandpaMo** [comment]
Update:

I think I found the exact issue and what is happening. 

I believe the class that is being deleted from the function clearPlayer from the youtube site is this element

<div class="html5-video-container" data-layer="0" draggable="true"><video tabindex="-1" class="video-stream html5-main-video" controlslist="nodownload" src="blob:https://www.youtube.com/3ab4001b-a100-4626-a6f8-52dfd8f06e11" style="width: 481px; height: 271px; left: 0px; top: 0px;"></video></div>

which has the similar class as the html5-video-player shown in the code.

However deleting only the player will cause the video output to gone but the controls and everything else including the audio to stay. This was found after deleting the element.

The element or the class specifically this was under was this 

"html5-video-player ytp-transparent ytp-exp-bottom-control-flexbox ytp-modern-caption ytp-exp-ppp-update ad-created ytp-fit-cover-video ytp-bigboards ytp-fine-scrubbing-exp ytp-hide-info-bar ytp-small-mode ytp-heat-map-v2 ytp-heat-map ytp-autonav-endscreen-cancelled-state ytp-branding-shown paused-mode"

This would contain all of it. Now I don't know if this have been tried before -- but if that doesn't work there are also greater classes that this class falls under that could also work including the style scope ytd player.

Is there something you could possibly test by changing what the clearPlayer function video deletes? I will try to see what I can get.
