### ISSUE TITLE
Video echoes and like button dissapeard 

### ISSUE THREAD

**Issue by GoldenLogic** [TheRealJoelmatic/RemoveAdblockThing#448]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by GoldenLogic** [comment]
Videos echoing since new update and dislikes have dissapeared.

**Comment by SleepingPig35** [comment]
See #449 for temporarily fix!
