### ISSUE TITLE
v5.4 there is a double sound in the video that is playing

### ISSUE THREAD

**Issue by ArinLP** [TheRealJoelmatic/RemoveAdblockThing#449]
**Script version**
5.4

**Describe the bug**
when I start a video on youtube it sort of starts 2x, one in the background and one normally, so when I watch the video I hear the same video in the background but a second delayed and you hear the video then 2x + when I want to click on the video using the mouse wheel to open it in another window it doesn't work

**Expected behavior**
so that the video can't be heard 2x at startup

**Desktop (please complete the following information):**
 - windows 11
 - Brave
 - Version (i dont know)

**Comment by muhdkhokhar** [comment]
Playback on other websites has been disabled by the video owner

Seeing this error.

**Comment by McBenjihood** [comment]
The issue came with the 5.4 update so just install 5.3
Here is the link: 

https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js

Just press open raw and then press reinstall.

**Comment by muhdkhokhar** [comment]
thanks man you saved me there haha

**Comment by SleepingPig35** [comment]
See #450 for fix.

**Comment by finkiki** [comment]
Same issue here, but there is no ad playing so there is real progress here!

**Comment by heyamay** [comment]
audio is playing in background

**Comment by pedrosimao** [comment]
Yes, I had the same.
I even had the sound of the ad playing on the background too.

**Comment by squilliams-unibrow** [comment]
I've just got the same issue, what I think happens is the actual working video gets obstructed by an embed of himself (no "next video" button or the appearance of one that says "watch on YouTube) and the embed buttons indeed do not do anything with the embed video, but I can click anywhere on the video (these buttons included) to stop/resume the hidden video. You can control the hidden video as usual with your keyboard but the embed is still overlapping it. The embed can't be paused in any way.

**Comment by JustExynous** [comment]
Just got my ears blasted off with baby shark ads... This is serious problem.

**Comment by JtMotoX** [comment]
> Just got my ears blasted off with baby shark ads... This is serious problem.

Please be kind and considerate to the developer of this script. Nobody is making you use this script. I have seen too many good projects go dead due to the tone and ungratefulness of the community.

**Comment by muhdkhokhar** [comment]
Everyone is kind to the developer . We always are thanksful to him 
Its just issues we are experiencing.

**Comment by AlehooH** [comment]
> El problema surgió con la actualización 5.4, así que simplemente instale 5.3. Aquí está el enlace:
> 
> https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js
> 
> Simplemente presione abrir sin formato y luego presione reinstalar.

Thanks Bro ;)

**Comment by JustExynous** [comment]
> > Just got my ears blasted off with baby shark ads... This is serious problem.
> 
> Please be kind and considerate to the developer of this script. Nobody is making you use this script. I have seen too many good projects go dead due to the tone and ungratefulness of the community.

Did I mock him? Everybody obviously knows solving this stuff def isn't easy. Just thought to report issues while being a tad bit funny...

**Comment by seriouslyallusernamesarealreadytaken** [comment]
FYI:

The 5.3 version work-around no longer works as YT has recognised it and is blocking the videos.
Update 5.5 of the script, released half an hour or so ago does not solve the issue. Video starts playing just fine but any commercials that might originally have played are now still playing with audio only. If no ads were at the start of the video, there's a delay in video audio and the audio doubles.

Kind regards,

**Comment by seriouslyallusernamesarealreadytaken** [comment]
FYI 2: Script version 3.8 seems to be working fine, that is, no ads and no double audio.

**Comment by kerth5** [comment]
5.5 does not solve dual sound issue. There is a new issue - if movie is blocked for a view outside of Youtube, it does not play.
