### ISSUE TITLE
Ads are not blocking

### ISSUE THREAD

**Issue by Lakshay2910** [TheRealJoelmatic/RemoveAdblockThing#45]
It is just a minor issue. It would be better, if these thumbnail ads also get's removes. See 👇🏻 these thumbnail ads are showing on browser. 
https://ibb.co/f28wYbf

And I have one more request.
I'm a YouTube user, and I find it inconvenient to click 'Show more replies' repeatedly to view all comments on videos. Could you please make a script on this, that loads all comments at once? It would make my YouTube experience much better.

**Comment by lushythedev** [comment]
This isn't an adblock remover. It just stops the "Anti-Adblock" popup.

**Comment by wefalltomorrow** [comment]
> And I have one more request. I'm a YouTube user, and I find it inconvenient to click 'Show more replies' repeatedly to view all comments on videos. Could you please make a script on this, that loads all comments at once? It would make my YouTube experience much better.

This script offers that: https://greasyfork.org/en/scripts/405614-youtube-polymer-engine-fixes

**Comment by lushythedev** [comment]
Yeah, I think in the sense that it stops them from showing. May be wrong.

**Comment by kosovito** [comment]
It does not works for me either on the last version from today, ADS still appears in the video

**Comment by gjlmotea** [comment]
Use the rule `@@||youtube.com/watch*^$document` instead of `@@||youtube.com/*^$document` in Adblock.
This is my solution, not sure if it's what you're looking for.

https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/61/files
