### ISSUE TITLE
v5.4 removes Theater mode button

### ISSUE THREAD

**Issue by freshefisch** [TheRealJoelmatic/RemoveAdblockThing#451]
**Script version**
5.4

**Describe the bug**
When using the newest version, the button for Theater mode disappears. Using the hotkey (t) also doesn't work.

**Desktop (please complete the following information):**
Firefox on Windows 11

**Comment by Krishn-G** [comment]
I believe an embed in the latest 5.4 version overlaps the actual video, causing these issues. For me, the 5.0 version is working fine. You can use the following link to downgrade the script:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v5.0/Youtube-Ad-blocker-Reminder-Remover.user.js

**Comment by minanagehsalalma** [comment]
@Krishn-G thx man
