### ISSUE TITLE
v5.4 timestamped links are broken

### ISSUE THREAD

**Issue by freshefisch** [TheRealJoelmatic/RemoveAdblockThing#452]
**Script version**
5.4

**Describe the bug**
When opening a link with a timestamp at the end (for example &t=494s), it does not go to the specified time, but starts the video from the beginning.

**Desktop**
Firefox on Windows 11

**Comment by Krishn-G** [comment]
I believe an embed in the latest 5.4 version overlaps the actual video, causing these issues. For me, the 5.0 version is working fine. You can use the following link to downgrade the script:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v5.0/Youtube-Ad-blocker-Reminder-Remover.user.js
