### ISSUE TITLE
v5.4 issue with audio

### ISSUE THREAD

**Issue by K4IZ3H** [TheRealJoelmatic/RemoveAdblockThing#454]
**Script version**
v5.4

**Describe the bug**
when starting a video the audio is either overlapping itself so like 2 at once or more commonly, playing the audio from the supposed advertisement while the video is playing

**Expected behavior**
skipped ad and ad block popup 
**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser opera gx
 - Version most recent as of the third of june 2024

**Additional context**

**Comment by lukastm321** [comment]
Same in google chrome

**Comment by muhdkhokhar** [comment]
Its even worst
come on pleae fix

**Comment by RikuZonex** [comment]
You need to downgrade to v5.3 it works for me at least

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
