### ISSUE TITLE
5.4 issue with double playback of video

### ISSUE THREAD

**Issue by Skykasih** [TheRealJoelmatic/RemoveAdblockThing#455]
**Script version**
v5.4

**Describe the bug**
YT Videos are played twice (I assume by YT and the AdBlock). Sound overlaps and the Adblock replay was not synced with the YT one. Only the AdBlock video is seen/interactable (i.e. paused and stuff). I can hear both videos, but only the adblock video pauses.

**Expected behavior**
A single video is played (as previous versions have done) and still skips ads.

**Screenshots**
No screenshot would be helpful since the YT video runs in the background without visuals.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Browser Chrome
 - Version 125.0.6422.141

**Additional context**

**Comment by AlehooH** [comment]
The same thing happens to me, using Google Chrome the audio of the video I watch is played twiceThe same thing happens to me, using Google Chrome the audio of the video I watch is played twice

**Comment by AlehooH** [comment]
Does anyone know how I can find out when they fix it?

**Comment by BoAW** [comment]
Video playing twice, overlapped by add

OS: Windows 11
Browser Chrome
Version 125.0.6422.141

**Comment by RikuZonex** [comment]
You need to downgrade to v5.3 it works for me at least

**Comment by perrolas** [comment]
Yeah, i just received an update and got that issue as well, i have to turn off the script on mozilla

**Comment by Kawwaka** [comment]
same here

**Comment by AlehooH** [comment]
Gente usen la version 5.3 confirmado que en esta version no tendran ese error :)

**Comment by Flower32bit** [comment]
how can I downgrade to v5.3?

**Comment by mirosali** [comment]
Same here. How can I downgrade to 5.3v?

**Comment by ponder1440** [comment]
same here

**Comment by GroggyOtter** [comment]
> Does anyone know how I can find out when they fix it?

If you go to YouTube and there's a new version of RAT, TamperMonkey should automatically notify you with a pop stating a new version is available. And it gives you the option to download it.

**Comment by BoAW** [comment]
You may try to get v5.3 from here
https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js
Then click on "Raw", and then on reinstall

**Comment by Willco9455** [comment]
> how can I downgrade to v5.3?

If you cant do it directly through tampermonkey then you can get the old 5.3 code [here](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js) and then just replace the 5.4 script with that 5.3 script in tampermonkey

**Comment by Skykasih** [comment]
> Does anyone know how I can find out when they fix it?

I assume we'll just see if next update the bug is fixed.

**Comment by WoeIsLee** [comment]
> You may try to get v5.3 from here https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js Then click on "Raw", and then on reinstall

good lookin

**Comment by GroggyOtter** [comment]
Temp Fix: Temp fix: https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)

**Comment by AlehooH** [comment]
I have already been testing version 5.3 of the extension for 2 days and it works, but YouTube is already detecting that we are using something external that skips the ads, in addition to the fact that tampermoney also automatically updates the version of the Ad-blocker to the most current one which still They don't fix this bug
