### ISSUE TITLE
Core YouTube features are gone and videos are double loading

### ISSUE THREAD

**Issue by GroggyOtter** [TheRealJoelmatic/RemoveAdblockThing#457]
**Script version**:
v5.4

**Describe the bug**: 
Multiple "features" of YouTube seem to be missing.  
This happened after I was notified to update to the new version.  
I'm assuming this is caused by the addon, as I don't think YouTube would randomly remove these features:  

- Autoplay is no longer available. Playlists stop when the first song is done playing.  
- The ability to "hold down left mouse to run video at double speed" doesn't seem to exist.
- The "skip to next video" button no longer shows up on the UI.  
- These are the things I immediately noticed and there very well could be more missing.

Also, videos are now double-loading:

- There's a live version playing normally and one "behind the live version". Pausing the top one leaves the other video playing in the background with no way to pause or otherwise stop it (other than closing that tab).

**Desktop (please complete the following information):**
 - OS: Windows 10, 64-bit
 - Browser: Chrome v125.0.6422.114 (Official Build)

**Comment by zombiegak** [comment]
I installed the update today and noticed I'm getting echos of the video I'm watching. 
OS Win 10 64 bit
Firefox 126.0.1 64 bit

But in writing this I also had a update notice for TamperMonkey. Once the v5.1.1 update was installed the problem disappeared.
