### ISSUE TITLE
Ad Audio Playing in the Background of the Video

### ISSUE THREAD

**Issue by Mr-Merp** [TheRealJoelmatic/RemoveAdblockThing#458]
**Script version**
Version 5.4

**Describe the bug**
When you start a video sometimes, audio of an advertisement will be playing in the background overlapping the actual video. After the background ad is done, it will start playing the original video's audio twice leading to more overlapping audio.

**Expected behavior**
No advertisement audio to begin with and no overlapping audio

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version 125

**Additional context**
Sometimes when this bug occurs, if you have another youtube tab open with the video paused, the audio on that tab will start playing, but the video won't be playing causing even more overlap in audio

**Comment by Jurigag** [comment]
I have the same :/

**Comment by lerokko** [comment]
To expand on this I have that but with the video itself. The video play in the background and the foreground player plays the video a second time and I can only control the 2nd playback.

That uncontrollable "background video" then also play ads at the end.

**Comment by VerzatileDev** [comment]
I seem to be instead having overlapping audio of the main video itself

**Comment by GroggyOtter** [comment]
Temp fix: https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by kpods** [comment]
same, bug

**Comment by theashiqshow** [comment]
I have the same issue

**Comment by theashiqshow** [comment]
> Temp fix: #460

How can I do that?

**Comment by GroggyOtter** [comment]
> > Temp fix: #460
> 
> How can I do that?

Click the link. 😐

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
