### ISSUE TITLE
Unexpected changes in The YouTube Layout After The Last Update !!!

### ISSUE THREAD

**Issue by MDXD** [TheRealJoelmatic/RemoveAdblockThing#459]
The buttons have completely changed inside the video box at the bottom and a sign written YouTube appeared when you put the cursor on it saying watch on YouTube and when you click on it it takes the user to the same video clip this is very annoying, 

and when the video is paused, an annoying bar of suggested videos appears, which is even worse than ads

and also there is a double sound that appears sometimes even if the video is stopped the sound continues despite the absence of a source for this sound, 

and also regarding the shape of the video box that is being played it has become as if it resembles the shape of a mobile phone there is the title of the video above the video box that is being played, I only use this method to block ads I do not want the Layout of YouTube website to change

I don't know if this is a bug or is part of the contents of the update, but I hope that the fix will be done as soon as possible and that the focus will be on the main function of the code, which is to block ads without changing anything. 
This was not present in the version that preceded this.
![After](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26487274/138885d1-1d54-4bd6-800e-1bb99fb000b5)
![Before](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/26487274/35c73e01-1234-4ffa-96a9-6469563f3614)

**Comment by Kawwaka** [comment]
same

**Comment by GroggyOtter** [comment]
Temp fix: https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by AnubisTheGreatPharaoh** [comment]
same

**Comment by jerpytheawesomefella** [comment]
That appears to be an embed. Judging on how it was used here, we should expect it in the future unfortunately.

**Comment by argentinekiranomaze** [comment]
same it's doubled can't be close

**Comment by demdbeef** [comment]
Same issue, sometimes video is doubled so you hear two audios

**Comment by MDXD** [comment]
> Temp fix: #460
 the new update has the same problem that i mentioned in this issue
