### ISSUE TITLE
❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]

### ISSUE THREAD

**Issue by GroggyOtter** [TheRealJoelmatic/RemoveAdblockThing#460]
# Temporary Fix: Downgrading to v5.3

### Reverting to version 5.3 fixes the problems introduced by 5.4 and 5.5, making YouTube actually useable.  

How to downgrade to 5.3:  

[Step-by-step video instructions.](https://streamable.com/7e7qgn).

or

Text instructions:  

1. Get the 5.3 source code.
  I've already pulled it from GitHub and uploaded it to [this pastebin post](https://pastebin.com/raw/8JvsaYhf).
  Copy all the code (Ctrl+a to select all and Ctrl+c to copy).
2. Open up TamperMonkey.
3. Navigate to the the TamperMonkey dashboard.
4. Find the "Remove AdBlock Thing" script, and click on it. This will take you to the editor.
5. Highlight the current code (Ctrl+a), press delete or backspace to get rid of it, then paste the v5.3 code you just copied (Ctrl+v).
6. Click File > Save to save this version over 5.4.
7. You're done. Go back to YouTube and you should be prompted that version 5.4 is out.
You want to click "Skip" for version 5.4, as it's known to be a faulty version.
8. You should no longer get notifications about 5.4, but you SHOULD get a notification when 5.5 comes out.
9. Everything should be working now.

***
Update: v5.5 came out and still has issues.  
v5.3 still works.  
Keep using v5.3 for now.

**Comment by GrandpaMo** [comment]
Or just go this link

https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js

and press "Raw" and then press "reinstall".

**Comment by oomek** [comment]
Downgrading does not work for me. I'm still having doubled audio in 5.3

**Comment by GrandpaMo** [comment]
> Downgrading does not work for me. I'm still having doubled audio in 5.3



> Downgrading does not work for me. I'm still having doubled audio in 5.3

Doubled Audio should not occur in 5.3 because that method of embed video was only added in 5.4. Try reloading your page, you need to sometimes close out and reopen youtube and make sure it is the correct version in your dashboard.

**Comment by oomek** [comment]
You are right. The script has upgraded back to 5.4 even though I told it not to do so. I'm on 5.3 an audio doubling is gone.

**Comment by GrandpaMo** [comment]
> You are right. The script has upgraded back to 5.4 even though I told it not to do so. I'm on 5.3 and the audio doubling is gone.



> You are right. The script has upgraded back to 5.4 even though I told it not to do so. I'm on 5.3 and the audio doubling is gone.



> You are right. The script has upgraded back to 5.4 even though I told it not to do so. I'm on 5.3 and the audio doubling is gone.

Okay great to hear. I tried to fix it and I feel like I found the issue -- but I am currently to busy to do anything about it. I am currently satisfied with what I have that removes all ads. Hope 5.5 gets resolved soon.

**Comment by Spearman-98** [comment]
Same here, downgrading did not fix the problem for me.

**Comment by GroggyOtter** [comment]
> Same here, downgrading did not fix the problem for me.

@Spearman-98 
Ensure you restart your browser.
Verify in the TamperMonkey Dashboard that v5.3 is what's installed.
If there's an auto-updater active, you may have gotten updated back to v5.4

**Comment by cminglap** [comment]
"Remove Adblock Thing: New version is available.
Do you want to update?"

This pops up immediately again once I downgraded from 5.4 to 5.3, do I need to upgrade it again or just ignore it for now?

**Comment by GrandpaMo** [comment]
> "Remove Adblock Thing: New version is available. Do you want to update?"
> 
> This pops up immediately again once I downgraded from 5.4 to 5.3, do I need to upgrade it again or just ignore it for now?



> "Remove Adblock Thing: New version is available. Do you want to update?"
> 
> This pops up immediately again once I downgraded from 5.4 to 5.3, do I need to upgrade it again or just ignore it for now?

There should be a skip button you can press in the middle. If not, ignore it. Do not upgrade it because it will be 5.4 and it will change the code to that.

**Comment by GroggyOtter** [comment]
> "Remove Adblock Thing: New version is available. Do you want to update?"
> 
> This pops up immediately again once I downgraded from 5.4 to 5.3, do I need to upgrade it again or just ignore it for now?

I cover this in the main text of the post as well as the video........

**Comment by GroggyOtter** [comment]
> Downgrading to v5.3 is pointless because it doesn't block YouTube ads. It's better to just use it with the script disabled.

Haven't seen a single ad and YT has been up and running most of the day.

**Comment by Blodyholy** [comment]
Can confirm that this method doesn't work GroggyOtter 

> > Downgrading to v5.3 is pointless because it doesn't block YouTube ads. It's better to just use it with the script disabled.
> 
> Haven't seen a single ad and YT has been up and running most of the day.

Are you signed in to your Google account while watching? I've noted that if I use a VPN and don't sign in to my account, the subject method to block works, but if I'm not on a VPN connection and signed in, the subject method doesn't work -- I still see ads,

**Comment by GroggyOtter** [comment]
@Blodyholy 


Can confirm that this method doesn't work GroggyOtter

Downgrading to v5.3 is pointless because it doesn't block YouTube ads. It's better to just use it with the script disabled.

Haven't seen a single ad and YT has been up and running most of the day.

> Are you signed in to your Google account while watching? 

Yes.

> I've noted that if I use a VPN and don't sign in to my account, the subject method to block works, but if I'm not on a VPN connection and signed in, the subject method doesn't work -- I still see ads,

It has been working for me and I'm not currently using my VPN. Normal connection.

**Comment by Blodyholy** [comment]
> @Blodyholy
> 
> Can confirm that this method doesn't work GroggyOtter
> 
> Downgrading to v5.3 is pointless because it doesn't block YouTube ads. It's better to just use it with the script disabled.
> 
> Haven't seen a single ad and YT has been up and running most of the day.
> 
> > Are you signed in to your Google account while watching?
> 
> Yes.
> 
> > I've noted that if I use a VPN and don't sign in to my account, the subject method to block works, but if I'm not on a VPN connection and signed in, the subject method doesn't work -- I still see ads,
> 
> It has been working for me and I'm not currently using my VPN. Normal connection.

That first sentence of mine came out rather strong, apologies. I'm not sure what the issue is I guess, I'm rather confused as to why this works for some but not others. *shrug*

**Comment by GroggyOtter** [comment]
> That first sentence of mine came out rather strong, apologies. I'm not sure what the issue is I guess, I'm confused as to why this works for some but not others. _shrug_

It's all good. No harm done.  
I wish I could help you out more.

If it's any consolation, the problem you're describing is something I've experienced, well before either of these patches.  
And if it's the same thing I've experienced (random videos start having short ads at the beginning), I have good news for you. It should just go away after a bit. Like within a day. So I sure hope it's the same thing I've experienced (Also noticed that it's more frequent right after a chrome browser update and I wonder if that has something to do with it).

If it's something different, I can't speak to that but I wish you luck.

**Comment by Blodyholy** [comment]
> > That first sentence of mine came out rather strong, apologies. I'm not sure what the issue is I guess, I'm confused as to why this works for some but not others. _shrug_
> 
> It's all good. No harm done. I wish I could help you out more.
> 
> If it's any consolation, the problem you're describing is something I've experienced, well before either of these patches. And if it's the same thing I've experienced (random videos start having short ads at the beginning), I have good news for you. It should just go away after a bit. Like within a day. So I sure hope it's the same thing I've experienced (Also noticed that it's more frequent right after a chrome browser update and I wonder if that has something to do with it).
> 
> If it's something different, I can't speak to that but I wish you luck.

The short bit of ads I can attest to seeing as well, prior to the updates. Thank you for help and kind words =) I'll give it a bit and see if it shakes out. I understand this is an ever-moving process, with YouTube playing a virtual 'whack-a-mole' to these tools.

**Comment by rarachi** [comment]
To solve the issue of Tampermonkey automatically upgrading versions, I suggest you try using version 5.3 and manually change 
// @version 5.3 to // @version 5.4 in the editing function. 
This way, Tampermonkey should not attempt to automatically upgrade your version to the actual 5.4, and it will still automatically upgrade to 5.5 when the author releases that version.

**Comment by elvinsadiq** [comment]
Where can I find the version 4.0 ?

**Comment by GroggyOtter** [comment]
> Where can I find the version 4.0 ?

[v4.0](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/e6258e9e7d9c0093434ed18c55ba52e173259489/Youtube-Ad-blocker-Reminder-Remover.user.js)

**Comment by alif748** [comment]
I've changed the ad speed to x5, and it works, undetected

https://github.com/alif748/random-test/blob/main/YT-ad/speed-x5.js

**Comment by gcairesg** [comment]
Decided to comment here since its the issue topic with most replies.
Another "temp fix" if we can call it that way in 5.4 is pressing spacebar (obviously on the yt page) it will pause the 2nd video running on the background and the video being displayed works as expected.

**Comment by GroggyOtter** [comment]
> Decided to comment here since its the issue topic with most replies. Another "temp fix" if we can call it that way in 5.4 is pressing spacebar (obviously on the yt page) it will pause the 2nd video running on the background and the video being displayed works as expected.

Unfortunately, that only addresses one of the many problems that 5.4 introduced.  (And v5.5)
Downgrading is pretty much the best solution for right now.

**Comment by BlannyBlannyBlanc** [comment]
God bless you, thank you so much. I keep getting duplicated audio on videos, as well. Damn pooptoobe!

**Comment by Mendax1989** [comment]
Doesn't work.

**Comment by danaiDZ** [comment]
Doesn't work.

**Comment by DownyDawn** [comment]
Big thanks for your hardwork <3 Youtube gonna kill me with their ***** pubs. Love you <3

**Comment by DanteAnuj** [comment]
5.3 isn't working as well, it plays advertisements fast forward and sometimes still gives the Ad blockers violate YouTube's Terms of Service error. Someone help which version to use for smooth experiance

**Comment by GroggyOtter** [comment]
> 5.3 isn't working as well, it plays advertisements fast forward and sometimes still gives the Ad blockers violate YouTube's Terms of Service error. Someone help which version to use for a smooth experience

Might want to check [this reply](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460#issuecomment-2146718411).
That has happened to others, and it goes away.  
No idea what causes it, but it's happened to me a few times.

**Comment by slowbluesmaster** [comment]
Downgraded to 5.3 as instructed.

All is well again! Thank you!

macOS 10.13.6
Firefox 115.11.0esr

**Comment by Moredhel1983** [comment]
Thank you so much for this solution! I've been experiencing video reloads when switching between fullscreen mode and "normal" mode for two days now (though sometimes everything just worked) and was wondering what caused the problems, until I remembered I updated Tampermonkey three times in a row. Rollback to 5.3 fixed my problems!

**Comment by Aged-String** [comment]
I am either:
- Getting the video embed error
- Ads are embedded into the actual video with no way to skip them.
I've tried using many adblockers (including Ghostery and Ad Nauseam) but they fell through.
