### ISSUE TITLE
uBlock Origin is working now

### ISSUE THREAD

**Issue by brian840122** [TheRealJoelmatic/RemoveAdblockThing#461]
uBlock Origin is now working well again on YouTube without being detected. You might want to try it considering the recent issues we've encountered. Given YouTube's frequent updates against ad blockers, it might be better to keep both Remove Adblock Thing and uBlock Origin handy so we can switch if one gets blocked.

Thanks to all the devs for your hard work. Hoping to see the recent issues resolved soon!

**Comment by kodomozeza8** [comment]
Firefox user.
After the update, sometimes overlap video sound it like you play 2 video in the same time
ublock on if ublock off ads and video  still overlap

**Comment by Pooland1** [comment]
Yep guys uBlock is working still

**Comment by muhdkhokhar** [comment]
Hw is itworking now? that's good to know

**Comment by WoeIsLee** [comment]
Dont know what you're talking about, just updated all filters and its still broken.

**Comment by brian840122** [comment]
> Dont know what you're talking about, just updated all filters and its still broken.

Dont know what you mean broken.

**Comment by WoeIsLee** [comment]
> > Dont know what you're talking about, just updated all filters and its still broken.
> 
> Dont know what you mean broken.

As in still not working correctly. The only thing that works is dropping down to 5.3.

**Comment by muhdkhokhar** [comment]
ublock origin workst a treat
