### ISSUE TITLE
Video is playing itself twice

### ISSUE THREAD

**Issue by RicoFighter** [TheRealJoelmatic/RemoveAdblockThing#462]
**Script version**
5.4

**Describe the bug**
I'm no expert in coding, but after latest update. When I play a video, all ads are skipped, but the video audio is played twice, I can stop the video on my screen and that stops one audio track, but then i can hear the video again in the background without the possiblity of stopping it.

**Desktop (please complete the following information):**
 - OS: W10
 - Browser Chrome

**Additional context**

**Comment by NewNiklas** [comment]
Have the same issue. Reloading the page fixes it most of the time but it's really annoying.

**Comment by ozioma147** [comment]
Yes, i'm also having the same issue. I do notice that you can pause and play the background audio by first clicking somewhere around the video and the pressing space.

**Comment by pravnyadv** [comment]
having the same issue. the ad voice plays in the background

**Comment by radarblack** [comment]
Seconding this report. Can 100% confirm that the issue happens still. Having the script disabled fixes the issue for me as it also breaks other extensions I'm using for YouTube.

**Comment by davidkcyip** [comment]
Seconding this report too. I don't want to complain because it's free but it seems every update recently has made things worse.

**Comment by CherifBouabdallah** [comment]
> Yes, i'm also having the same issue. I do notice that you can pause and play the background audio by first clicking somewhere around the video and the pressing space.

Solves it for me, thanks !

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
