### ISSUE TITLE
Ad blockers and video play work well. But there are minor bugs.

### ISSUE THREAD

**Issue by skadygks** [TheRealJoelmatic/RemoveAdblockThing#4624]
**Script version**
5.6

**Describe the bug**
1 The video player is different from the previous one
1-1 not working auto play
1-2 After playing the video, If you click on the recommended video, it will open in a new tab.

**Expected behavior**
disable the script, works fine.

**Screenshots**
Before applying the script
![1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/72414160/ac8e5b18-879a-41f0-af64-f04c4c7d6cd3)
After applying the script
![2](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/72414160/3b66cecb-b2f4-4f23-88e5-cd92dac11edc)

**Desktop (please complete the following information):**
 - OS: WINDOW11
 - Browser : MS EDGE
 - Version 126.0.2592.81(64bit)

**Additional context**
I think it's probably because use a YouTube video player linked to another external site.

**Comment by theinit01** [comment]
Plus sometimes the keyboard shortcuts don't work too

**Comment by jongdetim** [comment]
Same on Chrome

**Comment by DC-Shi** [comment]
I also found this in playlist, where it cannot automatically go to next video in the list. I think it replaced the video with an embedded video which showed less ads. Thus losts the playlist information

**Comment by PaulWU1996** [comment]
Same issue here, and I didn't find a solution. I have tried to downgrade, but it still does not work.
