### ISSUE TITLE
2 Videos at the same time

### ISSUE THREAD

**Issue by D3v10n** [TheRealJoelmatic/RemoveAdblockThing#463]
2 videos were playing a once

**Comment by kschoi2** [comment]
When RABv5.4 executed 2 videos audio paly at  a same time.
I hope fixed as soon as possible.

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
