### ISSUE TITLE
Video is playing itself twice

### ISSUE THREAD

**Issue by D3VOZA** [TheRealJoelmatic/RemoveAdblockThing#464]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
