### ISSUE TITLE
5.4 palys 2 video sounds at a same time 

### ISSUE THREAD

**Issue by kschoi2** [TheRealJoelmatic/RemoveAdblockThing#465]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by kerth5** [comment]
I have exacly asme problem. MacOS, Chrome 125.0.6422.114 (newest, checked also on older one)
second sound is starting after a few seconds, everytime.

**Comment by raykyko** [comment]
Exacly the same problem..  Versão 5.1.1 
Second sound is starting after a 1/2 seconds, everytime.
SO: Windows 11 home, Chrome
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/23382220/186ee890-b512-467b-86fa-a263dea6e290)
If you pause the video on YouTube the video continues playing the audio

**Comment by ghwgrieq** [comment]
Same Problem Here,

**Comment by toothedCrib** [comment]
> Same Problem Here,

Hey Follow this link and the steps mentioned to fix the issue for now
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by toothedCrib** [comment]
> Same problem OS: Linux Manjaro KDE Plasma 6.0.5 Browser Chrome Version 125.0.6422.141 (64 bits)

Hey Follow this link and the steps mentioned to fix the issue for now
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by tohol24** [comment]
Same. For the first time ad sound played and at the same time music video was on. For the second time music was playing duplicite.

**Comment by toothedCrib** [comment]
> I have exacly asme problem. MacOS, Chrome 125.0.6422.114 (newest, checked also on older one) second sound is starting after a few seconds, everytime.

Hey Follow this link and the steps mentioned to fix the issue for now
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by gcairesg** [comment]
As I just commented on the mentioned topic above, you can also solve the problem by pressing spacebar at 5.4
Should work for everybody I guess

**Comment by jimmyleocn** [comment]
same here

**Comment by markox21** [comment]
same problem

**Comment by kimcuong9a** [comment]
same here

**Comment by TathagataDasgupta** [comment]
same problem

**Comment by TheRealJoelmatic** [comment]
I've pushed an update to hopefully address this (v5.5)

Also, this is a duplicate issue. (https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/449)
