### ISSUE TITLE
AD AUDIO PLAYING background and duplicate main video sound???

### ISSUE THREAD

**Issue by imbader** [TheRealJoelmatic/RemoveAdblockThing#467]
**Script version**
4.6 , the 3.4 was way better 
**Describe the bug**
Ad audio playing background and the main video sound duplicates

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by miko6** [comment]
Same problem

**Comment by VivekSVDEV** [comment]
same issue

**Comment by anss2110** [comment]
same issue here bruh

**Comment by Wiese2007** [comment]
same w10 FF 126.0.1 Script 5.4

**Comment by karl0905** [comment]
same here

**Comment by Hello411** [comment]
for AD audio add UBLOCK extension

for double audio, refresh the page with F5

it's my solutions for instant

**Comment by nicetry001** [comment]
same for me.

**Comment by nicetry001** [comment]
> same for firefox
> 
> for AD audio add UBLOCK extension
> 
> for double audio, refresh the page with F5
> 
> it's my alone solutions for instant

how do you do this my friend

**Comment by The1B4U** [comment]
Same issue.

**Comment by GroggyOtter** [comment]
Joelmatic knows about the problems.
Downgrading to 5.3 works for now until a new stable version is released.

[❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)

**Comment by Mendax1989** [comment]
Same.
