### ISSUE TITLE
Black screen in next videos played

### ISSUE THREAD

**Issue by tigirius** [TheRealJoelmatic/RemoveAdblockThing#468]
First video has double the sound so pausing it is the only way to listen to the video.
Sound is coming from the background of the video without the foreground playing video, there is no control to stop the background audio from playing.

After the audio of the video has completed the next video begins playing if autoplay is on but the box where the video is normally displayed suddenly goes black and even the controls for the video disappear.

This is of course on Youtube.com

**Comment by The1B4U** [comment]
I'm getting black screen on "YouTube Shorts"

**Comment by GroggyOtter** [comment]
Did ya'll skip the post titled...?

[❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)

Joelmatic knows about the problems.
Downgrading to 5.3 works for now until a new stable version is released.
