### ISSUE TITLE
5.5 still not working, same problems as before.

### ISSUE THREAD

**Issue by WoeIsLee** [TheRealJoelmatic/RemoveAdblockThing#469]

**Comment by JimBimBum** [comment]
also having issue on 5.3 i think it's youtube's "stabal audio" feature.

**Comment by whitedr00id** [comment]
still having the issue but now sometimes the time of delay is variable

**Comment by The789Guy** [comment]
I can confirm this is the case.
[screen-capture.webm](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/43525032/e46c9c23-2398-45c4-91e4-b06bbc891e0a)

**Comment by puunyapat** [comment]
Another issue I found is when you click the timestamp link, YT plays the background video instead.

**Comment by The1B4U** [comment]
I can confirm this. Ad sound plays in the background and  Shorts have black screen.

**Comment by GroggyOtter** [comment]
Did ya'll skip the post titled...?

[❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)

Joelmatic knows about the problems.
Downgrading to 5.3 works for now until a new stable version is released.

**Comment by Mendax1989** [comment]
Audio problems, red progress bar not working.

**Comment by WoeIsLee** [comment]
> Did ya'll skip the post titled...?
> 
> [❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)
> 
> Joelmatic knows about the problems. Downgrading to 5.3 works for now until a new stable version is released.

That was the entire purpose of 5.5, to fix 5.4.
