### ISSUE TITLE
downgraded to v5.0, no issues

### ISSUE THREAD

**Issue by misterslowly** [TheRealJoelmatic/RemoveAdblockThing#470]

**Comment by muhdkhokhar** [comment]
how to downgrade

**Comment by GroggyOtter** [comment]
@misterslowly  
Why 5.0 instead of 5.3?

@muhdkhokhar  
The post in the issues tab that stands out and is called:  
[❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)

**Comment by AlbertoHK** [comment]
@GroggyOtter 
In my tests 5.0 works skipping ads, while 5.3 play it in 2x speed.

**Comment by Rashedul3777** [comment]
> @misterslowly Why 5.0 instead of 5.3?
> 
> @muhdkhokhar The post in the issues tab that stands out and is called: [❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)


Bro 5.3 And 5.4 and 5.5 not working . Please Give Me solve
