### ISSUE TITLE
Embedded videos are blacked out

### ISSUE THREAD

**Issue by SimonMalicek** [TheRealJoelmatic/RemoveAdblockThing#471]
**Script version**
 5.5

**Describe the bug**
When I launch an embedded video it shows UI for a few milliseconds then turn black, I can play/pause it by clicking on it

**Expected behavior**
Video should just normally visible 

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/74243866/8e8126c3-4f8e-4e5f-9cc4-c6b12d36ed9b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 125.0.6422.114

**Comment by slowbluesmaster** [comment]
Same here, all embedded videos are black.

Script disabled. All is well again.
