### ISSUE TITLE
much bugs 5.5

### ISSUE THREAD

**Issue by dantassgb** [TheRealJoelmatic/RemoveAdblockThing#472]
Version 5.5 is broken, audio duplicates upon entering the video, and clicking on the timestamp leads to a black screen and a strange player.

**Comment by GroggyOtter** [comment]
[❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions]](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)
