### ISSUE TITLE
new version broke

### ISSUE THREAD

**Issue by quackerjack25** [TheRealJoelmatic/RemoveAdblockThing#473]
getting this error on some youtube videos, the video works as it usually does once I disable the script 
<img width="675" alt="image" src="https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/54336558/64977c92-79e2-4279-8c86-f770106d818d">

**Comment by DownyDawn** [comment]
Go back to 5.3 https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460
