### ISSUE TITLE
Age restricted videos are getting blocked

### ISSUE THREAD

**Issue by Ryom3nSukuna** [TheRealJoelmatic/RemoveAdblockThing#4739]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/174993543/92cbf9f1-ccec-4bbc-a2f0-fb79861058d2)

**Comment by supersmith2500** [comment]
Not just age-restricted ones. EVEN uploaders have the power to block them from playback on other websites too.

**Comment by AleksHR3** [comment]
I'm getting this too.
