### ISSUE TITLE
version 5.5 is unusable.

### ISSUE THREAD

**Issue by Popcornagraphy** [TheRealJoelmatic/RemoveAdblockThing#474]
latest version (5.5) , google chrome , installed by tampermonkey , 

it plays the ad sound and i can't get rid of it. also it plays the sound of the video twice with no control to fix it.

**Comment by vallme2003** [comment]
+1 on above , downgrading to v5 for now

**Comment by DomPrice** [comment]
Experiencing the same issue

**Comment by jongdetim** [comment]
can confirm.

**Comment by Pointsigns** [comment]
same here. No controls on YT at all

**Comment by dramr** [comment]
this is why i still use 5.3. no build after 5.3 is stable/working so.

**Comment by Popcornagraphy** [comment]
i recommend using ublock origin instead. works like a charm
