### ISSUE TITLE
Next video won't autoplay

### ISSUE THREAD

**Issue by Kevinwulf0** [TheRealJoelmatic/RemoveAdblockThing#4748]
**Script version**
5.6

**Describe the bug**
After a video plays, the next video will not play automatically. Even if it is playlist format, it only plays the video then shows the suggested 12 videos.

**Expected behavior**
The next video should autoplay.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 126.0.6478.127 (Official Build) (64-bit)

**Additional context**
Aside from showing a brief second of the ad at the start of the video, the lack of autoplay seems to be the only issue.

**Comment by Pathetacy** [comment]
i'm having this issue too, and its also tied with the fact that a few of the buttons on the video simply dont appear. autoplay is the biggest one here. its not just for playlists, its for whenever the script is running

**Comment by Wolf1030** [comment]
yea 5.6 is broken for the most part. Myself like a few others here, have had better results with 5.4, though it has it's own bugs, but everything works.

**Comment by akavi1** [comment]
I'm having the same issue on Chrome 125.0.6422.113 on MacOS Sonoma 14

**Comment by Kevinwulf0** [comment]
> yea 5.6 is broken for the most part. Myself like a few others here, have had better results with 5.4, though it has it's own bugs, but everything works.

Do you happen to have a link to 5.4? I couldn't find it under the releases or as a tag. It's much appreciated.

**Comment by Prathamesh7003** [comment]
im facing the same issue for the version 5.6 the autoplay button disappears after enabling the script and also if playlist is on manually we have to change the video

**Comment by Wolf1030** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/44e0c00ef38067a4918cf58d09e9f75bd18c7c8f/Youtube-Ad-blocker-Reminder-Remover.user.js


> > yea 5.6 is broken for the most part. Myself like a few others here, have had better results with 5.4, though it has it's own bugs, but everything works.
> 
> Do you happen to have a link to 5.4? I couldn't find it under the releases or as a tag. It's much appreciated.
