### ISSUE TITLE
Bug Complicated

### ISSUE THREAD

**Issue by MrHafid** [TheRealJoelmatic/RemoveAdblockThing#475]
**Script version**
All version to last update

**Describe the bug**
Bug is double audio, video, blank short video, and ads is play but video play too soo video play double and very annoying

**Expected behavior**
Fix them before update is normal

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 125.0.6422.113 (Official Build) (64-bit)

**Comment by PENNNA** [comment]
i have the same thing
