### ISSUE TITLE
HERE LATEST WORKING SCRIPT

### ISSUE THREAD

**Issue by dramr** [TheRealJoelmatic/RemoveAdblockThing#4760]
https://pastebin.com/2K6sGik5      use this script instead of the 5.6 one and u will be fine

**Comment by optionen100** [comment]
still displays the same "Adblock is not allowed" whenever an ad would play

**Comment by dramr** [comment]
> still displays the same "Adblock is not allowed" whenever an ad would play

disable any adblocker u have on your browser and use the tampermonkey+ this instead

**Comment by Babayaga-0007** [comment]
please prefer this script it is working https://pastebin.com/2K6sGik5 just edit the previous script in the Tampermonkey with this latest one

**Comment by Babayaga-0007** [comment]
> https://pastebin.com/2K6sGik5 use this script instead of the 5.6 one and u will be fine

Great work by the way.

**Comment by netnazgul** [comment]
This is the raw copy of https://github.com/TheRealJoelmatic/RemoveAdblockThing/commit/861272fb6b4aee20cd6b59f281b2034926e174c0 in case anyone is suspicious (v5.3 that speeds up ads, wasn't tagged as release for some reason). Can copy the script there as well.
