### ISSUE TITLE
unnecessary refresh, and shortcut not working ?

### ISSUE THREAD

**Issue by kuchaguangjie** [TheRealJoelmatic/RemoveAdblockThing#4761]
1. when switch full / non-full screen, it will switch, and start play from 0:00, don't remember the progress.
2. after the refresh, shortcut doesn't work, e.g left / right won't change progress, due to not focused ?

**Comment by Babayaga-0007** [comment]
please prefer this script it is working https://pastebin.com/2K6sGik5 just edit the previous script in the Tampermonkey with this latest one

**Comment by riky0701** [comment]
you can use this 
https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/main/Youtube-Ad-blocker-Reminder-Remover.user.js
