### ISSUE TITLE
Embed videos with black screen

### ISSUE THREAD

**Issue by BrenoS93** [TheRealJoelmatic/RemoveAdblockThing#4762]
Script version 5.6 on Violentmonkey

playing on any website causes this problem https://steamcommunity.com/sharedfiles/filedetails/?id=3209239259

 - OS: Windows 10 22H2
 - Browser Firefox
 - Version 127.0

**Comment by GaryParkin** [comment]
OS: Windows 10
Browser: Firefox
Tamper Monkey Version: 5.1.1
Adblock Thing Version: 5.6

Same issue.
Yes this is a dup but I wanted to stay informed.
