### ISSUE TITLE
Getting black screen while audio still playing

### ISSUE THREAD

**Issue by iamumairayub** [TheRealJoelmatic/RemoveAdblockThing#4764]
**Script version**
5.0

**Describe the bug**
Getting black screen while audio still playing

**Screenshots**

![60cc1025-2a58-453d-afa1-5d4131cdf77d](https://github.com/user-attachments/assets/350371b8-51be-4c69-ba01-cfb288991ccb)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 126.0.6478.182 (Official Build) (64-bit)

**Comment by GaryParkin** [comment]
OS: Windows 10
Browser: Firefox
Tamper Monkey Version: 5.1.1
Adblock Thing Version: 5.6

I'm getting the same thing.

**Comment by jesvijonathan** [comment]
fixed in PR : #4756, Lets hope the maintainers push the code changes
