### ISSUE TITLE
"Playback on other websites has been disabled by the video owner" message pops up in some videos

### ISSUE THREAD

**Issue by hikagura99** [TheRealJoelmatic/RemoveAdblockThing#4765]
**Script version**
5.6

**Describe the bug**
Some videos are impossible to watch bc the author might have disabled the chance to watch it as an embedded video

**Expected behavior**
I wanted to watch [this video](https://www.youtube.com/watch?v=jD3b1s-s9bk)

**Screenshots**
![image](https://github.com/user-attachments/assets/f665aef2-26b2-4845-949f-624ce1363ae5)

**Desktop (please complete the following information):**
 - OS: Arch Linux, Linux Zen 6.9.10-zen1-1-zen
 - Browser Mozilla Firefox 
 - Version 128.0-2

**Comment by Sadenkhan** [comment]
Same problem

**Comment by supersmith2500** [comment]
Because they want people to watch on YouTube's main site.
Google finding ways to **punish users** as usual!

**Comment by GaryParkin** [comment]
OS: Windows 10
Browser: Firefox
Tamper Monkey Version: 5.1.1
Adblock Thing Version: 5.6

I'm getting the same thing.
