### ISSUE TITLE
good news! it removes the adblock-block screen! bad news! it removes the entire video itself.

### ISSUE THREAD

**Issue by Pathetacy** [TheRealJoelmatic/RemoveAdblockThing#4769]
**Script version**
5.6

**Describe the bug**
video plays for roughly five seconds, before the script removes the entire video screen while the audio plays, and only reverses when the entire page is refreshed, and even then it still keeps on doing it.

**Expected behavior**
video plays while also blocking ads.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Opera GX on windows 10

**Additional context**
also removes the autoplay, miniplayer and theater mode buttons.

**Comment by GaryParkin** [comment]
OS: Windows 10
Browser: Firefox
Tamper Monkey Version: 5.1.1
Adblock Thing Version: 5.6

I'm getting the same thing.

**Comment by jesvijonathan** [comment]
fixed in PR : #4756, Lets hope the maintainers push the code changes
