### ISSUE TITLE
White Screen of (Video) Death - Adblock Works, but video playback ends

### ISSUE THREAD

**Issue by djdaem0n** [TheRealJoelmatic/RemoveAdblockThing#4770]
**Script version**
5.6

**Describe the bug**
The Adblock screen never appears, the video starts, but then about 8 seconds in (no matter where you skip to in the video) the entire video playback goes white. The audio continues to play, but the video never returns.

**Expected behavior**
Obviously, the adblock screen shouldn't be there and the video and audio should play in sync without issues.

**Screenshots**
![youtubethingbug](https://github.com/user-attachments/assets/5deb942b-39e5-407c-8de0-4d376ed19b3d)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 126.0.6478.183

**Additional context**
If I notice anything else about the issue i'll **EDIT** and add here.

**Comment by jesvijonathan** [comment]
fixed in PR : #4756, Lets hope the maintainers push the code changes

**Comment by thefemaledog** [comment]
I tried downloading an older version (i.e. v5), and it still functions! May wanna try it yourself!
