### ISSUE TITLE
Video unavailable

### ISSUE THREAD

**Issue by elvinsadiq** [TheRealJoelmatic/RemoveAdblockThing#4775]
**Script version**
Version 5.6

**Describe the bug**
Video unavailable
Playback on other websites has been disabled by the video owner
[Watch on YouTube]

**Screenshots**
![Screenshot 2024-07-30 100830](https://github.com/user-attachments/assets/27b9c779-ad30-4ccf-a8e8-28a4baa2a95a)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser: Chrome
 
 After disabling Remove Adlock Thing the video starts to play. Guess they found a way to completely block users watching video if they are using Remove Adlock Thing

**Comment by Hugs-4-Bugs** [comment]
I have resolved this and enabled the autoplay the next video automatically
