### ISSUE TITLE
Opening private videos with access bugged

### ISSUE THREAD

**Issue by Kemzol** [TheRealJoelmatic/RemoveAdblockThing#4779]
**Script version**
5.6

**Describe the bug**
When im trying to open youtube private video (with given access to me) it always show that its private, and even if i am the creator of the private video.

**Expected behavior**
Open private videos with no bugs.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version idk

**Additional context**

**Comment by Hugs-4-Bugs** [comment]
Replace your old code with new one
