### ISSUE TITLE
YouTube Shorts is not Working for 5.5

### ISSUE THREAD

**Issue by KingTigerThomas** [TheRealJoelmatic/RemoveAdblockThing#478]
**Script version**
5.5

**Describe the bug**
YouTube Shorts Video itself not playing (screen is just black out), even after F5, audio still works

**Expected behavior**
I expected the video to also play, not black out.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171751775/511203c0-84fd-4a6d-b480-762ae63b4edd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Google Chrome
 - Version 125.0.6422.142 (Official Build) (64-bit)

**Additional context**
Non

**Comment by DownyDawn** [comment]
You try go back to 5.3 ? https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by KingTigerThomas** [comment]
> You try go back to 5.3 ? #460

That version wasn't working for me as well.

**Comment by Smith873** [comment]
Same problem with Win7, FireFox v115.11.0esr.
Script v5.5.
