### ISSUE TITLE
I still gett ads in the 5.0 

### ISSUE THREAD

**Issue by SneakyFox123** [TheRealJoelmatic/RemoveAdblockThing#4780]
**Script version**
5.0

**Describe the bug**
I still get ads when I click on the videos and I cant even skip the add I have to refresh to not get the one that is 2 min long

**Screenshots**
![image](https://github.com/user-attachments/assets/db8f74ed-4c4f-4dc6-8228-4bb1c5025150)

Cant skip it 

**Desktop (please complete the following information):**
 - 
 - Browser chrome
 

**Additional context**
Do any of you guys have the same

**Comment by howTOdoIT2** [comment]
i use 3.8 version on firefox and no ads

**Comment by Hugs-4-Bugs** [comment]
update your browser and make sure no other adblocker is enabled

**Comment by RikuZonex** [comment]
Just update. 5.0 is not latest, 5.6 is

**Comment by Hugs-4-Bugs** [comment]
Try updating the timer 1000 to 10000, it will remove that 5 sec ads under 1 sec....
