### ISSUE TITLE
Problems with Tampermonkey v5.6

### ISSUE THREAD

**Issue by Kopus123** [TheRealJoelmatic/RemoveAdblockThing#4782]
After using this new version I found a bunch of things that make watching videos very inconvenient:
1. Theater mode disappears
2. Some glitches with full screen can occur
3. When paused the "More videos" tab appears which I find very annoying
4. Cannot scroll to comment section in full screen anymore
5. Autoplay button is gone
6. The "Youtube" button that only appears when watching a youtube video on an external site appears even though it shouldn't (clicking on it opens a new tab of the same video)
It seems as if this update tries to bypass ads by making youtube think that the user is trying to watch it on an external site, however this creates more problems than can be handled so the youtube experience is pretty bad now. Unfortunately as of today no other previously good working versions (3.8, 5.0, 5.3) seem to be working anymore, so 5.6 is the only option as 5.4 and 5.5 were very buggy.

**Comment by SneakyFox123** [comment]
And the speed to x2 when you hold your mouse is not working
