### ISSUE TITLE
Youtube Auto play not work (Button is gone)

### ISSUE THREAD

**Issue by Dollekil** [TheRealJoelmatic/RemoveAdblockThing#4783]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

i use Version 5.6

**Describe the bug**

Auto play not working / button is gone

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.
![image](https://github.com/user-attachments/assets/bda2747f-70c9-4865-bc71-63442385e0be)

**Desktop (please complete the following information):**

**Additional context**

i use the new Youtube addblock script but My Auto Play button is Gone when i use the script if i disable the scripts the button is back Auto play is alsno not working is there any solution

**Comment by GroggyOtter** [comment]
Yup. That's one of the many known bugs in 5.6 and 5.7 is nowhere to be seen.

Downgrade to 5.3 and it'll fix that problem.

**Comment by SneakyFox123** [comment]
on 5.3 I get adds why is that

**Comment by Dollekil** [comment]
with the 5.3 version i get adds but it skips very fast

**Comment by GroggyOtter** [comment]
My setup is win10 + chrome browser + tampermonkey with 5.3 and I get no ads.  
If you're getting ads, there's an X-factor not being accounted for.

I did have a couple times when ads randomly came up, but refreshing the browser got rid of it.  
This behavior has happened on versions other than 5.3, so it's not an error inherent to 5.3 nor does it happen often.

**Comment by MikeVin-do** [comment]
![image](https://github.com/user-attachments/assets/01d94b11-ba26-4936-8d0c-b3b643a0621c)
![Screenshot 2024-08-12 162231](https://github.com/user-attachments/assets/70c4cf41-8c03-47ef-ba4a-7c4d36e4e214)
 nothing happend

**Comment by GroggyOtter** [comment]
> ![image](https://private-user-images.githubusercontent.com/173903804/356994382-01d94b11-ba26-4936-8d0c-b3b643a0621c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTI0MzIsIm5iZiI6MTcyMzg1MjEzMiwicGF0aCI6Ii8xNzM5MDM4MDQvMzU2OTk0MzgyLTAxZDk0YjExLWJhMjYtNDkzNi04ZDBjLWIzYjY0M2EwNjIxYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQyMzQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTc0NjY1Mjk2ZTlmOWZjOTQyZjQ1NDAwNzI4MmE5MGM4Y2NiYjk0MjJkMTZjYzM5YzU0MzNlNTY0YWI3ZjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6zRv3sFjmvFJoWTgZZfViBOQu72Vqop2-INbtrfve6k) ![Screenshot 2024-08-12 162231](https://private-user-images.githubusercontent.com/173903804/356994461-70c4cf41-8c03-47ef-ba4a-7c4d36e4e214.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM4NTI0MzIsIm5iZiI6MTcyMzg1MjEzMiwicGF0aCI6Ii8xNzM5MDM4MDQvMzU2OTk0NDYxLTcwYzRjZjQxLThjMDMtNDdlZi1iYTRhLTdjNGQzNmU0ZTIxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxNlQyMzQ4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jOGQwNDEwZTA4Y2VmNDBjMmE4OGZmMTIzYWRjN2UyZDE0N2RhN2ZiNjEyNzE4NGRhNWFlZmM2ZWQ0MjFmMWE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2yU9PsvvEs31GaR4kA39BLWQ-41suyV4aq_djHB8JA8) nothing happend

That's because you're still on 5.6...
