### ISSUE TITLE
Joel, are you ever going to update this...? I'm still running on 5.3 b/c 5.4 - 5.6 are all broken...

### ISSUE THREAD

**Issue by GroggyOtter** [TheRealJoelmatic/RemoveAdblockThing#4784]
Title says it all.

Been having to run on a downgraded 5.3 install (as it still seems to be working).

What's the update on getting 5.7 out?

Edit: For anyone who wants to downgrade to a working version, [click here for 5.3](https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js), press the `Raw` button, and TamperMonkey should automatically open up.  
Click the `Downgrade` button and it'll install 5.3.

Reload your browser. When you get a popup saying "a new version is available", click the red `Skip` button or you'll just upgrade back to 5.6.

While not required, another thing you can do is go into the script, and look for this line:
`// @version      5.3`  
And change it to this:
`// @version      5.6`  
Make sure to save.

That's what I've been using for over 2 months (since 5.4 broke everything...) and it has been working flawless.

Disclaimer: I'm using Win 10 + Chrome browser so YMMV if those are different.

**Comment by Aizotope** [comment]
I'm still running on 5.3, too.
Chrome is also saying "This extension may soon no longer be supported" regarding to Tampermonkey. 
I wonder if that has anything to do with anything?

**Comment by WarpigtheKiller** [comment]
You guys and turn of auto update.

**Comment by yuhalam** [comment]
> 여러분, 자동 업데이트를 끄세요.
자동 업데이트 어떻게 끔?
