### ISSUE TITLE
Error with RemoveAdblockThing

### ISSUE THREAD

**Issue by AlehooH** [TheRealJoelmatic/RemoveAdblockThing#4785]
Maybe someone knows how to stop YouTube Ad Skipping from updating ?? I use version 5.3 that works for me and it does not have the error of playing the same audio 2 times, but it always updates itself and I have to reinstall the same version again, some solution ???

**Comment by hilmanfaiz** [comment]
To turn off auto-update on individual script:

1. Open Tampermonkey Dashboard
2. In the tab "Installed Userscript", click edit on "Remove Adblock Thing"
3. Select tab "Setting"
4. Uncheck the option "Check for updates"

Then you can downgrade back to 5.3

**Comment by AlehooH** [comment]
> Para desactivar la actualización automática en un script individual:
> 
> 1. Abrir el panel de Tampermonkey
> 2. En la pestaña "Userscript instalado", haga clic en editar en "Eliminar Adblock Thing".
> 3. Seleccione la pestaña "Configuración"
> 4. Desmarque la opción "Buscar actualizaciones"
> 
> Luego puedes volver a bajar a 5.3.

Thank you very much bro, is that the only option to "avoid" the error of the second play in that script?
