### ISSUE TITLE
youtube screen stays dark when playing

### ISSUE THREAD

**Issue by ghostii404** [TheRealJoelmatic/RemoveAdblockThing#4786]
currently on version 5.6, all the other versions now prompts youtube to say it detects an ad blocker. 

when it's toggled as on in the tampermonkey utilities page, when a youtube video plays, it lags on the screen saying "no adblocker please" before it blacks out, the screen where the youtube video should be stays black, but the video will play (like the background overlay of the adblock blocker is still there)

the blocker worked until today, usually it just plays a second of the ad before skipping to video, now it stays on a black screen
(note: i'm on opera gx, when i switch tabs and the youtube video automatically turns into a pop out tab of the video, the video itself keeps its graphics, but not when it's in the youtube video's tab itself)

![image_2024-08-04_231438538](https://github.com/user-attachments/assets/cc99ee9a-c168-4091-98a9-113885cd6098)
(the small sound icon on the left side of the tab indicates that the video is playing and has the sound playing, i just thought it would help to attach this here)

**Comment by jesvijonathan** [comment]
fixed in PR : https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/4756, Lets hope the maintainers push the code changes

**Comment by rephlex-ctrl** [comment]
@jesvijonathan i think it works! But no ambient mode on dark theme. And shows me "You Tube" button instead of mini player and theater mode.

**Comment by rephlex-ctrl** [comment]
@jesvijonathan i think it works! But no ambient mode on dark theme. And shows me "You Tube" button instead of mini player and theater mode.
![ytube](https://github.com/user-attachments/assets/5dd47b97-b68f-4628-9c3d-2291e2394e73)

**Comment by rephlex-ctrl** [comment]
@jesvijonathan i think it works! But no ambient mode on dark theme. And shows me "YouTube" button instead of mini player and theater mode.Next button is missing.
![ytube](https://github.com/user-attachments/assets/44cd68c8-4c9c-4ca5-b974-e45d73f2ca93)

**Comment by rephlex-ctrl** [comment]
@jesvijonathan i think it works! But no ambient mode on dark theme. And shows me "YouTube" button instead of mini player and theater mode."Next" button is missing also.
![ytube](https://github.com/user-attachments/assets/06dd5903-9930-4916-806a-a3c87b0276b8)

**Comment by Tiropitaki1** [comment]
5.6 has all videos in black just like @ghostii404. Tried different styles on themes as @jesvijonathan mentioned but no luck. Tested on Chrome and Avast Secure browser. Yes, it was working on Avast up until 25th of June. Joelmatic maintains the code but I'm guessing he's on vacation

**Comment by ghostii404** [comment]
hello!! i wanted to update everyone who commented, a solution (likely temporary) that i found was to stay on 5.6, but reset all cache and re-login into youtube, it fixed the issue for me but so far i’m not sure if it would be detected again ^^

**Comment by Badassious** [comment]
> hello!! i wanted to update everyone who commented, a solution (likely temporary) that i found was to stay on 5.6, but reset all cache and re-login into youtube, it fixed the issue for me but so far i’m not sure if it would be detected again ^^

Thank you, ghostii404, It works for me too. Youtube has been fighting back hard. I hope we can get through this

**Comment by ghostii404** [comment]
forgot to mention, thank you @jesvijonathan regarding the pr #4756 fix! it took me a bit to change it (i'm barely a beginner coder so i didn't quite know how to import the code to tampermonkey, i got it now though 👍 )

the thread will be closed here!! note to future readers, as of august 6th 2024 the pr #4756 fix does work and fix the problem

(and i also hope youtube stop fighting back so aggressively, it's actually getting wildly upsetting)
