### ISSUE TITLE
Black screen returned with a vengeance

### ISSUE THREAD

**Issue by Badassious** [TheRealJoelmatic/RemoveAdblockThing#4788]
Getting black screen while audio still playing even if I sign out. I know this is an older issue yet our previous solution won't work
![black youtube](https://github.com/user-attachments/assets/f6e930b8-751e-4c6e-ba47-102760942192)

**Comment by BeefBaby** [comment]
Mine is stuck on a spinning loading icon with a black screen no audio or playback. It works singed out in a incognito window though.

**Comment by jesvijonathan** [comment]
fixed in PR : https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/4756, Lets hope the maintainers push the code changes
