### ISSUE TITLE
Can't watch age restricted videos

### ISSUE THREAD

**Issue by YeijDG** [TheRealJoelmatic/RemoveAdblockThing#479]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

Version 5.5

**Describe the bug**

Tried to listen to some DJ Screw and the video wouldn't play, telling me it was age-restricted and that I had to watch it on YouTube (even though I already was). When the page opened, I think it reloaded the video player about three times since the player flickered to black two times. Side note: after the first flicker to black, I noticed that the video player resized to the smallest size, and I could no longer switch it to theater mode. Only full screen or normal. Anyways, after the first flicker, it gave me an age-restricted warning, preventing me from watching the video even though I was signed in and watching the video on YouTube.

**Expected behavior**

I expected the page to smoothly load to the video player, skip any ads that were on the video, and for the video to play so that I could listen to some DJ Screw.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

![00 Age-Restricted for some reason](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/73915736/421b1279-b6a1-42cb-bc25-75f82b856964)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Mozilla Firefox
 - Version 126.0.1 (64-bit)

**Additional context**

N/A

**Comment by howTOdoIT2** [comment]
is working with this script https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass  on firefox v126.0.1
