### ISSUE TITLE
video blocked by age restriction

### ISSUE THREAD

**Issue by Omelette-God** [TheRealJoelmatic/RemoveAdblockThing#4790]
**Script version**
version 5.6

**Describe the bug**
some videos are entirely blocked by age restriction

**Screenshots**
![image_2024-08-11_025514185](https://github.com/user-attachments/assets/588de04d-ca42-496b-b6ac-cac4b7e65c5f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera GX

**Comment by Smith873** [comment]
I've experienced the same problem. Not often, maybe once every few days.

OS: Win7
Firefox 115.14.0esr (64 bit)

**Comment by hjgfdszwtfhzwtghs** [comment]
https://github.com/zerodytrash/Simple-YouTube-Age-Restriction-Bypass
