### ISSUE TITLE
mix wont autoplay

### ISSUE THREAD

**Issue by Nevel123** [TheRealJoelmatic/RemoveAdblockThing#4793]
**Script version**
5.6

**Describe the bug**
single songs in a mix wont work, you have to click play after every song.

**Expected behavior**
a mix has to autoplay

**Screenshots**
![image](https://github.com/user-attachments/assets/be52b86b-2a72-4dc4-8be7-f32155ec610d)
**Desktop (please complete the following information):**
 - Browser chrome
 - Version 5.6

**Comment by acaticba** [comment]
same
Chrome Version 129.0.6668.59 (Official Build) (64-bit)
version 5.6
