### ISSUE TITLE
Playlist not autoplaying

### ISSUE THREAD

**Issue by alesxanroad111** [TheRealJoelmatic/RemoveAdblockThing#4794]
**Script version**
5.6

**Describe the bug**
Playlist not autoplaying

**Desktop (please complete the following information):**
 - Desktop microsoft Edge
 - lastest version

**Comment by louloudaki** [comment]
same issue here, windows 11 + chrome. playlist plays only the first video, next video button in player disappears because of this script.

**Comment by dcroal** [comment]
Same issue here. ChromeOS Version 127.0.6533.132 (Official Build) (64-bit)

**Comment by HidalgoIvan** [comment]
+1 Happening to me as well
Chrome Version 128.0.6613.86 (Official Build) (arm64)

**Comment by acaticba** [comment]
Chrome Version 129.0.6668.59 (Official Build) (64-bit)

**Comment by ncku-yee** [comment]
same issue here, Microsoft Edge version. 129.0.2792.52 (64-bit)

**Comment by hejonejo** [comment]
This happend also to me Opera GX
