### ISSUE TITLE
View won't registered on youtube

### ISSUE THREAD

**Issue by pewqp** [TheRealJoelmatic/RemoveAdblockThing#4796]
**Script version**
5.6

**Describe the bug**
Youtube 90% of the time cannot recognize that I watched a video using the script, so it will not be saved in the history and the videos I have already watched continue to be recommended on my home page, this also harms the general daily recommendations

**Expected behavior**
I dont know 😂

**Desktop:**
 - OS: Windows 10
 - Browser Opera GX
 - Version 111.0.5168.90

**Comment by AuZ-ASD** [comment]
history works with older verstion 5.3 but there the ads are not totaly blocked but "fast forward"
