### ISSUE TITLE
Not working properly

### ISSUE THREAD

**Issue by ar0o7** [TheRealJoelmatic/RemoveAdblockThing#4797]
**Script version**
What version is the script on eg 5.6 ect

**Describe the bug**
1. Two sound appear when tab is loaded, it means that in one tan two video played. 
2. When long press spacebar 2x speed function of YouTube is not functioning.

**Expected behavior**
1. tab load only once with one sound.
2. 2x speed function work when spacebar press for long time.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome,]

**Additional context**

**Comment by jongdetim** [comment]
same issue

**Comment by jesvijonathan** [comment]
fixed in PR : https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/4756, Lets hope the maintainers push the code changes
