### ISSUE TITLE
Video disappears like it just blends in witht the website and is not even there 

### ISSUE THREAD

**Issue by Xenophanes99** [TheRealJoelmatic/RemoveAdblockThing#4798]
like it just blends in witht the website and is not even there 
![image](https://github.com/user-attachments/assets/08030efc-3871-44be-8db3-9e1ddeac00f1)

**Comment by CyberKaze** [comment]
Maybe at the same time u have two ADblockers on? I had same issue until i noticed i had another ADblocker on. Maybe Error comes from what.

**Comment by jesvijonathan** [comment]
fixed in PR : https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/4756, Lets hope the maintainers push the code changes

**Comment by jesvijonathan** [comment]
fixed in PR : https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/4756, Lets hope the maintainers push the code changes
