### ISSUE TITLE
no history 

### ISSUE THREAD

**Issue by rbcsxyh** [TheRealJoelmatic/RemoveAdblockThing#4799]
I eliminated the plugins one by one, and found that this plugin should be the one that causes the history of youtube not to be synchronized, and I can't watch the watched video records.
OS: Windows 11
Browser chrome
Version 128.0.6613.114

**Comment by AuZ-ASD** [comment]
history is working with 5.3. but there the adds are only in "fast forward" and not totaly blocked

**Comment by jpichie** [comment]
can confirm this issue since July, would be great to have blocking ads and history tracking working again
