### ISSUE TITLE
Double Audio

### ISSUE THREAD

**Issue by Dessin1** [TheRealJoelmatic/RemoveAdblockThing#480]
**Script version**
5.5

**Describe the bug**
Double audio occurs if the video has a watch history, and in all cases, skipping a section through text causes double audio.

**Expected behavior**
-

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - chrome
 - Version 125.0.6422.114

**Additional context**
-

**Comment by ladymollelle** [comment]
Windows 11, Chrome
I have an issue similar to this: When I click on a video, an ad plays in the background. And when I press K or SPACE bar, either the ad pauses or the video pauses. Not the mention when both of them play at the same time, it drives me absolutely insane because it sounds like 5 tabs playing at once. Very weird!

**Comment by Wayc0des-Land** [comment]
same issue bruh
Windows 10
Chrome Version 125.0.6422.142 (Official Build) (64-bit)
Version 5.5

**Comment by Hirushan86** [comment]
I'm getting the same thing, it's like playing an add in background.

**Comment by gstrange42** [comment]
Youtube shorts are just black video.

**Comment by lodyachmad** [comment]
same issue and double audio please fix it after update

**Comment by LostSkyZ** [comment]
Same issue here, opening any video will play two audios and even if I pause the video there will still be the audio of the video playing in the background

**Comment by Shweepit** [comment]
Same Issue. Two audios over one video. When the video first loads up it's just the two audios and a blurred screen for the video until I refresh. Windows 11 on YouTube, and the browser is Chrome.

**Comment by trunghieu7502** [comment]
Brave browser here, just update to 5.5 and got the same issue.

**Comment by chamdim** [comment]
Same here. At least double audio stops when i pause the playback through youtube controls.
Brave: Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)
OS: Manjaro KDE

**Comment by dxchien** [comment]
Same Issue

**Comment by Shweepit** [comment]
> Youtube shorts are just black video.

The same things happening on my end.

**Comment by ray6an1** [comment]
I am facing a double sound in Firefox on windows 11. After pausing the video, the audio is playing automatically.

**Comment by Ash00182** [comment]
Fix that worked for me:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460#issuecomment-2146297048
