### ISSUE TITLE
Double audio / Echo and Refresh

### ISSUE THREAD

**Issue by obertscloud** [TheRealJoelmatic/RemoveAdblockThing#4802]
**Script version**
5.6

**Describe the bug**
Sometimes when viewing a YTVideo i get a echo or it refreshes the tab and the echo, then i must manually refresh to make the echo go away. if i pause the video the echo plays but at least not doubled

**Expected behavior**
To lead without an echo , 20 % of the time it loads without

**Screenshots**
none
**Desktop (please complete the following information):**
 - OS:  Windows 11
 - Browser Chrome 
 - Version Version 129.0.6668.22 (Official Build) beta (64-bit)

**Additional context**
None

**Comment by jongdetim** [comment]
Exactly the same issue but on Windows 10.

**Comment by Nedrapter** [comment]
Same issue here.

**Comment by XCisCoX** [comment]
i agree it's a problem,

**Comment by matthias-nicoloso** [comment]
Same. Looks like that youtube also plays the video in the embeded version (hence the lack of options on the bottom right corner of the player).
