### ISSUE TITLE
Autoplay and memorizing viewed videos

### ISSUE THREAD

**Issue by n00bKarray** [TheRealJoelmatic/RemoveAdblockThing#4804]
**Script version**
5.6

**Describe the bug**
Autoplay and memorizing old viewed videos

**Additional context**
Is there any workaround or fix to have the autoplay videos again? The ads are completely gone, but Autoplay is no longer available.  and YouTube is not memorizing anymore when I view a video so I don't open it again in all my subscribed channels

**Comment by Newtoneiro** [comment]
Seems like the autoplay bug is caused by insertion of an iframe element instead of playing in on regular yt component. I will try to fix that in a PR.
