### ISSUE TITLE
Player does not work with mine private video

### ISSUE THREAD

**Issue by dxchien** [TheRealJoelmatic/RemoveAdblockThing#481]
**Script version**
5.5

**Describe the bug**
Player does not work with mine private video

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/4531494/16fc891b-d8ea-4666-b4d8-22f28f9b42d5)

**Comment by vagman** [comment]
v.5.6 the problem continues.
