### ISSUE TITLE
5.6 Worked but 5.7 is not

### ISSUE THREAD

**Issue by dateno1** [TheRealJoelmatic/RemoveAdblockThing#4814]
**Script version**
5.7

**Describe the bug**
Video always stopped at 01:00 (Endless loading)

**Expected behavior**
5.6 Work well but 5.7 has problem

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Firefox
 - Version 133.0.3

**Additional context**
Rollback version to 5.6 work again

**Comment by mwbreur** [comment]
I just get adds? i'll just use brave then

**Comment by WarpigtheKiller** [comment]
I've no problems with 5.7, it runs as good as 5.3. With 5.6 I had many problems.

**Comment by dateno1** [comment]
> I just get adds? i'll just use brave then

Not single video

Test with multiple videos but same result

**Comment by vec7or-arrow** [comment]
do you have the link for v5.6

**Comment by babelnaut** [comment]
i have this issue with 5.7 on my desktop, but same update works fine on my laptop. who knows.
did not have issue with 5.6 on either
rolling back on desktop for now
thx for txt backup

**Comment by truonghoaitcm** [comment]
Hi, Thanks for this script!
But now it stop working on 2024-12-24

**Comment by dateno1** [comment]
> Hi, Thanks for this script! But now it stop working on 2024-12-24

Work tested today (Now i playing Youtube without ad)
