### ISSUE TITLE
Not Skipping Ads

### ISSUE THREAD

**Issue by lukastrsl** [TheRealJoelmatic/RemoveAdblockThing#4816]
**Script version**
5.7

**Describe the bug**
Whenever an ad starts, it just plays fast-forwarded but in loop and the video does not play until you press the skip button (whether it appears that is)

**Expected behavior**
It should just skip the ad or remove it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 22H2

**Comment by XTREMRUST** [comment]
I'm in the same situation. 

Please fix ♥
