### ISSUE TITLE
Other website not showing video (but sound only)

### ISSUE THREAD

**Issue by UsernameCOCO** [TheRealJoelmatic/RemoveAdblockThing#482]
**Script version**
5.5

**Describe the bug**
 Title is content (sry, i'm korean.. not good at eng) / but, youtube site video watch well.

site check : namu.wiki / arca.live

**Expected behavior**

**Screenshots**

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171764464/36d584d7-fd5f-40c8-8c5d-d583dd881e66)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser chrome 
 - Version 125.0.6422.114 (64 bit)

**Additional context**

Good day, bro :D

**Comment by sonbosun** [comment]
Solution found : Install (or enable) AdGuard and disable this script.
Works perfectly for now.

**Comment by svenko99** [comment]
I have the same problem.

**Comment by dictatorbiden** [comment]
> Solution found : Install (or enable) AdGuard and disable this script. Works perfectly for now.

that is a bad solution to switch to a different software. 

Better solution is to just turn the script off while not on youtube and wait for fix.
