### ISSUE TITLE
YT Audio Bug

### ISSUE THREAD

**Issue by djdaem0n** [TheRealJoelmatic/RemoveAdblockThing#483]
**Script version**
Version 5.5

**Describe the bug**
Sometimes immediately, sometimes after several seconds, a second audio track plays with the video.
The second track is sometimes the audio track for the video that is already playing (doubling effect).
Other times it's the audio for an ad, which is followed by audio for the video already playing.

**Expected behavior**
Removing the Adblock thing without allowing this audio track to occur in the background.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version: 125.0.6422.142

**Additional context**
It should be noted that this bug has been occuring since the 5.4 update and was not addressed with 5.5
Also the video for YT shorts appears to cut out now after a few secs while the audio continues to play.

**Comment by RifqiSkom** [comment]
yuup same problem bro

**Comment by oscariquelme01** [comment]
Same problem here :(

**Comment by Blaazouille** [comment]
Same issue on Firefox.

**Comment by Ash00182** [comment]
Fix that worked for me:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460#issuecomment-2146297048

**Comment by kaynoh** [comment]
I have same problem too.

**Comment by Danforthvill** [comment]
I am having the exact same issue. I always have to refresh the video page a couple of time to play properly. The first attempt without a refresh plays both the audio associated with the main video and the one from ads. When the page is refreshed for the first time, then only the audio for the video plays but it echoes.

**Comment by djdaem0n** [comment]
> Fix that worked for me: [#460 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460#issuecomment-2146297048)

This is a solid temporary fix for sure.
Hopefully we can get a real fix somewhere down the line before YT makes things worse.

**Comment by djdaem0n** [comment]
> This is a solid temporary fix for sure. Hopefully we can get a real fix somewhere down the line before YT makes things worse.

It appears YT is catching up to this version and i'm getting the block screen, but only for the first ads. One or two refreshes and an ad free version will start, and the mid roll ads work fine. But we're definitely going to need a working fix for this soon.
