### ISSUE TITLE
bug in youtube

### ISSUE THREAD

**Issue by frayrr** [TheRealJoelmatic/RemoveAdblockThing#488]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**
When I activate this script and play the video on YouTube, I get two issues.
1. In the shorts, instead of the video, only a screen filled with black comes out.
2. In a typical video, the advertisement is partial (about three to five seconds) and the video appears. Sometimes the advertisement doesn't appear. In fact, that's not a problem. That's how much you can afford. The real problem is that there are two audio clips. One is the sound when the advertisement is removed normally, and the other is the sound of the video after a short advertisement. Sometimes one sound comes out first without the sound of an advertisement, followed by the same sound after a while. It's like a spinning song (canon, for example). You might pause the video and suggest a way to timing the two audio. I actually tried it. But to no avail.
I desperately hope these issues will be resolved. Only you can save my life. I look forward to your update.
All of these sentences have been translated. I hope you understand.

**Expected behavior**
I desperately hope these issues will be resolved. Only you can save my life. I look forward to your update.
All of these sentences have been translated. I hope you understand.

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by LarsK81** [comment]
Same here, the sound is actually playing, but I haven´t started the video yet. Basically, I have a still image, but hear the advertisement first, and then the sound of the video, without the video actually playing. Or I also have double the sound overlapping, the sound of the ad and the sound of the video. I can stop the sound only by reloading.
