### ISSUE TITLE
✔v5.5 still has many problems

### ISSUE THREAD

**Issue by kschoi2** [TheRealJoelmatic/RemoveAdblockThing#489]
✨ A critical bug
v5.5 still has many problems
1.Sometimes it works normally
2. In some cases, the screen does not appear at all.
3. There are cases where sounds are duplicated.

So, I first replace it with v5.3.

**Desktop (please complete the following information):**
 - OS: [windows 10]
 - Browser [chrome]
 - Version [22H2]

**Additional context**

**Comment by LarsK81** [comment]
Same here:


    OS: [MacOS Sonoma 14.5 ]
    Browser [Firefox]

**Comment by errfiles** [comment]
Same:
```
OS: [linux 6.9.2-1-MANJARO]
Browser: [Firefox]
```

**Comment by gmdevz** [comment]
Same:
```
OS: [Windows11]
Browser: [Min]
```
