### ISSUE TITLE
random you tube video audio 

### ISSUE THREAD

**Issue by Thetonypm** [TheRealJoelmatic/RemoveAdblockThing#491]
**Script version**
v4.0

**Describe the bug**
I click to watch a video, but in addition to the video I'm watching i also get audio from a random you tube video.

**Expected behavior**
To skip the ad that plays before a video without any other issues

**Comment by Hagave** [comment]
There's some video playing in the background. I noticed the YouTube shorts aren't working too. I click and start playing, but the shorts get a black screen.
