### ISSUE TITLE
Ad audio still plays over video

### ISSUE THREAD

**Issue by littlegeckko** [TheRealJoelmatic/RemoveAdblockThing#492]
version 5.5
The audio for the ad is still playing over the video even though there is no ad video playing
No ad video or audio should be playing (hopefully)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Windows 10

It sometimes corrects itself after refreshing the page

**Comment by survivalizeed** [comment]
same here
