### ISSUE TITLE
Newest version dosen't work    :0 (Also audio dublication FIX) how to fix it ;)

### ISSUE THREAD

**Issue by Cl0ud-ex** [TheRealJoelmatic/RemoveAdblockThing#493]
**Script version**
5.0

**Describe the bug**
So newest version dosen't work - when video is opened at first it tries to play it yt shows an add = blocks it and then opens it like from chrome where you can press the youtube to open it on yt (so that's already annoying) [I attached photo] 
But the worst problem is that when you play the video it starts another one in bg and even if you pause the video audio keeps playing

**Expected behavior**
It should work like it should have before the update.

**Fix**
Go to all realeses, find the 3.8 and downgrade ;D (it fixes the problem)
 
**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171823824/f07d248a-626d-4ca7-bc91-c0b3e750817b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 125.0.6422.142 (Official Build) (64-bit)     [Chrome version]

**Additional context**
Annoying but fixable by downgrading

**Comment by Scott16546** [comment]
disabling it works too

**Comment by Cl0ud-ex** [comment]
> disabling it works too

but then u get ads >_<

**Comment by Rubickevich** [comment]
Thanks, that helped! Now the question is: if youtube can't detect the v3.8 adblocker anyway and it was blocking the ads perfectly fine, why implement changes and ruin it?

**Comment by Cl0ud-ex** [comment]
> Thanks, that helped! Now the question is: if youtube can't detect the v3.8 adblocker anyway and it was blocking the ads perfectly fine, why implement changes and ruin it?

Idk, that's fir developers to answer, changelog said that they were fixing the ad blocker, but i suppose they broke it

**Comment by punctdan** [comment]
It's funny but you can bypass it in Opera. Youu go to a new tab when the audio is doubled. Then there is a smaller video screen that appears. You can pause that one and watch the original one without an issue.
