### ISSUE TITLE
Youtube shorts novideo after some seconds

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [TheRealJoelmatic/RemoveAdblockThing#494]
**Script version**
5.5

**Describe the bug**
Some secs after playing an short in youtube the video shut down, keeping only a black screen instead with audio running.

**Expected behavior**
Play any shorts and video flow without problems.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Microsoft Edge
 - Version 125.0.2535.85

**Comment by XTREMRUST** [comment]
+1

**Comment by Arnav-png** [comment]
+2

**Comment by wakmail** [comment]
change @match to youtube.com/watch?v=*

**Comment by Ameer-Jamal** [comment]
Put up a PR to fix this @wakmail @Arnav-png @XTREMRUST @M4rQu1Nh0S #505 help review and merge, its just cuz its a clear all players shouldnt apply to shorts

**Comment by M4rQu1Nh0S** [comment]
> change @match to youtube.com/watch?v=*

@wakmail suggestion fixed the issue.
