### ISSUE TITLE
 Firefox has double playback on the official YouTube site (not in embedds)

### ISSUE THREAD

**Issue by RandomAccountWithRandomUser** [TheRealJoelmatic/RemoveAdblockThing#496]
**Script version**
on the extension version 5.5 (and 5.4) this issue occurs:

**The bug**
1:The player now always opens as if it's an embedded page even on the official YouTube site
2:The default player seems to still be on as after a few seconds it plays again (refreshing fixes this)
3:Ad blocking still works perfectly so there's that

**Expected behavior**
It to open with default [YouTube.com ](youtube.com) video player and not have the video playing double

**Screenshots**
It's just the embedded video player instead of the usual player, for the rest it's the same

**Desktop:**
 - OS: Linux
 - Browser Firefox

**Additional context**
issues started appearing in the first few v5s however I'm only confident about 5.5 and 5.4

**Comment by GaryParkin** [comment]
Yes, I came here to report this too.

**Comment by ZeroNullID** [comment]
This is also occurring on opera gx, win11

**Comment by 1396837342** [comment]
一样

**Comment by StoneMoney** [comment]
Temporary fix, disable the script and mute your youtube player, then re-enable the script. You'll still have double videos playing but the one that gets overwritten won't be playing audio

**Comment by RandomAccountWithRandomUser** [comment]
> Temporary fix, disable the script and mute your youtube player, then re-enable the script. You'll still have double videos playing but the one that gets overwritten won't be playing audio

omg your a genius
