### ISSUE TITLE
After problems with V5.5, I reinstalled V3.8 and everything works without any problems.

### ISSUE THREAD

**Issue by MGPelec** [TheRealJoelmatic/RemoveAdblockThing#497]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Opius134** [comment]
Just pinging here to second my findings here. 3.8 seems to _just work._

**Comment by drnovaa** [comment]
how do u revert back to 3.8? newbie here

**Comment by Arijit1000** [comment]
@MGPelec @Opius134 Where can I find the script of V3.8?

**Comment by liupinero** [comment]
[https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases](url)

**Comment by c22dev** [comment]
You can find the script of 3.8 right here:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js

To disable updates, you can edit the JS and change the following:

From this
```javascript
const updateCheck = true;
```

To this
```javascript
const updateCheck = false;
```

You could edit this either in your Userscripts extension text editor (if it has one) or in anything like TextEdit or Notepad.

If you have some issues editing the file, use the edited version from my gist here:

https://gist.githubusercontent.com/c22dev/5db395d9ce177ab36a00a931e6a02087/raw/youtubeRemoveAdblockThing3.8.user.js

**Comment by drnovaa** [comment]
@c22dev 

thanks a bunch man. that worked great. Duno why 3.8 script download is so hard to find. I looked everywhere lol

**Comment by TheEngiNerd70** [comment]
I also downgraded to 3.8 and it seems more stable than 5.5.  I was hearing the audio from the ad playing in the background of the video.  I would have to reload the video a couple of times to get it to play without the ads.  It would skip the ads in the middle of videos fine; it was just at the beginning of the video I saw all the issues.

**Comment by GroggyOtter** [comment]
Why 3.8...?
5.3 works fine.
I posted a guide on downgrading to it almost 3 days ago...

https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460

**Comment by Mendax1989** [comment]
> Why 3.8...? 5.3 works fine. I posted a guide on downgrading to it almost 3 days ago...
> 
> [❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions] #460](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)

Doesn't work, remove ad block message appears.

**Comment by GroggyOtter** [comment]
> > Why 3.8...? 5.3 works fine. I posted a guide on downgrading to it almost 3 days ago...
> > [❗Temp Fix To Current v5.4/v5.5 problem❗ - Downgrade to v5.3 [Text and video instructions] #460](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/460)
> 
> Doesn't work, remove ad block message appears.

It does work.  
I've been using it since 5.4 was released and haven't seen a single ad.  

The problem you're describing has happened with multiple other versions of RAT, even before 5.0 came out. I've experienced them, and it usually happens after a Chrome update.  
The problem goes away quickly.

Others have reported the same thing.

**Comment by TheEngiNerd70** [comment]
All,

If/when you manually change versions of RAT, you MUST restart your browser to get the changes to take effect.  I have done this with both 3.8 and 5.3 downgrades (@GroggyOtter Thanks for the instructions!! 👍 ), I see no more ads with YT for both versions.  

It looks like for 5.3 it fast forwards through the ads; with 3.8 it seems to just skip them.  I wonder if the ads that are fast-forwarded, does the content creator get credit for the ad being watched?  If they can get credit for the ad AND I don't have to watch it, for me, it's a win-win! 😃

**Comment by c22dev** [comment]
Yeah, even normal script is broken for me…On 6 Jun 2024, at 14:57, Cl0ud-ex ***@***.***> wrote:﻿

You can find the script of 3.8 right here: https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js
To disable updates, you can edit the JS and change the following:
From this
const updateCheck = true;
To this
const updateCheck = false;
You could edit this either in your Userscripts extension text editor (if it has one) or in anything like TextEdit or Notepad.
If you have some issues editing the file, use the edited version from my gist here:
https://gist.githubusercontent.com/c22dev/5db395d9ce177ab36a00a931e6a02087/raw/youtubeRemoveAdblockThing3.8.user.js

This breaks the ad blocker and get detected (atleast for me)
