### ISSUE TITLE
Embedded videos on funnyjunk are just black sqaures, i can still play them but no video. Problem goes away when script disabled 

### ISSUE THREAD

**Issue by dictatorbiden** [TheRealJoelmatic/RemoveAdblockThing#498]
**Script version**
Latest version as of 5. june 2024

**Describe the bug**
Title
**Expected behavior**
I expect the video to play embedded on funnyjunk. 
**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 latest version of win10 running chrome
**Additional context**
here is a link, in the comment section I couldn't open embedded video 
https://funnyjunk.com/Melodic+honorable+eager/reoxRer/

**Comment by dictatorbiden** [comment]
I also want to add, that i haven't got a youtube warning past 24+ hours with the latest version. 
I know this is a war and moment you push update they push update in 2 hours but just know we love you man. You will forever be welcomed in my house for what you doing dev.

**Comment by muchandr** [comment]
Hmm. I might be getting this on Quora. (Audio plays, but video is a black square) Too early to tell though.

**Comment by Smith873** [comment]
Same problem with embedded Youtube videos on Firefox v115.11.0esr, Win7.
