### ISSUE TITLE
Does this work for you?

### ISSUE THREAD

**Issue by PierrunoYT** [TheRealJoelmatic/RemoveAdblockThing#50]
// ==UserScript==
// @name         YouTube Ad Block Bypass
// @namespace    Pierruno
// @version      1.0
// @description  Bypass YouTube ad block blocker
// @match        https://www.youtube.com/*
// @grant        none
// ==/UserScript==

// Remove ad block overlay
const removeAdBlockOverlay = () => {
  const adBlockOverlay = document.querySelector('.ytd-popup');
  if (adBlockOverlay) {
    adBlockOverlay.remove();
  }
};

document.addEventListener('DOMContentLoaded', removeAdBlockOverlay);

**Comment by TheRealJoelmatic** [comment]
Well yes, this solution works but there are side effects to it.

- It Removes unrelated popups
- It does not unpause the video
- If YouTube blocks your video player from the 3 video thing you are forced to watch YouTube without an adblocker.

**Comment by PierrunoYT** [comment]
I have the adblocker disabled and it still works. Am I wrong?
