### ISSUE TITLE
Two things, the video sometimes plays two sessions at once, or plays the ad and the video in the same session. 

### ISSUE THREAD

**Issue by tantelman** [TheRealJoelmatic/RemoveAdblockThing#501]
**Script version**
5.5

**Describe the bug**
1. Video plays twice at the same time (audio). When I pause the video, it can still hear the audio playing, and when I hit play, I hear the audio from two different session. 
2. Add plays at the same time as video (I can hear the audio from the ad, and the video/audio of the video I'm trying to watch)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win 11
 - Browser [e.g. chrome, safari] chrome 
 - Version [e.g. 22] Version 121.0.6167.189 (Official Build) (64-bit)

**Comment by tantelman** [comment]
desktop_polymer.js:1462 
        
        
       GET https://googleads.g.doubleclick.net/pagead/id net::ERR_BLOCKED_BY_CLIENT
Mpa @ desktop_polymer.js:1462
Gl @ desktop_polymer.js:1469
(anonymous) @ desktop_polymer.js:6104
mj @ desktop_polymer.js:979
C8a @ desktop_polymer.js:6101
(anonymous) @ desktop_polymer.js:6135
(anonymous) @ desktop_polymer.js:1424
desktop_polymer.js:1462 XHR failed loading: GET "https://googleads.g.doubleclick.net/pagead/id".
Mpa @ desktop_polymer.js:1462
Gl @ desktop_polymer.js:1469
(anonymous) @ desktop_polymer.js:6104
mj @ desktop_polymer.js:979
C8a @ desktop_polymer.js:6101
(anonymous) @ desktop_polymer.js:6135
(anonymous) @ desktop_polymer.js:1424
serviceworker-kevlar-appshell.js:816 Fetch finished loading: GET "https://www.youtube.com/s/desktop/dcce8ad1/cssbin/www-main-desktop-player-skeleton.css".
(anonymous) @ serviceworker-kevlar-appshell.js:816
Promise.then (async)
ho @ serviceworker-kevlar-appshell.js:816
(anonymous) @ serviceworker-kevlar-appshell.js:812
b @ serviceworker-kevlar-appshell.js:4
Promise.then (async)
f @ serviceworker-kevlar-appshell.js:6
(anonymous) @ serviceworker-kevlar-appshell.js:7
ea @ serviceworker-kevlar-appshell.js:6
r @ serviceworker-kevlar-appshell.js:8
fo @ serviceworker-kevlar-appshell.js:812
(anonymous) @ serviceworker-kevlar-appshell.js:835
(anonymous) @ serviceworker-kevlar-appshell.js:7
ea @ serviceworker-kevlar-appshell.js:6
r @ serviceworker-kevlar-appshell.js:8
m @ serviceworker-kevlar-appshell.js:834
base.js:2007 XHR finished loading: POST "https://www.youtube-nocookie.com/api/stats/qoe?fmt=247&afmt=251&cpn=_GkrPveAxSheK4TJ&el=embedded&ns=yt&fexp=v1%2C24004644%2C130666%2C73455%2C230596%2C121055%2C6271%2C26443548%2C7111%2C36343%2C9954%2C1192%2C26496%2C6966%2C2%2C2871%2C3818%2C2007%2C9072%2C29151%2C752%2C315%2C1130%2C9996%2C1103%2C21%2C4241%2C203%2C2487%2C101%2C7396%2C8%2C1503%2C2036%2C503%2C548%2C929%2C492%2C1008%2C4076%2C39%2C55%2C2368%2C713%2C2585%2C2%2C8%2C1357%2C508%2C278%2C4780%2C25%2C26%2C254%2C1133%2C995%2C1377%2C3578&cl=639870113&seq=6&docid=UBkggBf3Qcs&ei=l75gZvWaNLWAir4P34zO4QI&event=streamingstats&plid=AAYaKbQ4_uKrt22F&referrer=https%3A%2F%2Fwww.youtube-nocookie.com%2Fembed%2FUBkggBf3Qcs%3Fautoplay%3D1%26modestbranding%3D1&qclc=ChBfR2tyUHZlQXhTaGVLNFRKEAY&cbr=Chrome&cbrver=121.0.0.0&c=WEB_EMBEDDED_PLAYER&cver=1.20240603.01.00&cplayer=UNIPLAYER&cos=Windows&cosver=10.0&cplatform=DESKTOP&bwe=235.291:3987814,235.292:3987814,240.015:3987814&bat=235.291:1:1,235.292:1:1,240.015:1:1&vis=235.291:3&cmt=235.291:2.546,235.292:2.546,240.015:2.546&bh=235.291:112.485,235.292:112.485,240.015:112.485".
Aqa @ base.js:2007
g.WA @ base.js:2013
Jdb @ base.js:6951
(anonymous) @ base.js:6972
$A.then @ base.js:8952
Qdb @ base.js:6971
g.k.reportStats @ base.js:12880
(anonymous) @ base.js:6976
(anonymous) @ base.js:1972
base.js:2007 XHR finished loading: POST "https://www.youtube.com/api/stats/qoe?fmt=247&afmt=251&cpn=Sl8-vLOj5w40et1O&el=detailpage&ns=yt&fexp=v1%2C24004644%2C2969%2C127697%2C73455%2C230596%2C111097%2C9958%2C6271%2C133212%2C14625955%2C11684381%2C7111%2C21854%2C14489%2C9954%2C1192%2C7913%2C18583%2C4147%2C2819%2C2%2C6689%2C2007%2C9072%2C29152%2C2196%2C5115%2C4881%2C19%2C2%2C1082%2C21%2C4444%2C2488%2C100%2C7396%2C8%2C1503%2C2538%2C1478%2C492%2C1008%2C3795%2C281%2C39%2C55%2C830%2C1538%2C713%2C2585%2C2%2C8%2C1357%2C508%2C278%2C4780%2C25%2C26%2C254%2C314%2C1814%2C1377%2C710%2C2869%2C435&cl=639870113&seq=13&docid=UBkggBf3Qcs&ei=jb5gZtDPGcay2_gPkKSigQU&event=streamingstats&plid=AAYaKbOZ66nzat7N&referrer=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DUBkggBf3Qcs&sdetail=rv%3AUBkggBf3Qcs&sourceid=yw&qclc=ChBTbDgtdkxPajV3NDBldDFPEA0&cbr=Chrome&cbrver=121.0.0.0&c=WEB&cver=2.20240530.02.01&cplayer=UNIPLAYER&cos=Windows&cosver=10.0&cplatform=DESKTOP&bwm=243.704:853412:0.100&bwe=243.704:3280237,243.708:3280237,250.012:3280237&bat=243.704:1:1,243.708:1:1,250.012:1:1&vis=243.704:3&cmt=243.704:235.570,243.708:235.574,250.012:241.878&bh=243.704:116.389,243.708:116.389,250.012:114.461&vps=250.012:PL".
Aqa @ base.js:2007
(anonymous) @ base.js:2013
Jdb @ base.js:6951
(anonymous) @ base.js:6972
(anonymous) @ base.js:8952
Qdb @ base.js:6971
(anonymous) @ base.js:12880
(anonymous) @ base.js:6976
(anonymous) @ base.js:1972

**Comment by tantelman** [comment]
As you can see the api is being called twice for the same Get url.

**Comment by gmdevz** [comment]
I have the same experience.. hope it gets fixed soon

**Comment by kerth5** [comment]
I have same problem - Macos Sonoma 14.4.1 and newest Chrome

**Comment by yunionlassalle** [comment]
It happens to me all the time after the last update, i pause the video and stil hear the other instance behing. When the video open the first time you see how the windows refresh and other isntance of the ame video opens in background, i can hear it but cannot be closed. I use vivaldi browser. built it Blocking is disabled

**Comment by tantelman** [comment]
Confirmed that it is now worked as expected!
