### ISSUE TITLE
Black Screen and Duplicated sound! WTF V 5.5 Hotgrabgeshit Edition

### ISSUE THREAD

**Issue by imbader** [TheRealJoelmatic/RemoveAdblockThing#503]
**Script version**
5.5 Hotgrabgeshit Edition
**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by karlosculo** [comment]
i have the same issue

**Comment by Ameer-Jamal** [comment]
Have a pull request up to fix it on shorts it has to do with the clearAllPlayers function PR #505

**Comment by ZeroCool22** [comment]
Same problem, FireFox.
