### ISSUE TITLE
Guys, Ver. 3.8 works! Downgrade to 3.8. 

### ISSUE THREAD

**Issue by Danforthvill** [TheRealJoelmatic/RemoveAdblockThing#504]
As suggested by another thread, I downgrade to 3.8 from 5.5 and no more YT's annoying message about adblock or weird sound issues. Please downgraded to 3.8. The link to 3.8 is provided in one of the threads below this one. Hope this helps!

**Comment by Tetanki-HUN** [comment]
cant you just, send the link maybe insteaf of sending us out on a hide and seek mission?-

**Comment by Ameer-Jamal** [comment]
> cant you just ... send the link maybe? Instead of sending us out on a hide and seek mission?-

https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.8

**Comment by Tetanki-HUN** [comment]
your a goat man :D 

thank you and i really hope you can find a fix for the bugs which is happening in 5.5 ^^;
remember, dont rush it!! you already made so much for us with just creating this in the first place and keep developing it :)

**Comment by Ameer-Jamal** [comment]
> your a goat man :D
> 
> thank you and i really hope you can find a fix for the bugs which is happening in 5.5 ^^; remember, dont rush it!! you already made so much for us with just creating this in the first place and keep developing it :)



> your a goat man :D
> 
> thank you and i really hope you can find a fix for the bugs which is happening in 5.5 ^^; remember, dont rush it!! you already made so much for us with just creating this in the first place and keep developing it :)

I am not the orignal owner of this script, I am putting up PR's tho to try to solve some issues, just another open source member, but thank you!

**Comment by Smith873** [comment]
> > cant you just ... send the link maybe? Instead of sending us out on a hide and seek mission?-
> 
> https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js
> 
> REF: https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.8

Thanks. That worked.
I'd guess is that Youtube is chasing the script as it changes. Youtube has made a change that messes up v5.5 of the script, but the change also happens to undo previous YouTube attempts to disable the script.

**Comment by mokaka231** [comment]
so clean!!!!!!!!! so cool!!!!!!! TY!!!

**Comment by loczippo** [comment]
not useful. I downgrade to 3.8 and welcome ads back to me again

**Comment by cminglap** [comment]
It works! Thanks mate

**Comment by RikuZonex** [comment]
version 3.8 is being recognized by youtube

**Comment by cminglap** [comment]
> version 3.8 is being recognized by youtube

No, it's working perfectly fine for now.

**Comment by IvanLauLinTiong** [comment]
Thanks, it's working (for now).

**Comment by Danforthvill** [comment]
Ver. 3.8 still works for me perfectly without any issues. My region is set to Canada. Hope this helps. I guess we'll have to wait until Ver. 5.6 solves all the problems. Thanks!

**Comment by Smith873** [comment]
> Ver. 3.8 still works for me perfectly without any issues. My region is set to Canada. Hope this helps. I guess we'll have to wait until Ver. 5.6 solves all the problems. Thanks!

I'm actually in Canada and the YT adblocker screen sometimes appears. If you refresh the screen several times, the adblocker page goes away.

I went back to v3.8 yesterday and it worked perfectly until now.
