### ISSUE TITLE
Ye Same thing here doubled vid, yt short & multiple other yt fonction not working

### ISSUE THREAD

**Issue by ShadOmega** [TheRealJoelmatic/RemoveAdblockThing#506]
Issues i noticed with the new YT version :
- video playing in 2 different instance ( one visible & another one behind ) one is affected by clicking on the video directly & the other one can be interacted with when clicking anywhere else & using keys (space bar arrows etc ... ) also time stamps in description affect the "hidden" video
- Yt shorts will only display a black screen but audio will still play
- not sure if it's related to the script but live / vod's chat take a while to load

**Comment by crcpflac** [comment]
Two videos are playing simultaneously, in one video the ad is getting skipped but in the one which is running in the background the ad keeps playing continuously and if I am playing any video then I don't know why two videos are playing simultaneously
