### ISSUE TITLE
No ads shown but the ads audio play from background together with audio from the video

### ISSUE THREAD

**Issue by fndrsm** [TheRealJoelmatic/RemoveAdblockThing#507]
**Script version**
v5.5

**Describe the bug**
As title said, this morning i was trying to watch youtube, but when i played the video. Other audio came out of nowhere so loud, i thoght it was autoplay video from other tabs, but after i closed all the other tabs, the audio still playing. I dont recognized what audio is that. So i just pause the audio with keyboard media shortcut, and the audio is stopped.

After playing other youtube video, it keeps repeating. And at some point i realized that was ads audio (Ads from brand that i recognized).  No ads shown but the ads audio play from background together with audio from the video. The youtube video keep running smoothly, but also the ads audio only (full length ads, audio wont stop).

Honestly i dont know which side is wrong, this script or my adguard extension or youtube is broken again. Because they change the layout little bit again, with "More videos" pop up when pausing video and "Copy link" button on the top-right corner.

**Expected behavior**
Ads should be skipped or not shown, both video and audio.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/48046968/fdc8fe51-920e-4378-a436-e5e9700fb35f)

> Note : i cant show the ads because the only the ads shown was the audio it self, playing together along side the youtube video.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Firefox 
 - Version 125.0.3 (32-bit)

**Additional context**

**Comment by pllop330792** [comment]
I had this problem too and thought it was an extension conflict, so I deleted all my extensions and tried using a different browser, but the same thing kept happening.

Now I downgraded from 5.5 to 5.0 and since then the 5.0 version is working fine.

**Comment by fndrsm** [comment]
@pllop330792 @nitemare13 

I used #504 this workaround. Use v3.8 even tho its still shows Blocked Pop Up, but after refreshing the page 2-3 times the popup will disappeared. I'll try to use v5.0 as @pllop330792 said. But @nitemare13 you can try use v3.8
