### ISSUE TITLE
Request for version 5.6 identical to version 3.8

### ISSUE THREAD

**Issue by XTREMRUST** [TheRealJoelmatic/RemoveAdblockThing#508]
**Script version**
5.5

**Describe the bug**
Problems blocking and doubling videos

**Expected behavior**
The old version 3.8 is working. 
So as not to miss out on the next update, we need to keep this wonderful program always up to date.
To do this, you'll need to create a version 5.6 identical to 3.8.

**Desktop**
 - OS: W10
 - Browser: Chrome
 - Version: last version

**Additional context**
Thanks for all your help in deleting those pesky ads!

**Comment by RikuZonex** [comment]
version 3.8 is being recognized by youtube

**Comment by MGPelec** [comment]
Everything still works fine on my Win7 computer.
I'm not against ads, I would like to click away a few ads, but not the way YT is doing it now.

**Comment by MGPelec** [comment]
> Win7? Oof.

Yes, Win7 pc for programming µcontrollers, I have also Win8.1, W10 laptops, but I prefer to work on my win7 pc  ;)
