### ISSUE TITLE
Double Audio on everyvideo I play

### ISSUE THREAD

**Issue by Tizio4** [TheRealJoelmatic/RemoveAdblockThing#510]
**Script version : latest

**Describe the bug**
Everytime I open a new video two audios are playing simultaneously, the ad is getting skipped but I have 2 audio in the background. Quite chaotic. If I resfresh the single page then everything work.

**Comment by PaulWU1996** [comment]
same here

**Comment by OneProblemAtATime** [comment]
I have this issue as well. It is occurring for me in Edge and Chrome. Sometimes there is ad audio and other times there is a duplicate audio of the video playing. Even when I refresh it continues to occur. I have to refresh 5-10 times to get a single audio.

**Comment by PaulWU1996** [comment]
My solution is to downgrade to version 5.3; it works well now. Hope it helps some.

**Comment by Sh1KaD0Ta** [comment]
> My solution is to downgrade to version 5.3; it works well now. Hope it helps some.

How did you manage to downgrade it ? 
I'm also having issues with double audio, some videos have ads and goes into a refresh loop trying to make the video without ads and forces the double audio again, so how did  you downgrade?

**Comment by PaulWU1996** [comment]
u can search v5.3, and someone forks the original code. u can replace it directly.

**Comment by ISLjam** [comment]
Same issue here.  Delayed double audio playing in background when a single video is played. Sometimes refreshing fixes. Other times the double audio just loops continuously. Sometimes ad audio plays in background with no option to close it.
