### ISSUE TITLE
Double audio, and no video on reels (Firefox only, in Chrome its works perfect) have a temporary solution. See the below comments

### ISSUE THREAD

**Issue by binurawidanagama** [TheRealJoelmatic/RemoveAdblockThing#512]
**Script version**
5.5

**Describe the bug**
When I click on the YouTube video sometimes I hear the audio of the ad along with the audio of the video even though the video is started, sometimes I hear double the audio of the video I'm playing, only in the Firefox browser. Ad blocker is disabled.
+
Only audio is playing in reels, visual is not available. (only in Firefox browser)

**Expected behavior**
Play audio without an issue in normal videos.
Play reels with visuals

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/49783200/eac282ba-63cc-4bb2-af9d-496eace78dfc)

**Desktop (please complete the following information):**
 - OS: Windows 10 latest update
 - Browser Firefox
 - Version 126.0.1 (latest)

**Additional context**

**Comment by olblackeyes** [comment]
for me, it doesnt work even in Chrome

**Comment by Mailootje** [comment]
Same issue in chrome. Not always. I once kept refreshing and it went away.
But I watched the video went to a other video and the same issue happened again

**Comment by binurawidanagama** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150654219
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150758838
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2152530753

**Comment by binurawidanagama** [comment]
For me 5.5 worked fine in chrome. But apparently lots of people got the issue in chrome and edge as well. I only checked couple of times in chrome coz i mainly use firefox

**Comment by olblackeyes** [comment]
> Solution - credits to the fellow memeber who found it
> 
> [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150654219) [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150758838) [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2152530753)

I just tried it and it worked! thx

**Comment by Mailootje** [comment]
> Solution - credits to the fellow memeber who found it
> 
> [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150654219) [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150758838) [#497 (comment)](https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2152530753)

Yep, this works indeed! :)

**Comment by Mailootje** [comment]
Well.... soon this probably wont work anymore. Youtube want to implement ads into the video it self.
