### ISSUE TITLE
Double audio, can't skip videos

### ISSUE THREAD

**Issue by theAmbor** [TheRealJoelmatic/RemoveAdblockThing#513]
When I'm listening to a music mix, the skip buttons just disappear. Not only that, but when the songs/videos are over, the next doesn't play automatically.

**Comment by Mailootje** [comment]
Try this:

This user found a solution:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150654219

Just go back to the older version.

Click this link:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js

Click downgrade.

Edit the script and change this:
From this

```js
const updateCheck = true;
```

To this

```js
const updateCheck = false;
```

**Comment by zMantleS** [comment]
I get this also on the latest version, but I press the spacebar and it stops the underlying advertisement from playing, whilst the original video carries on.
