### ISSUE TITLE
Playback on other websites has been disabled by the video owner

### ISSUE THREAD

**Issue by Rooobertas** [TheRealJoelmatic/RemoveAdblockThing#514]
**Script version**
5.5

**Describe the bug**
On some videos a message is displayed: Playback on other websites has been disabled by the video owner

**Expected behavior**
Click on the video and the playback is blocked, disabling the script and reloading the page fixes the issue

**Screenshots**
This video causes the issue
https://www.youtube.com/watch?v=H0fNB4s-dhg

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Mozilla
 - Version 126.0.1 (64-bit)

**Additional context**

**Comment by Mailootje** [comment]
Yep same issue for chrome and windows 11.

**Comment by edmund119** [comment]
I also encountered the same problem
