### ISSUE TITLE
Shorts are blank screen

### ISSUE THREAD

**Issue by Alw04j** [TheRealJoelmatic/RemoveAdblockThing#515]
Version: 5.5

YouTube Shorts are just blank screen, but audio is still available.

The short should play as it is.

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/149885455/69e8d788-ee0c-4b9c-b05f-92bc53998740)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/149885455/c83ad55a-eab1-4a16-8363-60c768ee6daf)

 OS: Windows 11 23H2 
 Edge Version 125.0.2535.85 (Official build) (64-bit)

**Comment by Mailootje** [comment]
You can give this a try:

This user found a solution:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/497#issuecomment-2150654219

Just go back to the older version.

Click this link:
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js

Click downgrade.

Edit the script and change this:
From this

```js
const updateCheck = true;
```

To this

```js
const updateCheck = false;
```
