### ISSUE TITLE
work with 3.8 + remove check for updates popups 

### ISSUE THREAD

**Issue by Bangsart13** [TheRealJoelmatic/RemoveAdblockThing#516]
Hey guys, i've tried the 3.8 version and trying to remove the "check for updates" popups script
and i think it worked for me no more adblock alert again after refreshed the adblock alert
try this :  
https://gist.github.com/Bangsart13/7c41df0aa0890400efc9d128aa719edd

**Comment by statchamber** [comment]
thank you 🙏
