### ISSUE TITLE
Delayed duplicate video Audio in background. Ad audio playing in background over the top of video audio, but no option to close ad. 

### ISSUE THREAD

**Issue by ISLjam** [TheRealJoelmatic/RemoveAdblockThing#517]
**Script version**
5.5

**Describe the bug**
When I play a YT video, there is a delayed, duplicate audio playing in the background of a single video. But no option to close it. After refresh, ad audio plays in background over the top of video and no option to close it.

Chrome
Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by GrooveHacker** [comment]
I'm having this same issue.

**Comment by cclin0302** [comment]
I think the ad sound is still play in the background and the video is not on the same page.

**Comment by JaggedCiprian** [comment]
same bug

**Comment by Czesio845** [comment]
same issue

**Comment by cclin0302** [comment]
Same situation.....I have to back to the previous 5.0 verision https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by Tibbs1cat** [comment]
Same here unfortunately, blasted YouTube!!

**Comment by Alikhan247** [comment]
Same issue. YouTube at it again.

**Comment by RGM179** [comment]
When I come across this bug, I hit F5 to refresh and then the video plays normally without the ad audio over top. Not sure if it matters, but I am also using uBlock Origin along with the recommended settings from the official uBlock Origin subreddit to stop youtube ads as well. Yes, I'm aware that the link recommends not using multiple blockers, but it generally works for me.

https://www.reddit.com/r/uBlockOrigin/comments/1atwzem/youtube_detection_ads_breakages_2024_02_18_ubo/

**Comment by V01D-NULL** [comment]
same issue here. It's usually fixed with a refresh or two

**Comment by yossarian162** [comment]
i have the same problem.

**Comment by alfrederique** [comment]
Same issue here :(

**Comment by jazzhbk** [comment]
use [cclin0302]'s link to downgrade to 5.0 version...work like charm ..life saver ..thanks to [cclin0302]

**Comment by ISLjam** [comment]
> Same situation.....I have to back to the previous 5.0 verision https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases Version 125.0.6422.142 (Official Build) (64-bit)

Version 5 doesn't really work. Comes up with YT ad blocker warning. Sometimes it works after several refreshes, but is still very buggy. At least on Chrome.
