### ISSUE TITLE
3.8 is recognized by YT: The annoying message about ad-block appears again

### ISSUE THREAD

**Issue by Danforthvill** [TheRealJoelmatic/RemoveAdblockThing#519]
I started seeing the annoying message about ad-block again with 3.8 installed. But, I keep refreshing the page until I don't see the message. Guess I'll have to wait for Ver. 5.6.

**Comment by Tetanki-HUN** [comment]
yup sadly it is like that

**Comment by TheLime1** [comment]
for me it still act like v5.5 , do i need to remove cach or what ?

**Comment by Willolito** [comment]
Yah. It was working perfectly yestarday. Sad :,)

**Comment by Smith873** [comment]
Yes, same here. Win7, FF115.11.0esr, script v3.8.
