### ISSUE TITLE
Scroll bar in YouTube full screen

### ISSUE THREAD

**Issue by leonkennedyrookie** [TheRealJoelmatic/RemoveAdblockThing#52]
The scroll bar is still there when in full screen 
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/148483124/bed88f0a-b4d7-439c-82b4-3bd97cd60d0a)

**Comment by DanielDuesentrieb257** [comment]
For me its working to remove Line 89 which says:
`            bodyStyle.setProperty('overflow-y', 'scroll', 'important');`

**Comment by Qwanderin** [comment]
> For me its working to remove Line 89 which says: ` bodyStyle.setProperty('overflow-y', 'scroll', 'important');`

i tried this and it only made the snapping more noticeable
