### ISSUE TITLE
Video title appears on the top almost like it's in fullscreen

### ISSUE THREAD

**Issue by hazmatguy88778** [TheRealJoelmatic/RemoveAdblockThing#520]
**Script version**
5.5

**Describe the bug**
The video title seems to appear on the top of the video like it would be in fullscreen, but this interferes with certain keys, such as fast-forwarding and it will not work unless you hover your mouse over the video which can be really annoying at times.

**Expected behavior**
Expected to play out like any other video without the annoying keys being ignored if the mouse is not hovering over the video.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/134218867/740809ba-e6da-4be0-bcb6-6666be80e76b)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/134218867/2e2717b3-7388-4488-abce-c206a7e7ac3f)
To clarify, the top screenshot is with the adblocking script and the bottom screenshot is without the adblocking script to signify the difference.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro latest
 - Browser Opera GX
 - Version 109.0.5

**Additional context**
Also, the adblocker is still detected by youtube.

**Comment by GrooveHacker** [comment]
I think that's because this newer version of the script puts the embedded version on top to get around the adblocker warning. Just have to wait until the next update, I guess.
