### ISSUE TITLE
Age-Restricted videos are unwatchable

### ISSUE THREAD

**Issue by yossarian162** [TheRealJoelmatic/RemoveAdblockThing#521]
**Script version**
5.5

**Describe the bug**
A screen pops up telling me that age-restricted videos are only watchable on youtube. clicking "watch on youtube" opens another tab which also does not let you watch the video.

**Screenshots**
![bug report screenshot](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/171994103/b3903328-07d2-4a62-94ad-b645bfe776ef)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 125.0.6422.142

**Comment by AzureDao** [comment]
Me to

**Comment by Barnacl437** [comment]
seems like this is shown as external web embed rather than built-in YouTube player (probably developer's move), and yeah depending on the uploaders' preferences on videos they might not be played back. I guess just wait for a fix.

**Comment by statchamber** [comment]
https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass
