### ISSUE TITLE
Hearing ads on top of youtube video

### ISSUE THREAD

**Issue by gh0st11111** [TheRealJoelmatic/RemoveAdblockThing#522]
**Script version**
Version 5.5

**Describe the bug**
When I play a video, I hear an ad but the video is also playing. I do not see the ad, but both sounds play at the same time. The issue sometimes resolves itself if I refresh the page once or twice.

**Desktop (please complete the following information):**

Brave: Version 1.66.118 Chromium: 125.0.6422.147 (Official Build) (64-bit)]
OS: Windows 10 Pro, 19045.4412, just updated

**Comment by tito-Saptarshi** [comment]
Same here

**Comment by Bien-ops** [comment]
it's also showing on some channels that all of the content is not viewable

**Comment by AzureDao** [comment]
Me to, it's double the video in 1 tap, the one on top is free ads and good but there's another video, same video on the back somewhere that the ads is not blocked, and some video is black screen and only audio....

**Comment by KamelAhmed01** [comment]
same

**Comment by Cubitus75** [comment]
same
solution i found (for Chrome)  is to pause the video in the audio tab icon on the top right, which will stop the video in the youtube player also, then hit play again in the youtube player.

**Comment by Amulchan** [comment]
Same...last update was good where ads are sped up instead of blocking them..in this update i am getting tha video but ad is also playing in the background..which is kinda annoying

**Comment by hassanelb22** [comment]
same

**Comment by Shoya-Igawa** [comment]
this fixed it for me https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/544#issuecomment-2156076563
