### ISSUE TITLE
3.8 works fine, but has problems

### ISSUE THREAD

**Issue by zzimtong80** [TheRealJoelmatic/RemoveAdblockThing#524]
Advertisements inserted in the middle of a video pass quickly as before. However, the ad at the beginning of the video is still blocked, so I have to press refresh several times.
Since 5.x is currently difficult to use, we recommend version 3.8 as the next best solution despite this problem.

3.8->
https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.8/Youtube-Ad-blocker-Reminder-Remover.user.js

참조: https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.8

**Comment by djdaem0n** [comment]
From the sound of it, there is zero difference between this and how v5.3 is reacting.

**Comment by finkiki** [comment]
What do you mean "works fine but have problems" ?

**Comment by jongdetim** [comment]
Yeah it works better than 5.5, but YT patched something, because up until yesterday, 3.8 worked well. Now it's playing ads or a copy of the audiostream in the background after a delay. Really annoying.

**Comment by kschoi2** [comment]
V3.8 works well, But the ad at the beginning of the video is still blocked, so I have to press refresh two times.
I want to make it better

**Comment by JimBimBum** [comment]
it's playing an embeded video over the original now. doesn't work though and prevents videos that won't allow embedding to play including age restricted videos but you can also toggle for youtube to not allow embedding of your video.
