### ISSUE TITLE
5.5 Ads doesn't play, but the sound of the ad still plays in the background

### ISSUE THREAD

**Issue by William-ZhiZheng** [TheRealJoelmatic/RemoveAdblockThing#525]
**Script version**
5.5

**Describe the bug**
sound of the ads still play

**Expected behavior**
sound of the ads still play

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome, safari

**Comment by Coyley** [comment]
I get this on 5.5 but I'm using Arc (Chromium). The Ad isn't blocked, it's opened up in a new tab in a different space.
