### ISSUE TITLE
when the video starts, double sounds are heard

### ISSUE THREAD

**Issue by Sarunas323** [TheRealJoelmatic/RemoveAdblockThing#526]
Version 5.5

**Comment by toaitoai35** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js

 press "Raw" and then press "reinstall".

**Comment by Sarunas323** [comment]
> https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js
> 
> press "Raw" and then press "reinstall".

working thanks
