### ISSUE TITLE
This is not work working I click a video it's play same time same video one background and one front

### ISSUE THREAD

**Issue by Shoaibbd27** [TheRealJoelmatic/RemoveAdblockThing#528]
This is not work working I click a video it's play same time same video one background and one front

**Comment by KrystalzzZzZ** [comment]
Yes that's occuring to ne as well the plugin is playing youtube videos twice

**Comment by MAN19700** [comment]
just refresh the website, thats what helps me to make it go away.

**Comment by KrystalzzZzZ** [comment]
But it is very annoying ngl can we get the previous version or is it not
working?
