### ISSUE TITLE
audio of video plays twice

### ISSUE THREAD

**Issue by 3dumplings** [TheRealJoelmatic/RemoveAdblockThing#531]
version 5.5

audio of the video plays twice
google, windows

**Comment by 3dumplings** [comment]
changed to version 5.0 seems to be fixed now

**Comment by Drone-Catcher** [comment]
how can i downgrade to 3,4

**Comment by boukhir** [comment]
here's the script of this version (u can find it in the assets of the 3.5 release in this repo), a tampermonkey window should open and u just have to click on downgrade : https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.3/Youtube-Ad-blocker-Reminder-Remover.user.js 

btw, remove the "upgrade notification" of this version u can edit the script using tampermonkey, just remove this part of code : 
if (githubVersion > currentVersion) {
+                    console.log('Remove Adblock Thing: A new version is available. Please update your script.');
+
+                    var result = window.confirm("Remove Adblock Thing: A new version is available. Please update your script.");
+
+                    if (result) {
+                        window.location.replace(scriptUrl);
+                    }
+
+                } else {
+                    console.log('Remove Adblock Thing: You have the latest version of the script.');
+                }

**Comment by Istoleyourfrogs** [comment]
audio plays twice in videos + the YouTube shorts are only black screen with sound

**Comment by gstrange42** [comment]
> here's the script of this version (u can find it in the assets of the 3.5 release in this repo), a tampermonkey window should open and u just have to click on downgrade : https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/download/v3.3/Youtube-Ad-blocker-Reminder-Remover.user.js
> 
> btw, to remove the "upgrade notification" of this version u can edit the script using tampermonkey, just remove this part of code : ` if (githubVersion > currentVersion) { console.log('Remove Adblock Thing: A new version is available. Please update your script.');
> 
> ```
>                 var result = window.confirm("Remove Adblock Thing: A new version is available. Please update your script.");
> 
>                 if (result) {
>                     window.location.replace(scriptUrl);
>                 }
> 
>             } else {
>                 console.log('Remove Adblock Thing: You have the latest version of the script.');
>             }`
> ```

It's okay for normal video but YT shorts are still black
