### ISSUE TITLE
It doesn't function anymore

### ISSUE THREAD

**Issue by AmrSakar** [TheRealJoelmatic/RemoveAdblockThing#533]
**Script version**
5.0

**Describe the bug**
YouTube now detects the script, so It doesn't work anymore.

**Screenshots**
![nz270mnwjmub1](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/172076323/c4e60c06-a76c-4bc8-b0f0-190e224ce049)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Edge
 - Latest Version

**Comment by ZachRK44** [comment]
Script version 
v.5.3
OS: Windows 10 Home
Browser: Edge Version 125.0.2535.85
It works like 30% of the time, but otherwise, I have to reload the page couple of times to make it work.
