### ISSUE TITLE
Version 5.5 missing theatre mode? and double sound

### ISSUE THREAD

**Issue by Solvmane** [TheRealJoelmatic/RemoveAdblockThing#535]
**Script version**
5.5
**Describe the bug**
the theatre mode button is just missing and I have to restart the page several times the restart is because it will stop the add but the sound is still playing over the same video, if I mute the video the add sound keeps playing, occasionally the video basically has double layered sounds. like an extra sound is playing over itself (hopefully I described that right?)  
as well as the "theatre mode" style of the video option is just gone (I think I attached the picture/screen-snip correctly) 

if I turn off the tamper monkey script and refresh page zero of my stated issues occur

**Screenshots**
turned off:
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/99376584/5749361d-6039-491b-840d-0add2ec52f24)
script toggled on:
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/99376584/4abc87d1-cdb6-4d7f-bdc2-efc2574354a2)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome
 - Version: Chrome Version 125.0.6422.142 (Official Build) (64-bit)
 script version 5.5

**Additional context**
thank you!

**Comment by greysc4le** [comment]
I found if I changed line 58 let isVideoPlayerModified to true instead of false it gave me back the regular bar. I'm not any kind of expert though so take this with a grain of salt.

**Comment by riky0701** [comment]
> I found if I changed line 58 let isVideoPlayerModified to true instead of false it gave me back the regular bar. I'm not any kind of expert though so take this with a grain of salt.

but if I change it to true, the video won't play
