### ISSUE TITLE
Try disable line 112 to solve the double sound problem in 5.5

### ISSUE THREAD

**Issue by RayRayGitGit** [TheRealJoelmatic/RemoveAdblockThing#541]
Sounds like video.play can be invoked two times (maximum). I'm not familiar with YouTube's background API, so I don't ensure the problem can be solved, but you may try:

            // Check if the video is paused after removing the popup
            if (!video.paused) return;         
            // UnPause The Video
            //video.play();                             <----put double slash in front of the Line 112

Need Professionals to riddle out the problem for 5.6. Hopes it would help.

Amature
Ray

**Comment by gstrange42** [comment]
It doesn't work for me, and the shorts are still black video

**Comment by ZachRK44** [comment]
It works for me. At least for now. Thank you for this quick fix!!
OS:  Windows 10 Home
Script Version: 5.5
Browser: Edge Version 125.0.2535.92 (Official build) (64-bit)

I used 5.3 but unfortunately, the ad kept repeating at least twice in a very very fast speed. And about 30% chance the youtube detects the ad block. So for me, this fix is a lifesaver.

**Comment by 542104564958469q** [comment]
It works for me. Thank you for this quick fix!
OS: Windows 10 Pro
Script Version: 5.5
Google Chrome : Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by hcarrega** [comment]
it work with my, but now still video promos on videos
