### ISSUE TITLE
ideos are played overlapping 

### ISSUE THREAD

**Issue by RoadGorilla** [TheRealJoelmatic/RemoveAdblockThing#544]
**Script version**
5.5

**Describe the bug**
the sound of the Ad is played while the video is playing.

**Expected behavior**
Please fix this

**Desktop (please complete the following information):**
 - Window 11
 - Firefox

**Additional context**

**Comment by BeefBaby** [comment]
same issue

**Comment by kodomozeza8** [comment]
v5.3 with ublock still work

**Comment by yourmamamyllama** [comment]
same issue here too

**Comment by BeefBaby** [comment]
> same issue

how do you downgrade to 5.3?

**Comment by OakyTree** [comment]
> > same issue
> 
> how do you downgrade to 5.3?

Grab this version of the file, https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js, and copy/paste it into your script manager.

**Comment by ToiYeuTien** [comment]
> > > same issue
> > 
> > 
> > how do you downgrade to 5.3?
> 
> Grab this version of the file, https://github.com/TheRealJoelmatic/RemoveAdblockThing/blob/861272fb6b4aee20cd6b59f281b2034926e174c0/Youtube-Ad-blocker-Reminder-Remover.user.js, and copy/paste it into your script manager.
> 
> If you open the raw file in Github your script manager may offer to handle the downgrade for you.

thank for help !

**Comment by Weezy69** [comment]
same

**Comment by LeoGirl0727** [comment]
If you use AdBlock, then just watch YT videos in Incognito Mode until Tamper fixes the issue.  I have had no problems. I am not positive if Tamper works in Incognito Mode or not, but I am not seeing the extension icon.

**Comment by LeoGirl0727** [comment]
If you use AdBlock, then just watch YT videos in Incognito Mode until Tamper fixes the issue. I have had no problems. I am not positive if Tamper works in Incognito Mode or not, but I am not seeing the extension icon.
