### ISSUE TITLE
Fix it pleaseeeeeeee.................

### ISSUE THREAD

**Issue by DuongEoKay** [TheRealJoelmatic/RemoveAdblockThing#550]
**Script version**
What version is the script on eg 2.9 , 3.1 ect
5.x
**Describe the bug**
duplicate sound of that video (sometime ad)
**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: win11
 - Browser edge

**Additional context**

**Comment by UnknownUser010** [comment]
Same thing, please fix that because it's very annoying.

**Comment by Ridoushka** [comment]
Same here! After the update, I've been experiencing duplicated sound from ads, and also when I rewind or speed up a video!
Pleeaaasseee fix!!!

**Comment by Weezy69** [comment]
same

**Comment by kasem545** [comment]
try downgrade to 3.5 https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.3 it worked for me
