### ISSUE TITLE
No Video on Shorts

### ISSUE THREAD

**Issue by MetalHeadSeven** [TheRealJoelmatic/RemoveAdblockThing#553]
**Script version**
5.5

**Describe the bug**
Playing Shorts there is no Video only Audio
**Expected behavior**
Playing of Video and Audio
**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 125.0.6422.142 (Official Build) (64-bit)

**Additional context**
Also getting duplicate Audio on some full size videos that resolves with reloading.

**Comment by shanmugad** [comment]
I am facing same isssue

**Comment by shivesh96** [comment]
#582 Solved here
