### ISSUE TITLE
Thank you for doing this for us dev! 

### ISSUE THREAD

**Issue by dictatorbiden** [TheRealJoelmatic/RemoveAdblockThing#554]
This might not be the best place to say this but I really thank you for doing this and waging this war with youtube for us. 
I would like to hear more about this struggle from you, would you spare few words about this project with us here? Tell us more about how the war is going, how fast are they patching. I am very interested in hearing your story

**Comment by dictatorbiden** [comment]
I've read about how they patched in less then 2 hours after pushing an update, am keen to hear more of this.

**Comment by VeXLevCtrl** [comment]
you don't have any problem with this update?

**Comment by dictatorbiden** [comment]
Yeah i have the double audio, but I know this man is waging a war with google right now. He pushes an update and they counter-update within ours. He has my respect
