### ISSUE TITLE
Video is no longer technically on YouTube

### ISSUE THREAD

**Issue by Spiderfreak** [TheRealJoelmatic/RemoveAdblockThing#555]
Script version
5.5

Describe the bug
There's a button to force the current video to YouTube now on every video. That also hides the expand view button, and it's a result of the script.

Expected behavior
Not to have that button shown and to instead show (2nd image)

Screenshots
If applicable, add screenshots or a video to help explain your problem.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/47091397/8e63838e-8271-4e59-a93e-4af45e390893)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/47091397/ae9520ac-5dbc-497d-84b2-b1c471454a41)

Desktop (please complete the following information):

OS: Windows 10
Browser: Opera GX
Version LVL5 (core: 109.0.5097.108)
Additional context
Turning off the script fixes this issue but obv the ads then play as a result

**Comment by supersmith2500** [comment]
The script is forcing the site to load a copied player which you find on many sites rather than a main player which blocks the script.

**Comment by Spiderfreak** [comment]
> The script is forcing the site to load a copied player which you find on many sites rather than a main player which blocks the script.

is there a fix or is this the workaround that is being done to try to combat the main issue?

**Comment by Ghos7ted** [comment]
i also have this problem 
is there any fix to it ?
