### ISSUE TITLE
The video starts over and over again. (with video proof)

### ISSUE THREAD

**Issue by itsmetoolala** [TheRealJoelmatic/RemoveAdblockThing#558]
EDIT:
Problem solved (so far) but still using 5.3 coz 5.6 is not yet good at all. (to me)
I've never used Tempermonkey, only "Tweaks for Youtube" which has JS built in where I can paste JS code.
THAT was the problem.
Installed Tempermonkey now and everything runs fine.
Sooo faaaar no problems at all.
DEV's oder MOD's can delete this entire posting. (if neccessary)

....

**Comment by sammyensah** [comment]
can I have the 5.3 version please
