### ISSUE TITLE
Cannot scroll if popup appears (Chrome 117)

### ISSUE THREAD

**Issue by Qwanderin** [TheRealJoelmatic/RemoveAdblockThing#56]
I am running Chrome 117 and whenever the block appears, it removes it but I am no longer able to scroll down the page, it just snaps back to the top of the page.

**Comment by SleepDaemon** [comment]
hi, so I notice before the yt pages loads fully I am able to load but once it has scroll gets locked. My guess is that the anti-adblock doesn't show up till the page is fully loaded. Once it has the script removes the the pop up but doesn't remove the scroll lock.

So most likely you will need to add code to re-enable scrolling or removes lock.
