### ISSUE TITLE
Cant play youtube videos at all now.

### ISSUE THREAD

**Issue by Pinkyo2386** [TheRealJoelmatic/RemoveAdblockThing#560]
**Script version**
5.5

**Describe the bug**
Video tries to start playing but then the video player goes away.

**Expected behavior**
the video to start

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/120321868/5f36bc62-1c9e-44e0-ad9e-aa9eb5d06f25)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version 125.0.2535.92 (Official build) (64-bit)

**Additional context**
Before this I had the issue with videos playing twice.

**Comment by AJIT301** [comment]
Youtube is did a good job for being cancer of this planet. Turned from biggest video platform into shithole. Will never ever spend a cent on this garbage platform anymore. I wish some other companies would step in to counter this monopoly loving google nonsense. World don't belong to you. And people will quickly realise that there is always same good alternatives without this rape with those disguisting ads which I WAS BLOCKING ALL MY LIFE. IT MEANS MORE THAN 15 YEARS IN A ROW. I NEVER WATCHED YOUR ADS AND WILL NEVER WILL!!!!!!!! GET CANCER, GOOGLE
