### ISSUE TITLE
the video runs twice

### ISSUE THREAD

**Issue by sammyensah** [TheRealJoelmatic/RemoveAdblockThing#562]
**Script version**
5.5

**Describe the bug**
Everytime I run a video, it runs twice

**Comment by 6ix9ine4our20wenty** [comment]
same here, if you pause the video quickly it fixes it

**Comment by nibroos** [comment]
i suggest you downgrade the version. im using 4.0 version, no issue yet

**Comment by LeoGirl0727** [comment]
If you use AdBlock, then just watch YT videos in Incognito Mode until Tamper fixes the issue. I have had no problems. I am not positive if Tamper works in Incognito Mode or not, but I am not seeing the extension icon.
