### ISSUE TITLE
Clicking on a video before it loads somehow fixes the double sound issue?

### ISSUE THREAD

**Issue by JustMechas** [TheRealJoelmatic/RemoveAdblockThing#563]
**When I click on a place where the video appears right when I load the page before it's even loaded (only once), it somehow stops the additional invisible video, making the actual video play as normal. In order for it to happen, I have to click quite fast, otherwise it doesn't work. On first glance, it seems that you are clicking on a blank space, but it works somehow.**

I've tested it multiple times on a clean v5.5 version on a chrome-based browser. Tampermonkey version v5.1.1. Not sure if it will work for other people but still typing it regardless in case if it will work for someone. Still, just wanted to share with a temporary solution I've found.

**Comment by LeoGirl0727** [comment]
If you use AdBlock, then just watch YT videos in Incognito Mode until Tamper fixes the issue. I have had no problems. I am not positive if Tamper works in Incognito Mode or not, but I am not seeing the extension icon.
