### ISSUE TITLE
Can't watch videos that have playback disabled on other websites

### ISSUE THREAD

**Issue by InfernalCoding** [TheRealJoelmatic/RemoveAdblockThing#564]

**Comment by supersmith2500** [comment]
You need to be more specfic regarding the issue.

**Comment by InfernalCoding** [comment]
Youtubers have an option to disable you from watching a youtube video on other websites through means such as embedding videos on Google Slides. If a youtuber toggles that setting on for a specific video, having the Adblock script enabled will block you from seeing that particular video.

**Comment by Peryite89** [comment]
Same. I get a message "Video not available. Playback on other websites has been disabled by the video owner. Watch on YouTube"
