### ISSUE TITLE
Cannot watch age-restricted videos due to YouTube forcing users to watch it on their ad-infested video player

### ISSUE THREAD

**Issue by supersmith2500** [TheRealJoelmatic/RemoveAdblockThing#565]
**Script version**
5.5

**Describe the bug**
Since the RemoveAdblockthing is using copied links that we see on websites. Google is NOT ALLOWING users to watch age-restricted videos outside of YouTube and forces them to watch on their instead.

**Expected behavior**
Excepting the video to load

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version N/A

**Additional context**
YouTube has always being punishing their users for months and possibly years now by introducing many worse changes and this is one of them. It's also even worse that on a rare ocassion that copyright holders even force you to watch it on YouTube as well. Good luck fixing this issue.

**Comment by LeoGirl0727** [comment]
If you use AdBlock, then just watch YT videos in Incognito Mode until Tamper fixes the issue. I have had no problems. I am not positive if Tamper works in Incognito Mode or not, but I am not seeing the extension icon.

**Comment by supersmith2500** [comment]
It will just give me an anti ad-block message and force me to sign in. Not worth my time.

**Comment by LeoGirl0727** [comment]
I just leave the browser open after I sign in.  I am an American, but I am living in Spain right now, so I watch YouTube all the time. So maybe it's a better option for those who constantly use YT.
