### ISSUE TITLE
I swear this place has a youtube spy (Not fully a "real" issue just noticing some stuff)

### ISSUE THREAD

**Issue by Tetanki-HUN** [TheRealJoelmatic/RemoveAdblockThing#568]
5.5 and any vers

Idk brothers but everytime someone mentions a version to try out, for some time it works then it gets randomly patched out later
This has happened from 5.5-5.0, 3.8, 3.9, HELL EVEN  2.9 WORKED FOR SOME TIME
Then for some reason all of the same bugs happen with those version just what we experience with 5.5 to this day

**Desktop (please complete the following information):**
 - OS: IOS
 - Browser opera
 - Version latest

I know this isn't really a "real" bug report or anything and for that its my apologies, i know this is getting hard worked on but im i the only who experiences this?? Im i goin crazy?!?? o-O

**Comment by CatPieLeaf** [comment]
i can't say much about the other versions, but 5.4 just had an implementation bug, it has nothing to do with patches... "(5.4) New solution **not ideal atm but it works well**"
i'm using the script with all the changes from the PRs, and it works like a charm
