### ISSUE TITLE
Double audio and other issues

### ISSUE THREAD

**Issue by Dimitris-Klis** [TheRealJoelmatic/RemoveAdblockThing#569]
**Script version:** 5.5

**Describe the bug**
After a recent update to YouTube's interface, double audio plays, almost as if a video is playing on top of another one. Clicking timestamps brings the audio of the invisible video and not the normal one.

Also, YouTube thinks I'm not on YouTube since a little "watch this on YouTube" button pops up. The solution turned out to be disabling this script, indicating that the script is the problem.

I haven't had an anti-adblock message _yet_, which is good but please find a solution for this.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version 125.0.6422.142

**Comment by riky0701** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js
u can use this

**Comment by ramigamalrihawi** [comment]
Thanks! you're great @riky0701

**Comment by Dimitris-Klis** [comment]
That does fix it, although it breaks extensions like YouTube Enhancer
