### ISSUE TITLE
Constant refreshing

### ISSUE THREAD

**Issue by SpringySpring04** [TheRealJoelmatic/RemoveAdblockThing#57]
Constant refreshing when opening YouTube video player in any context (new tab, home page, enlarge mini player, etc.);

The page refreshes repeatedly for on average 30-45 seconds before it stabilizes and begins playing the video. 
If on a playlist or queue, shuffle and loop settings are lost.

I'm using Opera GX (version in Opera GX menu > "Help" > "About Opera" says "LVL5 (core: 102.0.4880.104)").

**Comment by TheRealJoelmatic** [comment]
Is this issue still happening?
