### ISSUE TITLE
Fixed: 5.6 double audio, ads Fixed

### ISSUE THREAD

**Issue by rafathasan** [TheRealJoelmatic/RemoveAdblockThing#570]
To use, click this link below and click update

https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js

thanks to @statchamber

**Comment by CatPieLeaf** [comment]
https://github.com/CatPieLeaf/RemoveAdblockThing/raw/test/Youtube-Ad-blocker-Reminder-Remover.user.js
this one has all changes from the recent PRs.

**Comment by FrozenDragon0** [comment]
Seems to have only worked briefly, dreaded ad blockers not allowed on YouTube message is back with 5.6
