### ISSUE TITLE
Pausing a video opens bar with next (related) videos

### ISSUE THREAD

**Issue by Leonixar** [TheRealJoelmatic/RemoveAdblockThing#572]
I wouldn't expect a script that is supposed to help me block a blocker of adblockers - to do anything other than what it is intended to do. Gradually, and also at once, I have disabled all plugins and scripts in Tampermonkey and the only thing causing this thing is this script from Joelmatic. Simply, when I pause a video, it shows me a panel with other videos on the player (see picture). Is there any way to remove/disable/turn it off? Maybe remove part of the script or just comment it out... o.o

![opera_2024-06-10_00-42-40](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/7763385/a5db907e-df96-48ff-a512-33cdebc3f3c0)

**Comment by CatPieLeaf** [comment]
Unfortunately, this can't be disabled through player parameters
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/149953009/901dd3d5-0a4d-482d-90b5-4389de40bae3)
but i'll push a PR adding `rel=0` anyways
