### ISSUE TITLE
video controls act like its in fullscreen, double audio after skipping ads, max volume after skipping ads, ad audio plays over video, playlist videos no longer autoplay the next one

### ISSUE THREAD

**Issue by SlipDK** [TheRealJoelmatic/RemoveAdblockThing#573]
Most recent version

- when you pause the video it shows popups like "more like this" when it usually shouldn't.
- on occasion after an ad is skipped it will play the video's audio twice, overlapping eachother, this bug can also stack with the max volume bug and be deafening
- about 50% of the time after an ad is skipped it will continue to play the ad's audio over the video you're watching
- if a video in a playlist ends it won't automatically skip to the next video despite me having autoplay on. (it works when i disable the script)

Browser: Chrome

**Comment by ParzivalWolfram** [comment]
https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/546
