### ISSUE TITLE
Duplicate audio fixed, but Ads no longer skipping with 5.6.

### ISSUE THREAD

**Issue by ISLjam** [TheRealJoelmatic/RemoveAdblockThing#576]
5.6

Ads are not skipping, just playing as normal.

Chrome Version 125.0.6422.142 (Official Build) (64-bit)

**Comment by Smith873** [comment]
> 5.6
> 
> Ads are not skipping, just playing as normal.
> 
> Chrome Version 125.0.6422.142 (Official Build) (64-bit)

I've experienced the same problem.

v5.6
Win7
Firefox v115.11.0esr (64-bit

**Comment by kasem545** [comment]
try downgrade to 3.5 https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.3 it worked for me
