### ISSUE TITLE
theater mode notavailable

### ISSUE THREAD

**Issue by Raps0daa** [TheRealJoelmatic/RemoveAdblockThing#577]
Script version 5.5

When activating the script theater mode isnt available

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/172233370/731c54d1-74ee-4c27-b88c-d7d37ea822ce)

![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/172233370/5f85aba3-b8dd-425a-bd2c-728c6614551f)

**Comment by ItsNyQuil** [comment]
You can always just hit "Shift T" to bring it up.

**Comment by Raps0daa** [comment]
> You can always just hit "Shift T" to bring it up.

i get duplicated audio doing that..

**Comment by ItsNyQuil** [comment]
> > You can always just hit "Shift T" to bring it up.
> 
> i get duplicated audio doing that..

I see you are only on 5.5 this issue was fixed in [5.6](https://raw.githubusercontent.com/TheRealJoelmatic/RemoveAdblockThing/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js).
