### ISSUE TITLE
it have another video run on Background sometime, i have to reload page for make it disappear

### ISSUE THREAD

**Issue by r3gas-p** [TheRealJoelmatic/RemoveAdblockThing#579]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Kush3007** [comment]
The Script version is 5.0, and still the error continues in youtube

**Comment by adriansasu** [comment]
The problem still persist

**Comment by kasem545** [comment]
try downgrade to 3.5 https://github.com/TheRealJoelmatic/RemoveAdblockThing/releases/tag/v3.3 it worked for me

**Comment by Phil171** [comment]
Same for me, version 5.5 up to date
Xubuntu 22.04 up to date
Firefox 126.01

**Comment by Euripididdy** [comment]
Same here. Latest version runs the ad and the video at the same time. Sometimes refresh will fix the issue but many times not. Also shorts do not work they just show black/blank video screen.
