### ISSUE TITLE
As of today 20/10 no longer works.

### ISSUE THREAD

**Issue by jongdetim** [TheRealJoelmatic/RemoveAdblockThing#58]
Blocks the ads, but still has to wait for the ad to be over before playing the video. This happens with or without AdBlockPlus.

**Comment by Qwanderin** [comment]
have you tried using other adblockers along with adblockplus? i use catblock, ABP, and ublock

**Comment by Alaunae** [comment]
As of now, the only adblocker that does bypass the youtube restrictions is on chrome and is called : Youtube Adblock By Friendly. 

I have not seen anything else for firefox sadly.. or any other browser.

**Comment by jongdetim** [comment]
> As of now, the only adblocker that does bypass the youtube restrictions is on chrome and is called : Youtube Adblock By Friendly.
> 
> I do use it with this script, and also youtube enhancer. If you do use youtube enhancer, go in your settings and do check if you do not have block adds activated on the extension.
> 
> I have not seen anything else for firefox sadly.. or any other browser.

Doesn't fix it for me.
