### ISSUE TITLE
 Although version 5.6 has fixed the problem of duplicated audio, YouTube cannot automatically change songs

### ISSUE THREAD

**Issue by vutom17** [TheRealJoelmatic/RemoveAdblockThing#580]
**Script version**
5.6

**Describe the bug**
Although version 5.6 has fixed the problem of duplicated audio, YouTube cannot automatically change songs

**Comment by xkid-discord** [comment]
Where is this 5.6 version  ..?

**Comment by Homerpeco** [comment]
still keep the duplicate audio

**Comment by CatPieLeaf** [comment]
Playlists have already been fixed
https://github.com/TheRealJoelmatic/RemoveAdblockThing/pull/571

**Comment by hisbalah** [comment]
I have d same question like wuxs42? Where is the version 5,6??? I have double audio too.
