### ISSUE TITLE
5.6 Works!

### ISSUE THREAD

**Issue by Danforthvill** [TheRealJoelmatic/RemoveAdblockThing#588]
Update to 5.6. I've been using 3.8 but that did not fix the annoying adblock message from Youtube. Now 5.6 works without issues.

**Comment by mokaka231** [comment]
how do i download?? i'd update but 5.5v is last

**Comment by shafwann** [comment]
check pull request

**Comment by mokaka231** [comment]
oh TY!!!

**Comment by fuhraren** [comment]
> check pull request

what does this mean, im new to this

**Comment by shafwann** [comment]
#538 here you go

**Comment by Zukokiko** [comment]
here's a script that prevents the adblock message from appearing:
https://github.com/NullDev/YT-Anti-Anti-Adblock

**Comment by GroggyOtter** [comment]
v5.6 does not work.

The "next" and "previous" video buttons still don't show up.  
And the "autoplay" toggle doesn't appear, either.

Sticking with v5.3 as it's still working perfect.
