### ISSUE TITLE
Most videos are not registered on the youtube history

### ISSUE THREAD

**Issue by ZanEtherial** [TheRealJoelmatic/RemoveAdblockThing#591]
**Script version**
5.5

**Describe the bug**
with the script active, youtube does not register most of the videos watched in the history and keep present those to you back in home as are not yet watched

**Expected behavior**
every video that you atleast play should be present in the history

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 126.0.1

**Additional context**
some videos will be added as usual but very rarely, probably has something to do if the video has ads active or not, 

They found a way to not get the creators credit for ads fast forwarded and negate the vievws from the get go?

**Comment by Mendax1989** [comment]
Same.
