### ISSUE TITLE
5.6 Faulty

### ISSUE THREAD

**Issue by IDK222222222222** [TheRealJoelmatic/RemoveAdblockThing#593]
Started a video and immediately had multiple audio from the one video also the button like skip video is missing etc

Anyone know the most recent non faulty version so I can download it?

**Comment by slackappu** [comment]
had the same issue

went to release then clicked on the latest release (5.0) and clicked on the file which led to a new tab in chrome asking me if i wanted to downgrade

**Comment by rbcsxyh** [comment]
I've encountered this problem too. I thought I had multiple videos open because I could hear two voices at the same time.

**Comment by Robpcfl** [comment]
I am using 5.5 (Latest version I see posted) and having issues with duplicate audio.  I have encountered this with multiple Youtube videos.  I have to refresh multiple times before it comes in with only one audio track.  I am using this with Chrome 125.0.6422.142 (Latest build as of 6/11/24)
