### ISSUE TITLE
Still issue with double audio on 5.5

### ISSUE THREAD

**Issue by csptt-alt** [TheRealJoelmatic/RemoveAdblockThing#595]
**Script version**
5.5

**Describe the bug**
Still getting double audio, tried to downgrade to 5.3/3.4 but same issue. Cleared out cache/history, reinstalled tampermonkey, incognito mode same issue.

Some workaround do work - refresh page and hit space to pause the first audio then click with mouse but the timing needs to be exact. It reloads 2 times.

**Expected behavior**
Youtube without add and double audio when playing.

**Screenshots**
its an audio issue, cant send pic of this.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome/edge
 - Version Edge Version 125.0.2535.92

**Comment by ViSlayer** [comment]
Same I need to reload the page then wait for the video overlay to show up then hit play if i press play one time or let it auto play an add runs or the vid plays twice

**Comment by ItsNyQuil** [comment]
[5.6](https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js) is the latest.

**Comment by csptt-alt** [comment]
> [5.6](https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/180c55ef13ac8f87866caa7df4afd1594cb531cc/Youtube-Ad-blocker-Reminder-Remover.user.js) is the latest.

Updated it and its the same issue with double audio.

I have restarted the browser, cleared history/cache.

There was one that stood 5.6 but downgraded to 5.5
