### ISSUE TITLE
No longer have access to private videos

### ISSUE THREAD

**Issue by vagman** [TheRealJoelmatic/RemoveAdblockThing#597]
**Script version**
5.6

**Describe the bug**
Private videos are no longer available. I get the error message "This video is private" whereas in version 3.8 I have access to the video normally.

**Expected behavior**
Access to private videos that belong to your account.

**Desktop (please complete the following information):**
 - OS: Windows 11 Enterprise Version 10.0.22635 Build 22635
 - Browser: Google Chrome 
 - Version 126.0.6478.57 (Official Build) (64-bit)

**Comment by mamnnn** [comment]
Chromebook, Version 126.0.6478.57 (Official Build) (64-bit). the videos are of my account, Remove Adblock Thing 5.6. thanks
