### ISSUE TITLE
Auto-play didnt work

### ISSUE THREAD

**Issue by kami-yukiko** [TheRealJoelmatic/RemoveAdblockThing#598]
**Script version**
5.5

**Describe the bug**
The video player seem to work to force the video become an ad, apperantly it make auto-play cant work 
Pretty anoyed especially when listening to music on yt

**Expected behavior**

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/172404309/6e18a45b-27aa-4249-9247-490630c821dd)
![Uploading image.png…]()

**Desktop (please complete the following information):**
 - OS: [Window]
 - Browser [Chrome]
 - Version [Version 125.0.6422.142]

**Additional context**

**Comment by Asherit** [comment]
Have the same issue. Autoplay no longer working

**Comment by justguywithglasses** [comment]
me too. and the player is not youtube's. i think that;s why.
