### ISSUE TITLE
This video is age-restricted and only available on YouTube

### ISSUE THREAD

**Issue by CaptainAlex787** [TheRealJoelmatic/RemoveAdblockThing#599]
**Script version**
5.6

**Describe the bug**
Even though my account is age verified, I am no longer able to see some videos and I get the message 
"This video is age-restricted and only available on YouTube"

**Expected behavior**
Being able to watch the video

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 10
 - Browser Opera
 - Version everything latest release

**Comment by quantummy** [comment]
me 2

**Comment by FrozenDragon0** [comment]
Can confirm am also getting this with 5.6 using Chrome.
