### ISSUE TITLE
5.5 Audio playing twice Also not being able to minimise YouTube Video. Also thank you so much for giving us access to this for free!

### ISSUE THREAD

**Issue by carrotsiwiwie** [TheRealJoelmatic/RemoveAdblockThing#600]
5.5 Adblocker

Audio playing twice every time I click on a YouTube video to watch I have to reload page the page then audio only is good. Also minimise is unavailable to minimise the video.

If this could please be fixed! Tysm.

Minimise unavailable see below not sure if i can upload pics 
Without adblock thing
![Without Adbloxck thing](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/67058409/b3345756-d0b7-4524-a7c1-8c68c2b33a67)
Vs with
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/67058409/f204f142-6079-4bf9-909d-6902c3a04133)

Chrome Browser

Also just thank you again for creating this JoelMatic and sharing it with others for free appreciate it!

**Comment by Ninjatintin** [comment]
my prediction on why it's happening is that it's replacing the video with an embedded video, meaning it has the embedded video GUI, less options, and the recommended videos when pausing
