### ISSUE TITLE
Avoid auto update?

### ISSUE THREAD

**Issue by muhdkhokhar** [TheRealJoelmatic/RemoveAdblockThing#601]
how I avoid auto update
I have to keep rolling back to previous working version
its so annoying

**Comment by sorphin** [comment]
You change the autoupdate flag from true to false in the script code in tampermonkey.

**Comment by Lydialuvs** [comment]
> You change the autoupdate flag from true to false in the script code in tampermonkey.

Can you share where specifically in the code that is :)?

**Comment by sorphin** [comment]
It's up at the top area...  See where I have an arrow to "right here" below..

`
// ==UserScript==
// @name         Remove Adblock Thing
// @namespace    http://tampermonkey.net/
// @version      5.6
// @description  Removes Adblock Thing
// @author       JoelMatic
// @match        https://www.youtube.com/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=youtube.com
// @updateURL    https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js
// @downloadURL  https://github.com/TheRealJoelmatic/RemoveAdblockThing/raw/main/Youtube-Ad-blocker-Reminder-Remover.user.js
// @grant        none
// ==/UserScript==

(function()
 {
    //
    //      Config
    //

    // Enable The Undetected Adblocker
    const adblocker = true;

    // Enable The Popup remover (pointless if you have the Undetected Adblocker)
    const removePopup = false;

    // Checks for updates (Removes the popup)
    const updateCheck = true;    <-------------------------- Right here

    // Enable debug messages into the console
    const debugMessages = true;

    // Fix timestamps in the youtube comments for new method
    const fixTimestamps = true;

    // Enable custom modal

`
