### ISSUE TITLE
Stop forcing 5.6 update, only 3.8 works.

### ISSUE THREAD

**Issue by Mendax1989** [TheRealJoelmatic/RemoveAdblockThing#604]
I click skip, keeps updating. Only 3.8 works.

**Comment by keithseric** [comment]
You can turn off updating in the script.  5.6 is working best for many of us.

**Comment by bringalas** [comment]
> You can turn off updating in the script. 5.6 is working best for many of us.

how

**Comment by keithseric** [comment]
In Tampermonkey, go to the Dashboard and click the edit icon on the right-hand side of the script.  Change updateCheck=true; to false.  Click File, then Save.
