### ISSUE TITLE
Auto Play not working on playlists, No "Next" button visible on the player.

### ISSUE THREAD

**Issue by kr4kken** [TheRealJoelmatic/RemoveAdblockThing#605]
**Script version**
5.6

**Describe the bug**
Auto Play not working on playlists, No "Next" button visible on the player.

**Expected behavior**
The next video should play after the current video ends.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/130484511/8c5f4eab-e535-41f6-8cf9-3e1223a09a77)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 125.0.6422.142

**Additional context**
None so far, ad skipping pretty good, just that autoplay issue. Thanks!

**Comment by Vlxst** [comment]
Maybe because he changed the player to "embedded"?
It doesn't jump by itself here either and there's no record in the history

**Comment by kr4kken** [comment]
is there an update that i've missed @TheRealJoelmatic ?? coz this got closed, sorry for bothering you bossman
