### ISSUE TITLE
Audio Doubling + More

### ISSUE THREAD

**Issue by Lydialuvs** [TheRealJoelmatic/RemoveAdblockThing#607]
When an ad gets skipped with the script, the video gets played twice with audio doubling. This sometimes gets fixed when refreshing, but sometimes not. Another big issue I am having is that it is not saving my spot in videos. If i have watched a video partially, this script will force the video to play from the beginning (it plays from my halfway spot when this script is turned off). I also sometimes use console mode on my browser to speed up the video beyond 2x speed, and that is also now broken with this script.
Also, when looking at console mode, it says "Duplicate video found and muted" and the number of duplicate videos found keeps constantly ticking up, I am wondering if this relates to the audio doubling issue.

**Comment by Necrome397** [comment]
it blocks ads for me and is working fine but no video can be found in the history anymore, only shorts are in the history.
