### ISSUE TITLE
3.8 is no more, check out this fix

### ISSUE THREAD

**Issue by muchandr** [TheRealJoelmatic/RemoveAdblockThing#609]
Gives the three videos warning

Have been able to fix uBlock with this hack

https://www.reddit.com/r/youtube/comments/15i7vql/video_player_will_be_blocked_after_3_videos_if/

CODE:

youtube.com##+js(set, yt.config_.openPopupConfig.supportedPopups.adBlockMessageViewModel, false)

youtube.com##+js(set, Object.prototype.adBlocksFound, 0)

youtube.com##+js(set, ytplayer.config.args.raw_player_response.adPlacements, [])

youtube.com##+js(set, Object.prototype.hasAllowedInstreamAd, true)

--------------------------------------------------------------------------------------------------------------------

possibly applicable to Tempermonkey?

**Comment by Deec3** [comment]
I'm on version 5.6 and haven't had any ads today. a few fast ads but has been acting in a way that doesnt disturb my experience. for the past week or two I've been refreshing and changing versions. But its working fine for me now.

**Comment by muchandr** [comment]
> I'm on version 5.6 and haven't had any ads today. a few fast ads but has been acting in a way that doesnt disturb my experience. for the past week or two I've been refreshing and changing versions. But its working fine for me now.

Hmm. Are you sure? People claimed that 5.6 still has the double audio problem. I only tried up to 5.5 myself, and it had the double audio and a conflict with YouTube Enhancer to boot.

This alt script also seems to work. (need to try on my other machine with more browsers though)

https://github.com/TheRealJoelmatic/RemoveAdblockThing/issues/602

I am kinda chicken to try the original script anymore, because I seem to be on some kind of "three strike" regiment :) I think I'll wait for a few days.
