### ISSUE TITLE
My Private Videos on Youtube can't access; went back to 5.3, & access is perfect

### ISSUE THREAD

**Issue by mamnnn** [TheRealJoelmatic/RemoveAdblockThing#611]
**Script version**
What version is the script on eg 2.9 , 3.1 ect

**Describe the bug**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by vagman** [comment]
Duplicate of #597 , you can delete it.
