### ISSUE TITLE
Video unavailable

### ISSUE THREAD

**Issue by BallisticJew** [TheRealJoelmatic/RemoveAdblockThing#614]
**Script version**
5.6

**Describe the bug**
Video unavailable
Playback on other websites has been disabled by the video owner
[Watch on YouTube]
This is what pops up on a grey background on some videos.

**Expected behavior**
I would expect to watch the video normally without any issues. Upon turning the script off, everything is fine 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 126.0.1 (64-bit)

**Additional context**
Not sure if it happens elsewhere.
![tampermonkey](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/143848840/038c9037-ba9f-4210-af0b-0d0feac98f56)

**Comment by pratikgujral** [comment]
I can confirm, I am seeing the same error.

OS: Windows 11, 
Browser: Microsoft Edge
RemoveAdBlockThing version: 5.6
