### ISSUE TITLE
5.6 has some problems

### ISSUE THREAD

**Issue by dfcfaaa** [TheRealJoelmatic/RemoveAdblockThing#642]
**Script version**
5.6

**Describe the bug**
- Still has double audio
- Youtube Shorts only plays audio
- It does not block ads; ads are still played without skipping
- No theater mode

**Expected behavior**
It should skip ads without any problems

**Screenshots**
If applicable, add screenshots or a video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 126.0.6478.62

**Additional context**

**Comment by bryanh-9** [comment]
For what it's worth, not sure if this is true universally, I have only noticed the double audio in the latest version when I open in a new tab, and let the tab load before focusing it. If that is also true for you, that is a temporary fix (go to the tab quicker, or open in current tab), and also a clue. This is is consistently reproducable for me.

My guess here, is that the script destroys the old player on page load, but seemingly youtube actually creates it dynamically when you first focus the tab.

So waiting to destroy the old player until there is a focus event might be the key?

There are some other oddities, but I think it may come down to a similar issue, ie if a tab is unfocused for long enough and the browser hits memory savings, then things re-render on focus again, same issue.
