### ISSUE TITLE
Youtube now detects this script and blocks it

### ISSUE THREAD

**Issue by McBenjihood** [TheRealJoelmatic/RemoveAdblockThing#644]
**Script version**
5,6

**Describe the bug**
When the script is enabled and I try to watch a video, this screen appears:
There is now way around this screen, only if I disable the script. The thing is that im already signed in so I cant sign in "again", to confirm im not a bot.

**Screenshots**
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/88515315/49ac2918-5b74-4701-a8ad-246b92db30c9)
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/88515315/fa9f7bfd-c93b-41d8-b4d8-66662d5b6313)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Opera GX

**Comment by muchandr** [comment]
This seems more of a bug, than a (deliberate) feature. Anybody else on Opera GX?
