### ISSUE TITLE
Shows scroll bar while playing video in full screen.

### ISSUE THREAD

**Issue by Lakshay2910** [TheRealJoelmatic/RemoveAdblockThing#66]
Whenever I play video in full screen, it shows scroll bar in the video.

![Scroll_Bar](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/124456959/a39b702f-fe0b-4bbd-929f-7230b1577409)

**Comment by lushythedev** [comment]
Same issue here. For now, turn on dark mode; easier on the eyes.

**Comment by Akshar-Premnath** [comment]
If this is on a macOS:

1. Open System Settings
2. Go to the Appearance tab
3. Find the menu box "Show scroll bars" 
4. Select the "Automatically based on mouse or trackpad" option

This worked for me; I am on an Apple Macbook Air M1, 2020 running macOS Sonoma 14.0 (23A344).

**Comment by TheRealJoelmatic** [comment]
It should be fixed in the latest vertion.
