### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Gersonzao** [TheRealJoelmatic/RemoveAdblockThing#7]
Is it compatible with Violentmonkey?

Is it supposed to also remove this message?
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/85644671/c1ce4679-396e-480e-89f7-37628fd7451a)

**Comment by TheRealJoelmatic** [comment]
> Is it compatible with Violentmonkey?
I've only tested it with tampermonkey.

> Is it supposed to also remove this message?
Yes that the point of the script

**Comment by boelle** [comment]
does it also make sure that peoples account dont get blocked if an adblocker is detected a number of times ?

**Comment by TheRealJoelmatic** [comment]
> does it also make sure that peoples account dont get blocked if an adblocker is detected a number of times ?

It should as we remove the cookie that stores that info.

**Comment by boelle** [comment]
google are more smarter than using a cookie for that

ie if you login and they detect the adblocker i'm sure they are not dumb enough to trust a cookie you can just delete....
and if you look arround people allready start to get their account locked in such a way they cant play videos even if they delete all cookies

**Comment by TheRealJoelmatic** [comment]
> google are more smarter than using a cookie for that
> 
> ie if you login and they detect the adblocker i'm sure they are not dumb enough to trust a cookie you can just delete.... and if you look arround people allready start to get their account locked in such a way they cant play videos even if they delete all cookies

Atm I've not had any problems with this type of thing as I used to see the pop-up saying "the video player will be disabled after 3 more videos". And I have never been blocked from the video player after using this script.
