### ISSUE TITLE
How this guide works ... !

### ISSUE THREAD

**Issue by JordanToAlani** [TheRealJoelmatic/RemoveAdblockThing#70]
### Hello everyone i see everyone having problem with the guide or they say it doesnt work first of what u do  : 
_u follow the guide here_  :
[https://github.com/TheRealJoelmatic/RemoveAdblockThing](url)   _the steps of [Installation]_ 

### _**then the most important step is  go to three dots if u use google chrome and extensions+manage extensions and close all the ad block extensions you have even ublock origin if u have turn it off .**_

Then go to youtube re-sign with ur account and you are ready  is working  you dont see anymore this message of block notification ad the only thing u need to do is if the video isnt starting  you need to refresh the video or wait some 3-5 sec and u watch for free any video u like . 

This is how it works this guide and to be honest its completely fine i have no problem some videos are starting automatically and there are some videos where u need to wait 3-5 sec or to fresh the page

_**By Jordan.**_

**Comment by Davy49** [comment]
Jordan,
Thanks so much for posting your comments, like you stated if you follow the directions EXACTLY then this does in fact function properly, at least for me it does.

**Comment by JordanToAlani** [comment]
i agree now  there alot of days that passed and i have no problems .
