### ISSUE TITLE
scrollbar is visible when video is full screen

### ISSUE THREAD

**Issue by teetangh** [TheRealJoelmatic/RemoveAdblockThing#71]
scrollbar is visible when video is full screen

**Comment by androgouws911** [comment]
simple fix for this.
update Line 104:
 bodyStyle.setProperty('overflow-y', 'scroll', 'important');
to:
bodyStyle.setProperty('overflow-y', 'auto', 'important');

**Comment by androgouws911** [comment]
> scrollbar is visible when video is full screen

simple fix for this.
update Line 104:
bodyStyle.setProperty('overflow-y', 'scroll', 'important');
to:
bodyStyle.setProperty('overflow-y', 'auto', 'important');

**Comment by yankeesback** [comment]
i don't get why they didn't fix yet? does he even read the "issues" section? now using "Ad Skip Master for Youtube" chrome extension which is way a more reliable solution.

**Comment by TheRealJoelmatic** [comment]
It has been fixed now in the latest version.
