### ISSUE TITLE
scrollbar suddenly visible when youtube is full screen

### ISSUE THREAD

**Issue by gamemaniac123** [TheRealJoelmatic/RemoveAdblockThing#75]
![full screen](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/148631943/b94e6478-6211-4412-bf78-07b88edf8b69)

**Comment by AnomSanjaya** [comment]
Me too...

![gambar](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/31486344/c64f657b-9087-499f-9652-b562cceb5b2b)

**Comment by ChaseYUL99** [comment]
I have the same issue
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/35789362/2c836f46-98b4-4476-8316-a139af8522c6)

**Comment by TheRealJoelmatic** [comment]
This should be fixed in the latest version (2.6)
