### ISSUE TITLE
now it show ads

### ISSUE THREAD

**Issue by tozxart** [TheRealJoelmatic/RemoveAdblockThing#77]
I believe YouTube has made some updates, and it's now showing ads. It didn't show ads before, but now it does.

**Comment by 0x48piraj** [comment]
If anyone wants an undetectable YT ad blocker (until uBlock stabilizes again) for the time-being on Chrome, Firefox, Opera, Edge and Brave browsers, here you go,

**Chrome:** https://chrome.google.com/webstore/detail/fadblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc
**Firefox:** https://addons.mozilla.org/en-US/firefox/addon/fadblock/

**GitHub:** https://github.com/0x48piraj/fadblock _(read the FAQ)_

P.S. I'm the author, the extension is completely **open-source** so you can have a look under-the hood and here's the [new post](https://www.reddit.com/r/youtube/comments/179yebo/fadblock_bullsht_free_youtube_ads_blocker_for/) as well as the [old post](https://www.reddit.com/r/youtube/comments/177ijjb/a_fast_lightweight_and_undetectable_youtube_ads/) for social-proof.

**Comment by TheRealJoelmatic** [comment]
This should be fixed in the latest version (2.6)
