### ISSUE TITLE
Doesn't work too well anymore (10/21)

### ISSUE THREAD

**Issue by jhones-dev** [TheRealJoelmatic/RemoveAdblockThing#78]
It was working until yesterday, but it seems youtube is already patching it. Every video that starts, it flashes a message alerting that adblocks violates their terms and also the video doesn't start (black screen). If you try a lot refreshing the page, soon it will bypass, but it's hard, you have to refresh at least 5 times per video

**Comment by mahmoudjaradat** [comment]
> It was working until yesterday, but it seems youtube is already patching it. Every video that starts, it flashes a message alerting that adblocks violates their terms and also the video doesn't start (black screen). If you try a lot refreshing the page, soon it will bypass, but it's hard, you have to refresh at least 5 times per video

**Comment by Lumiceron** [comment]
I'm facing the same problem.

**Comment by Sp0kzz** [comment]
just install "Ad Skip Master for Youtube" after whitelisting youtube on your adblocker.
this script is not worth our time.

**Comment by 0x48piraj** [comment]
If anyone wants an undetectable YT ad blocker (until uBlock stabilizes again) for the time-being on Chrome, Firefox, Opera, Edge and Brave browsers, here you go,

**Chrome:** https://chrome.google.com/webstore/detail/fadblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc
**Firefox:** https://addons.mozilla.org/en-US/firefox/addon/fadblock/

**GitHub:** https://github.com/0x48piraj/fadblock _(read the FAQ)_

P.S. I'm the author, the extension is completely **open-source** so you can have a look under-the hood and here's the [new post](https://www.reddit.com/r/youtube/comments/179yebo/fadblock_bullsht_free_youtube_ads_blocker_for/) as well as the [old post](https://www.reddit.com/r/youtube/comments/177ijjb/a_fast_lightweight_and_undetectable_youtube_ads/) for social-proof.

**Comment by proff20012001** [comment]
Its worst now it just black screen you see

**Comment by jhones-dev** [comment]
> If anyone wants an undetectable YT ad blocker (until uBlock stabilizes again) for the time-being on Chrome, Firefox, Opera, Edge and Brave browsers, here you go,
> 
> **Chrome:** https://chrome.google.com/webstore/detail/fadblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc
> **Firefox:** https://addons.mozilla.org/en-US/firefox/addon/fadblock/
> 
> **GitHub:** https://github.com/0x48piraj/fadblock _(read the FAQ)_
> 
> P.S. I'm the author, the extension is completely **open-source** so you can have a look under-the hood and here's the [new post](https://www.reddit.com/r/youtube/comments/179yebo/fadblock_bullsht_free_youtube_ads_blocker_for/) as well as the [old post](https://www.reddit.com/r/youtube/comments/177ijjb/a_fast_lightweight_and_undetectable_youtube_ads/) for social-proof.

This actually works! However if you have Enhancer for Youtube, you need to disable it (and other adblocks of course), otherwise it won't work. I will be using it for the time being. Love you ❤️

**Comment by jenko** [comment]
FWIW, it was working for me for a bit, then stopped. So I went through my other extensions, and, unbeknownst to me, another extension I use, "Enhancer for youtube", has its own ad-blocker (among its many features).  When I turned that feature off, RemoveAdblockThing started working again.

**Comment by Drakonas** [comment]
The issue stems from the fact that when they are updating this script, they are not increasing the version number, so Tampermonkey will never automatically update it even though the script is changing. Make sure to click the install link again and hit "reinstall". You'll notice there are lines being changed in the install window. The updates are fixing problems. Keep it updated people!

**Comment by Lecrapouille** [comment]
For the moment, the two working solutions are:
- Firefox open the video in new privacy windows.
- Click on the button "share" then click on "embedded"
No extension worked for me

**Comment by Davy49** [comment]
It's been my experience that if you follow the instructions EXACTLY then at least for me this is functioning properly.

**Comment by Drakonas** [comment]
Yes everyone... you need to make sure that your normal Adblock is not loading for the website. This userscript will block all the ads necessary. However Google seems to actively be trying to counteract it. Keep it updated!

**Comment by neosubhamoy** [comment]
> If anyone wants an undetectable YT ad blocker (until uBlock stabilizes again) for the time-being on Chrome, Firefox, Opera, Edge and Brave browsers, here you go,
> 
> **Chrome:** https://chrome.google.com/webstore/detail/fadblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc **Firefox:** https://addons.mozilla.org/en-US/firefox/addon/fadblock/
> 
> **GitHub:** https://github.com/0x48piraj/fadblock _(read the FAQ)_
> 
> P.S. I'm the author, the extension is completely **open-source** so you can have a look under-the hood and here's the [new post](https://www.reddit.com/r/youtube/comments/179yebo/fadblock_bullsht_free_youtube_ads_blocker_for/) as well as the [old post](https://www.reddit.com/r/youtube/comments/177ijjb/a_fast_lightweight_and_undetectable_youtube_ads/) for social-proof.

As of (26/10/2023) FadBlock is working for me like a charm...!! 🤩
*(BUG: Sometimes it shows the Video Ad for <1sec then skips autometically.....not a serious issue for me....!!)

IMPORTANT:
1. Disable other AdBlockers (extensions & in-built) (eg: uBlock Origin, Brave Shield)
2. If you are using Enhancer for YouTube extension Disable it's 'Block Ads' feature from settings
3. Disable RemoveAdblockThing script from Tampermonkey (FadBlock is still undetectable by YouTube. So, you will not get the annoying pop-up anyways....I disabled it as i'm facing some scrolling issues....!!)

@0x48piraj thanks for sharing bro...!! ❤

**Comment by Lecrapouille** [comment]
@Davy49 @neosubhamoy maybe because I've a stack of ad-blockers, therefore fadblock would not help me. Anyway, opening YT video with Firefox in privacy windows is by far the easier and working solution.

**Comment by Davy49** [comment]
At least for the short term I'm thinking I'll give either firefox or a fork of it another trial.

**Comment by Davy49** [comment]
Like other people have previously mentioned that if you are using uBlock origin what seems to help is to go into the settings area and select purge databases and then update to receive the latest versions.
