### ISSUE TITLE
Live Chat Comment - 3 Dots Drop-Down Menu (to Remove a Chat Comment) not Working

### ISSUE THREAD

**Issue by Zacchino** [TheRealJoelmatic/RemoveAdblockThing#81]
Repro Steps:

1. When watching a Live Video on YouTube, some of the Youtubers enable a "Live Chat" for the audience to comment during the live.

2. With RemoveAdblockThing Enabled: The "Remove" option that pops-up when clicking on the drop-down " ⁞ " button next to a message to delete it, does not show-up anymore.

3. With RemoveAdblockThing Disabled: This option shows-up / works as intended.

Hope this helps!

**Comment by TheRealJoelmatic** [comment]
Should be fixed in the latest version (2.6)
