### ISSUE TITLE
Chapters will not open

### ISSUE THREAD

**Issue by Timbuktu22** [TheRealJoelmatic/RemoveAdblockThing#88]
Button to view chapter and open chapter menu does nothing, but chapter progression seems to display fine in the title and loading bar.

**Comment by fuste76** [comment]
Same behaviour here.

**Comment by aspizu** [comment]
Can reproduce. Disabling the script resolves the issue.

**Comment by TheRealJoelmatic** [comment]
should be fixed in the latest version (2.6)
