### ISSUE TITLE
Video Not playing and black screen

### ISSUE THREAD

**Issue by downloadyetter** [TheRealJoelmatic/RemoveAdblockThing#91]

**Comment by downloadyetter** [comment]
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/93855974/a24e2caf-2f94-4065-99d5-8e02fb47d934)

**Comment by AsparagusEduardo** [comment]
Same

**Comment by watercup0926** [comment]
just whitelist youtube and reinstall RAT

**Comment by Shrey1517** [comment]
how do i do that

**Comment by watercup0926** [comment]
The easiest way is uninstall the AdBlock extension and use RAT itself

**Comment by matrixfan007** [comment]
same. i can play exactly play one youtube video without a problem. from the next video on it won't play anymore, the no adblock quickly flashes and then black, as screenshotted above. have to quit and reopen safari to restart this.

**Comment by Suzuki108** [comment]
Same. My screen is blank where there should be a video.

**Comment by TheEngiNerd70** [comment]
I have uBlock by Orgin, and I had to add 'youtube.com' to the Trusted Site list to get this script to work correctly.
I had to do this even though I have it disabled.
Hope this helps someone!! :)

**Comment by khorchanov** [comment]
Same problem here, none of the solutions above works for me

**Comment by Jeko83** [comment]
> I have uBlock by Orgin, and I had to add 'youtube.com' to the Trusted Site list to get this script to work correctly. I had to do this even though I have it disabled. Hope this helps someone!! :)

Did the same, this doesn't work for me unfortunately. On opera one

**Comment by Pathetacy** [comment]
> The easiest way is uninstall the AdBlock extension and use RAT itself

what is RAT?
i dont do coding at all so i dont know anything about this stuff. i'm getting the black screen problem and i dont know how to fix it. can somebody help me?

**Comment by Pathetacy** [comment]
> > The easiest way is uninstall the AdBlock extension and use RAT itself
> 
> what is RAT? i dont do coding at all so i dont know anything about this stuff. i'm getting the black screen problem and i dont know how to fix it. can somebody help me?

apparently it just fixed itself???

**Comment by Davy49** [comment]
> The easiest way is uninstall the AdBlock extension and use RAT itself
Can you please enlighten me as to what "RAT" stands for, all I know is that google/youtube is making it extremely difficult to enjoy watching videos on their site.

**Comment by Timmiej93** [comment]
> Add youtube.com to the integrated browser adblocker whitelist

This was my issue, I also completely forgot my browser has adblocking functionality. Great catch!

> what is RAT?

It's the acronym of the name of this script, **R**emove**A**dblock**T**hing. If you get a black screen, most likely you still have an ad blocker running somewhere. Check if your browser has a built-in ad blocker.

**Comment by Davy49** [comment]
> > Add youtube.com to the integrated browser adblocker whitelist
> 
> This was my issue, I also completely forgot my browser has adblocking functionality. Great catch!
> 
> > what is RAT?
> 
> It's the acronym of the name of this script, **R**emove**A**dblock**T**hing. If you get a black screen, most likely you still have an ad blocker running somewhere. Check if your browser has a built-in ad blocker.
Timmiej93,
Thanks so much for your timely detailed clarification to my question.

**Comment by TheRealJoelmatic** [comment]
## Common Issues

**"Ad Blockers violate Youtube Terms Of Service" OR Just a black screen**

This happens when there is an adblock other than the script running. Common ways you may be blocking ads accidentally on Youtube is:

- **Adblock extension:** Disable or whitelist YouTube on your ad blocker extension.

- **Browser built-in adblock:** Some browsers have built-in ad blockers. Disable or configure them.

- **Other Tampermonkey scripts:** Scripts like YouTube enhancer may conflict. Disable them one by one to identify the issue.

- **Wi-Fi/DNS/Firewall adblock rules:** Check network settings for any ad-blocking configurations.

- **Windows hosts file rules:** Inspect the Windows hosts file (C:\Windows\System32\drivers\etc) for ad-blocking rules.
