### ISSUE TITLE
View transcript of video does not work as of Oct 26 23 

### ISSUE THREAD

**Issue by calchip** [TheRealJoelmatic/RemoveAdblockThing#92]
I discovered today that the "view transcript" functionality does not work, probably because it's caught as a pop-up. This is on Firefox for Mac v 119.0

**Comment by coldpines** [comment]
Same for me. I need this for my job as well, so to see it I have to turn this script off.

**Comment by ngrfgt** [comment]
Same

**Comment by andrey-mikhaylov** [comment]
I've got the same problem. I use Vivaldi browser.
To get the transcript I open the video url in another browser (chrome with no tampermonkey)

**Comment by andrey-mikhaylov** [comment]
I cannot into js, but the problem is somewhere in this block:
```
if (childElement.data.targetId && childElement.data.targetId !=="engagement-panel-macro-markers-description-chapters")
                          //Skipping the Chapters section
                            childElement.remove();
                          });
                       } else {
                           element.remove();
                       }

```
so i've tried to detect the transcript by replacing/adding some code:

```
            sponsor?.forEach((element) => {
                 if (element.getAttribute("id") === "panels") {
                    element.childNodes?.forEach((childElement) => {
                      if (childElement.data.targetId && childElement.data.targetId ==="engagement-panel-searchable-transcript") {
                          // do nothing
                      } else if (childElement.data.targetId && childElement.data.targetId !=="engagement-panel-macro-markers-description-chapters")
                          //Skipping the Chapters section
                            childElement.remove();
                          });
                       } else {
                           element.remove();
                       }
             });

```
the transcript now shows ok, but I am not sure about ads

**Comment by Felina-Lain** [comment]
> I cannot into js, but the problem is somewhere in this block:
> 
> ```
> if (childElement.data.targetId && childElement.data.targetId !=="engagement-panel-macro-markers-description-chapters")
>                           //Skipping the Chapters section
>                             childElement.remove();
>                           });
>                        } else {
>                            element.remove();
>                        }
> ```
> 
> so i've tried to detect the transcript by replacing/adding some code:
> 
> ```
>             sponsor?.forEach((element) => {
>                  if (element.getAttribute("id") === "panels") {
>                     element.childNodes?.forEach((childElement) => {
>                       if (childElement.data.targetId && childElement.data.targetId ==="engagement-panel-searchable-transcript") {
>                           // do nothing
>                       } else if (childElement.data.targetId && childElement.data.targetId !=="engagement-panel-macro-markers-description-chapters")
>                           //Skipping the Chapters section
>                             childElement.remove();
>                           });
>                        } else {
>                            element.remove();
>                        }
>              });
> ```
> 
> the transcript now shows ok, but I am not sure about ads

Thanks, this solved the problem for me, and it seems to not make the ads return
(for anyone looking, the line to replace was around 160)
