### ISSUE TITLE
Script is no longer working

### ISSUE THREAD

**Issue by nmanove** [TheRealJoelmatic/RemoveAdblockThing#93]
We get the "No add blockers allowed" message for a moment and then a blank screen.

**Comment by Bruskiah** [comment]
Same thing for me using Opera.

**Comment by GroggyOtter** [comment]
> We get the "No add blockers allowed" message for a moment and then a blank screen.

I'm using the addon successfully on Chrome right now.  
The only issue I've seen in the last few days is that it doesn't auto-skip the panel with the "skip ad" button on it. And all that means is waiting 5 seconds for the timeout to occur.  

Ads are still being skipped/blocked.

Are you **positive** that you don't have anything else blocking the ad?  
What you're describing is exactly what happened to me when I first installed RemoveAdblockThing but still had uBlock enabled on YouTube.  
uBlock blocking the ad and causing the black screen made it seem like RemoveAdblockThing wasn't working.

**Comment by fadster** [comment]
> The only issue I've seen in the last few days is that it doesn't auto-skip the panel with the "skip ad" button on it. And all that means is waiting 5 seconds for the timeout to occur.

If you're seeing the "skip ad" button then this script isn't working. What's the point if ads are still playing?

**Comment by rubywastaken** [comment]
> We get the "No add blockers allowed" message for a moment and then a blank screen.

I use Firefox + uBlock Origin. When I get this issue, I just go to uBlock dashboard, then to 'filter lists', purge all caches, wait for it to clear then restart my browser. It's working again.
![image](https://github.com/TheRealJoelmatic/RemoveAdblockThing/assets/143356421/130c4c27-210f-492a-8630-cb4aeb9d0b65)

**Comment by nmanove** [comment]
Yes, going to the uBlock dashboard, and then to 'filter lists' and purging all the caches worked for me.

**Comment by Skyknight47** [comment]
Bump, this is still happening for https://getadblock.com on a Chrome browser.

**Comment by 128ajb** [comment]
> Same thing for me using Opera.

With Opera, you will have to disable or whitelist youtube with the ad blocker built into opera. My laptop gave me issues and disabling opera's adblock fixed it. my desktop worked without that for some reason, which is odd, but win 11 (desktop) and win 10 (laptop) could be to blame
