### ISSUE TITLE
Scrolling impossible/video stops playing

### ISSUE THREAD

**Issue by LoveSpock** [TheRealJoelmatic/RemoveAdblockThing#98]
When I start a new playlist in Youtube, the script works fine. But after maybe every third video, it will pause automatically when starting a new one. And that's not the only problem, at the same time scrolling on Youtube will not work anymore. When I scroll down, it just jumps back to the top. Is this a common problem?

Anyway, thanks that you wrote this script, Youtube is so stingy right now... I don't care for advertisement but not this much...

**Comment by TheRealJoelmatic** [comment]
This was fixed in the latest version.
